### ISSUE TITLE
Guide users to install any missing dependencies.

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#101]
**Is your feature request related to a problem? Please describe.**

Some use cases require external dependencies. For example, local Lambda debugging requires SAM CLI, and each runtime requires the appropriate VS Code extension for that runtime. If a user attempts to complete a task that requires missing dependencies, they will have a poor experience trying to figure out why the task isn't working.

**Describe the solution you'd like**

When the user intiates a task that requires external dependencies, check for missing dependencies. If any are found, guide the user to install them.

**Describe alternatives you've considered**

#### Bundle all dependencies with the VS Code toolkit
This is out of scope for the toolkit. It would increase the size and complexity of toolkit installation, and would require duplication of effort from the existing dependencies' installers.

**Additional context**

What is the best way to determine whether SAM CLI is installed?

**Comment by gholt-aws** [comment]
Focus on the entry points and conditions we need to cover. The destination should be a web page. We can work with Dhruv and the doc writers on that.

**Comment by justinmk3** [comment]
Toolkit now has 

1. a "walkthrough" which guides on various topics
2. auto-install of tooling such as `session-manager-plugin`
    - todo:  autoinstall of `sam` cli is tracked in backlog
