### ISSUE TITLE
Step Functions: Add support to the linter to ignore a line

### ISSUE THREAD

**Issue by krissmilne** [aws/aws-toolkit-vscode#1016]
In other linters such as pyLint a line, or section of code can be marked as ignore through the use of comments.

Currently the Step Functions linter marks invalid Arn's through the use of a regular expression. However Arn's may not be available or known during development of the step function.

In my case I've designed a CI/CD pipeline step that reads the step function asl file into a cloudFormation state machine resource. I'm using cloudFormation !Sub references to insert Arn's. Unfortunately the step function linter marks the Arn as invalid, this also prevents the graph from rendering.

Providing support to tell the linter to ignore a line would be a great way for developers to control the behaviour.

**Comment by wong-a** [comment]
The fix was released in version 1.9.0

**Comment by wong-a** [comment]
@krissmilne Are there any other types of validations besides ARNs that you'd want to ignore?

I'm sure how that would work for a ASL files, as JSON doesn't support inline comments.

**Comment by studds** [comment]
Some tools do support comments in their JSON files. For example, you can have comments in your tsconfig.json. My deploy pipeline for statemachines strips comments (using https://www.npmjs.com/package/strip-json-comments), so having editor support for comments would be good.

(Further to this, if ASL were updated to support comments, that would be a real boon. It would be nice to be able to add comments to complex state machines as a "built in" functionality.)"

**Comment by wong-a** [comment]
@studds ASL does support comments but not in C/JavaScript style. Comments can be specified in the optional `Comment` field at the top-level of the state machine or in any state. That's obviously less flexible as inline comments, but it's currently built in to the language so you won't lose it between authoring and deployment.

https://states-language.net/spec.html#states-fields

**Comment by alanbo** [comment]
@studds , We recently added YAML support in aws toolkit and cloud formation. YAML format supports comments. https://aws.amazon.com/about-aws/whats-new/2021/03/aws-step-functions-adds-tooling-support-for-yaml/

**Comment by bryceitoc9** [comment]
Closing at the request of @alanbo (SFN team).

**Comment by skwashd** [comment]
If you're using JSONata in your step functions, you can now include comments in your ASL file. I wrote a post about how to include [inline comments in Step Functions with JSONata](http://proactiveops.io/archive/step-functions-jsonata-and-comments/).
