### ISSUE TITLE
Step Functions: Add support to ignore errors when rendering the graph

### ISSUE THREAD

**Issue by krissmilne** [aws/aws-toolkit-vscode#1017]
If any lint errors exist in the asl template the render graph option does not run.

While most errors may prevent the graph from rendering due to invalid syntax or step function declaration. Some errors are a non-issue.

Arn syntax errors are a good example of errors that could be safely ignored by the render graph option.

**Comment by alanbo** [comment]
@krissmilne , Are there any other examples of errors that you think can be safely ignored except for invalid Arn's?

**Comment by krissmilne** [comment]
@alanbo , None that I have encountered yet. As far as step functions is concerned during the development the only things that may need to be substituted by a build/deployment process or not available during development are external resources such as Lambda functions, SNS topics, DynamoDB etc... which are referenced by Arn. DynamoDB uses the table name which I don't think has any regex condition.

**Comment by awschristou** [comment]
A change for this has been released in v1.9.0 of the toolkit
