### ISSUE TITLE
Feature: Invoke/Debug non-SAM-based Lambda Function

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#102]
**Is your feature request related to a problem? Please describe.**

Projects created with `sam init` contain a `template.yaml` file with all of the information that SAM CLI needs for local invoke/debug. For projects not created with `sam init`, we should not require users to write their own `template.yaml` just to invoke/debug.

**Describe the solution you'd like**
For projects not created with `sam init`, we should generate a temporary `template.yaml` on the fly.

**Comment by awschristou** [comment]
These details are now folded into #135
