### ISSUE TITLE
Local debugging node lambda with extra params in version 1.8

### ISSUE THREAD

**Issue by dmpratt** [aws/aws-toolkit-vscode#1031]
**Desktop (please complete the following information):**

-   OS: OS X (Catalina)
-   VS Code version: 1.44
-   AWS Toolkit extension version: 1.8

**Question**
I would like to use the "Run Locally" and "Debug Locally" shortcuts in VS Code while working on my Lambda. However, I need to launch sam local invoke with a couple of additional parameters. I'd like to set the AWS region and profile --region and --profile. I've tried setting environment variables in the templates.json by clicking "Configure" and either adding AWS_PROFILE="blah" or trying to set DEBUGGER_ARGS but neither have an effect. I cannot find any updated documentation that covers how this can be accomplished. Any ideas?

**Comment by awschristou** [comment]
Hey @dmpratt thanks for letting us know about your use cases.

Currently we don't have a way to override those settings. We're working on a new local debugging experience, which you can see the current design for in https://github.com/aws/aws-toolkit-vscode/blob/master/designs/sam-debugging/local-sam-debugging.md . This should accommodate your needs once it is ready

**Comment by briantd** [comment]
@dmpratt 
In case this is helpful -- I recently discovered the same limitation and performed a kludgy workaround by editing "/usr/local/bin/sam" directly to set the AWS_PROFILE env var to the desired profile. Suboptimal, but at least I can now use the built-in local debug feature.

**Comment by justinmk3** [comment]
AWS Toolkit 1.12 (released today) includes the new [SAM local Lambda debugging experience](https://github.com/aws/aws-toolkit-vscode/pull/1215) which leverages VS Code "launch configurations". 

Full documentation: https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/run-debug-sam-app.html

> However, I need to launch sam local invoke with a couple of additional parameters.

The new `aws-sam` launch configuration supports a `aws` field which allows selecting a profile, and also a `sam` field which supports various settings like `sam.localArguments` and `sam.buildArguments`, for fine-grained control of the SAM CLI invocations.
