### ISSUE TITLE
Feature: View CloudWatch Logs

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#104]
**Is your feature request related to a problem? Please describe.**
If I want to view the CloudWatch logs for my lambda, I shouldn't have to hunt for them in the console. I should be able to quickly view them directly from my IDE.

**Describe the solution you'd like**

Add a "View CloudWatch Logs" command.
Add a "View CloudWatch Logs" item to the Lambda Explorer context menu.

**Comment by justinmk3** [comment]
related

- https://github.com/aws/aws-toolkit-vscode/pull/1092
- https://github.com/aws/aws-toolkit-vscode/pull/1200

**Comment by bryceitoc9** [comment]
This was released on August 24th in the toolkit's 1.13.0 release.
