### ISSUE TITLE
Feature: View source for live Lambda (go to definition)

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#105]
**Is your feature request related to a problem? Please describe.**

If I have a lambda in my AWS account, I should be able to quickly download and view its source code.

**Describe the solution you'd like**
Add "View Lambda Source" command
Add "View Lambda Source" item to Lambda Explorer context menu.

**Comment by awschristou** [comment]
I think these should be two distinct actions the user can choose to initiate:
* download Lambda Source
* go to definition

**Comment by juranich** [comment]
+1

**Comment by justinmk3** [comment]
"Import Lambda" feature was implemented in https://github.com/aws/aws-toolkit-vscode/pull/1236

**Comment by justinmk3** [comment]
Toolkit 1.16 was released today and includes "Import Lambda" feature.
