### ISSUE TITLE
Enable Schemas in AWS Explorer for all regions that support EventBridge Schema Registry

### ISSUE THREAD

**Issue by sliedig** [aws/aws-toolkit-vscode#1068]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Enable Schemas in AWS Explorer for all regions that support EventBridge schema registry: US East (Ohio and N. Virginia), US West (Oregon and N. California), Canada (Central), EU (Stockholm, Paris, Ireland, Frankfurt, and London), Asia Pacific (Mumbai, Tokyo, Seoul, Singapore, Hong Kong, and Sydney), and South America (Sao Paulo).

System info: 
OS:  Darwin x64 18.7.0
Visual Studio Code Version:  1.44.2
AWS Toolkit Version:  1.9.0

**Additional context**
![image](https://user-images.githubusercontent.com/597073/80940710-2dac2280-8e13-11ea-92a6-e8253a39d023.png)

**Comment by justinmk3** [comment]
In Toolkit 1.12 , I see the Schemas node for those regions. So I assume this can be closed.

**Comment by sliedig** [comment]
Thank you!
