### ISSUE TITLE
Viewing state machine errors

### ISSUE THREAD

**Issue by ury** [aws/aws-toolkit-vscode#1069]
**Desktop (please complete the following information):**

-   OS:  Windows 10
-   VS Code version: 1.44.2
-   AWS Toolkit extension version: 1.9.0

**Question**

Hi,
Is there a way to view the errors in the machine state json file?

**Comment by wong-a** [comment]
@ury When you have an Amazon States Language file open, validation errors are shown with a squiggly line where the error is identified. If you hover your cursor over those lines, you'll see a description of it. 

The list of errors are also shown in the **Problems View**. You can open it by clicking the error and warning icons on the status bar or selecting **Problems: Focus on Problems View** from the command palette.

Here is a screenshot that shows both places to view them with red and blue rectangles over the places I noted above:

![Screen Shot 2020-05-04 at 12 44 22 PM](https://user-images.githubusercontent.com/55506708/81007309-d6ec1c00-8e05-11ea-9033-a076ffcaced6.png)

**Comment by ury** [comment]
I guessed that something is wrong with my VS Code setup.  I'm not getting either of the above.
For example, in the screenshot below, I changed the "Next" value to a non-existing state name - no problem is reported:
![image](https://user-images.githubusercontent.com/827898/81036521-18350800-8ea8-11ea-8c5c-04d936ec5122.png)

Is it an cross-extension issue?

Here's a list of my installed extensions:

> code --install-extension amazonwebservices.aws-toolkit-vscode
> code --install-extension Angular.ng-template
> code --install-extension aws-scripting-guy.cform
> code --install-extension azuredevspaces.azds
> code --install-extension champgm.cloudformation-yaml-validator
> code --install-extension Dart-Code.dart-code
> code --install-extension Dart-Code.flutter
> code --install-extension dbaeumer.vscode-eslint
> code --install-extension devadvice.serverlessconsole
> code --install-extension DotJoshJohnson.xml
> code --install-extension eamodio.gitlens
> code --install-extension EditorConfig.EditorConfig
> code --install-extension eg2.vscode-npm-script
> code --install-extension EliotVU.uc
> code --install-extension esbenp.prettier-vscode
> code --install-extension googlecloudtools.cloudcode
> code --install-extension HookyQR.beautify
> code --install-extension huizhou.githd
> code --install-extension johnpapa.angular-essentials
> code --install-extension johnpapa.Angular2
> code --install-extension johnpapa.vscode-peacock
> code --install-extension johnpapa.winteriscoming
> code --install-extension jumpinjackie.vscode-map-preview
> code --install-extension kddejong.vscode-cfn-lint
> code --install-extension mark-tucker.aws-cli-configure
> code --install-extension ms-azuretools.vscode-docker
> code --install-extension ms-dotnettools.csharp
> code --install-extension ms-kubernetes-tools.vscode-aks-tools
> code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
> code --install-extension ms-python.python
> code --install-extension ms-vscode.azure-account
> code --install-extension ms-vscode.cpptools
> code --install-extension ms-vscode.Go
> code --install-extension ms-vscode.powershell
> code --install-extension ms-vscode.vscode-typescript-tslint-plugin
> code --install-extension msjsdiag.debugger-for-chrome
> code --install-extension msjsdiag.debugger-for-edge
> code --install-extension naco-siren.gradle-language
> code --install-extension natewallace.angular2-inline
> code --install-extension nrwl.angular-console
> code --install-extension oderwat.indent-rainbow
> code --install-extension PKief.material-icon-theme
> code --install-extension reageyao.biosyntax
> code --install-extension redhat.java
> code --install-extension redhat.vscode-yaml
> code --install-extension SirTori.indenticator
> code --install-extension VisualStudioExptTeam.vscodeintellicode
> code --install-extension vscjava.vscode-java-debug
> code --install-extension vscjava.vscode-java-dependency
> code --install-extension vscjava.vscode-java-pack
> code --install-extension vscjava.vscode-java-test
> code --install-extension vscjava.vscode-maven

VS Code configuration:

> Version: 1.44.2 (system setup)
> Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
> Date: 2020-04-16T16:36:23.138Z
> Electron: 7.1.11
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.18363
>

**Comment by wong-a** [comment]
@ury Were you able to figure it out? Looking at your screenshot, I see the language mode is set to **JSON**. In order for the extension to validate the JSON as ASL code, the language must be set to **Amazon States Language (asl)**. The extension auto-detects this if the file extension is `.asl.json`, the file was the AWS Toolkit command, or you configure VS Code to treat that file as ASL.

![languagemode](https://user-images.githubusercontent.com/55506708/81623993-e8a36580-93a9-11ea-8832-7e7605b4c980.gif)

**Comment by ury** [comment]
Thanks Adam, that was it!
Changing the file extension to ".asl.json" solved the issue.
