### ISSUE TITLE
Users can browse and manage custom sample Lambda events to use as starting points for input into their Lambda handlers

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#107]
Lambda invocations require a JSON "event". You can find sample events for AWS services [in the public docs](https://docs.aws.amazon.com/lambda/latest/dg/eventsources.html), but users might want to define their own sample events.

* Create a "Sample Lambda Event Manager" view, and add it to the AWS viewCollection
* event manager tree would have two top level nodes: "Curated Events", and "Custom Events". This issue deals with the latter (#106 deals with the former)
* each node under Custom Events represents a single event that a user has created and can manage
* each custom event has a name and optional description, which will be surfaced in selection pickers
* All custom events are backed by a single json file that resides in the workspace. UX gestures to modify the file ultimately end up opening this file in an editor for the user to work with
* custom events can be added, edited, and deleted (hook up to context menus appropriately)

Later on, when we have the ability to Run/Debug Lambda Handlers locally, these events will be referenced as options to pass into the handler.

**Comment by justinmk3** [comment]
merged w/ https://github.com/aws/aws-toolkit-vscode/issues/106
