### ISSUE TITLE
Event schema code bindings directory structure rework

### ISSUE THREAD

**Issue by jimmone** [aws/aws-toolkit-vscode#1086]
When you download event schema code bindings using the AWS Toolkit the directory structure is horrible. Importing is a long mess like `import { EC2InstanceTerminateSuccessful } from './event-schemas/schema/aws/autoscaling/ec2instanceterminatesuccessful/EC2InstanceTerminateSuccessful'`. Also you can't download multiple bindings under same directory without deleting the README file first because of the following error: `Unable to place schema code in workspace because there is already a file README.md in the folder hierarchy`

It would be much cleaner if the directory structure was like `autoscaling/EC2InstanceTerminateSuccessful` so my import statements would be much cleaner `import { EC2InstanceTerminateSuccessful } from './event-schemas/autoscaling/EC2InstanceTerminateSuccessful'.` I would appreciate if the useless README.md file could be removed aswell.

What I am doing now is I remove some of the excess folders to make the import statement look cleaner `import { EC2InstanceLaunchSuccessful } from './aws-event-schemas/autoscaling/ec2instancelaunchsuccessful/EC2InstanceLaunchSuccessful'`

**Comment by ejafarli** [comment]
Thanks for the request @jimmone . The purpose of README.md is to ensure that user knows what dependencies are required to use code bindings for each respective language. 

We'll soon introduce a feature to give the user ability to override or keep existing files when collision occurs. Notification would pop up on the right bottom corner and once the user selects desired collision fix option, download will resume. That should fix any conflict issues including README.md during download of multiple bindings under the same directory. 

Regarding generated lengthy class path, they follow similar convention as AWS Java SDK. We are not planning changing them at the moment.  In the future, we might introduce versioning on the code bindings, shorten the generated class path as well as other type of fixes, but ensure that will not introduce a change to users who already took the dependency on the existing code.

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/1089 was merged and included in version 1.12 of the Toolkit
