### ISSUE TITLE
Using federated/SSO Credentials

### ISSUE THREAD

**Issue by ury** [aws/aws-toolkit-vscode#1096]
OS:  Windows_NT x64 10.0.18363
Visual Studio Code Version:  1.45.1
AWS Toolkit Version:  1.9.0

We are using AWS CloudControl with AWS SSO login and credentials.
Credentials are changing frequently (with each logging and after a few hours) and I've yet to find the proper way to work with AWS Toolkit without constantly, manually updating the /.aws/credentials file, which is one of the options described in the login page (the other being updating environment variable).

Is there a good practice for working with the AWS Toolkit from a ControlTower/feserated/SSO account?

The only mentioning of SSO login I've found is in [this issue](https://github.com/aws/aws-toolkit-vscode/issues/57), but without any resolution.

**Comment by awschristou** [comment]
The SSO feature request you referenced (#57) is something we plan to investigate (please take a moment to add a reaction to the issue, which helps us measure interest in the feature).

In the meantime, setting up a [`credential_process` based profile](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html) around your rotating credentials may be your best workaround.
