### ISSUE TITLE
Add support for Fn::GetAtt in the Step Function Resource Attributes

### ISSUE THREAD

**Issue by alexanderluiscampino** [aws/aws-toolkit-vscode#1102]
Currently, step functions can be written using the new functionality in AWS toolkit, which is quite helpful. One thing I do, is handle all deployment using serverless. For that, I parameterize my resources using the Fn::GetAtt instead of hardcoding the name of the lambda function in the JSON definition.

For example, the following state will be okay with serverless framework, but the rendering does not accept it:
```
"Downloader":{
      "Type": "Task",
      "Resource": {"Fn::GetAtt": ["download-handler", "Arn"]},
      "Catch": [
        {
          "ErrorEquals": [
            "Runtime.ExitError"
          ],
          "Next": "RedefineParameters"
        },
        {
          "ErrorEquals": [
            "Task.Failed"
          ],
          "Next": "HandleFailure"
        }
      ],
      "Retry": [ {
              "ErrorEquals": ["Lambda.ServiceException", "Lambda.AWSLambdaException", "Lambda.SdkClientException", "Lambda.TooManyRequestsException"],
              "IntervalSeconds": 5,
              "MaxAttempts": 10,
              "BackoffRate": 2
            } ],
      "ResultPath": "$.results",
      "Next": "IsCommpleted"
    }
```

**Describe the solution you'd like**
I would like this to not be flagged as a faulty JSON definition and the rendering to work

**Describe alternatives you've considered**
I have been manually removing all my parameterized resource names with empty `""`. But this can be tedious and error prone as your state machine grows in size

**Additional context**
Serverless will accept the JSON as write above, which is great. But the rendering of the state machine is not working which causes problems with dev speed

**Comment by wong-a** [comment]
Related to https://github.com/aws/aws-toolkit-vscode/issues/1016

The plugin only validates ASL, which doesn't include intrinsic functions and placeholders used in CloudFormation templates.

**Comment by alexanderluiscampino** [comment]
> Related to #1016
> 
> The plugin only validates ASL, which doesn't include intrinsic functions and placeholders used in CloudFormation templates.

Hi @wong-a, thank you for yout reply.
#1016 is indeed related to ignore a invalid ARN, so if I remove the `{"Fn::GetAtt": ["download-handler", "Arn"]}` and replace with empty `""`  it will render it, with an invalid ARN.

But if I leave the  `{"Fn::GetAtt": ["download-handler", "Arn"]}` , which is still invalid in ASL, it does not render it. Am I wrong, or should it render either way? Both empty string and the function are invalid ARN, they should just be both ignored by the renderer.

I don't care about it recognizing the placeholder, I wish for it just to render the overall state-machine.

**Comment by alexanderluiscampino** [comment]
Just a quick update on a workaround that Im using. If you define the state as follows, the renderer seems to not throw an error:
``` json
                "AddPartition": {
                        "Type": "Task",
                        "Resource": "arn:aws:states:::lambda:invoke",
                        "Parameters":{
                            "FunctionName": {"Ref": "add-partition"},
                            "Payload": "$"
                        },
                        "TimeoutSeconds": 60,
                        "Catch": [
                            {
                            "ErrorEquals": [
                                "Runtime.ExitError",
                                "Lambda.Unknown",
                                "States.Timeout",
                                "States.TaskFailed"
                            ],
                            "ResultPath": "$.errorInfo",
                            "Next": "FluxFailure"
                            }
                        ],
                        "Retry": [ {
                                "ErrorEquals": [
                                    "Lambda.ServiceException",
                                    "Lambda.AWSLambdaException",
                                    "Lambda.SdkClientException",
                                    "Lambda.TooManyRequestsException"
                                ],
                                "IntervalSeconds": 5,
                                "MaxAttempts": 10,
                                "BackoffRate": 2
                                } ],
                        "End": true
                    
```

**Comment by wong-a** [comment]
Thanks for the follow-up @alexanderluiscampino.

The validator only checks that `Parameters` is an object and does not validate the fields for each service integration. This is why the CloudFormation syntax isn't marked as invalid there.

**Comment by alanbo** [comment]
@alexanderluiscampino , you major pain point is not being able to render the state machine when it is invalid but in fact could be rendered, right?

**Comment by alexanderluiscampino** [comment]
@alanbo, yes, I'd like to be able to use this sort of nomenclature:

`"Resource": {"Fn::GetAtt": ["download-handler", "Arn"]},`

And still be able to render it and visualize it on the right hand side.

**Comment by ffxsam** [comment]
Just wanted to throw my hat into the ring here, in support of this change/fix. I understand `"Resource": {"Fn::GetAtt": ["download-handler", "Arn"]}` is not valid as far as a raw state definition. But if the purpose is to help us visualize the step function before deploying it, and many people are using SAM or Serverless Framework, it would make sense to allow `Resource` to be an object.

It's a bit tedious to go through and temporarily replace the resources with strings.

**Comment by alanbo** [comment]
@ffxsam , I recommend you looking into definition substitutions. This way you can use placeholders in your state machine json and add a list of substitutions with "DefinitionSubstitutions" property. Example of a placeholder: `${dollar_sign_brace}` .
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-definitionsubstitutions

**Comment by bryceitoc9** [comment]
Closing at the request of @alanbo (SFN team).

**Comment by ffxsam** [comment]
@bryceitoc9 I noticed this was closed with no comments. Is this a `wontfix`? What's the status of this?
