### ISSUE TITLE
Step Functions: Add lint highlighting for missing .$

### ISSUE THREAD

**Issue by krissmilne** [aws/aws-toolkit-vscode#1116]
Step Functions ASL language requires a trailing '.$' for object reference lookups in the input.

For example

`"Demo State": {
    "Type": "Pass",
    "Comment": "Demonstrate the use of dot dollar",
    "Parameters": {
        "myVariable.$":"$.inputVariable"
    }
    "End": true
}`

This should be relatively easy to flag in the step function asl linter. If JSON value starts with '$.' require the JSON key to end with '.$'. The same should also be highlighted in the reverse. If the JSON key ends with '.$' require the JSON value to start with '$.'.

This is an easy thing for developers to overlook (it's happened to me multiple times :) )

**Comment by wong-a** [comment]
Thanks for the feature request @krissmilne. Create/UpdateStateMachine API validates this, so it makes sense for the linter to do this as well.

I created an issue in amazon-states-language-service, where the functionality will be implemented: https://github.com/aws/amazon-states-language-service/issues/26

**Comment by alanbo** [comment]
"The same should also be highlighted in the reverse" - I skipped the reverse. I think some people may want to use a string that starts with $ or even a json path as a string value of regular property. While unusual, it could be a genuine use case.

**Comment by justinmk3** [comment]
AWS Toolkit 1.11.0 has been released, which fixes this issue.
