### ISSUE TITLE
Step Functions: "State cannot be reached error" when it can be

### ISSUE THREAD

**Issue by farski** [aws/aws-toolkit-vscode#1117]
**Describe the bug**

I have a Step Function defined in ASL that [includes a state](https://github.com/PRX/Porter/blob/master/template.yml#L2690) used as a catcher for a different `Map` type [state](https://github.com/PRX/Porter/blob/master/template.yml#L2122). When this state machine/SAM template is deployed, that state does not raise any errors, and correctly appears in the diagram as one of the output paths of the `Map` state.

![Screen Shot 2020-05-28 at 6 52 18 AM](https://user-images.githubusercontent.com/3483/83132790-e92d4300-a0af-11ea-819d-7d47577cce96.png)

If I pull this ASL definition into it's own file to get checked my AWS Toolkit, the `Tasks Map Catcher` state triggers an error: 

>The state cannot be reached. It must be referenced by at least one other state.

```json
{
	"resource": "/Users/farski/Repositories/Porter/state-machine.asl.json",
	"owner": "_generated_diagnostic_collection_name_#5",
	"severity": 8,
	"message": "The state cannot be reached. It must be referenced by at least one other state.",
	"startLineNumber": 694,
	"startColumn": 5,
	"endLineNumber": 694,
	"endColumn": 24
}
```

There seems to be a discrepancy between the way AWS Toolkit is checking for state reachability and the way Step Functions itself is resolving possible transitions.

**To Reproduce**

Save the ASL from [this template](https://github.com/PRX/Porter/blob/master/template.yml#L1997) to its own file and have it checked by AWS Toolkit. Compare the result with a deploy of that template.

**Expected behavior**

No error.

**Desktop:**

-   OS: macOS 10.15.4
-   Visual Studio Code Version: 1.45.1
-   AWS Toolkit Version: 1.10

**Comment by farski** [comment]
@alanbo How long does it take for work in ASLS to get into the VSC toolkit?

**Comment by alanbo** [comment]
I will update the AWS Toolkit to the new version of ASLS and it will be available with the next release. Usually, merged/released updates to the ASLS npm package will be available with the next release of the AWS Toolkit.

**Comment by shopsinc** [comment]
I've encountered a similar problem and I've managed to whittle it down to a very simple step function where it breaks simply by changing the order the states appear in the file.  The first case works, the second fails. 
![works](https://user-images.githubusercontent.com/984663/90446144-e179ab00-e0ae-11ea-96a0-a50d64f8e444.png)
![broken](https://user-images.githubusercontent.com/984663/90446421-564ce500-e0af-11ea-8e2c-1106de2205fd.png)

**Comment by justinmk3** [comment]
@shopsinc what version of AWS Toolkit are you using exactly?

**Comment by shopsinc** [comment]
1.12.0

**Comment by wong-a** [comment]
Reproduced the issue @shopsinc reported in version 1.13.0 with the following definition. It happens when the `Next` state appears *before* the Choice state where it is referenced. I created an issue in to fix this in https://github.com/aws/amazon-states-language-service/issues/53

```
{
  "StartAt": "ChoiceState",
  "States": {
    "FailState": {
      "Type": "Fail"
    },
    "ChoiceState": {
      "Type": "Choice",
      "Choices": [
        {
          "Variable": "$.myVariable",
          "StringEquals": "bug",
          "Next": "FailState"
        }
      ]
    }
  }
}
```

Moving the state after the choice state does not trigger the warning:
```
{
  "StartAt": "ChoiceState",
  "States": {
    "ChoiceState": {
      "Type": "Choice",
      "Choices": [
        {
          "Variable": "$.myVariable",
          "StringEquals": "bug",
          "Next": "FailState"
        }
      ]
    },
    "FailState": {
      "Type": "Fail"
    }
  }
}
``` 

Adding `Default` field for the same state also doesn't trigger a warning:

```

{
  "StartAt": "ChoiceState",
  "States": {
    "FailState": {
      "Type": "Fail"
    },
    "ChoiceState": {
      "Type": "Choice",
      "Choices": [
        {
          "Variable": "$.myVariable",
          "StringEquals": "bug",
          "Next": "FailState"
        }
      ],
      "Default": "FailState"
    }
  }
}
```

Note that this is a separate problem from what was initially reported by @farski.
