### ISSUE TITLE
Unable to Publish to Step functions in my region

### ISSUE THREAD

**Issue by sashamitrovich** [aws/aws-toolkit-vscode#1131]
**Describe the bug**

When I try Quick Update of my Step function, the dialog shows no available Step functions, because it's looking in the wrong region (es-east-1) and my stuff is in Europe (Stockholm):

<img width="748" alt="Screenshot 2020-06-04 at 09 20 31" src="https://user-images.githubusercontent.com/15609655/83727075-c917f980-a644-11ea-9d06-0edc5f61c9dd.png">

Downloading the definition of the Step function from my region in the AWS: Explorer worked without issues. 

**To Reproduce**

Try publishing or updating a step function to a region different than us-east-1

**Expected behavior**

I'd like to be able to update an existing Step function in a region of my choosing.

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Mac OS 10.15.5 (19F96)
-   Visual Studio Code Version:
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (2 wks ago)
-   AWS Toolkit Version: 1.10.0

**Comment by wong-a** [comment]
Hi @sashamitrovich, "Quick Update" and "Quick Create" use as many defaults as possible to reduce friction in performing these actions. They use the default region specified in your AWS profile. If not specified, it defaults to us-east-1. To publish to another region, you can change the default region in your credentials profile or create a new one.

Create and update commands with a fuller set of options is something we would like to add in the future.

See the following documentation about configuring credentials:
* https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/setup-credentials.html
* https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html

**Comment by sashamitrovich** [comment]
Thanks so much, @wong-a. I confirm that adding the setting
```regions = eu-north-1``` to the profile did the trick.
