### ISSUE TITLE
Deploying Layers - Error - does not contain a package.json file

### ISSUE THREAD

**Issue by stuartabrown** [aws/aws-toolkit-vscode#1137]
**Describe the bug**

I am following the guide at https://aws.amazon.com/blogs/compute/working-with-aws-lambda-and-lambda-layers-in-aws-sam/ and everything works perfectly working locally with layers (code in `dependencies/nodejs`) and running `sam local start-api` however as soon as I try to deploy from VS Code `Deploy SAM Application` I get the following error:
```
Building SAM Application...
Error with child process: Building function 'TempConversionFunction'
,Running NodejsNpmBuilder:NpmPack
,Error: NodejsNpmBuilder:NpmPack - NPM Failed: npm ERR! code ENOLOCAL
npm ERR! Could not install from 
"../../../../../../../Users/stuartbrown/Documents/web/serverless-test-app/hello-world" as it does not contain a package.json file.

```
**To Reproduce**

Follow the tutorial at https://aws.amazon.com/blogs/compute/working-with-aws-lambda-and-lambda-layers-in-aws-sam/.  The last comment a year ago on that post seems to report the same issue.

**Expected behavior**

I am expecting the application to be deployed with the inclusion of a layer

**Desktop (please complete the following information):**

-   OS: MacOS Catalina
-   Visual Studio Code Version:
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
-   AWS Toolkit Version:
OS:  Darwin x64 19.4.0
Visual Studio Code Version:  1.45.1
AWS Toolkit Version:  1.10.0

**Additional context**

If I run the deploy from the CLI `sam package --template-file template.yaml --s3-bucket bucketname --output-template-file out.yaml` & 
`sam deploy --template-file ./out.yaml --stack-name test-app-stack --capabilities CAPABILITY_IAM` the deployment is successful and the app works.  It's just via the VS Code toolkit that I get the error
<img width="565" alt="Screenshot 2020-06-08 at 17 15 44" src="https://user-images.githubusercontent.com/44773993/84054754-c2261980-a9ab-11ea-8041-ba0df05a86e8.png">

**Comment by justinmk3** [comment]
Thanks for the report! This is a known issue, see https://github.com/aws/aws-toolkit-vscode/issues/746
