### ISSUE TITLE
Step Functions: Cannot render a state machine with a numeric parameter

### ISSUE THREAD

**Issue by andreylh** [aws/aws-toolkit-vscode#1140]
**Describe the bug**

I am trying to render a state machine with a numeric parameter, but I got `Value expected asl(516)`

**To Reproduce**

Create the following state machine and try to render:

```
{
  "StartAt": "PassState",
  "States": {
    "PassState": {
      "Type": "Pass",
      "Result": {
        "data1": ${Param1}
      },
      "End": true
    }
  }
}
```

**Expected behavior**

Render the state machine correctly

**Screenshots**

![image](https://user-images.githubusercontent.com/3869224/84141899-4323f600-aa2a-11ea-84cf-d628958384a6.png)

**Desktop (please complete the following information):**

 - OS:  Linux x64 5.5.16-100.fc30.x86_64
 - Visual Studio Code Version:  1.45.1
 - AWS Toolkit Version:  1.10.0

**Comment by vaib-amz** [comment]
Hi,

In the example snippet posted on the issue, is `${Param1}` supposed to be a placeholder variable to be used for the [DefinitionSubstitutions property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-definitionsubstitutions) for the State Machine CloudFormation resource? Currently, only string-type values are supported for the `DefinitionSubstitutions` property and as placeholder variables within the State Machine definitions.

**Comment by justinmk3** [comment]
AWS Toolkit 1.11.0 has been released, which fixes this issue.
