### ISSUE TITLE
Test-drive the SAM "debug config" feature

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#1146]
The [`feature/debugconfig` branch](https://github.com/aws/aws-toolkit-vscode/tree/feature/debugconfig) implements the [new SAM debugging experience](https://github.com/aws/aws-toolkit-vscode/blob/162857540c2b0df8b20c20b76a358021f986f2c3/designs/sam-debugging/local-sam-debugging.md) based on VS Code [_launch configurations_](https://code.visualstudio.com/docs/editor/debugging#_launch-configurations). This new experience replaces the old [Run Locally | Debug Locally](https://github.com/aws/aws-toolkit-vscode/blob/9231bf0f5499448a715f3747a763700d41e10f9d/extension-readme.md#serverless-applications-lambda-functions-and-cloudformation-stacks) experience.

You can try out the new experience and give us feedback:

## Install

1. Download [aws-toolkit-vscode-1.12.0-SNAPSHOT.vsix](https://github.com/aws/aws-toolkit-vscode/releases/tag/1.12.0-1%2Bdebugconfig) (updated 22 July 2020)
3. Use the VSCode `Extensions: Install from VSIX...` command to install it.
4. Extension version should be `1.12.0-SNAPSHOT`

## Usage

The updated AWS Toolkit allows you to run or debug AWS SAM Lambdas locally by running a launch config of `type: aws-sam`. 

1. Create a launch config for a SAM Lambda using any of the following approaches:
   - Visit the `template.yaml` in your SAM project, place the cursor on a lambda resource, and click the `Add Debug Configuration` CodeLens. This will add a pre-populated launch config to your `launch.json`.
   - **Alternative:** visit the handler source code (`.js`, `.cs`, or `.py` file) in your SAM project, place the cursor on a lambda handler, and click the `Add Debug Configuration` CodeLens. This will add a pre-populated launch config to your `launch.json`.
   - **Alternative:** Edit `launch.json` and create a new item by hand (where `projectRoot` points to a valid directory,  `lambdaHandler` is the name of the handler, and `runtime` is a valid runtime (`nodejs12.x`, `python3.7`, `dotnetcore2.1`, ...)):
     ```
     {
        "type": "aws-sam",
        "request": "direct-invoke",
        "name": "my-config",
        "invokeTarget": {
            "target": "code",
            "projectRoot": "src",
            "lambdaHandler": "myHandler"
        },
        "lambda": {
            "runtime": "nodejs12.x",
            "event": {},
            "environmentVariables": {}
        },
        "sam": {}
        "aws": {}
     },
     ```
2. Visit the "Run" panel (in the VS Code sidebar)
3. Select the launch config (named `my-config` in the above example)
   ![image](https://user-images.githubusercontent.com/55561878/84336098-6a261900-ab4b-11ea-908d-e26e578ff031.png)
4. Hit F5 or click the "play" button in the Run panel

**Comment by dtelaroli** [comment]
+1

Impossible configure it with multi folder workspace

**Comment by justinmk3** [comment]
@dtelaroli Can you open a new issue with steps to reproduce the issue? 

Closing this issue, because this feature was released today.
