### ISSUE TITLE
AWS Toolkit does not support most recent version of SAM CLI 0.52.0

### ISSUE THREAD

**Issue by jayheavner** [aws/aws-toolkit-vscode#1150]
**Desktop (please complete the following information):**

-   OS: Mac
-   VS Code version: 1.36.1
-   AWS Toolkit extension version: View AWS Toolkit Logs

**Question**

I'm getting an error `Your SAM CLI version 0.52.0 does not meet requirements (0.38 < version < 0.50.0). Please check the Marketplace for an updated Toolkit.` Per the Marketplace, I am running the most current version.

**Comment by abrooksv** [comment]
The latest versions of the toolkit require a minimum VSCode version of 1.42.0
