### ISSUE TITLE
Build failed when requirement "line-bot-sdk"

### ISSUE THREAD

**Issue by chris80124** [aws/aws-toolkit-vscode#1151]
**Desktop (please complete the following information):**

-   OS: Windows 10
-   VS Code version: 1.46.0
-   AWS Toolkit extension version: 1.10.0

**Question**

I create a new basic SAM Application with python3.8, and add `line-bot-sdk` in requirement.txt.
When I execute Debug Locally, I get these error messages.
![擷取](https://user-images.githubusercontent.com/57885457/84754138-82d27b00-aff2-11ea-8564-e5690cc39daf.PNG)

How to solve this problem?

**Comment by bryceitoc9** [comment]
Looks like this may be an issue with the aws-lambda-builders package (see a similar issue in JB): https://github.com/aws/aws-toolkit-jetbrains/issues/1169

Does this work if you manually run the build command? Check the `AWS Toolkit Logs` output channel for the raw SAM command being executed (if it's not there, swap your AWS log level to  Debug and rerun).
