### ISSUE TITLE
disconnect or logout

### ISSUE THREAD

**Issue by wilberh** [aws/aws-toolkit-vscode#1161]
Is there a way to disconnect / logout from an AWS connection in VSCode?

**Comment by justinmk3** [comment]
Good question! That feature doesn't exist yet. 

Can you describe your use-case? I can imagine one use-case: to avoid unnecessary network/service requests.

We could add a "Disconnect" action in the root menu:

<img width="381" alt="Screen Shot 2020-06-18 at 12 50 48 PM" src="https://user-images.githubusercontent.com/55561878/85065685-753c0300-b162-11ea-8d79-25fe6f946b7f.png">

And:

- persist that choice
-  next time VSCode starts up, the AWS Toolkit would not connect until explicitly requested.

**Comment by awschristou** [comment]
At this time, the command **AWS: Sign out** is available in the Command Palette. 
This command disconnects your AWS Explorer, but does not terminate any connections you may have open in other tabs (for example, if you were searching schemas or invoking a Lambda function).

**Comment by justinmk3** [comment]
Because the `AWS: Sign out` command is available and there doesn't seem to be much interest in the other suggestions, let's close this.

**Comment by justinmk3** [comment]
Note also that VSCode provides the ability to disable any extension. Disabling an extension requires a reload, but re-enabling the extension does not. 

<img width="654" alt="Screen Shot 2020-10-13 at 2 26 49 PM" src="https://user-images.githubusercontent.com/55561878/95918264-593b1d80-0d60-11eb-8f00-8c7247647342.png">
