### ISSUE TITLE
An error occurred trying to run SAM Application locally: Template does not contain any Lambda resources

### ISSUE THREAD

**Issue by heitorlessa** [aws/aws-toolkit-vscode#1177]
**Desktop (please complete the following information):**

-   OS: Mac Mojave 10.14.6 
-   VS Code version: 1.46.1
-   AWS Toolkit extension version: 1.10.0

**Question** - Trying to either invoke or debug a Python function locally through the toolkit and I receive this error

"An error occurred trying to run SAM Application locally: Template does not contain any Lambda resources"

**templates.json** file generated

```json
{
    "templates": {
        "src/backend/payment/template.yaml": {
            "handlers": {
                "collect.lambda_handler": {
                    "event": {
                        "chargeId": "ch_1Edea2F4aIiftV70kgOJC7FO",
                        "customerId": "test_customer_id",
                        "outboundFlightId": "test_flight_id"
                    },
                    "environmentVariables": {
                        "PAYMENT_API_URL": "https://ct21smx12c.execute-api.eu-west-1.amazonaws.com/prod/charge"
                    }
                }
            }
        }
    }
}
```

Using `SAM CLI` as a standalone works just fine both building and invoking the function - Any pointers would be much appreciated.

Thanks

**Comment by awschristou** [comment]
Can you check if `collect.lambda_handler` matches your template.yaml file's `Handler` value? 

If you run "Create new SAM Application" from the command palette of VS Code and produce an application, I'd be interested to hear if you are successful in running/debugging this. If so, using the Configure CodeLens to produce a templates.json entry may offer some clues around the configuration differences.

**Comment by heitorlessa** [comment]
I’ll come back to you on that result next week - I’m still on PTO.

**Comment by justinmk3** [comment]
We've released several improvements since then. If this is still an issue please leave a comment, thanks!
