### ISSUE TITLE
Configuration options for templates.json

### ISSUE THREAD

**Issue by heitorlessa** [aws/aws-toolkit-vscode#1178]
**Desktop (please complete the following information):**

-   OS: Mac Mojave 10.14.6 
-   VS Code version: 1.46.1
-   AWS Toolkit extension version: 1.10.0

**Question**

Is the `templates.json` configuration options available anywhere? 

I'm trying to invoke and debug functions with their respective event and environment variables file, parameter overrides, debug port to connect to, and custom manifest file to use.

**Comment by awschristou** [comment]
Hi @heitorlessa , unfortunately the `templates.json` is not documented. We're working on a new debug experience, which leverages the VS Code launch.json debug configurations, and no longer uses templates.json. If you're interested in trying this out (and seeing its associated design docs), please have a look at #1146 . We'd be interested in hearing any feedback you have!

**Comment by justinmk3** [comment]
AWS Toolkit 1.12 was released now, including the new [SAM local Lambda debugging experience](https://github.com/aws/aws-toolkit-vscode/pull/1215) which leverages VS Code "launch configurations". 

Documentation: https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/run-debug-sam-app.html

**Comment by heitorlessa** [comment]
Thanks a lot Justin
