### ISSUE TITLE
Document how to build and install Extension locally

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#118]
Until the extension is on the marketplace, we may wish to provide guidance on how users can build and install the toolkit into their own VS Code instances without having to run it in the debugger from an experimental VS Code instance.

Looks like the following is necessary:
* updates to README.md to satisfy requirement "Image URLs in README.md and CHANGELOG.md need to resolve to https URLs." It might be that vsce doesn't support the markdown aliasing currently used the file?
* update `repository` section of `package.json`
User instruction:
* `npm install -g vsce`
* run `vsce package` from the extension root
* on successful completion, run the following from the extension root
  * `code --install-extension aws-toolkit-vscode-<VERSION>.vsix`

Information sources:
* https://code.visualstudio.com/docs/extensions/publish-extension
* https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by stuti8P** [comment]
Even after completing the above steps.  code --install-extension aws-toolkit-vscode-<VERSION>.vsix throws the error bash:VERSION no file or directory.

**Comment by awschristou** [comment]
@stuti8P did you type in the literal `code --install-extension aws-toolkit-vscode-<VERSION>.vsix` or did you replace `<VERSION>` with the version produced? If you run `ls` (or `dir`) for `*.vsix`, you can see what vsix files you have, and use that filename. At this time, it's likely 0.0.1, so you'd run the command `code --install-extension aws-toolkit-vscode-0.0.1.vsix`
