### ISSUE TITLE
Code validation ("ASL Linter") itemspath required although it is specified as Optional

### ISSUE THREAD

**Issue by stagr** [aws/aws-toolkit-vscode#1196]
**Code validation ("ASL Linter") itemspath required in Map State although it is specified as Optional**

Given the following minimal example:

`{
  "StartAt": "Test Map State",
  "States": {
    "Test Map State": {
      "Type": "Map",
      "Iterator": {
        "StartAt": "State A",
        "States": {
          "State A": {
            "Type": "Pass",
            "End": true
          }
        }
      },
      "End": true
    }
  }
}`

The following error message is given in VS Code:

> Missing property "ItemsPath".

Trying to render the state machine also fails.

**To Reproduce**

Create a file with the above contents in VS Code.

**Expected behavior**

Since ItemsPath is optional it should not be required by the code validation.

**Workaround**

Explicitly add "ItemsPath": "$":

`{
  "StartAt": "Test Map State",
  "States": {
    "Test Map State": {
      "Type": "Map",
      "ItemsPath": "$",
      "Iterator": {
        "StartAt": "State A",
        "States": {
          "State A": {
            "Type": "Pass",
            "End": true
          }
        }
      },
      "End": true
    }
  }
}  `

**Screenshots**

![image](https://user-images.githubusercontent.com/20762751/87790949-c7cb1680-c817-11ea-8cc4-758bf3b46ff7.png)

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Visual Studio Code Version: 1.47.1
-   AWS Toolkit Version: v1.10.0

**Comment by justinmk3** [comment]
cc @alanbo

**Comment by alanbo** [comment]
I acknowledge the bug. I'm looking into it.

**Comment by justinmk3** [comment]
AWS Toolkit 1.11.0 has been released, which fixes this issue.
