### ISSUE TITLE
Retry same profile again, after refreshing credentials, instead of manually selecting profile again

### ISSUE THREAD

**Issue by felipe1982** [aws/aws-toolkit-vscode#1226]
**Describe the bug**

when I restart vscode in the morning, my aws credentials have expired, but the aws toolkit gives me an error. This is understandable.

Then I refresh my credentials, but aws toolkin does not link back to the profile which I have previously chosen. I have to manually select the profile (again).

Expected behaviour is that it keeps trying the new credentials every 100 seconds, silently, until successful.

**To Reproduce**

Select a profile which has fresh credentials.
Allow those creds to expire.
Close vscode
Open vscode
Refresh credentials

**Expected behavior**

I expect aws toolkit to retry the same profile again.

**Desktop (please complete the following information):**

OS:  Linux x64 4.19.104-microsoft-standard
Visual Studio Code Version:  1.47.3
AWS Toolkit Version:  1.12.0

**Additional context**

I am using wsl2

**Comment by awschristou** [comment]
Thank you for reaching out @felipe1982 , to better understand the scenario, can you provide a little more information about your credentials. Are they MFA based, do you have an external tool rotating the credentials files, or some other situation?

**Comment by felipe1982** [comment]
Yes, I am using federated credentials, not MFA based. I'm using [saml2aws](/Versent/saml2aws) to get credentials from SAML provider. They expire after 8 hours.

**Comment by acdha** [comment]
I hit this for the same reason — and since our SSO has a shorter TTL it's more noticeable. It would also be nice if the UI handled the expired credential error code directly since you could provide a nice experience for anyone using SSO: “Your credentials have expired. Please restart your session.” and do what tools like Terraform do and wait for `~/.aws/credentials` to update before seamlessly resuming.

**Comment by justinmk3** [comment]
AWS Toolkit 1.41 should greatly improve the case where the SDK understands that the credentials "expired", and then will refresh the credentials from the credentials provider.

However the case of an external tool / user manually updating the ~/.aws/credentials file still isn't solved. That is the case described in this issue, however it's also covered by #2465 , so let's track it there.
