### ISSUE TITLE
Missing "Run Locally", "Debug Locally", "Configure"

### ISSUE THREAD

**Issue by Chigozie391** [aws/aws-toolkit-vscode#1227]
-   OS: Windows 10
-   VS Code version:1.47.3
-   AWS Toolkit extension version:1.12.0

**Question**
How do I enable this in the latest version of this extension

Action buttons are missing after update to the latest version of AWS tool kit extensions.
![image](https://user-images.githubusercontent.com/24697877/89132146-ddc02300-d509-11ea-8f5a-15d56d7408b6.png)

**Comment by drziskind** [comment]
Happens to me too, going back to 1.11.0 and restarting vscode with no other changes brings back the commands

**Comment by awschristou** [comment]
A new SAM local Lambda debugging experience was released in version 1.12.0 of the AWS Toolkit. The changes can be seen in PR #1215 . This experience makes use of VS Code _launch configurations_, as well as VS Code's standard entrypoints for debugging: 
- using F5 to start debugging
- the Run panel
- VS Code commands such as `Run: Start Without Debugging` and `Debug: Select and Start Debugging`

Documentation about the new debugging experience can be found at: https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/run-debug-sam-app.html

Summary: The CodeLenses mentioned in the original post are no longer available. After creating a debug configuration, you can press F5 to debug.
