### ISSUE TITLE
Debugging Lambdas Locally with Credentials

### ISSUE THREAD

**Issue by 4n7h0** [aws/aws-toolkit-vscode#1234]
Hello, 

Until now,  I had the following actions "Run Locally / Debug locally / Configure" just at the top of my lambda source code. Now, I just have an "add a debug configuration" .... Anyway,  I tried to create and adjust this configuration (lauch.json from vs code) and now, I can debug and attach vs code debugger to the SAM application / Docker to test and debug my lambda function locally with a payload, environment variables,etc... but... 
I still have an issue: it seems that my AWS profile is not used during the debug because I have a "internal error: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records."  when I tried to use AWS SDK (especially a S3.getObject()) in my lambda function. 
Until now, I didn't have to provide my AWS credentials in my lambda functio, the AWS Toolkit did the job and everything worked fine.
Can you tell me what's wrong ? I guess I miss something but I don't know where... :/ 
Maybe, you can give me some hint ? 
Best Regards.

**Comment by 4n7h0** [comment]
Hello, 

I'm sorry. 
I just tried on my windows PC and it works. My lambda is executed without any issue.
The issue "internal error: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records." is only on my mac. 
I don't know why for now but I guess I missed something during the install/setup (AWS CLI,  SAM CLI,  DOCKER, AWS Toolkit).

**Comment by bryceitoc9** [comment]
Hi @4n7h0,

The previous SAM functionality always used the `default` AWS credentials profile since there was no concept of a credentials profile tied to SAM. Are you using a different profile with invalid credentials on the Mac? If you're unsure, you should be able to remove the entire `aws` field from the debug configuration.

**Comment by awschristou** [comment]
Documentation related to the debug configuration can be found in the user guide, at https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/run-debug-sam-app.html . You may be interested in checking out the section `AWS Connection ("aws") properties` to reference a specific profile.

**Comment by justinmk3** [comment]
As @bryceitoc9 mentioned, the `aws` field is optional, so leave it out (if you were including it). Also if you can post your launch config here, that may help.

**Comment by 4n7h0** [comment]
Hi everyone ! 
Now, it works on my mac !!! 
My bad, when I created my AWS profile,  I named it by my name and not as **default** (thanks @bryceitoc9).
It's all my fault. 
Thank you so much for your help!
Best regards! :)
