### ISSUE TITLE
As a user, I can create a new Sam Application project so that I can start developing, without having to manually create files or run commands outside the Toolkit

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#124]
This is a wizard-like flow that creates an initial Sam Application for the user, which is then ready for implementing, iterating, and deploying.

Acceptance criteria:
* User doesn't have to create files by hand
* User doesn't have to run commands at a command prompt
* User has a set of files produced for them that they can start working from

---

A Command Palette command kicks off a `sam init` call to make a new SAM Application.

Before the application can be created, some information is needed. Instead of a Web View, the information will be obtained in wizard fashion using the Command Palette box as follows:

* A selector presents valid Runtimes for selection
* A selector then presents valid Application Templates to produce the application from
* A selector then presents possible locations to select where to place the new application code
  * Shows all current VS Code Workspace folders, and a `Let me choose a different location...` option
  * If `Let me choose a different location...` is selected...
    * A folder picker comes up, letting user select a custom location
    * This folder is added to the VS Code workspace folders (after sam init is run), if it is not contained within the existing workspace folders
    * If the folder picker is cancelled, flow returns to the folder selector
* An input then prompts for the name of the new application
  * The input description should show the final folder location (app name appended to the selected location)
  * This is validated for legal file characters, and that the length of the final folder is not too long

Additional requirements:
* The 'wizard' should have a 'Back' button that goes to the previous stage of the flow
* `sam init` is called after all information has been gathered

Here is a mock flow:

![new-app-flow](https://user-images.githubusercontent.com/39839589/49887129-60a1e080-fdf0-11e8-88cc-d3979e3008af.gif)

**Comment by mpiroc** [comment]
Shelving this for now. WIP here: https://github.com/aws/aws-toolkit-vscode/tree/pirocchi/init
