### ISSUE TITLE
SAM CLI detection: "Don't show again" if SAM CLI is not found

### ISSUE THREAD

**Issue by davidmcl** [aws/aws-toolkit-vscode#1244]
**Is your feature request related to a problem? Please describe.**

I don't have the SAM-CLI installed ... and don't plan to do so (at least until you have an option to install on Linux that doesn't include Homebrew...it's a personal thing :-) ; so an error message repeatedly comes up to tell me to find it.

**Describe the solution you'd like**
Setting to disable/ignore specific service(s) in the toolkit...especially as you add more services; it might be a good thing to consider anyway.

**Describe alternatives you've considered**
...I was able to put a dummy `sam` file in /usr/bin/local to quiet the messages...so it's an annoyance, not critical

Thanks,
David

**Comment by justinmk3** [comment]
We are currently making improvements to SAM CLI detection, so this is a timely request :)

Just for reference, is the message showing once at startup, or more often than that?

I think it makes sense to add a "Don't show this again" button on the message.

**Comment by davidmcl** [comment]
Sorry I didn't get back to you sooner...got busy and also was in the midst of changing from gmail to WorkMail :-)

Anyway, all of "this" was going on while I was enabling the settings synch feature new on VSCode 1.48, so some of the "repeats" may have been as a result of that synching process (3 physical machines plus 6 dev VMs - 4 linux & 2 windows).

Part of it was that the SAM Cli location got cleared as some instances had a value and some didn't ...probably a timing issue of the vscode synch...but what seems repeatable in my attempts to diagnose this, is that the message seems to repeat on each start-up of VSCode after a short period (timeout?) and, of course, if I try to access the SAM functions.

Hope that helps.
David

**Comment by justinmk3** [comment]
> while I was enabling the settings synch feature new on VSCode 1.48

That might be helped by https://github.com/aws/aws-toolkit-vscode/pull/1241 (unreleased, expected in Toolkit 1.13) which changes the setting to `machine` scope, depending on the environments.

> seems to repeat on each start-up of VSCode after a short period

For this we can add a "Don't show again" option. Or perhaps we should never show again, until user explicitly does something that requires `sam`. 

Also related: https://github.com/aws/aws-toolkit-vscode/pull/1242

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/1242 removes this startup behavior. Could you confirm that it works for you?

1. Download and extract [buildArtifacts.zip](https://github.com/aws/aws-toolkit-vscode/files/5315323/buildArtifacts.zip)
2. In VSCode run the  `Install from VSIX...` command to install the extracted `*.vsix`.
3. Reload VSCode and verify that the Toolkit has the new version (not the release/older version).

**Comment by justinmk3** [comment]
Toolkit 1.15 was released today, the "missing SAM CLI" message now only appears if/when you explicitly set the `aws.samcli.location` vscode setting.
