### ISSUE TITLE
View CloudWatch Logs

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#126]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

* Users are able to view cloud watch logs for lambda functions that they have access to
* TBD: Date range / all log groups+entries / local vs temp storage

**Describe alternatives you've considered**

**Additional context**

**Comment by micholas** [comment]
This is a key focus of mine. The functional limitations and throttling limits of the CWL API make it not really suitable for multiple team members making API calls as part of their workflow for this use case. The CW Logs need to be indexed somewhere to support more powerful queries, visually interactive analytics, and more than [5 requests per second](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html). The most appropriate approach that I've experienced is to stream CWL into AWS Elasticsearch and have end users and/or our UI hit AWS ES which enables much more powerful searches and better handles user load.  Key concepts:

1. Enable user to select which CWL group(s) to index into AWS
2. Enable user to select an AWS ES cluster into which logs will be indexed (and workflow with reasonable defaults to spin up a new ES cluster in customer's account
3. Enable user to select retention period (to age data out of AWS ES and possibly CWL). Users often store logs in CWL indefinitely. They could instead archive them in S3 or Glacier and use the cost saving towards their AWS ES cluster while having a much better user experience.
3. Automatically spin up infrastructure needed to stream logs into ES (perhaps simply Kinesis Firehose)

**Comment by justinmk3** [comment]
@bryceitoc9 is working on this

**Comment by bryceitoc9** [comment]
This was released on August 24th in the toolkit's 1.13.0 release.
