### ISSUE TITLE
ASL schema validation doesn't understand 'IsPresent' variable condition

### ISSUE THREAD

**Issue by dcitguy** [aws/aws-toolkit-vscode#1265]
When trying to create a definition file, a syntax warning is generated for using the `IsPresent` condition (which is perfectly valid and works in state machines). This is preventing the ability to visualize the state machine in VS Code.

Sample:
```json
"StartAt": "Choice",
"States": {
    "Choice": {
        "Type": "Choice",
        "Choices": [
            {
                "Variable": "$.sheet_data.column_table",
                "IsPresent": false,
                "Next": "Create a Column Mapping Table"
            }
        ]
```

**Comment by wong-a** [comment]
The new ASL features, including the new Choice operators released in version 1.13 of the extension on August 24 ([Changelog](https://marketplace.visualstudio.com/items/AmazonWebServices.aws-toolkit-vscode/changelog)). Which version of the extension are you using? 

I'm able to use this state machine definition without any errors:
```
{
  "StartAt": "Choice",
  "States": {
    "Choice": {
      "Type": "Choice",
      "Choices": [
        {
          "Variable": "$.myVariable",
          "IsPresent": false,
          "Next": "NextState"
        }
      ]
    },
    "NextState": {
      "Type": "Succeed"
    }
  }
}
```
