### ISSUE TITLE
Invoke nodeJs functions using SAM Local

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#128]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

* A Gutter icon appears for functions that match the Lambda Function definitions in the Explorer which can be used to invoke locally
* Context Menu on all functions that appear to be lambda handlers has an option to invoke locally

Invoking a function locally:
* Example command when the task is invoked: `echo "{}" | sam local invoke <MyFunction> -d 5858`.
* Debug configurations created from our configuration provider (see #74) should invoke this task as a pre-launch task.

**Describe alternatives you've considered**

**Additional context**

**Comment by mpiroc** [comment]
For VS Code, I think that [CodeLens](https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup) would be an ideal way to implement this. Note that in VS (and I think VS Code), this would mirror the experience of invoking unit tests directly from code, so users should already be familiar with the UI paradigm.

**Comment by awschristou** [comment]
Gutter icons are decorative only. We are going to start with CodeLens for local Run/Debug.
Closing in favor of #135
