### ISSUE TITLE
Support opening S3 files inside VS Code

### ISSUE THREAD

**Issue by saulimus** [aws/aws-toolkit-vscode#1284]
I was a bit surprised to see that files from S3 must be saved first, before they can be opened in VS Code.
Sure, once the file is saved, VSCode does show the uri of the downloaded file which can then be followed using a modifier key+mouse click to open it.
However, seems like too much work just to open a file quickly.
There could be an option such as "Open" that would save it to a temporary folder and open it in a new tab afterwards.
Maybe even support how the normal file explorer works, allowing the user to drag the file into the editor area, as it's how I normally tend to use the explorer.

**Comment by justinmk3** [comment]
We are considering [this UX](https://github.com/aws/aws-toolkit-vscode/blob/7bae2e01c7e1da7c77a42f0f3d2edde87af0c8c8/designs/s3/design-vscode-s3.md#s3-objects):

-  Double-clicking an S3 object downloads it and opens it as a [virtual document](https://code.visualstudio.com/api/extension-guides/virtual-documents).
    -  If item is 4MB+, prompt user to ask if download should begin.

**Comment by justinmk3** [comment]
Implemented in https://github.com/aws/aws-toolkit-vscode/pull/2349 (not released yet).
