### ISSUE TITLE
Strip (or render) the formatting codes returned by sam local output

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#129]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Running SAM Local produces output that includes color coding. Try to remove these codes if they are not being rendered correctly.

**Describe alternatives you've considered**

**Additional context**

**Comment by awschristou** [comment]
TBD - we should discuss and see if SAM Local can or should help remove the color codes.

**Comment by bryceitoc9** [comment]
Are there any examples of this not rendering? SAM Local output renders to terminal correctly for me in both Windows and Ubuntu.

**Comment by awschristou** [comment]
![image](https://user-images.githubusercontent.com/39839589/55522473-fed4e300-5639-11e9-8cf1-e00a4d5674d4.png)

The sam process is run in a terminal, and we do not have access to its output. If we change how we're launching SAM CLI commands in the future, there is a better chance this will not be an issue.

Closing.
