### ISSUE TITLE
Remote coding 

### ISSUE THREAD

**Issue by patienceigiraneza2** [aws/aws-toolkit-vscode#1293]
**Desktop (please complete the following information):**

-   OS: Window
-   VS Code version: new released I downloaded today
-   AWS Toolkit extension version: new exactly now 

**Question**
I want to edit and codes files in ec2 instances but not working 
How can I do it?

**Comment by justinmk3** [comment]
> I want to edit and codes files in ec2 instances but not working

Can you expand on the exact steps you tried?

Are you asking for something like https://github.com/aws/aws-toolkit-vscode/issues/1011 or https://github.com/aws/aws-toolkit-vscode/issues/1007 ?
