### ISSUE TITLE
SAM debug cannot find SAM CLI in Toolkit 1.13+ (WSL 2)

### ISSUE THREAD

**Issue by tasq-inc** [aws/aws-toolkit-vscode#1300]
**Describe the bug**

The toolkit is unable to find SAM CLI when running a debug session on lambda functions, even when setting the path expliciltly. This appears to happen in Ubuntu 20.04 via WSL 2 as I did not encounter this issue when booting directly into Ubuntu 20.04. Installing AWS Toolkit 1.12.0 works as expected.

**To Reproduce**

1. After installing SAM CLI and updating to 1.13.0, create a launch configuration
2. Specify configuration (see below)
3. Start Debugging using the configuration
4. Notified that SAM CLI was not found

**Expected behavior**

Debugging instance is built and ran as normal.

**Screenshots**

```
{
    "configurations": [
        {
            "type": "aws-sam",
            "request": "direct-invoke",

            "name": "function_name",
            "invokeTarget": {
                "target": "code",
                "projectRoot": "src/functions/function",
                "lambdaHandler": "function.handler"
            },
            "lambda": {
                "runtime": "python3.7",
                "payload": {}
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/60201386/93291329-f7f34f00-f79f-11ea-9d47-915a585708f8.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04 (WSL 2)
-   Visual Studio Code Version: 1.49.0
-   AWS Toolkit Version: 1.13.0

**Additional context**

Lambda function is running Python 3.7 runtime.

**Comment by justinmk3** [comment]
@tasq-inc Thanks for your report.

> even when setting the path expliciltly. This appears to happen in Ubuntu 20.04 via WSL 2

In https://github.com/aws/aws-toolkit-vscode/pull/1241 (part of 1.13) the SAM CLI setting was changed to "machine" scope. I wonder if machine-scope has any quirks with WSL.

The following steps would greatly help us to debug this issue:

- Run the `AWS: View Toolkit Logs` command and check for any log messages that mention `failed to set config`. [code](https://github.com/aws/aws-toolkit-vscode/pull/1241/files#diff-3c371652fecdf0bb76a62c5d5271b2a7R55)
- Can you share the exact path (or something very similar but with private names changed to `x`). 
  - If the path has characters outside `[a-zA-Z]` please also include those.
  - Preserve the slashes `/` or `\` exactly as you have them. 
- How did you start VSCode?
- If you run the `AWS: Detect SAM CLI` command, what does it say?

**Comment by tasq-inc** [comment]
Thanks @justinmk3!

- This is the log when I try and run lambda debugging. I'm prompted with the `Cannot find SAM CLI` error just as `Building SAM Application...` shows up in the output.
```
2020-09-16 22:16:04 [INFO]: log level: info
2020-09-16 22:16:04 [INFO]: Retrieving AWS endpoint data
2020-09-16 22:16:04 [INFO]: OS:  Linux x64 4.19.84-microsoft-standard
Visual Studio Code Version:  1.49.0
AWS Toolkit Version:  1.13.0

2020-09-16 22:16:05 [INFO]: SAM CLI location: /home/linuxbrew/.linuxbrew/bin/sam
2020-09-16 22:16:13 [INFO]: Preparing to debug 'appsync_sources_v2___vsctk___debug.lambda_handler' locally...
2020-09-16 22:16:13 [INFO]: Building SAM Application...
```
- The SAM CLI path is as it is stated in the log: `/home/linuxbrew/.linuxbrew/bin/sam`
- I start VSCode by first starting opening Windows Terminal (defaulting to WSL 2, Ubuntu 20.04, using zsh). Then I navigate to my project base folder and type `code .` to open VSCode
- When running `AWS: Detect SAM CLI`, I get the following notification:
![image](https://user-images.githubusercontent.com/60201386/93420034-69e49a80-f86b-11ea-8258-0f4f94f8ce64.png)

**Comment by justinmk3** [comment]
Great, thank you! One last question, can you open devtools in vscode by running the vscode command: `Developer: Toggele Developer Tools`, then in the devtools console try this:

    require('fs').existsSync('/home/linuxbrew/.linuxbrew/bin/sam')

Does it return `true` or `false`?

**Comment by tasq-inc** [comment]
Running the above returns `false`.

**Comment by justinmk3** [comment]
Thanks, that suggests nodejs doesn't understand that path. I wonder how vscode extensions are expected to deal with this.

- In the vscode devtools console, what does `process.platform` report ?
- Are you connecting to your WSL project by the [Remote - WSL extension](https://code.visualstudio.com/docs/remote/wsl) ?
- What is the full path to the `code` you are running (`which path`)? [This (old) comment](https://www.reddit.com/r/bashonubuntuonwindows/comments/de09co/code_vscode_not_working_reset_wsl_windows_paths/) suggests there is a `code` script (as opposed to `code.exe`); if that exists perhaps it is worth a try.

**Comment by tasq-inc** [comment]
It looks like running `process.platform` reports `win32` and `which code` indeed points to a file in the windows file system (`/mnt/c/Users/Kenneth Nguyen/AppData/Local/Programs/Microsoft VS Code/bin/code`), which appears to be a bash script. I am connecting via the Remote - WSL extension.

**Comment by patricknazar** [comment]
This should be an easy fix, please prioritize this

**Comment by justinmk3** [comment]
@patricknazar since `require('fs').existsSync('/home/linuxbrew/.linuxbrew/bin/sam')` returns false it does not seem easy to me, unless we just ignore that check. But `process.platform` returns `win32` so can't just skip it for "WSL". 

Is there an easy change that I missed?

**Comment by patricknazar** [comment]
@justinmk3 I'm not saying I have a solution, but I have other extensions that execute commands in Windows and WSL no problem, I would have *thought* executing sam would be the same sort of thing. I am making the assumption that there is a os-independent way of doing this, seeing as other extensions do it. As an example, Python's "Run Python File in terminal" feature executes in both standard windows or in WSL remote. Same for Docker extension. So, whatever method they are using I would have thought would work with sam too. Feel free to point out the fault in my logic.

**Comment by evanerwee** [comment]
Issue persist in 1.14

**Comment by justinmk3** [comment]
I am working on this in https://github.com/aws/aws-toolkit-vscode/pull/1242

**Comment by bryceitoc9** [comment]
Getting around to replicating this on my end: just making sure, is everyone here using the VS Code Remote WSL extension to connect to the WSL env, or are you running VS Code in WSL via X-Server (or something else)?

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/1242 removes the "eager validation", so that whatever you have set in the "SAM CLI location" setting, will be used. Or if that setting is empty, then `sam` will be used, hoping that it will resolve in `$PATH` (this should match 1.12 behavior).

Could you confirm that it works for you?

1. Download and extract [toolkit.zip](https://github.com/aws/aws-toolkit-vscode/files/5315405/toolkit.zip)
2. From the VSCode command list (`ctrl-shift-p` or `cmd-shift-p`) run `Install from VSIX...` to install the `*.vsix` file.
3. Reload VSCode and verify that the Toolkit has the new version (not the release/older version).

**Comment by evanerwee** [comment]
Will confirm first thing in the morning (7am EST)
  
  
  
    
  

  
  
>

**Comment by tasq-inc** [comment]
Thanks, @justinmk3! Just tested and the local lambda debugger is working for me now

**Comment by evanerwee** [comment]
Thank you. Working just fine.

**Comment by patricknazar** [comment]
@justinmk3 I can also confirm it appears to be working, when can we expect it to be released?

**Comment by tolsen7** [comment]
Thank you **@justinmk3**.  This VS Code AWS toolkit update 1.15.0 solved the problem for me.  I'm using VS Code Remote WSL extension.  SAM CLI and Docker installed in WSL (ubuntu 20.04) and local Lambda debugging from VS Code is now working well.

**Comment by justinmk3** [comment]
Toolkit 1.15 was released today. Thanks for the help, everyone!
