### ISSUE TITLE
Dont have Run Locally, Debug Locally, Configure option in Codelens of app.py 

### ISSUE THREAD

**Issue by kenchoong** [aws/aws-toolkit-vscode#1301]
**Describe the bug**

I install the Hello world SAM application using Vscod aws toolkit, it should be have Run Locally,Debug Locally and Configure options in the Codelens of the function of app.py. But I try everything but didnt have this options. 

**To Reproduce**

1. Create SAM application 
2. Python 3.8 for runtime 
3. Select AWS Hello World 
4. Enter name and folder of the application 
5. Open app.py 
6. Connected to aws using the access key and secret access key 

**Expected behavior**

Above `def lambda_handler(event, context):` in `app.py` should have **Run locally | Debug locally | Configure** option. 

**Screenshots**

But only have this in `app.py` 

![a12](https://user-images.githubusercontent.com/8010129/93351062-d65f9980-f86b-11ea-9c90-272810f95c17.png)

Only `Add debug configuration ` but dont have **Run locally | Debug locally | Configure** 

**Desktop (please complete the following information):**

-   OS: Windows 10 
-   Visual Studio Code Version: Version 1.49(user setup)
-   AWS Toolkit Version: v1.13.0 

**Additional context**

Don't know what I can do for now, please give the solution about this

**Comment by awschristou** [comment]
A new SAM local Lambda debugging experience was released in version 1.12.0 of the AWS Toolkit. The changes can be seen in PR #1215 . This experience makes use of VS Code _launch configurations_, as well as VS Code's standard entrypoints for debugging: 
- using F5 to start debugging
- the Run panel
- VS Code commands such as `Run: Start Without Debugging` and `Debug: Select and Start Debugging`

Documentation about the new debugging experience can be found at: https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/run-debug-sam-app.html

Summary: The CodeLenses mentioned in the original post are no longer available. After creating a debug configuration, you can press F5 to debug.

**Comment by kenchoong** [comment]
lolz.. that's means I already good to go right? 

This cost me the whole day to figure out what I missing out. 

Anyway thanks
