### ISSUE TITLE
dotnet core 3.1 lambda debugging

### ISSUE THREAD

**Issue by kumaranbsundar** [aws/aws-toolkit-vscode#1336]
**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04.1 (WSL 2)
-   VS Code version: 1.49.3
-   AWS Toolkit extension version: v1.15.0-SNAPSHOT

**Question**

I am trying to locally debug a dotnet core 3.1 lambda. I have followed the instructions given at this link
https://github.com/aws/aws-toolkit-vscode/blob/master/docs/debugging-dotnet-lambda-functions.md

I start the debugger from terminal like below and it is waiting for debugger to attach
![image](https://user-images.githubusercontent.com/10552837/95097589-42a71d80-06f3-11eb-926b-e0f0e92b2e68.png)

When I F5 start vscode it seem to attach to the debugger (or so it seems) like below
![image](https://user-images.githubusercontent.com/10552837/95097705-68ccbd80-06f3-11eb-8705-857955bced01.png)

But the terminal window never says the debugger was attached and after a while times out and finishes the execution like below.
![image](https://user-images.githubusercontent.com/10552837/95097895-a03b6a00-06f3-11eb-91fa-cebb0bc7904b.png)

This is a default HelloWorld project created using the VS Toolkit "New Project" menu. Attached are my template.yaml and launch.json files. Running this is WSL2
[launch.zip](https://github.com/aws/aws-toolkit-vscode/files/5328258/launch.zip)

Can you please tell me what i am doing wrong? Is dotnetcore3.1 debugger supported yet?

**Comment by justinmk3** [comment]
Thanks for reporting. The Toolkit should have shown a warning that mentions debugging isn't supported yet for dotnet 3.1.

After https://github.com/aws/aws-toolkit-vscode/pull/1333 , dotnet 3.1 debugging will be enabled. Would be great if you can confirm that the build from https://github.com/aws/aws-toolkit-vscode/pull/1333 works for you! 

1. To try it out, visit https://github.com/aws/aws-toolkit-vscode/pull/1333 and then [download the artifact](https://github.com/aws/aws-toolkit-vscode/blob/master/CONTRIBUTING.md#ci-artifact).
1. Extract the zip to get a `.vsix` file.
2. From the VSCode command list (`ctrl-shift-p` or `cmd-shift-p`) run `Install from VSIX...` to install the `*.vsix` file.
3. Reload VSCode and verify that the Toolkit has the new version (not the release/older version).

**Comment by kumaranbsundar** [comment]
SAM CLI Version: 1.4.0
I can try out #1333 but i can't find the artifact of CI build. Can you point out the link to download the artifact?

**Comment by justinmk3** [comment]
Thanks. The link is here (reachable from any `VSCode Package Test` CI job): https://d1ihu6zq92vp9p.cloudfront.net/bfadb4b9-08f0-43ca-b696-0a5e91c56b33/report.html

**Comment by justinmk3** [comment]
Thanks. The link is here (from any `VSCode Package` CI job): 

https://d1ihu6zq92vp9p.cloudfront.net/335e685b-9a06-4f29-9a4f-2786727c730f/report.html

**Comment by justinmk3** [comment]
Released in Toolkit 1.5 (requires SAM CLI 1.4.0)
