### ISSUE TITLE
Explorer does not refresh after switching profiles

### ISSUE THREAD

**Issue by mverkerk-godaddy** [aws/aws-toolkit-vscode#1341]
-   OS: Windows 10 (18362) running vscode/WSL (remote Ubuntu 18.04)
-   VS Code version: 1.50.0-insider
-   AWS Toolkit extension version: 1.15.0

**Question**
After changing profiles from the status bar "profile picker", the AWS Explorer tree still shows contents from the previous profile, even after clicking "Refresh AWS Explorer".
The expected behavior is that AWS Toolkit re-connects to AWS using the new profile, followed by a refresh of the Explorer.
My profiles are in ~/.aws/credentials and they use `credential_process` for SSO login.

Is this behavior by design?

**Comment by bryceitoc9** [comment]
Hi,

I just tried this with some premade credentials and two executable `.sh` files containing the following simple credential process (both of which pointed to different accounts) and couldn't replicate:
```
#!/bin/bash
echo '{
    "Version": 1,
    "AccessKeyId": "<AccessKey>",
    "SecretAccessKey": "<SecretKey>",
    "SessionToken": "<SessionToken>",
    "Expiration": "2020-10-20T15:10:23Z"
}'
```

Can you ensure that your credential profile in the bottom right corner of the IDE is changing, and can you ensure that the actual credential process is working correctly?

**Comment by Verkurkie** [comment]
Hey @bryceitoc9 - the profile _is_ definitely changing in the bottom right corner and i use my various profiles multiple times a day to switch accounts/roles in AWS so i know they work. I don't see anything in the AWS Toolkit output/logs suggesting that it's doing anything with the profile switch -  I just started using this extension so I'm not sure if i should expect to see anything there?

**Comment by bryceitoc9** [comment]
If you have logging set to Verbose and you view the AWS Toolkit Logs (either through output channel or via command palette), you should see something like the following when swapping between credential process profiles (comments are my own), are you seeing this (specifically the "Updating AWS Explorer" sections)?:
```
# Initial toolkit activation with `AltCredProcess` profile selected
2020-10-08 09:46:01 [VERBOSE]: Profile AltCredProcess contains credential_process - treating as Process Credentials
2020-10-08 09:46:01 [VERBOSE]: Getting AccountId from region us-east-1
2020-10-08 09:46:01 [VERBOSE]: Credentials changed (profile:AltCredProcess), updating AWS Explorer
# swapping to `CredProcess` profile
2020-10-08 09:49:34 [VERBOSE]: Profile CredProcess contains credential_process - treating as Process Credentials
2020-10-08 09:49:34 [VERBOSE]: Getting AccountId from region us-east-1
2020-10-08 09:49:34 [VERBOSE]: Credentials changed (profile:CredProcess), updating AWS Explorer
# Swapping back to `AltCredProcess` and using a cached copy of credentials as they're not yet expired
2020-10-08 09:50:56 [VERBOSE]: Getting AccountId from region us-east-1
2020-10-08 09:50:56 [VERBOSE]: Credentials changed (profile:AltCredProcess), updating AWS Explorer
```

**Comment by justinmk3** [comment]
(To set the log level, in the vscode settings UI search for "aws log level")

**Comment by Verkurkie** [comment]
With verbose turned on, i can now see the profile switch, but the Explorer doesn't update. On startup, AWS Toolkit was already connected to the `rum-p` profile. I changed it to `rum-d` but in the CloudWatch tree, i still see Lambda functions from `rum-p` that don't exist in `rum-d` ... i then changed the profile `rum-t` but still see entries from the initial profile `rum-p` ... it looks like the Explorer never updates. I can even get Log Streams from a Lambda function that i know only exists in `rum-p` even though the profile is set to `rum-d` or `rum-t` which both don't have that function so i know it's still talking to the account associated with the first `rum-p` profile ...

Here's my log output:
```Error logs for this session are permanently stored in /home/mverkerk/.config/Code/logs/aws_toolkit/aws_toolkit_20201008T232116.log
2020-10-08 23:21:18 [INFO]: log level: info
2020-10-08 23:21:18 [INFO]: Retrieving AWS endpoint data
2020-10-08 23:21:18 [INFO]: OS:  Linux x64 4.4.0-18362-Microsoft
Visual Studio Code Version:  1.50.0-insider
AWS Toolkit Version:  1.15.0

2020-10-08 23:21:20 [WARN]: Shared Credentials Profile default is not valid. It will not be used by the toolkit. Profile default is not supported by the Toolkit.
2020-10-08 23:21:50 [INFO]: Setting log level to: verbose
2020-10-08 23:21:50 [VERBOSE]: Log level is now: verbose
# First profile switch - to rum-d
2020-10-08 23:22:31 [VERBOSE]: Profile rum-d contains credential_process - treating as Process Credentials
2020-10-08 23:22:32 [VERBOSE]: Getting AccountId from region us-west-2
2020-10-08 23:22:34 [VERBOSE]: Credentials changed (profile:rum-d), updating AWS Explorer
# Clicked on "Connect to AWS" and chose rum-d again
2020-10-08 23:25:49 [VERBOSE]: Getting AccountId from region us-west-2
2020-10-08 23:25:50 [VERBOSE]: Credentials changed (profile:rum-d), updating AWS Explorer
2020-10-08 23:26:20 [INFO]: Successfully sent a telemetry batch of 12
# Second profile switch - to rum-t
2020-10-08 23:27:58 [VERBOSE]: Profile rum-t contains credential_process - treating as Process Credentials
2020-10-08 23:27:59 [VERBOSE]: Getting AccountId from region us-west-2
2020-10-08 23:28:00 [VERBOSE]: Credentials changed (profile:rum-t), updating AWS Explorer
2020-10-08 23:31:21 [INFO]: Successfully sent a telemetry batch of 4
```

**Comment by bryceitoc9** [comment]
Does refresh work in any context, e.g. does starting the IDE, expanding a resource pane, and refreshing cause any changes? Alternately, do any creative/destructive actions show up (like creating or deleting a folder in an S3 bucket; these constitute a refresh of the affected node)?

**Comment by Verkurkie** [comment]
Here's what I tried:
- vscode startup: last profile is pre-selected (`rum-p`), explorer is showing the correct tree/resources
- switch profile to `rum-dp`: output log says `"Credentials changed (profile:rum-dp), updating AWS Explorer"` but explorer still shows `rum-p` resources
- hit "Refresh AWS Explorer": nothing in the output log, no spinners, no progress bar, explorer still shows `rum-p` resources
- expand S3: nothing in the output log, i see the spinner in front of "S3", explorer still shows `rum-p` resources
- create S3 bucket: i get "403 - Access Denied" even though the underlying role has the necessary rights to do this ...
- close vscode: leaving the profile set to `rum-dp`
- vscode startup: last profile is pre-selected (`rum-dp`), explorer still shows `rum-p` resources!
   - during the startup, i noticed this in the output log: `credentials: found profiles: default,rum-dpp,rum-dp,rum-d,rum-t,rum-p` which are all in my `~/.aws/credentials` file ...

The last one surprised me! I expected to see `rum-dp` resources after the restart so i wonder if something else at a lower level is playing tricks on me ...
btw: it would be helpful to see the AccountId in the output logs. At some point, i see `Getting AccountId from region us-west-2` in the log -> after this line would be a great moment to actually show the AccountId that was retrieved ...

**Comment by bryceitoc9** [comment]
Out of curiosity, does this also happen if you're running a non-Insiders build of VS Code?

**Comment by Verkurkie** [comment]
Not sure if you both gave my last comment thumbs up because you thought I got it working (?) - if so, that means my comment was not clear - i edited it to clarify that the refresh is still **not working** ...

@bryceitoc9 - I have not tried the non-insider build yet but i will when i have some extra time and will report back here... thx!

**Comment by justinmk3** [comment]
Related: https://github.com/aws/aws-toolkit-vscode/issues/1226

**Comment by justinmk3** [comment]
@mverkerk-godaddy are you still having this issue, and if so can you share your ~/.aws/config (with private info removed)?
