### ISSUE TITLE
launch.json: Type warning for payload.json field

### ISSUE THREAD

**Issue by farski** [aws/aws-toolkit-vscode#1344]
**Describe the bug**

When creating a `launch.json` configuration for locally debugging a Lambda function, IntelliSense throws a warning when the properties included in `lambda.payload.json` have any type other than string, number or boolean. Putting in other values, like an object, and running the debugger produces the desired result, so this seems like a validation error.

**Screenshots**

![Screen Shot 2020-10-09 at 9 52 24 PM](https://user-images.githubusercontent.com/3483/95642915-c5c0ce80-0a79-11eb-8de2-c747c03f0e89.png)

![Screen Shot 2020-10-09 at 9 57 09 PM](https://user-images.githubusercontent.com/3483/95643028-69aa7a00-0a7a-11eb-91a5-679f77db8586.png)

**Desktop (please complete the following information):**

-   OS: macOS 11.0 
-   Visual Studio Code Version: 1.49.3
-   AWS Toolkit Version: 1.15.0

**Additional context**

There's basically no information in the documentation that I could find about how to use the `payload` property of these configurations. There's a [page](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/run-debug-sam-app.html#debug-config-ref) that does list the property, but it doesn't even mention that the valid options are `json` or `path`, or how to use either of them.

**Comment by justinmk3** [comment]
Thanks for the report. In [package.json](https://github.com/aws/aws-toolkit-vscode/blob/a4997528a8e2762f195b3b0be44da86e13d93431/package.json#L272) we specify the type of `json` as `object`, so there is either a problem with our generator or vscode itself.



> how to use the `payload` property of these configurations. There's a [page](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/run-debug-sam-app.html#debug-config-ref) that does list the property, but it doesn't even mention that the valid options are `json` or `path`, or how to use either of them.

That is definitely an oversight.

**Comment by justinmk3** [comment]
Confirmed with this launch.json: 

```
{
    "configurations": [
        {
            "type": "aws-sam",
            "request": "direct-invoke",
            "name": "sam-samples:app.lambdaHandler (nodejs12.x)",
            "invokeTarget": {
                "target": "code",
                "projectRoot": "sam-samples/hello-world",
                "lambdaHandler": "app.lambdaHandler"
            },
            "lambda": {
                "runtime": "nodejs12.x",
                "payload": {
                    "json": {
                        "foo": {
                            "bar": "baz",
                            "zim": 42
                        }
                    }
                },
                "environmentVariables": {
                    "zim": "ok",
                    "zub": "ok"
                }
            }
        }
    ]
}

```

The `payload` type in `src/shared/sam/debugger/awsSamDebugConfiguration.gen.ts` is defined as:

```
  payload?: {
    /**
     * %AWS.configuration.description.awssam.debug.event.json%
     */
    json?: {
      [k: string]: string | number | boolean;
    };
    /**
     * %AWS.configuration.description.awssam.debug.event.path%
     */
    path?: string;
  };
```

So this is a problem with our generator.

**Comment by justinmk3** [comment]
> no information in the documentation that I could find about how to use the `payload` property of these configurations. There's a [page](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/run-debug-sam-app.html#debug-config-ref) that does list the property, but it doesn't even mention that the valid options are `json` or `path`, or how to use either of them.

Documentation has been updated: https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/run-debug-sam-app.html

Thanks again for mentioning that!

**Comment by justinmk3** [comment]
Toolkit 1.16 was released today and includes a fix for this issue.
