### ISSUE TITLE
Run/Debug Lambda Locally with CodeLens on source code

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#135]
Code that has been detected as possible Lambda Function handlers should have CodeLenses to Run and Debug as a Lambda Function locally, making use of `sam local invoke`.

* initial implementation will pass in `{}` as the event
* a temporary `template.yaml` should be used, to cover whether or not the function is referenced by an existing Sam Template file

**Comment by awschristou** [comment]
Supporting tasks were spun off from this one
#149 #150 #151

**Comment by awschristou** [comment]
At this point there is a known issue #200 where debugging does not always attach in time.
Currently, this task's changes are in a feature [branch](https://github.com/aws/aws-toolkit-vscode/tree/feature/code-lens) `feature/code-lens`, which will be merged into `develop` when more of the overall local debugging story is complete
