### ISSUE TITLE
SAM Template does not display "Add Debug Configuration" codelens until the template has been modified

### ISSUE THREAD

**Issue by rli** [aws/aws-toolkit-vscode#1350]
1. Create a new SAM app using the SAM CLI
2. Open the parent folder of the template in VS Code
3. Observe that the template does not show the codelens until the yaml file has been modified

**Screenshots**
![sam](https://user-images.githubusercontent.com/742829/95927660-3c104a00-0d74-11eb-862e-62fed25b971e.gif)

-   OS: macOS Catalina
-   Visual Studio Code Version: 1.50.0
-   AWS Toolkit Version: 1.15.0

**Comment by awschristou** [comment]
Can you check if the Outline panel (below the explorer pane) is similarly empty until after making a file edit? I'm wondering if the yaml extension activation is in play here.

**Comment by justinmk3** [comment]
Could be that the template is not in the templateRegistry.

To debug I would add a breakpoint to `SamTemplateCodeLensProvider.provideCodeLenses()` and if `symbolResolver` returns nothing then I would check what's going on in `CloudFormationTemplateRegistry`.

**Comment by rli** [comment]
outline on a fresh app: 
![image](https://user-images.githubusercontent.com/742829/95927955-0c157680-0d75-11eb-8035-8768df46ae40.png)

**Comment by rli** [comment]
both `apiResources` and `apiResources` in `provideCodeLenses` returns empty list and `addTemplatesToRegistry` does not appear to ever be called until the file is changed or the workspace is reopened

**Comment by bryceitoc9** [comment]
I can try and replicate...just making sure, VS Code is closed when the SAM app is created via CLI, then opened to a blank VS Code workspace, then VS Code opens the folder in question?

**Comment by justinmk3** [comment]
> both `apiResources` and `apiResources` in `provideCodeLenses` returns empty list and `addTemplatesToRegistry` does not appear to ever be called until the file is changed or the workspace is reopened

Possibly fixed by https://github.com/aws/aws-toolkit-vscode/commit/5d1f1807d9b9546e6ccc0ef1728d6303a6cedb89 and followup commits related to template registry.
