### ISSUE TITLE
SAM debug with explicit API Gateway in template.yaml fails

### ISSUE THREAD

**Issue by deanthemachine2** [aws/aws-toolkit-vscode#1352]
**Describe the bug**

Whew this took a long time to track down, but here we are - 

Debugging a function based on a template (not code) no longer works (since the July migration to native VS Code debugging configurations) if you have an explicitly defined API Gateway in your template.yaml file, because the temporary yaml file that is created by this plugin does not include all the necessary resources.  

I don't have a lot to say other than I am disappointed in this change, and our team has to move away from using this formerly awesome feature until this design flaw is fixed. 

**To Reproduce**

I raised this on the SAM CLI repo thinking its them - it's not, it's this toolkit.
https://github.com/aws/aws-sam-cli/issues/2177

**Expected behavior**

I would expect that when using the template-based debug configurations, it uses the template I wrote - not the incomplete, temporarily generated one that vscode creates for me.  Until this is fixed we are abandoning any attempts to use this formerly great library.  I believe this weird temporary yaml file creation idea will preclude a lot of other use cases besides explicitly defined api gateways - for example, using layers!

This is as much for anyone else looking for answers in the dark as it is to provide a brief bit of feedback about the shortcomings of this once-great toolkit.

**Comment by justinmk3** [comment]
Thank you for reporting this. I see that https://github.com/aws/aws-sam-cli/issues/2177 has template.yaml example.

> I would expect that when using the template-based debug configurations, it uses the template I wrote - not the incomplete, temporarily generated one that vscode creates for me.

Agreed, and we've done some work to minimize the temporary template differences. We do hope to remove use of the temporary template, but meanwhile we may be able to work around it with a low-risk change.

**Comment by justinmk3** [comment]
> I believe this weird temporary yaml file creation idea will preclude a lot of other use cases besides explicitly defined api gateways - for example, using layers!

Did layers work for you in a previous version of the Toolkit? See https://github.com/aws/aws-toolkit-vscode/issues/1263 , https://github.com/aws/aws-toolkit-vscode/issues/746

NB: AFAIK the temporary template has always been a part of the Toolkit's sam debug logic.

**Comment by deanthemachine2** [comment]
No layers never worked - that said, we didn't happen to have tried that until after the change so what do I know.

Re: the temporary template always being this way - maybe that's the case, but I know it worked perfectly fine until we upgraded early August.

**Comment by justinmk3** [comment]
Using the template.yaml from https://github.com/aws/aws-sam-cli/issues/2177#issuecomment-691517651 I am able to reproduce the issue on main branch.

    **samcli.commands.validate.lib.exceptions.InvalidSamDocumentException:
    [InvalidResourceException('PostgresSelect', "Event with id [ApiEvent] is
    invalid. RestApiId must be a valid reference to an 'AWS::Serverless::Api'
    resource in same template.")] ('PostgresSelect', "Event with id [ApiEvent] is
    invalid. RestApiId must be a valid reference to an 'AWS::Serverless::Api'
    resource in same template.")**

So https://github.com/aws/aws-toolkit-vscode/commit/804f0e5f86033ff8e4e7c0da97e0294fa0238b6c does not fix this.

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/1363 addresses this, and will be included in the next release.

Thank you for taking the time to report this and provide a sample input!

**Comment by justinmk3** [comment]
Toolkit 1.16 was released today. Please let us know if it fixes this issue, thanks!
