### ISSUE TITLE
Exception creating s3 bucket in us-east-1 - s3 bucket creation works in other regions

### ISSUE THREAD

**Issue by dcrearer** [aws/aws-toolkit-vscode#1367]
Issue Type: <b>Bug</b>

at processTicksAndRejections (internal/process/task_queues.js:81:21)] {
  message: 'The specified location-constraint is not valid',
  code: 'InvalidLocationConstraint',
  region: null,
  time: 2020-10-24T02:43:59.897Z,
  requestId: '2ACC27038C705088',
  extendedRequestId: 'FS5rj8DW3qMI8jZ4hy5eScZYcx6LAt6uVJDj863zWngU8PYTrT1pnLFNaYN41iWdsgVb6/B6ogg=',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 36.200059425523776
}

Extension version: 1.15.0
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (2.14GB free)|
|Process Argv|--crash-reporter-id 700530e5-05e4-4253-887d-93b932d86515|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by justinmk3** [comment]
Toolkit 1.16 was released today and includes a fix for this issue.
