### ISSUE TITLE
Design initial post-install-first-run experience

### ISSUE THREAD

**Issue by steveataws** [aws/aws-toolkit-vscode#14]
After installation from the marketplace we want to invite the user to explore the capabilities of the toolkit and potentially include a gesture to set up initial credentials etc. Some extensions use a subtle pop-up window in the lower right to welcome the user, or invite the user to view details of an update. For updates some extensions display a nicely formatted webview (I'm thinking GitLens here).

This issue is to define what we want to do and will spawn additional refinement issues for the implementation.

**Comment by justinmk3** [comment]
Duplicate of https://github.com/aws/aws-toolkit-vscode/issues/508

Duplicate of https://github.com/aws/aws-toolkit-vscode/issues/545
