### ISSUE TITLE
Add CodePipeline runs and results in explorer

### ISSUE THREAD

**Issue by pgarbe** [aws/aws-toolkit-vscode#1412]
It's quite cumbersome when I commit some code changes to see when the deployment (in CodePipeline) is done and if it's failed what's the reason for it. I've to open the browser, go to CodePipeline and so on. It's an unnecessary context switch.

I'd like to see the pipeline runs within VS Code. Ideally the runs are mapped to my git commits. The status bar should show the results of the latest run. When it's failed, a click should jump to the explorer that shows the pipeline's stages and actions and their results and logs. The explorer should also show the pipeline history.

The name of the pipeline could be extracted from the cdk application. For cloudformation-based pipelines the name could be choosen manually and stored somewhere.

**Comment by justinmk3** [comment]
Thanks for your request. We are tracking the idea of introducing CodePipeline UX in https://github.com/aws/aws-toolkit-vscode/issues/711 .  I've added your request as an example there.

Consider adding your upvote 👍  to https://github.com/aws/aws-toolkit-vscode/issues/711 , this is part of how we prioritize new features. Thanks!
