### ISSUE TITLE
Request ability to suppress credential notification popup

### ISSUE THREAD

**Issue by brain-is-afk** [aws/aws-toolkit-vscode#1433]
**Is your feature request related to a problem? Please describe.**
I currently utilize temporary credentials for an AWS environment like most enterprise users.
When loading a new windows on vscode after credentials have expired, all windows that have the toolkit active will pop up a credential notification.  It's nice as a friendly reminder but I don't need every new window letting me know that my credentials have expired.  

**Describe the solution you'd like**

I would like to have a configurable option to suppress the notification that credentials are invalid or expired.  I'll get that if I forget to refresh credentials before execution.

**Describe alternatives you've considered**

I have considered disabling the toolkit until I need to use it for my specific use case.

**Additional context**

![image](https://user-images.githubusercontent.com/61764479/101645328-dea71b00-39fb-11eb-9a65-59626ccdc363.png)

**Comment by justinmk3** [comment]
> all windows that have the toolkit active will pop up a credential notification

By "windows" do you mean different instances of VSCode ?

**Comment by justinmk3** [comment]
### Proposal

- only show the notification if an action is taken, e.g. a command like `AWS: Deploy SAM Application` is explicitly run.
- if credentials fail passively, show the message in 
    1. the vscode statusbar 
    2. AWS Explorer panel
- detect when credentials become valid, then refresh the AWS Explorer (and clear the statusbar message, if vscode supports that)

**Comment by jstrese** [comment]
@justinmk3 where are we at with this proposal? I'm to the point where I'm about to just uninstall the toolkit because this message is annoying. We employ temporary credentials as well and they are expired 99% of the time, so this pops up on _every single new instance of VS Code_.

In terms of performance I think it's also kind of wasteful to automatically connect when a window is opened. Can we make this an option? Personally I'd like to see it try to connect when we click on the extension to use it.

**Comment by justinmk3** [comment]
@jstrese we will consider this for near-term plans. Please also 👍  the issue, this adds weight when prioritizing.

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/1708 tries to improve the experience here. @jstrese @brain-is-afk if you want to try it we'd love your feedback:

1. Download and extract [buildArtifacts.zip](https://github.com/aws/aws-toolkit-vscode/files/6417937/buildArtifacts.zip)
2. From the VSCode command list (`ctrl-shift-p` or `cmd-shift-p`) run `Extensions: Install from VSIX...` to install the `*.vsix` file.
3. Reload VSCode and verify that the Toolkit has the new version (not the release/older version).

**Comment by jstrese** [comment]
@justinmk3 #1708 seems to resolve my complaint with the AWS Toolkit. It attempts to connect when I go to use the extension and never before. Awesome job, thank you, and I can't wait for it to get merged in. Hopefully it works for @brain-is-afk as well.

**Comment by justinmk3** [comment]
Toolkit 1.25 was released, it only tries to autoconnect if the AWS panel is viewed.
