### ISSUE TITLE
Support samconfig.toml for debugging local lambda function

### ISSUE THREAD

**Issue by rynoV** [aws/aws-toolkit-vscode#1437]
**Is your feature request related to a problem? Please describe.**

I have a lot of default configuration for sam local defined in my samconfig.toml file, and I don't want to have to manually copy all of this config to launch.json to debug my functions.

**Describe the solution you'd like**

I'd like to be able to use my samconfig.toml file to configure the debug command.

**Describe alternatives you've considered**

Alternatives would be to manually copy this configuration into launch.json.

I also tried

```json
"sam": {
    "localArguments": ["--config-file", "samconfig.toml"],
},
```

but it seems like this tool is running the `sam local start-api` in another folder and not copying samconfig.toml.

**Comment by justinmk3** [comment]
> but it seems like this tool is running the `sam local start-api` in another folder and not copying samconfig.toml.

If `sam.localArguments` supported the `${workspaceFolder}` token, that could avoid that issue.

Perhaps the Toolkit should also copy the `samconfig.toml` file to the temporary folder?

**Comment by justinmk3** [comment]
`sam.LocalArguments` now supports `${workspaceFolder}`: https://github.com/aws/aws-toolkit-vscode/pull/1522

**Comment by rynoV** [comment]
This should fix the issue I was having, but I probably won't check to confirm anytime soon, so if no one else is having this issue I think this can be closed.

**Comment by justinmk3** [comment]
Looks like there might be additional work needed.

**Comment by hakanson** [comment]
The options for [sam build](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html) support parameters related to the configuration file. Any way to set these using the `buildArguments` and hope `sam build` just works as expected?

```json
            "sam": {
                "buildArguments": [
                    "--config-file",
                    "PATH",
                    "--config-env",
                    "TEXT"
                ],
                "localArguments": []
            },
```

**Comment by justinmk3** [comment]
Closing this because:

- eliminating the temp dir is covered by #2050
- samconfig.toml support  covered by #2011

**Comment by pstephenwille** [comment]
closed?  i'm still looking for a solution.

**Comment by justinmk3** [comment]
see https://github.com/aws/aws-toolkit-vscode/issues/1437#issuecomment-1074403764
