### ISSUE TITLE
SAM debug fails to attach with nodejs + "Image" API resource

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#1443]
**To Reproduce**

1. Create sam application with runtime `nodejs 12.x (Image)`
1. try to run/debug the API resource
1. debugger fails to attach

**Expected behavior**

API request should succeed. Debugger should attach.

**Desktop (please complete the following information):**

-   AWS Toolkit Version: https://github.com/aws/aws-toolkit-vscode/commit/9efb496151b5e49ebc295514dfc6454250a90f2d

**Additional context**

This appears to be a SAM CLI behavior difference. The issue happens with `sam local start-api` but not `sam local invoke`.

- ~~We could hack around the issue by not waiting for the "cue" message here:~~
    - https://github.com/aws/aws-toolkit-vscode/blob/978f87ba2a79349ae43495b0c98e16d76b8d428f/src/shared/sam/cli/samCliLocalInvoke.ts#L80
    - Edit: doesn't work. Related? https://github.com/aws/aws-sam-cli/issues/2668

**Comment by justinmk3** [comment]
Related:

- https://github.com/aws/aws-sam-cli/issues/2668
- https://github.com/aws/aws-sam-cli/issues/2447

**Comment by JadenSimon** [comment]
Happens with Go lambdas too. SAM appears to just skip over the debugging step for the Image + API case, so this may be an issue for other runtimes as well.
