### ISSUE TITLE
Debugging Local Lambda Function Accessing S3

### ISSUE THREAD

**Issue by tnorlund** [aws/aws-toolkit-vscode#1450]
**Desktop (please complete the following information):**

-   OS: Mac OS 11.1
-   VS Code version: 1.52.1
-   AWS Toolkit extension version: 1.17.0

**Question**
I just made a Lambda function that looks at a S3 bucket and reads a file when placed in a specific directory. I'd like to now create a Lambda function that crawls through the S3 bucket and does the same thing.

Previously I used the code editor in the Lambda console, but now I'd like to develop and debug this function locally. I just installed the AWS Toolkit along with SAM. I'd now like to develop the function that crawls through the bucket.

How do I configure the launch.json to access the S3 bucket? Is there a better way to develop this locally?

**Comment by justinmk3** [comment]
You can start by creating a SAM application (which is just a node, python or C# project that has a `template.yaml` file in it), by [running the "AWS: Create new SAM Application" command](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/serverless-apps.html#serverless-apps-create).

In the handler code, use the AWS SDK as usual to access the S3 bucket. Then you can test it locally using a launch.json config. To create such a config, you can use the "Add Debug Configuration" codelens which appears next to the handler code in VSCode. Then run that config using F5.
