### ISSUE TITLE
Cannot create SAM application because the toolkit looks for ...npm/sam.exe but the samcli installs to AWSSAMCLI/bin

### ISSUE THREAD

**Issue by yzpaul** [aws/aws-toolkit-vscode#1452]
**Describe the bug**

After installing Aws SAM CLI from aws website, and downloading the aws-tookit-vscode, then I try to create new SAM application in vscode. Error from toolkit logs:

2021-01-04 18:30:55 [ERROR]: An error occurred while creating a new SAM Application. Check the logs for more information by running the "View AWS Toolkit Logs" command from the Command Palette.
2021-01-04 18:30:55 [ERROR]: Error creating new SAM Application: [Error: ENOENT: no such file or directory, stat 'C:\Users\king\AppData\Roaming\npm\sam.exe'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\king\\AppData\\Roaming\\npm\\sam.exe'
}

**To Reproduce**

1. install aws sam cli from AWS website (.exe)
2. install vscode extension aws-toolkit-vscode
3. setup credentials
4. right click "Lambda" in Aws explorer and attempt to create SAM application

**Expected behavior**

Expected sam application to create

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Win10
-   Visual Studio Code Version: 1.52.1
-   AWS Toolkit Version: 1.17.0

**Additional context**

SAM.cmd exists in : C:\Program Files\Amazon\AWSSAMCLI\bin
after aws sam cli install, but this isnt the directory being referenced by the extension

**Comment by justinmk3** [comment]
This suggests that `C:\Users\king\AppData\Roaming\npm\` appears in your $PATH before `C:\Program Files\Amazon\AWSSAMCLI\bin`.

I suppose the Toolkit could explicitly look in `C:\Program Files\Amazon\AWSSAMCLI\bin`. Or check that `sam --version` found in $PATH returns an expected version string.

For reference, can you confirm that `C:\Users\king\AppData\Roaming\npm\sam` is [this package](https://www.npmjs.com/package/sam) ? Or, what exactly is living in `...\Roaming\npm\sam` ?

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/1465 should fix this. Can you confirm by testing the VSIX?

1. Download and extract [toolkit.vsix.zip](https://github.com/aws/aws-toolkit-vscode/files/5839581/toolkit.vsix.zip)
2. From the VSCode command list (`ctrl-shift-p` or `cmd-shift-p`) run `Install from VSIX...` to install the `*.vsix` file.
3. Reload VSCode and verify that the Toolkit has the new version (not the release/older version)..

**Comment by justinmk3** [comment]
Toolkit 1.19 includes a change that should fix this issue. Thanks for reporting!
