### ISSUE TITLE
SAM: support Typescript projects 

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#1453]
- local/run debug of Typescript Lambda handlers
- "Add Debug Config" codelens appears in `.ts` files

related #773
related JetBrains Toolkit PR: aws/aws-toolkit-jetbrains/pull/2397

**Comment by JadenSimon** [comment]
After https://github.com/aws/aws-toolkit-vscode/pull/3099 is released I think we can close this out.
