### ISSUE TITLE
Reevaluate design/need for commands `getLambdaConfig` and `getLambdaPolicy`

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#146]
getLambdaPolicy code was cleaned up, getLambdaConfig hasn't been.

Discuss whether or not to keep, modify, remove the functionality offered here. If we keep it, update the getLambdaConfig code.

Reference: 

@steveataws, from #144:

> Unconnected to this change but seeing it reminds me, I think we should remove the getLambdaConfig and ~getLambdaPolicy~ commands until we can eval if they are useful and if so, put a nicer UI around the output.

**Comment by awschristou** [comment]
Lambda Policy code tidied up in #181 , a similar change should happen with Lambda Config

**Comment by awschristou** [comment]
These features will be removed with #460. Closing.
