### ISSUE TITLE
AWS Explorer: Error loading API Gateway REST APIs

### ISSUE THREAD

**Issue by sliedig** [aws/aws-toolkit-vscode#1468]
**Describe the bug**
When opening the AWS Explorer API Gateway node you get an error if you have multiple APIs with the same name (in this case I have multiple Petstore APIs).

> Error details for API Gateway
Error code
> [no error code]
> Error message
        Conflict: Multiple items have the key 'PetStore'

**To Reproduce**
Create multiple REST endpoints with the same name

**Expected behavior**

List all APIs, as they appear in the AWS Console

**Screenshots**

<img width="752" alt="image" src="https://user-images.githubusercontent.com/597073/104833355-016a0080-58d3-11eb-9af9-7641c83ceece.png">

**Desktop (please complete the following information):**

OS:  Darwin x64 19.6.0
Visual Studio Code Extension Host Version:  1.52.1
AWS Toolkit Version:  1.18.0

**Additional context**
No error code

**Comment by bryceitoc9** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/1471

**Comment by justinmk3** [comment]
Toolkit 1.19 includes a change that should fix this issue. Thanks for reporting!
