### ISSUE TITLE
Unable to connect to AWS in VSCode using latest toolkit

### ISSUE THREAD

**Issue by bestbear** [aws/aws-toolkit-vscode#1473]
I can't connect to AWS using predefined profiles listed in VSCode
However, I can directly in an SSH window on my Mac using the same exact AWS profile.  It seems none of the profiles are working from inside the AWS Toolkit for some reason.

Switching to any available AWS profile in VSCode fails to connect to AWS

**To Reproduce**

**Comment by justinmk3** [comment]
> However, I can directly in an SSH window on my Mac using the same exact AWS profile

Is that using the `aws` command (AWS CLI)? The AWS CLI has more lenient parsing than the AWS JS SDK used by the VSCode AWS Toolkit. 

That means, if there is a syntax issue in your `~/.aws/credentials` or `~/.aws/config`, Toolkit may not be able to read it, even though AWS CLI can read it. 

In VSCode, can you try the `AWS: View AWS Toolkit Logs` command to see if the logs show related errors?

**Comment by bestbear** [comment]
Yes, you were correct.  There was a questionable bit of syntax in my ~/.aws/config file.  Once that was cleaned up VSCode works properly with the AWS Toolkit.  Many thanks!
