### ISSUE TITLE
How to setup SSO OIDC IdP (AzureAD) for easy enterprise integration experience?

### ISSUE THREAD

**Issue by smaud** [aws/aws-toolkit-vscode#1475]
**Desktop (please complete the following information):**

-   OS:WSL
-   VS Code version:Latest
-   AWS Toolkit extension version:Latest

**Question**

We need to integrate toolkit with out IdP AzureAD (OIDC) for enterprise SSO - how do I do this with the toolkit?

**Comment by justinmk3** [comment]
We are working on SSO support in https://github.com/aws/aws-toolkit-vscode/pull/1304 . If you want to try out the build from that PR, we would be glad to have your feedback:

1. Download and extract [toolkit.zip](https://github.com/aws/aws-toolkit-vscode/files/5890612/toolkit.zip)
2. From the VSCode command list (`ctrl-shift-p` or `cmd-shift-p`) run `Install from VSIX...` to install the `*.vsix` file.
3. Reload VSCode and verify that the Toolkit has the new version (not the release/older version).

**Comment by justinmk3** [comment]
- Toolkit 1.21 includes support for AWS SSO.
- For AzureAD, see the above comment linking to [AWS SSO documentation](https://docs.aws.amazon.com/singlesignon/latest/userguide/manage-your-identity-source-idp.html)
