### ISSUE TITLE
Error when rendering state machine graph after saving the file as YAML

### ISSUE THREAD

**Issue by ljacobsson** [aws/aws-toolkit-vscode#1477]
When trying to render ASL definitions written in YAML I get the following error: 'Errors detected. Cannot preview.'. this doesn't seem to be an issue with JSON definitions.

**To Reproduce**
1. Create new state machine from template
2. Select YAML
3. Select `AWS: Render state machine graph` 
4. Observe that it's rendered correctly
5. Save the file
6. Select `AWS: Render state machine graph` again
7. Error is displayed 

**Expected behavior**
Expecting it to render the graph

**Screenshots**
![ezgif-7-2072496793ca](https://user-images.githubusercontent.com/7579097/105696404-90929c00-5f03-11eb-908b-4fecc069b257.gif)

**Desktop (please complete the following information):**
-   OS: Ubuntu 20.04
-   Visual Studio Code Version: 1.52.1
-   AWS Toolkit Version: 1.18.0

**Comment by justinmk3** [comment]
cc @alanbo

**Comment by alanbo** [comment]
Thank you for the report! I tested it. The rendering will work when the file is saved with `*.asl.yaml` or `*.asl.yml` extension. Also it will work when `Amazon States Language (YAML)` Language Mode is selected.
Still, I think we should support rendering regular YAML files as well given that rendering of json files that are not marked as asl does work.

**Comment by justinmk3** [comment]
Included in AWS Toolkit 1.30
