### ISSUE TITLE
python Lambda local debugging failure

### ISSUE THREAD

**Issue by sungkim-remi** [aws/aws-toolkit-vscode#1479]
-   OS: Windows 10
-   VS Code version: 1.52.1
-   AWS Toolkit extension version: 1.18.0
-   python: 3.6.8

I am trying this sample Lambda
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-example-s3.html

And tried local debugging and followed the steps of document
https://github.com/aws/aws-toolkit-vscode/blob/master/docs/debugging-python-lambda-functions.md

The sample runs successfully in the AWS Cloud.
But when I tried local debugging, it failed.
![unnamed](https://user-images.githubusercontent.com/78059894/105931328-543f7700-608e-11eb-9439-33a1a1bc8f3a.png)

Of course, I have installed boto3 using "pip install ~"

Plz help me and thanks a lot.

**Comment by justinmk3** [comment]
Sounds like you might not have the vscode python extension ? 

> And tried local debugging and followed the steps of document
> https://github.com/aws/aws-toolkit-vscode/blob/master/docs/debugging-python-lambda-functions.md

Sorry, that document is outdated, I guess you found it through a websearch? We will remove it.

Here are the correct docs: https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/serverless-apps.html#serverless-apps-debug

**Comment by sungkim-remi** [comment]
When I follow the steps of document -
https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/serverless-apps.html#serverless-apps-debug
I can local-debug now, many thanks.
:)
