### ISSUE TITLE
Upload lambda from source directory

### ISSUE THREAD

**Issue by erobertshaw** [aws/aws-toolkit-vscode#1488]
I want to quickly redeploy a lambda function from source code in visual code using the aws plugin, for a shorter development cycle.

Problem: This is very user intensive for repeat use. Steps:There is an option to right click a lambda function -> "Upload lambda...." -> Directory -> select source code directory from finder -> Say "No aws toolkit will upload a zip of the selected directory" -> Dialog to acknowledge it might not work , select "Yes".

Solution: I would like to be able to press a single button and do all of this in one go. Better still if I can have a keyboard shortcut to do this.

**Comment by justinmk3** [comment]
> Better still if I can have a keyboard shortcut to do this.

We could provide a command, but how will the command know which Lambda to upload? Is it based on the cursor position?

**Comment by davallclarke** [comment]
Hello, you have to select a workspace to save the downloaded folder. You could add an option in the context menu of that folder for "Quick upload to [source]." [Source] was where the initial folder came from, store this info. For more advanced selections, users could use the usual tedious way. The "Quick" option would already have the folder path, and the zip folder option would also be obsolete. The shortcut key triggers the context menu selection of the active folder.

**Comment by EmmettM** [comment]
Any update on this?

**Comment by justinmk3** [comment]
- In 1.39 you can now right-click on a folder and choose `Upload Lambda`. https://github.com/aws/aws-toolkit-vscode/blob/master/CHANGELOG.md#1390-2022-06-06
- Further improvements towards faster/easier deploy, are tracked in:
    - https://github.com/aws/aws-toolkit-vscode/issues/900
    - https://github.com/aws/aws-toolkit-vscode/issues/1052
