### ISSUE TITLE
Design 'new project' experience

### ISSUE THREAD

**Issue by steveataws** [aws/aws-toolkit-vscode#15]
We want users to be able to create new Lambda functions (and potentially serverless apps?) from within VS Code using a command gesture or button on the Explorer. The resulting workflow will need to guide users through selecting a template (also known as a blueprint in Visual Studio toolkit) appropriate to what they want to build and deploy and the host language. 

This issue is to design the workflow and UI experience and will yield additional issues for implementation upon sign-off.

For example we could:
* Implement a multi-step picker that first narrows the selection down to a function or an app, then lists the available languages for the respective templates, then on selection displays a webview panel detailing the available templates
* or, we could have the command gesture launch a webview with filtering controls allowing the selection refinement process.

In either case, the webview should be structured such that clicking on a template fills out a panel with more details of what the template outputs and what it can be used for, plus any other relevant information (eg permissions required for it to work perhaps). A button on that panel will then allow the user to cause the project (workspace) to be generated from the template and VSCode then instructed to open it. We may also want an option to have the user elect to have the folder containing the generated project be added to the current workspace.

**Comment by awschristou** [comment]
Wizard for Creating a new SAM Application is now in #124
