### ISSUE TITLE
Investigate whether we should save the task when the user invokes a lambda from CodeLens

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#150]
When the user debugs a lambda from CodeLens, we generate and execute a task on the fly. We should investigate whether we should persist this task to `tasks.json`.

### What done looks like

This issue is 'done' when concrete implementation issue[s] are created and scheduled with detailed answers to the following questions:

- Should we always save, or ask the user whether to save?
- What 'remember my preference options' should we provide to the user?
- What if a corresponding task already exists? What if the existing task doesn't match the generated task?
- When the user debugs a lambda from CodeLens, we should also consider saving the config to `launch.json`.

**Comment by awschristou** [comment]
We decided against persisting to tasks.json. We're happy with running tasks on the fly. The variance in invoke inputs would also cause much persisting to the tasks.json file.
