### ISSUE TITLE
auth: support ECS credentials provider

### ISSUE THREAD

**Issue by hffmnn** [aws/aws-toolkit-vscode#1508]
**Describe the bug**

Trying to log in with a valid profile (in `~/.aws/config`) that has `credential_process` configured does not work. The log shows:

```
2021-02-09 21:45:00 [ERROR]: Error trying to connect to AWS with Credentials Provider profile:the.profile. Toolkit will now disconnect from AWS. [Error [CredentialsError]: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
...
```

When running `aws s3 ls --profile  the.profile` on the command line, everything works as expected:
- the credential process starts and the command shows the expected output.

The profiles are setup as follows:
```
[profile the.source.profile]
mfa_serial=arn:aws:iam::987654321:mfa/ch
credential_process=aws-vault exec the.source.profile --json --prompt=osascript

[profile the.profile]
source_profile=the.source.profile
role_arn=arn:aws:iam::123456789:role/some.role
```

**To Reproduce**

1. Open VS Code
2. Command Palette `AWS: Connect to AWS`
3. Select `the.profile`
4. See the error notifcation `Invalid credentials profile:the.profile, see logs for more information.`

**Expected behavior**

I should be logged in to AWS and everything works as expected.

**Desktop (please complete the following information):**

OS:  Darwin x64 20.3.0
Visual Studio Code Extension Host Version:  1.53.1
AWS Toolkit Version:  1.20.0

---
Any ideas what might be wrong? Do you need any more logs?

**Comment by justinmk3** [comment]
- Do other profiles work when selected with the Toolkit?
- Try creating an empty `~/.aws/credentials` if you don't already have one. https://github.com/aws/aws-toolkit-vscode/issues/641
- The `aws` CLI tool is more forgiving of `~/.aws/*` syntax, whereas the AWS JS SDK is not.

**Comment by hffmnn** [comment]
> Do other profiles work when selected with the Toolkit?

None of my profiles work with the Toolkit.

> Try creating an empty ~/.aws/credentials if you don't already have one

I already did that. Does not change the behavior

> The aws CLI tool is more forgiving of ~/.aws/* syntax, whereas the AWS JS SDK is not.

I tried with a simple AWS JS SDK script and with that at least it behaves as described in the docs: 

```
If more than one credential source is available to the SDK, the default precedence of selection is as follows:

    Credentials that are explicitly set through the service-client constructor
    Environment variables
    The shared credentials file
    Credentials loaded from the ECS credentials provider (if applicable)
    Credentials that are obtained by using a credential process specified in the shared AWS config file or the shared credentials file. 
    Credentials loaded from AWS IAM using the credentials provider of the Amazon EC2 instance (if configured in the instance metadata)
```

With `aws-vault` it is possible to emulate an ECS environment (https://github.com/99designs/aws-vault/blob/master/USAGE.md#--ecs-server) and when the script starts it triggers the third-party credential process and runs without a problem. In VS Code this doesn't happen.

Is this explicitly disabled for the toolkit or maybe a restriction from vs-code?

**Comment by justinmk3** [comment]
> With `aws-vault` it is possible to emulate an ECS environment (https://github.com/99designs/aws-vault/blob/master/USAGE.md#--ecs-server) and when the script starts it triggers the third-party credential process and runs without a problem. In VS Code this doesn't happen.

Hmm, that reference mentions: 

> this will only work with the AWS SDKs that support `AWS_CONTAINER_CREDENTIALS_FULL_URI`. The Ruby, .NET and PHP SDKs do not currently support it.

In general, environment variables aren't propagated to VSCode and the Toolkit would need to have explicit understanding of this use-case.

**Comment by hffmnn** [comment]
Ok, thanks for the info. I found a workaround where I temporarily generate a `~/.aws/credentials` file.
