### ISSUE TITLE
Support debugging of NodeJS lambda functions that are not in an npm package.

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#151]
When using the SAM CLI to invoke a lambda, SAM mounts the folder corresponding to the lambda's CodeUri property. When a lambda is detected directly from source code (but does not exist in `template.y[a]ml`), we need to provide the `CodeUri` property ourselves.

- If the lambda exists in an npm package (i.e., there is a `package.json` in its directory or an ancestor directory), we can use the directory containing `package.json` as the code uri.
- If no `package.json` is found when walking up the directory tree, default `CodeUri` to `${workspaceFolder}`, and make the `Handler` property relative to `${workspaceFolder}`.

#### Scenario

* A user opens a folder (in VS Code) containing JavaScript code, but no `package.json`.
* The JavaScript code exports at least one function that with a lambda-compatible signature.

#### Expected behavior

* Each lambda handler candidate displays a `Debug` CodeLens.
* When invoked, the `Debug` CodeLens launches a debugging session for associated handler.

**Comment by awschristou** [comment]
SAM CLI does not support this scenario. Closing.
