### ISSUE TITLE
URI handling for code-type launch configs is incorrect.

### ISSUE THREAD

**Issue by bryceitoc9** [aws/aws-toolkit-vscode#1511]
**Describe the bug**

Might be a Windows-only thing? We're not handling the `manifestUri` for `LambdaHandlerCandidate`s correctly, which means that the pathing is off: this should be an absolute path, but is returning (at least on Windows) as a scheme of `C` and an absolute fspath of the path from there.

**Expected behavior**

Absolute path is correct and scheme is `file`

**Screenshots**

![image](https://user-images.githubusercontent.com/29374703/107718320-87872600-6c8a-11eb-8b8e-59874fda4b9f.png)

**Comment by bryceitoc9** [comment]
PR https://github.com/aws/aws-toolkit-vscode/pull/1520

**Comment by justinmk3** [comment]
Fixed in [Toolkit 1.21](https://github.com/aws/aws-toolkit-vscode/releases/tag/v1.21.0)
