### ISSUE TITLE
Unable to Publish state machine to Step Functions

### ISSUE THREAD

**Issue by jkonkol** [aws/aws-toolkit-vscode#1526]
**Describe the bug**

Using HelloWorld quick start and no changes I am unable to Publish state machine to Step Functions.  

**To Reproduce**

Open Command palette
AWS: Create a new Step Functions state machine
Choose:  Hello world
Choose: YAML
Save File
Open Command palette
AWS: Publish state machine to Step Functions

Error:  
Command 'AWS: Publish state machine to Step Functions' resulted in an error (Running the contributed command: 'aws.stepfunctions.publishStateMachine' failed.)

**Expected behavior**

Expected the State Machine to be published

**Screenshots**

![image](https://user-images.githubusercontent.com/17801770/109025216-24cb5c80-7684-11eb-910f-03d4a7df5625.png)

**Desktop (please complete the following information):**

OS:  Darwin x64 20.2.0
Visual Studio Code Extension Host Version:  1.53.2
AWS Toolkit Version:  1.20.0

**Additional context**

I have verified AWS Credentials and can see other resources on AWS from within V.S. Code

**Comment by justinmk3** [comment]
Can you provide the logs? 

1. Set the Toolkit log level to "verbose": in VSCode settings search for "aws log level", then select "verbose".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View AWS Toolkit Logs` command to get the logs.

**Comment by jkonkol** [comment]
Here is the log entry from my execution this morning:

2021-02-25 07:50:28 [VERBOSE]: Credentials changed (profile:Konkol_IAM_User), updating AWS Explorer
2021-02-25 07:50:44 [ERROR]: Cannot publish state machine from Amazon States Language YAML file
2021-02-25 07:51:24 [INFO]: Successfully sent a telemetry batch of 4

Thanks

**Comment by jkonkol** [comment]
Reading my own error I see it says Cannot publish YAML file.  Is that the issue, that I'm using YAML?

**Comment by justinmk3** [comment]
Yes, that is a limitation currently: https://github.com/aws/aws-toolkit-vscode/blob/bed5d9e47645a62e018aa61840dbc386e4b8711c/src/stepFunctions/commands/publishStateMachine.ts#L33-L36

**Comment by arjungoel** [comment]
Hey @alanbo, this is my yaml file for step functions

![image](https://user-images.githubusercontent.com/25618368/113766762-7105c400-973b-11eb-8b17-5c5c4797c6fd.png)


But I am still getting the same error i.e.

`Command 'AWS: Publish state machine to Step Functions' resulted in an error (Running the contributed command: 'aws.stepfunctions.publishStateMachine' failed.)`

**Comment by justinmk3** [comment]
@arjungoel this change has not be released yet, however if you want to test the prerelease that would be great! 

Here is a test build of the AWS Toolkit extension: 

1. Download and extract [awstoolkit.zip](https://github.com/aws/aws-toolkit-vscode/files/6267199/awstoolkit.zip)
2. From the VSCode command list (`ctrl-shift-p` or `cmd-shift-p`) run `Extensions: Install from VSIX...` to install the `*.vsix` file.
3. Reload VSCode and verify that the Toolkit has the new version 1.23 (not the release/older version 1.22).
