### ISSUE TITLE
AWS Toolkit does not recognise access key ID

### ISSUE THREAD

**Issue by scarinza** [aws/aws-toolkit-vscode#1529]
Windows computer 
- Windows Version: windows 10 
- Visual Studio Version: latest
- AWS Toolkit for Visual Studio Version: 2019

I have managed to install the AWS Toolkit but when I go to create a new S3 bucket I get the error attached. 'The AWS Acess Key ID provided does not exist in our records'. Can you help me solve this please?
<img width="715" alt="VS AWS Error" src="https://user-images.githubusercontent.com/79640978/109153150-cc23be80-776c-11eb-8206-864d4ea68689.PNG">

**Comment by awschristou** [comment]
@scarinza you appear to be working with Visual Studio Code, not Visual Studio. I will transfer this issue to the AWS Toolkit for VS Code repo. 

CC: @bryceitoc9

**Comment by scarinza** [comment]
Hi @awschristou I had downloaded the wrong software. I have now installed Visual Studio, however I am not getting a different error. Coul you help me solve this one please? 
![image](https://user-images.githubusercontent.com/79640978/109480779-3f367900-7a7c-11eb-94cb-d7681d699cdb.png)

**Comment by justinmk3** [comment]
See the previous comment: https://github.com/aws/aws-toolkit-vscode/issues/1529#issuecomment-786069834

**Comment by scarinza** [comment]
Hi @justinmk3 I have tried to perform the actions in the comment you highlighted but I keep getting the same error as the my last picture attached

**Comment by justinmk3** [comment]
> You could try using the [AWS CLI](https://aws.amazon.com/cli/) from a command prompt to confirm if your system's credentials are in working order. For example `aws s3 ls` would test if you can list an account's buckets (here are [other s3 commands](https://docs.aws.amazon.com/cli/latest/reference/s3/))
> 
> This article may help you further: https://aws.amazon.com/premiumsupport/knowledge-center/access-key-does-not-exist/

@scarinza If the above steps don't work, this is unrelated to AWS Toolkit: you need to set up your credentials. Start with https://aws.amazon.com/premiumsupport/knowledge-center/access-key-does-not-exist/
