### ISSUE TITLE
AWS Explorer - EC2 support

### ISSUE THREAD

**Issue by corbuno** [aws/aws-toolkit-vscode#1559]
Show the list of EC2 instances under the AWS Explorer with simple right-click commands like 
- start/stop/restart/terminate
- connect in Terminal (Linux based EC2 instances)

Each EC2 instance line could also be expandable to list the EBS volumes with their own right-click commands.

**Comment by justinmk3** [comment]
# Status

AWS Toolkit 3.39.0 includes [these features](https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-2539726009):

* ✅ AWS Explorer (and VSCode command palette): Start/Stop/Reboot actions [#1559](https://github.com/aws/aws-toolkit-vscode/issues/1559)
* ✅ AWS Explorer: list EC2 instances, view their status.
* ✅ `AWS: Launch EC2 Instance` command opens the AWS web console launch page.
* ✅ `AWS: Open terminal to EC2 instance...` command opens a VSCode terminal connected to an EC2 instance.
    * Requires [remote-ssh](https://code.visualstudio.com/docs/remote/ssh) (which requires `ssh` on your local desktop).
    * Supports EC2 instances running Linux/macOS/**Windows**.
* ✅ `AWS: Connect to EC2 instance in New Window...` command connects VSCode to an EC2 instance.
    * Requires [remote-ssh](https://code.visualstudio.com/docs/remote/ssh) (which requires `ssh` on your local desktop).
    * Supports EC2 instances running Linux or macOS (**not Windows, currently**).
    * Your local desktop can be Linux/macOS/Windows.
    * <img width="591" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/55561878/8da31cbd-0542-4607-911b-d87ed39af443">
