### ISSUE TITLE
'Get Lambda function policy' leaves 'Loading...' on screen when Function Policy cannot be found

### ISSUE THREAD

**Issue by KaylorDave** [aws/aws-toolkit-vscode#156]
**Describe the bug**
When attempting to view my Lambda functions' policy, vscode opened a new tab but just sat on 'Loading...' indefinitely.

**To Reproduce**

1. Open vscode with the AWS toolkit for VSCode
2. Setup credentials and connect to AWS through the extension
3. Either from the command palette (F1) or through the AWS toolkit sidebar in VSCode using right-click, select 'Get Lambda Function Policy'
4. See that it hangs on Loading...

**Expected behavior**
I expected to see my Lambda functions' policy

**Screenshots**
![image](https://user-images.githubusercontent.com/41019097/49252798-d44bf280-f3d9-11e8-868e-2b591ae571fc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise v1809 build 17763.134
 - Visual Studio Code Version: 1.29.1 (user setup)
 - AWS Toolkit for Visual Studio Code Version: 0.0.1

**Additional context**
N/A

**Comment by awschristou** [comment]
Thank you for the report! Looks like some additional handling is required in cases where GetPolicy returns `ResourceNotFoundException`

**Comment by awschristou** [comment]
A fix has now been committed into the develop branch.
