### ISSUE TITLE
consolidated cloudwatch log group view

### ISSUE THREAD

**Issue by cloud-context** [aws/aws-toolkit-vscode#1577]
When searching through cloudwatch logs for something in particular, I need to know which log stream it is in. If I dont, i need to search each individual log stream for the information I'm looking for

I'd like to be able to select an option: "View all log streams" which functions in exactly the same way that the "Search All" button does in the AWS Log Group console screen

The alternative is to view the logs in cloudwatch directly

**Comment by justinmk3** [comment]
We are working on a "Search Log Group" feature. (Not released yet; living in branch: https://github.com/aws/aws-toolkit-vscode/tree/feature/cwl )

**Comment by justinmk3** [comment]
The [Search Log Group](https://github.com/aws/aws-toolkit-vscode/pull/3570) feature will be available in AWS Toolkit 1.78.

You can test a prerelease here: https://github.com/aws/aws-toolkit-vscode/releases/tag/prerelease
