### ISSUE TITLE
Apparent regression of issue #1244 after update to v1.21.0

### ISSUE THREAD

**Issue by davidmcl** [aws/aws-toolkit-vscode#1580]
**_An error occured while resuming SAM Application creation_**....however, this occurred on vscode startup and no SAM creation was ever attempted.

**To Reproduce**

- No value in aws.samcli.location
- sam cli not installed
- Error occurs every time VS Code is started.

SAM CLI not used, so.... No error should be received.

![Screenshot at 2021-03-18 12-43-09](https://user-images.githubusercontent.com/2047925/111681499-e93a3300-87e8-11eb-9e5d-1e84b05e3c3c.png)

**Comment by justinmk3** [comment]
related: https://github.com/aws/aws-toolkit-vscode/issues/1244

**Comment by justabuzz** [comment]
To add a bit more to the above - I have SAM installed, the bottom right corner message coming from AWS Toolkit mentions incompatibility even though I have the latest SAM version installed. Thanks.

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/1582 should fix this. 

Here is a prerelease build that includes that change, can you confirm it fixes the issue for you:

1. Download and extract [toolkit.zip](https://github.com/aws/aws-toolkit-vscode/files/6171326/toolkit.zip)
2. From the VSCode command list (`ctrl-shift-p` or `cmd-shift-p`) run `Install from VSIX...` to install the `*.vsix` file.
3. Restart VSCode and verify that the Toolkit has the new version 1.22 (not the release/older version 1.21).

**Comment by justinmk3** [comment]
Toolkit 1.22 released with a fix for this.
