### ISSUE TITLE
"Add Debug Configuration" codelens polluting python import statements

### ISSUE THREAD

**Issue by dferrante** [aws/aws-toolkit-vscode#1585]
**Describe the bug**

Seeing a cascade of Add Debug Configuration on my file imports.

How do I make these go away? I'm not using SAM so I'd like to disable that functionality entirely

**To Reproduce**

Run extension on a vscode instance that doesn't have SAM installed and open a python file

**Expected behavior**

I want it to not show any of that around the imports

**Screenshots**

![Screenshot-20210319131918-909x269](https://user-images.githubusercontent.com/758148/111819372-a050b000-88b6-11eb-9b1e-9cf5724c951e.png)

**Desktop (please complete the following information):**

OS:  Linux x64 5.8.0-44-generic (Ubuntu 20.04)
Visual Studio Code Extension Host Version:  1.54.3
AWS Toolkit Version:  1.21.0

**Additional context**

None

**Comment by justinmk3** [comment]
@dferrante does this happen on every python project, or only a particular one or particular file?

> vscode instance that doesn't have SAM installed

Does that mean the problem goes away if `sam` is on the system?

**Comment by bryceitoc9** [comment]
Our criteria for codelenses in Python files are:
* file is a child or sibling of a `requirements.txt` file
* File is identified as a function by the VS Code Python language server, and is an unindented (top-level) function.
(code here: https://github.com/aws/aws-toolkit-vscode/blob/a8a2fd8570c16ff142c04807a079ac2abf1c0f01/src/shared/codelens/pythonCodeLensProvider.ts#L38 )

Out of curiosity, do these codelenses show up in any places they're supposed to, and what gets outputted into the `launch.json` file if one of these is clicked?

**Comment by dferrante** [comment]
@justinmk3 my bad for being unclear, i have not tested it with SAM installed

@bryceitoc9 this screenshot is from a file within my (django/zappa) project, with a requirements.txt at the root of it.  i see now that the "Add Debug Configuration" pops up for each import that is also a function, though not always functions even within my project (e.g. `from django.urls import reverse` triggers it).  when the codelens is clicked, they do indeed open up my launch.json and add a aws-sam lambda invoke for this function pointed at the correct file. 

i'm now realizing that this is not quite a bug but a feature request to add a switch to turn off this codelens or otherwise disable aws-toolkit-vscode from treating my whole project like its a lambda function being deployed on its own.

**Comment by bryceitoc9** [comment]
We have a feature request for disabling the codelenses here: https://github.com/aws/aws-toolkit-vscode/issues/1374 (feel free to pile onto that one) , but this is definitely a bug (maybe the language server is flagging imported functions as function symbols instead of just functions declared in the file itself?). We'll keep this issue open while we investigate.

**Comment by dferrante** [comment]
@bryceitoc9 ah great thanks, and yes confirmed, the handler name in `launch.json` is `<handlerfile>.reverse`.  

fwiw my language server is jedi (which i believe is the default) and i have the following extensions installed:
```
amazonwebservices.aws-toolkit-vscode
atlassian.atlascode
aws-scripting-guy.cform
batisteo.vscode-django
bibhasdn.django-html
bibhasdn.django-snippets
bigonesystems.django
eamodio.gitlens
eg2.vscode-npm-script
formulahendry.vscode-mysql
GitLab.gitlab-workflow
kenhowardpdx.vscode-gist
LuminusDev.azureloginaws
magicstack.Chromodynamics
mechatroner.rainbow-csv
mhutchie.git-graph
ms-azuretools.vscode-docker
ms-python.python
ms-toolsai.jupyter
PsykoSoldi3r.vscode-git-flow
redhat.vscode-yaml
ryanluker.vscode-coverage-gutters
Shan.code-settings-sync
shyykoserhiy.vscode-spotify
waderyan.gitblame
ZainChen.json
```

thanks for your time!

**Comment by bryceitoc9** [comment]
Hmm, at a bit of a loss...I can't replicate with the `jedi` language server and (what I'm thinking is) a simple example:
![image](https://user-images.githubusercontent.com/29374703/111843491-8adf8400-88be-11eb-8e66-73eb3ee21de9.png)

Out of curiosity, does this flag any imports that aren't `django`-based? If so, it might be tied to some of the `django` plugins you have installed.

**Comment by dferrante** [comment]
@bryceitoc9 it seems to be any function, for instance: 
![image](https://user-images.githubusercontent.com/758148/112236832-bf817180-8c17-11eb-98e4-a28f2c833802.png)

**Comment by bryceitoc9** [comment]
Codelens toggle (also with a command to run the codelens action without clicking a codelens) here: #1681 ; feel free to give it a shot (download the artifact from the details of one of the finished packaging tests).

**Comment by dferrante** [comment]
@bryceitoc9 confirmed it works as expected, thank you, have a nice day!
