### ISSUE TITLE
Step Function definition in YAML doesn't produce graph

### ISSUE THREAD

**Issue by dsvensson** [aws/aws-toolkit-vscode#1595]
According to this announcement Step Function definitions can be declared in YAML. If I convert my JSON files to YAML Visual Studio Code no longer produces a graph when asked to render it. Just shows a red error message in the middle of the render view that says: "Errors detected. Cannot preview."

https://aws.amazon.com/about-aws/whats-new/2021/03/aws-step-functions-adds-tooling-support-for-yaml/

I did however just re-encode the file in yaml without changing the format due to lack of examples in the blog post. Are my expectations wrong?

**Comment by dsvensson** [comment]
humm found an example, probably something else that's wrong. Would be great with better error messages :/

**Comment by justinmk3** [comment]
Duplicate of https://github.com/aws/aws-toolkit-vscode/issues/1477 : 

> The rendering will work when the file is saved with `*.asl.yaml` or `*.asl.yml` extension. Also it will work when `Amazon States Language (YAML)` Language Mode is selected.
