### ISSUE TITLE
Implement an in-toolkit way for customers to provide direct feedback

### ISSUE THREAD

**Issue by steveataws** [aws/aws-toolkit-vscode#16]
This is an issue to define how to integrate a MVP user feedback (for issues or general feedback) gesture into the tool. Once the requirements and design are signed off we will create new issues from it for implementation.

Current MVP proposal is to use a button/command gesture that opens a browser onto our GitHub repo's [new issue](https://github.com/aws/aws-toolkit-vscode/issues/new) page. We would provide a nicely formatted template for the user to complete:

a) If they are logged in it is almost seamless, 
b) if they have an account it is reasonable, 
c) if they do not yet have an account, then we are encouraging them to become part of the community :-)

Other experiences may be possible in future, for now we'll stick to a GitHub based MVP for design purposes.

**Comment by awschristou** [comment]
This issue is outdated. Closing

* #962 added a quick feedback form, released in v1.8.0
* AWS Explorer has a menu item that takes users to the GitHub repo issues
