### ISSUE TITLE
SSO: Toolkit requires a credentials file in .aws even with sso

### ISSUE THREAD

**Issue by lpd-curi** [aws/aws-toolkit-vscode#1603]
**Describe the bug**
Even though it doesn't need credentials in .aws/credentials, the credentials file must be present (empty is fine) to connect to AWS when sso is set up for a profile.

**To Reproduce**
With sso configured, and logged in with:
aws sso login --profile myprofile

In VS code go to the command palette and try to connect using AWS: Connect to AWS
If there is no .aws/credentials file this fails, but if you "touch .aws/credentials" and retry it works.

**Expected behavior**

AWS Connect should succeed with a sso profile even if there is no credentials file (there should *not* be one, and having one breaks other tools including terraform).

**Screenshots**

**Desktop (please complete the following information):**

OS:  Windows_NT x64 10.0.19042
Visual Studio Code Extension Host Version:  1.54.3
AWS Toolkit Version:  1.22.0

**Additional context**

**Comment by justinmk3** [comment]
Toolkit 1.23 (unreleased) includes https://github.com/aws/aws-toolkit-vscode/pull/1626 which fixes the issue where Toolkit may fail to connect if  `~/.aws/credentials` does not exist.

The following prerelease build includes the fix, we appreciate your feedback:

1. Download/extract the prerelease build: [aws-toolkit.zip](https://github.com/aws/aws-toolkit-vscode/files/6281457/aws-toolkit.zip)
2. From the VSCode command list (`ctrl-shift-p` or `cmd-shift-p`) run `Extensions: Install from VSIX...` to install the `*.vsix` file.
3. Reload VSCode and verify that the Toolkit has the new version (not the release/older version).
