### ISSUE TITLE
Support latest version of AWS SAM CLI

### ISSUE THREAD

**Issue by SpencerHD2020** [aws/aws-toolkit-vscode#1605]
**Is your feature request related to a problem? Please describe.**

The newest version of the SAM CLI this works with is 0.5 but you get 1.2 from AWS official site!

**Describe the solution you'd like**

Update the extension or change the if statement to latest version if it is that simple.

**Describe alternatives you've considered**

Just using the CLI

**Comment by justinmk3** [comment]
Toolkit supports up to SAM CLI 2.0.

- What version of the Toolkit are you using?
- Can you paste the result of `About AWS Toolkit `command?
- Can you provide the information requested by the issue template? 
- What steps did you take exactly?

**Comment by SpencerHD2020** [comment]
**Describe the bug**



**To Reproduce**



**Expected behavior**

It shows that the SAM CLI version has to be greater than or equal to 0.38.0 and less than or equal to 0.50.0. I have version 1.21.1 of the SAM CLI. 

**Screenshots**

Linked above

**Desktop (please complete the following information):**



-   OS: Windows_NT x64 10.0.18363
-   Visual Studio Code Version: 1.41
-   AWS Toolkit Version: 1.8.0

**Additional context**


If there is a newer version I could not find it in the Extension store for VSCode. It says that the extension is up to date and I got the SAM CLI directly from AWS.

**Comment by justinmk3** [comment]
> * AWS Toolkit Version: 1.8.0

That is very old. Upgrade to Toolkit 1.22

**Comment by SpencerHD2020** [comment]
When I click install in the link provided it redirects me to VSCode and I see this:

![image](https://user-images.githubusercontent.com/63194987/112856827-d1c73980-9075-11eb-87f2-c99da196b83a.png)

**Comment by justinmk3** [comment]
> Visual Studio Code Version: 1.41

That is a very old version of VSCode, and is likely why you are seeing an old version of the Toolkit. Because old versions of VSCode show old versions of all extensions.

If you must use an old version of VSCode, then all extensions will be restricted to old versions also.

**Comment by SpencerHD2020** [comment]
Okay, I work for a company that distributes "verified" versions of SW and they are usually older with updates disabled. I will see if I can manually update. Thank you for the help

**Comment by justinmk3** [comment]
Toolkit 1.22 still supports vscode 1.42, so you can download the VSIX file here: https://github.com/aws/aws-toolkit-vscode/releases then install it using the VSCode command `Install from VSIX...`
