### ISSUE TITLE
credentials: cannot switch to profile with aws_session_token

### ISSUE THREAD

**Issue by travis-jorge** [aws/aws-toolkit-vscode#1609]
**Describe the bug**

When using a Named Profile (Not Default) VSCODE and the AWS Toolkit is not using the correct profile, It always uses default

**To Reproduce**

1.Create an AWS Named profile Not Default with AccessKey, Secret, and Session Token.
     a) I created the profile manually in the credentials file. VSCODE and AWS Toolkit can see the Named profile it just doesnt use it. 
2. In VS CODE set the profile to your new named profile
3. Run a python script to do anything with that profile
4. It will use the Default profile not the named one

**Expected behavior**

when the script runs it should use the credentials defined in the profile you have selected.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/80355769/113030644-d49c5a00-915b-11eb-9bf6-8a0f90d34674.PNG)

**Desktop (please complete the following information):**

VS Code Version: 1.54.3
OS Version:Windows_NT x64 10.0.19042
AWS Tool Kit:1.22.0

**Comment by justinmk3** [comment]
Can you provide the exactly `~/.aws/config` profile entry (not including AccessKey/Secret). 

Can you provide the logs? 

1. Set the Toolkit log level to "verbose": in VSCode settings search for "aws log level", then select "verbose".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View AWS Toolkit Logs` command to get the logs.

> Run a python script to do anything with that profile

What exactly are the steps here? Are you running the script with Toolkit? In VSCode? In a separate terminal?

**Comment by travis-jorge** [comment]
![credsfile](https://user-images.githubusercontent.com/80355769/113031648-f64a1100-915c-11eb-9e93-9c84d98df8a1.PNG)
Config file
[default]
region = us-west-2
output = json

[myview_dev]
region = us-west-2
output = json

2021-03-30 13:42:04 [VERBOSE]: Profile default contains aws_access_key_id - treating as regular Shared Credentials
2021-03-30 13:42:04 [VERBOSE]: Getting AccountId from region us-west-2
2021-03-30 13:42:05 [VERBOSE]: Credentials changed (profile:default), updating AWS Explorer
2021-03-30 13:42:08 [VERBOSE]: Getting AccountId from region us-east-1
2021-03-30 13:42:08 [VERBOSE]: Credentials changed (profile:myview_dev), updating AWS Explorer
2021-03-30 13:43:03 [INFO]: Successfully sent a telemetry batch of 20
2021-03-30 13:43:04 [INFO]: Successfully sent a telemetry batch of 2

@justinmk3  I see an issue from the logs that its trying to use us-east-1 but that is not what is set in the config file for that profile

**Comment by travis-jorge** [comment]
just to be clear i changed the name to myview_dev from dev_test in the first screen shot

**Comment by justinmk3** [comment]
The presence of `aws_session_token` seems related.

https://github.com/aws/aws-toolkit-vscode/commit/86e060496830d542396b added validation of `aws_session_token`.

After switching to `myview_dev` (`dev_test` in the screenshot), the logs should show:

    Profile myview_dev contains aws_session_token - treating as regular Shared Credentials

**Comment by justinmk3** [comment]
> Config file
> [default]
> region = us-west-2
> output = json
> 
> [myview_dev]
> region = us-west-2
> output = json

By this file, do you mean `~/.aws/config`? In that file, the non-default profile names must be prefixed with `profile`:

> Config file
> [default]
> region = us-west-2
> output = json
> 
> [profile myview_dev]
> region = us-west-2
> output = json

**Comment by travis-jorge** [comment]
ok, i made the change to the .config file and it now shows the correct region and Profile myview_dev contains aws_session_token - treating as regular Shared Credentials. Unfortunately, it still is using the default profile. I verified this by running a simple python script and it fails to connect but if I copy the access key, secret, and token to the default profile and rerun the script succeeds at connecting. @justinmk3

**Comment by justinmk3** [comment]
> I verified this by running a simple python script and it fails to connect

Can you expand on this, what are the exact steps you are taking to run a python script? I'm not aware of any feature to run a python script (except SAM local run/debug).

**Comment by travis-jorge** [comment]
ok thank you for clarifying that I thought it would grab the profile set by the tool kit. @justinmk3
