### ISSUE TITLE
auth: auto-configure .ssh/config to use SSM session manager so we can log into EC2

### ISSUE THREAD

**Issue by sholtomaud** [aws/aws-toolkit-vscode#1627]
Hi 

This is pretty limited extension. What we want is the following.

Ability to turn EC2s on and off manually and set EC2 shutdown schedule

Automatic configuration of .ssh/config to use ssm session manager so we can log into EC2s

The ability for an AWS Admin to pre-configure the toolkit so that a user gets certain features/services exposed but not others

The ability to setup/pre-configure OIDC federation between external Authentication services and AWS accounts. Typically we have external AzureAD auth service.

**Comment by justinmk3** [comment]
Thanks for your feedback! We are working on adding more services to AWS Explorer.

> Ability to turn EC2s on and off manually and set EC2 shutdown schedule

I have added this to https://github.com/aws/aws-toolkit-vscode/issues/1559 .

> The ability for an AWS Admin to pre-configure the toolkit so that a user gets certain features/services exposed but not others

Can you expand on the use-case here? Would this run in a locked-down version of VSCode (or compatible), managed by enterprise group policy? Or, are you envisioning controls in the AWS web console that would control what features the Toolkit exposes?

How would this differ from restricting the user's permissions via IAM?

> The ability to setup/pre-configure OIDC federation between external Authentication services and AWS accounts. Typically we have external AzureAD auth service.

Is that normally done in the AWS web console? Is something missing there? See https://github.com/aws/aws-toolkit-vscode/issues/1475#issuecomment-769469260

**Comment by sholtomaud** [comment]
> How would this differ from restricting the user's permissions via IAM?

It possibly wouldn't. Lets say there are x10EC2s in an account, and AWS toolkit user should only have access to x4 of the EC2s based on a combination of their IAM role & EC2 tags. The AWS toolkit should only show those x4 EC2s, and if I have permissions to start stop/schedule state changes these should be available (right-click?) from the toolkit. 

Needless to say the user might also want to log into the EC2 via session manager (aws cli) and VSCode Remote Explorer to edit some code on that EC2 instance. 

This in turn raises the question of Federated access.

> Is that normally done in the AWS web console? 

Normally there is some Authentication service for an enterprise. For us its AzureAD, and we want to pass that auth through (OIDC) not just to AWS APIs, but also to access the EC2 itself. To this end you might like to look at the following VSCode ticket [4866](https://github.com/microsoft/vscode-remote-release/issues/4866).

If I can right click on an EC2 presented in the AWS Toolkit, and that then will give me the option of launching the EC2 and connecting to a Remote SSH session through aws session manager, which in turn opens the EC2 file system in a VSCode workspace - it would be a bit win for the enterprise.

**Comment by justinmk3** [comment]
> To this end you might like to look at the following VSCode ticket [4866](https://github.com/microsoft/vscode-remote-release/issues/4866).

Thanks, subscribed :)

> If I can right click on an EC2 presented in the AWS Toolkit, and that then will give me the option of launching the EC2 and connecting to a Remote SSH session through aws session manager, which in turn opens the EC2 file system in a VSCode workspace - it would be a bit win for the enterprise.

Thanks for those details. We are thinking about this area for 2021, I will comment here when we have an update.

**Comment by pratiklotia** [comment]
Hello amazing team, is there any update on this feature?

**Comment by justinmk3** [comment]
@pratiklotia it's on our roadmap and will update this issue when we have something to show.

**Comment by sholtomaud** [comment]
@justinmk3  - is the roadmap public? 

Also be aware that at the moment there is a problem with VSCode remote desktop viewer which makes the ideas above non-viable. There is a leak in VSCode remote desktop code which makes remote servers unusable and Microsoft haven't shown any interest in fixing it. 

Given Amazon is a very large company you could use Electron to host your own VScode/cloud9 copy and release it as an app, or build your own version of VSCodium perhaps and fix the remote desktop bug, and put in SSO auth + even bundle the codeCommit auth package etc. 

If you need some on this ping me :)

**Comment by justinmk3** [comment]
> @justinmk3 - is the roadmap public?

Not yet (no ETA) but much of it is driven by highly-upvoted issues: https://github.com/aws/aws-toolkit-vscode/issues?q=is%3Aissue+is%3Aopen+label%3Afeature-request+sort%3Areactions-%2B1-desc

> Also be aware that at the moment there is a problem with VSCode remote desktop viewer which makes the ideas above non-viable.

Thank you for the help. Our plan is to start with something like https://github.com/aws/aws-toolkit-vscode/issues/941 . It works with ECS and I would expect it to work with any SSM => SSH endpoint.

> SSO auth + even bundle the CodeCommit auth package, aws cli, SAM,

We are actively working on improvements here! We've had some success auto-installing `session-manager-plugin` and are looking to apply that to `sam` cli and eventually `aws` cli (as private Toolkit-owned installs, which won't pollute the system $PATH). This will be optional, of course.

**Comment by sholtomaud** [comment]
> We've had some success auto-installing session-manager-plugin

ohhhhh, good work.

**Comment by justinmk3** [comment]
> Our plan is to start with something like #941 . It works with ECS and I would expect it to work with any SSM => SSH endpoint.

Status: https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-1609299367

**Comment by justinmk3** [comment]
# Status

AWS Toolkit 3.39.0 includes [these features](https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-2539726009):

* ✅ AWS Explorer (and VSCode command palette): Start/Stop/Reboot actions [#1559](https://github.com/aws/aws-toolkit-vscode/issues/1559)
* ✅ AWS Explorer: list EC2 instances, view their status.
* ✅ `AWS: Launch EC2 Instance` command opens the AWS web console launch page.
* ✅ `AWS: Open terminal to EC2 instance...` command opens a VSCode terminal connected to an EC2 instance.
    * Requires [remote-ssh](https://code.visualstudio.com/docs/remote/ssh) (which requires `ssh` on your local desktop).
    * Supports EC2 instances running Linux/macOS/**Windows**.
* ✅ `AWS: Connect to EC2 instance in New Window...` command connects VSCode to an EC2 instance.
    * Requires [remote-ssh](https://code.visualstudio.com/docs/remote/ssh) (which requires `ssh` on your local desktop).
    * Supports EC2 instances running Linux or macOS (**not Windows, currently**).
    * Your local desktop can be Linux/macOS/Windows.
    * <img width="591" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/55561878/8da31cbd-0542-4607-911b-d87ed39af443">
