### ISSUE TITLE
SAM UX: surface failed runtime version check ("executable found ... does not match runtime")

### ISSUE THREAD

**Issue by tyron** [aws/aws-toolkit-vscode#1643]
**Describe the bug**

When launching a debug session on macOS (Apple Silicon) with sam 1.22.0 installed via Homebrew (`/opt/homebrew/bin/sam`), execution fails with: `ImportError: No module named debugpy`.

This is a continuation of https://www.github.com/aws/aws-toolkit-vscode/issues/1507#issuecomment-817236370

**To Reproduce**

1. Create `launch.json` with the following contents:
```json
{
    "type": "aws-sam",
    "request": "direct-invoke",
    "name": "Invoke Lambda",
    "invokeTarget": {
        "target": "code",
        "lambdaHandler": "lambda_function.lambda_handler",
        "projectRoot": "${workspaceFolder}"
    },
    "lambda": {
        "runtime": "python3.8",
        "payload": {
            "json": {}
        }
    }
}
```
2. Start debug session

**Expected behavior**

Application to launch with attached debugger.

**Screenshots**

n/a

**Desktop (please complete the following information):**

-   OS: macOS BigSur 11.2.3
-   Visual Studio Code Version: 1.55.2
-   AWS Toolkit Version: 1.22.0

**Additional context**

Verbose logs: [sam.log](https://github.com/aws/aws-toolkit-vscode/files/6307698/sam.log)

**Comment by tyron** [comment]
Might be worth mentioning that I have a folder `venv` created with `python -m venv venv`, which contains my virtualenv. If I install debugpy on virtualenv (`source venv/bin/activate && pip install debugpy`), the behaviour is still the same, not working. However, if I add the library in my project's root folder with `pip install debugpy -t .`, then the execution works fine.

Do I need to install all libraries to my project's root folder?

**Comment by justinmk3** [comment]
> However, if I add the library in my project's root folder with `pip install debugpy -t .`, then the execution works fine.
> 
> Do I need to install all libraries to my project's root folder?

No. debugpy is installed implicitly to the mounted SAM build: https://github.com/aws/aws-toolkit-vscode/blob/925e15416acbf4be9fa8bed0010c7f807ac82c45/src/shared/sam/debugger/pythonSamDebug.ts#L62

Need to figure out why virtualenv would change behavior here.

**Comment by tyron** [comment]
> No. debugpy is installed implicitly to the mounted SAM build:

Sorry, I wasn't clear. I get that debugpy is (or should be) installed by SAM, I was wondering about other libraries. Let's say, I need `requests`, and I have it on my `requirements.txt`. Do I install it on the host's virtualenv (`pip install requests`) or do I place it on library folder (`pip install requests -t .`)?

And let me know if there's anything else I can provide. I noticed I don't have a requirements.txt in the root folder. Do I need it? Wondering if `manifestText` starts from an empty file and fails for some reason...

**Comment by justinmk3** [comment]
> Let's say, I need `requests`, and I have it on my `requirements.txt`. Do I install it on the host's virtualenv (`pip install requests`) or do I place it on library folder (`pip install requests -t .`)?

Normally it shouldn't be needed, because the Toolkit passes your requirements.txt to `sam` which then does a `pip install` in the container.

> I noticed I don't have a requirements.txt in the root folder. Do I need it? Wondering if `manifestText` starts from an empty file and fails for some reason...

Good question :) Can you try it?

**Comment by tyron** [comment]
I tried both and it didn't work still... Any other ideas? Do you happen to have a repo that has everything configured (app folder, `.vscode/launch.json`) and working that i could just checkout and run?

**Comment by justinmk3** [comment]
> Do you happen to have a repo that has everything configured (app folder, `.vscode/launch.json`) and working that i could just checkout and run?

Yes, if you create a new Lambda SAM app via the command `AWS: Create Lambda SAM Application` and choose python with the "hello world" template.

**Comment by tyron** [comment]
Just ran this and had the same error. Captured new logs from this attempt, as the file tree created by this command within VS Code is slightly different from just running the `sam init`.

Running `AWS: Create Lambda SAM Application` rendered this workspace:
```
.
├── .vscode
│   └── launch.json
└── lambda-python3.8
    ├── .gitignore
    ├── README.md
    ├── __init__.py
    ├── events
    │   └── event.json
    ├── hello_world
    │   ├── __init__.py
    │   ├── app.py
    │   └── requirements.txt
    ├── template.yaml
    └── tests
        ├── __init__.py
        ├── integration
        │   ├── __init__.py
        │   └── test_api_gateway.py
        ├── requirements.txt
        └── unit
            ├── __init__.py
            └── test_handler.py
```
Logs: [aws_toolkit_20210416T191520.log](https://github.com/aws/aws-toolkit-vscode/files/6328567/aws_toolkit_20210416T191520.log)

**Comment by justinmk3** [comment]
What python version is in the virtualeenv?

SAM CLI is reporting a mismatch:

```
,2021-04-16 23:20:34,729 | Invalid executable for python at /Users/my-user/.pyenv/shims/python
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.22.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 58, in wrapper
    valid_path = binary_checker.validator.validate(executable_path)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.22.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/validator.py", line 48, in validate
    raise MisMatchRuntimeError(language=self.language, required_runtime=self.runtime, runtime_path=runtime_path)
aws_lambda_builders.exceptions.MisMatchRuntimeError: python executable found in your path does not match runtime. 
 Expected version: python3.8, Found version: /Users/my-user/.pyenv/shims/python. 
 Possibly related: https://github.com/awslabs/aws-lambda-builders/issues/30
,2021-04-16 23:20:34,752 | Invalid executable for python at /usr/bin/python
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.22.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 58, in wrapper
    valid_path = binary_checker.validator.validate(executable_path)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.22.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/validator.py", line 48, in validate
    raise MisMatchRuntimeError(language=self.language, required_runtime=self.runtime, runtime_path=runtime_path)
aws_lambda_builders.exceptions.MisMatchRuntimeError: python executable found in your path does not match runtime. 
 Expected version: python3.8, Found version: /usr/bin/python. 
 Possibly related: https://github.com/awslabs/aws-lambda-builders/issues/30
```

It also mentions https://github.com/awslabs/aws-lambda-builders/issues/30

## Proposal

Toolkit should try to detect this issue to make it clearer to users.

**Comment by justinmk3** [comment]
> Proposal: Toolkit should try to detect this issue to make it clearer to users.

Implemented in https://github.com/aws/aws-toolkit-vscode/pull/3761
