### ISSUE TITLE
Activating the extension hangs forever (under some weird circumstances)

### ISSUE THREAD

**Issue by hunterwerlla** [aws/aws-toolkit-vscode#1649]
It seems like the extension activation hangs forever on activation when calling `getCredentials`, specifically the line `await provider.resolvePromise()` never resolves or times out

Here are what my credentials/config files look like:
`~/.aws/config`
```
[default]
region = us-west-2
```
`~/.aws/credentials`
```
[DEFAULT]

[default]
credential_process=/Users/werlla/<inhouse credentials process proram> credentials update
aws_access_key_id=<Access key>
aws_secret_access_key=<Secret access key>
aws_session_token=<token>
```
The inhouse credentials process program adds access key and secret access key when it runs. This works as expected from the toolkit for JetBrains and the AWS cli.

If nothing else, we should have a timeout for getting credentials since credential process/network can have issues never resolving preventing activation of the extension.

**Comment by justinmk3** [comment]
relevant code: https://github.com/aws/aws-toolkit-vscode/blob/46bb7fa80f6e774173c48d79982381b45c52ba3b/src/credentials/providers/sharedCredentialsProvider.ts#L188-L194

I don't see a timeout property on [AWS.ProcessCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ProcessCredentials.html) but maybe we can use `waitUntil()`.
