### ISSUE TITLE
Add CloudFormation to AWS Explorer

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#165]
The AWS Explorer has regions, and lambda functions per region. Add CloudFormation stacks.

* AWS Explorer Tree structure, similar to the AWS Toolkit for Jetbrains:
```
+ Region xxx
  + CloudFormation
    + Stack xxx
      + Lambda Function xxx
  + Lambda
    + Lambda Function xxx
```
![image](https://user-images.githubusercontent.com/39839589/49884936-e9b61900-fdea-11e8-88ac-95c225e54c65.png)

* Each CloudFormation stack shows the stack status
* Each CloudFormation stack lists Lambda Function resources as its children
* CloudFormation stacks can be deleted using the context menu

**Comment by acguglielmo** [comment]
I'm interested in working on this issue.

**Comment by awschristou** [comment]
Hi @acguglielmo , thank you for your interest in contributing! Feel free to look into this. Reach out if you have any questions, and please let us know if you make some progress, so we don't inadvertently duplicate the work :)
