### ISSUE TITLE
Release Pipeline

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#166]
Requirements (this might get split out into separate tasks):
* runs unit/integration tests where applicable
* Produces a .vsix extension file (versioned and branded)
* Digitally signs .vsix file (just like the AWS VSTS toolkit does)
* Publishes .vsix to VS Code Marketplace
* Archives the .vsix file
* Tags the commit used to make the build
* needs to run headless so that it can be triggered from commits, running somewhere like CodeBuild or TravisCI

**Comment by hunterwerlla** [comment]
Broke signing into issue #633 

I have completed the other taks
