### ISSUE TITLE
User's credentials are validated when changing profiles to reduce access errors

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#167]
When the Toolkit creates an initial AWS Credential profile, that profile is validated using STS `getCallerIdentity`. The same validation should happen whenever a user changes the Credential Profile used in the Toolkit. This helps to reduce the amount of errors encountered when trying to use invalid credentials.

**Comment by awschristou** [comment]
Postponed, see #188

**Comment by mpiroc** [comment]
Closed as dup of #576.
