### ISSUE TITLE
Unable to get S3 buckets information 

### ISSUE THREAD

**Issue by solairen** [aws/aws-toolkit-vscode#1671]
**Describe the bug**
After connection to the AWS toolkit, I'm unable to get S3 buckets.

```log
2021-04-23 19:13:50 [ERROR]: [Error: getaddrinfo ENOENT s3.eu-central-1.amazonaws.com
	at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)] {
  errno: 'ENOENT',
  code: 'NetworkingError',
  syscall: 'getaddrinfo',
  hostname: 's3.eu-central-1.amazonaws.com',
  region: 'eu-central-1',
  retryable: true,
  time: 2021-04-23T17:13:50.252Z
}
```

**To Reproduce**

1. Go to Extensions, type AWS Toolkit and install.
2. Click on the AWS icon in VSCode.
3. Log in to the AWS account.
4. Select S3

**Expected behavior**
All S3 buckets are visible in the S3 section.

**Desktop (please complete the following information):**

-   OS: Windows 10 Pro
-   Visual Studio Code Version: 1.55.2
-   AWS Toolkit Version: 1.24.0

**Additional context**

I've verified my Access Key and Secret Key using Postman and I am able to retrieve S3 information.
Also, I am able to create an S3 bucket from VSCode.

**Comment by justinmk3** [comment]
> Also, I am able to create an S3 bucket from VSCode.

Hmm. I can't think of how this could happen. Just guessing, are you behind a proxy?

**Comment by solairen** [comment]
@justinmk3 I've found the problem. My Pi-Hole is blocking all **S3.<region>.amazonaws.com** and that's why AWS Toolkit is unable to get information. It's strange that it allowed me to create an S3 bucket from VSCode and also it not blocking the AWS site.

I could check it earlier before I created an issue, sorry for that.
I'm closing this issue.
