### ISSUE TITLE
"Failed to run SAM application locally: template path does not exist" when --build-dir is set 

### ISSUE THREAD

**Issue by AbeGellis** [aws/aws-toolkit-vscode#1689]
**Desktop (please complete the following information):**

-   OS: Windows 10 Home version 2004
-   VS Code version: 1.55.2
-   AWS Toolkit extension version: 1.24.0

**Question**
I am able to configure and run the SAM hello-world example. However, when I attempted to use the VS Code extension to test local invocation, first it complained about working across multiple drives (AWS CLI, SAM, VS Code are all installed on my C: drive, while the project is in my D: drive) and when I attempted to correct this by adding a build-dir argument I found that that caused the process to fail in another way.

My configuration in launch.json is as follows:

> {
>       "type": "aws-sam",
>       "request": "direct-invoke",
>       "name": "ctb-serverless-backend:HelloWorldFunction (python3.8)",
>       "sam": {"buildArguments": ["--build-dir", "${workspaceFolder}/output"]},
>       "invokeTarget": {
>             "target": "template",
>             "templatePath": "${workspaceFolder}/template.yaml",
>             "logicalId": "HelloWorldFunction"
>       },
>       "lambda": {
>             "payload": {},
>             "environmentVariables": {}
>       }
> }
> 

and the output in AWS Toolkit logs is as follows:

> 2021-04-29 18:24:14 [INFO]: Preparing to debug locally: Lambda "app.lambda_handler"
> 2021-04-29 18:24:14 [INFO]: Building SAM application...
> 2021-04-29 18:24:16 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
> 2021-04-29 18:24:16 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
> 2021-04-29 18:24:16 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd build --build-dir C:\Users\ME\AppData\Local\Temp\aws-toolkit-vscode\vsctkNLSydY\output --template D:/Work/Projects/CTB-Serverless-Backend/ctb-serverless-backend/app___vsctk___template.yaml --manifest C:\Users\ME\AppData\Local\Temp\aws-toolkit-vscode\vsctkNLSydY\debug-requirements.txt --build-dir D:\Work\Projects\CTB-Serverless-Backend\ctb-serverless-backend/output]
> 2021-04-29 18:24:16 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd build --build-dir C:\Users\ME\AppData\Local\Temp\aws-toolkit-vscode\vsctkNLSydY\output --template D:/Work/Projects/CTB-Serverless-Backend/ctb-serverless-backend/app___vsctk___template.yaml --manifest C:\Users\ME\AppData\Local\Temp\aws-toolkit-vscode\vsctkNLSydY\debug-requirements.txt --build-dir D:\Work\Projects\CTB-Serverless-Backend\ctb-serverless-backend/output]
> 2021-04-29 18:24:21 [INFO]: Building codeuri: D:\Work\Projects\CTB-Serverless-Backend\ctb-serverless-backend\get_FLA_parent_activities runtime: python3.8 metadata: {} functions: ['getFLAparentactivities']
> 
> 2021-04-29 18:24:21 [INFO]: Running PythonPipBuilder:ResolveDependencies
> 
> 2021-04-29 18:24:34 [INFO]: Running PythonPipBuilder:CopySource
> 
> 2021-04-29 18:24:34 [INFO]: Building codeuri: D:\Work\Projects\CTB-Serverless-Backend\ctb-serverless-backend\hello_world runtime: python3.8 metadata: {} functions: ['HelloWorldFunction']
> 
> 2021-04-29 18:24:35 [INFO]: Running PythonPipBuilder:ResolveDependencies
> 
> 2021-04-29 18:24:50 [INFO]: Running PythonPipBuilder:CopySource
> 
> 2021-04-29 18:24:50 [INFO]: 
> Build Succeeded
> 
> 2021-04-29 18:24:50 [INFO]: 
> Built Artifacts  : D:\Work\Projects\CTB-Serverless-Backend\ctb-serverless-backend\output
> Built Template   : D:\Work\Projects\CTB-Serverless-Backend\ctb-serverless-backend\output\template.yaml
> 
> Commands you can use next
>
> =========================
> [*] Invoke Function: sam local invoke -t D:\Work\Projects\CTB-Serverless-Backend\ctb-serverless-backend\output\template.yaml
> [*] Deploy: sam deploy --guided --template-file D:\Work\Projects\CTB-Serverless-Backend\ctb-serverless-backend\output\template.yaml
>     
> 
> 2021-04-29 18:24:51 [INFO]: Build complete.
> 2021-04-29 18:24:51 [INFO]: Starting SAM application locally
> 2021-04-29 18:24:54 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
> 2021-04-29 18:24:56 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
> 2021-04-29 18:24:58 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
> 2021-04-29 18:24:58 [ERROR]: Failed to run SAM application locally: template path does not exist: C:\Users\ME\AppData\Local\Temp\aws-toolkit-vscode\vsctkNLSydY\output\template.yaml
> 2021-04-29 18:24:58 [INFO]: Attaching debugger to SAM application...
> 2021-04-29 18:25:33 [ERROR]: Retry limit reached while trying to attach the debugger.
> 2021-04-29 18:25:33 [ERROR]: Unable to attach Debugger. Check AWS Toolkit logs. If it took longer than expected to start, you can still attach.

I am unable to figure out why it is looking for a template at C:\Users\ME\AppData\Local\Temp\aws-toolkit-vscode\vsctkNLSydY\output\template.yaml or how to change that to look at the specified build-dir. I would like it if I could build within my project directory, or if not, to know why that is impossible.

Additionally, every time I run and it fails on any step before "Attaching debugger" it still attempts to attach the damn thing 9 times and throws an error up every time it fails. I've searched for settings and configuration options to change this - it's highly aggravating when trying to iterate on configurations that might cause those earlier steps to fail - to no avail.

Does anyone have any suggestions for what I can do to address either of these issues? Neither is present when I (successfully) use sam build and sam local invoke directly from cmd.

**Comment by justinmk3** [comment]
> I am unable to figure out why it is looking for a template at C:\Users\ME\AppData\Local\Temp\aws-toolkit-vscode\vsctkNLSydY\output\template.yaml or how to change that to look at the specified build-dir. 

Unfortunately `--build-dir` is not an arg we anticipated needing to customize; the Toolkit currently works by building in a separate temp directory (and thus clobbers the custom `--build-dir`). We have done some work to reduce the need for the temporary dir; for continuing that, it's useful to know about this use-case.

> I would like it if I could build within my project directory, or if not, to know why that is impossible.



> when I attempted to use the VS Code extension to test local invocation, first it complained about working across multiple drives

What was the exact message? I wonder which layer is complaining, and why...

**Comment by AbeGellis** [comment]
> Unfortunately --build-dir is not an arg we anticipated needing to customize; the Toolkit currently works by building in a separate temp directory (and thus clobbers the custom --build-dir). We have done some work to reduce the need for the temporary dir; for continuing that, it's useful to know about this use-case.

That makes sense. I saw the build-dir argument included twice in the command (and the second custom one seemed to be overriding the first). I can work in the C: drive even if if's not my first choice.

> What was the exact message? I wonder which layer is complaining, and why...

The specific error was:
> ValueError: path is on mount 'D:', start on mount 'C:'

But on further inspection, that's related to me trying to integrate a python layer in a different function in the same project. I stripped it down to just the Hello World function + API definition earlier to confirm that the first issue that I raised was independent of anything I had added myself, and I'll look closer into this before raising it as a separate issue.

> There shouldn't be a modal error for Python, which is why we retry in that case :( The reason for retrying is to avoid a fixed timeout when waiting for the python debugger to be available. Sounds like we need to revisit this.

Makes sense - it seems tricky to get everything working nicely with everything else. The number of retries seemed very specific so I was driving myself up a wall looking for a configuration that controlled it before I complained here.

Thanks for the explanation!

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/1690 should help with the experience here, in particular it should avoid the "retry spam". If you want to try it we would love your feedback:

1. Download and extract [buildArtifacts.zip](https://github.com/aws/aws-toolkit-vscode/files/6406623/buildArtifacts.zip)
2. From the VSCode command list (`ctrl-shift-p` or `cmd-shift-p`) run `Extensions: Install from VSIX...` to install the `*.vsix` file.
3. Reload VSCode and verify that the Toolkit has version 1.25 (not the release version 1.24).

**Comment by AbeGellis** [comment]
That did the trick! I deliberately reintroduced the 

> ValueError: path is on mount 'D:', start on mount 'C:'

error and it stopped processing immediately after. I then uncommented the Metadata > BuildMethod parameter in the template.yaml and got the expected output. Much less of a headache to mess around with, now - thank you!

**Comment by justinmk3** [comment]
I believe Toolkit 1.25 addresses the pain points here. If support for `--build-dir` is still needed please create a new issue describing the use-case.
