### ISSUE TITLE
Should not send log files to $HOME/.config/Code

### ISSUE THREAD

**Issue by tigerinus** [aws/aws-toolkit-vscode#1692]
**Describe the bug**

This extension pollutes `~/.config` folder with a whole bunch of `aws_toolkit_*.log` files.

My `~/.config` folder is version controlled. I could add `**/*.log` to `.gitignore`, but that's just a preventive approach. No extension, or any other code/app/service should write log files to `~/.config`.

**To Reproduce**

Use the extension for a while.

**Expected behavior**

As a best practice it should send the logs to a log folder.

**Screenshots**

![image](https://user-images.githubusercontent.com/7172560/116708632-e745c100-a99d-11eb-9414-b7e51dedb4b0.png)

**Desktop (please complete the following information):**

AWS Toolkit for VSCode: v1.24.0

Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Additional context**

**Comment by tigerinus** [comment]
I will definitely re-install this extension once this issue is resolved.

**Comment by bryceitoc9** [comment]
Hi @tigerinus ,

I think this was an oversight on our part not knowing exactly where VS Code put logs on non-Windows/Mac machines (the folder we're using for Mac and Windows are the same folder where VS Code puts their logs, albeit we don't have any cleanup logic): https://github.com/aws/aws-toolkit-vscode/blob/master/src/shared/logger/activation.ts#L142

Just out of curiosity, where is VS Code's default log folder on your machine, and what specific OS are you using (correct me if I'm wrong, but it looks like you're using WSL)? You should be able to find this by running the `Developer: Open Logs Folder` command in the command palette.

**Comment by tigerinus** [comment]
@bryceitoc9 , thanks for looking into this quickly.

There are two types of logs folders in VSCode apparently:
![image](https://user-images.githubusercontent.com/7172560/116718846-67712400-a9a8-11eb-8112-5a29444f666f.png)

I believe for this case it should go to Extension Logs Folder.

On machine it's `%APPDATA$\Code\logs\20210430T101000\exthost1` which is a Windows path, even though I use VSCode with WSL2 intensively.

There is this [OutputChannel](https://code.visualstudio.com/api/references/vscode-api#OutputChannel) interface from VSCode extension API. Isn't that something every VSCode extension should consider for output?

**Comment by justinmk3** [comment]
Toolkit 1.25 stores logs in `globalStoragePath` , which should implicitly store data in a reasonable place (and not `~/.config`).
