### ISSUE TITLE
Update Lambda Function with new Code

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#174]
Lambda Function nodes in the AWS Explorer should have a context menu item that allows for publishing updated code to the selected Lambda.

Requires the same code bundling used in #171 

* It should be possible to change the current Lambda Handler value
* an S3 bucket should be requested from the user for use in deploying the code

**Comment by bryceitoc9** [comment]
Code updates here: https://github.com/aws/aws-toolkit-vscode/pull/1269 . Does not currently support upload to S3 (although that can be finagled in at a later date).

**Comment by justinmk3** [comment]
Toolkit 1.16 was released today and includes "Upload Lambda" feature.
