### ISSUE TITLE
To Run/Debug a Lambda locally, user can use CodeLens from the SAM Template

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#177]
* A CodeLens for each of `Run` and `Debug` a Lambda Function locally appears on each Resource that is a Lambda Function
* instead of writing our own yaml parser, we can use VS Code's symbol retrieval, which then works if the user has a different extension installed which contains a yaml parser. Expectation is that the functionality simply "doesn't exist" (opposed to erroring) if we aren't able to get template file symbols
* User is expected to have a sam template with proper values filled in. Try to do _some_ validation where possible, but handle things as gracefully as possible if user tries to run a resource that isn't properly configured (example: if CodeUri is not correct).

Requires
* #135 to do the actual invoke

Observations
* if we had a way of referencing between Sam Template and actual function (#172) this could help validate the template.

**Comment by micholas** [comment]
Does it make sense to initiate Lambda debugging from the template? To debug the user should add break points which need to be added to the handler source file. Perhaps it makes more sense to only add support for running from a code lens in the template .

**Comment by justinmk3** [comment]
AWS Toolkit 1.12 (released today) includes a new [SAM local Lambda debugging experience](https://github.com/aws/aws-toolkit-vscode/pull/1215) which leverages VS Code _launch configurations_. The new UX allows using VS Code's standard entrypoints for debugging: 

- F5
- the Run panel
- VS Code commands such as `Run: Start Without Debugging` and `Debug: Select and Start Debugging`

Documentation: https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/run-debug-sam-app.html
