### ISSUE TITLE
Profiles not loaded correctly

### ISSUE THREAD

**Issue by share-me** [aws/aws-toolkit-vscode#1784]
**Describe the bug**

Only profiles not presents in "config" file are loaded

.aws/config
```ini
[profile second-role]
role_arn = arn:aws:iam::000000000000:role/myrole
source_profile = myrole
region = us-east-2
```

.aws/credentials
```ini
[first-role]
output = json
region = us-east-2
aws_access_key_id = secret
aws_secret_access_key = secret
aws_session_token = secret

[second-role]
output = json
region = us-east-2
aws_access_key_id = secret
aws_secret_access_key = secret
aws_session_token = secret
```

**To Reproduce**
1. Click on "Connect to AWS"
2. Only one profile appears (instead of 5)

**Expected behavior**

2 profiles

**Desktop (please complete the following information):**

OS:  Windows_NT x64 10.0.18363
Visual Studio Code Extension Host Version:  1.56.2
AWS Toolkit Version:  1.25.0

**debug**
2021-06-02 15:10:41 [INFO]: AWS Toolkit Version:  1.25.0
2021-06-02 15:36:46 [WARN]: Shared Credentials Profile first-role is not valid. It will not be used by the toolkit. Cycle detected within Shared Credentials Profiles. Reference chain: first-role -> first-role

**Comment by justinmk3** [comment]
Does it work with `aws` CLI?

> [WARN]: Shared Credentials Profile first-role is not valid. It will not be used by the toolkit. Cycle detected within Shared Credentials Profiles. Reference chain: first-role -> first-role

Doesn't this explain the issue? 



For reference, it could be useful to try the artifact from https://github.com/aws/aws-toolkit-vscode/pull/1766 :

1. Download and extract [buildArtifacts.zip](https://github.com/aws/aws-toolkit-vscode/files/6540621/buildArtifacts.zip)
2. From the VSCode command list (ctrl-shift-p or cmd-shift-p) run Extensions: Install from VSIX... to install the *.vsix file.
3. Reload VSCode and verify that the Toolkit has version 1.26 (not the release version 1.25).

**Comment by JadenSimon** [comment]
Just to be clear, the profiles in both credentials and config files are combined. That is, the `source_profile` should never refer to itself. The `profile` prefix in config files does not mean the profile is different from the credentials profile. In this example, the `[profile second-role]` and `[second-role]` parameters are being combined into one and thus self-referencing (assuming `myrole` is actually `second-role`).

Some more examples would be very helpful in figuring out this bug.

**Comment by share-me** [comment]
> 
> 
> Just to be clear, the profiles in both credentials and config files are combined. That is, the `source_profile` should never refer to itself. The `profile` prefix in config files does not mean the profile is different from the credentials profile. In this example, the `[profile second-role]` and `[second-role]` parameters are being combined into one and thus self-referencing (assuming `myrole` is actually `second-role`).
> 
> Some more context would be very helpful in figuring out this bug.

You were right, i was misusing this parameter..
