### ISSUE TITLE
Step Functions Quick Update reset "Enable X-Ray tracing"

### ISSUE THREAD

**Issue by FelixEnescu** [aws/aws-toolkit-vscode#1787]
**Describe the bug**

When using "Quick Update" to update a state machine the "Enable X-Ray tracing" flag is reset. 

**To Reproduce**

1. Go to AWs console and create a state machine "HelloXRay", the content does not matter, just use a template
2. Enable X-Ray by setting "Enable X-Ray tracing"
3. Go to VS Code ->  AWS -> Step Functions and download definition for "HelloXRay"
4. Make any change and save
5. Update definition using the "Quick Update" function
6. Go back to AWS console and check  "Enable X-Ray tracing", it is now not set.

**Expected behavior**

"Quick Update"  should preserve the "Enable X-Ray tracing" flag value

**Desktop (please complete the following information):**

OS:  Linux x64 5.4.72-microsoft-standard-WSL2
Visual Studio Code Extension Host Version:  1.56.2
AWS Toolkit Version:  1.25.0

**Comment by alanbo** [comment]
@FelixEnescu , thank you for reporting the issue. Confirming that I can reproduce it.

**Comment by alanbo** [comment]
This was an issue with actual UpdateStateMachine API and not VS Code. It's resolved now and we can close the ticket.

**Comment by bryceitoc9** [comment]
Thanks @alanbo !
