### ISSUE TITLE
Create build script

### ISSUE THREAD

**Issue by steveataws** [aws/aws-toolkit-vscode#18]
For development we can use the npm watch tasks defined in the workspace. However for release to the marketplace we need a build script/make file that can produce a digitally signed .vsix extension file that we can upload. 

Note digitally signing isn't (so far as we know right now) a requirement for the marketplace, but we should do it anyway for customer assurance - same as we do for the VSTS tools.

The build script needs to run headless so we can have it running 24x7 in CodeBuild, triggered from commits.

**Comment by mpiroc** [comment]
Related: #118

**Comment by awschristou** [comment]
Building the code is covered in #114 and #39 . A new issue will be created for a broader Release pipeline.
