### ISSUE TITLE
How to override default parameter value using SAM deploy?

### ISSUE THREAD

**Issue by sfanous** [aws/aws-toolkit-vscode#1812]
OS:  Windows_NT x64 10.0.17763
Visual Studio Code Extension Host Version:  1.57.0
AWS Toolkit Version:  1.25.0

I created a Lambda SAM Application using AWS Toolkit for VSCode. Coded my small application and tested it locally and all seems to be good.

My template.yaml includes 1 parameter with a default value. When I attempt to deploy the application using AWS Toolkit it asks me whether I want to override the default parameter. All is good if I decide to not override. If I choose override then `.aws\template.json` is created with just an empty JSON object.

I've tried to hack my way through this file but there's very little info about it on Google, so wondering how to get this functionality working please.

To temporarily workaround this issue, I packaged my application and generated a CloudFormation template and am using the CloudFormation Console when I want to override the default parameter.

**Comment by bryceitoc9** [comment]
Hi @sfanous 

I believe the syntax should be:
```
{
   "templates": {
        "./relative/path/to/template.yaml": {
            "parameterOverrides": {
                "param1": "value1",
                "param2": "value2",
                ...
            }
        }
    }
}
```
See https://github.com/aws/aws-toolkit-vscode/blob/b840baf6a9f510bb206201570fd45904e47a0100/src/lambda/config/parameterUtils.ts#L59

**Comment by justinmk3** [comment]
Related: https://github.com/aws/aws-toolkit-vscode/issues/900  https://github.com/aws/aws-toolkit-vscode/issues/1052

**Comment by sfanous** [comment]
> Hi @sfanous
> 
> I believe the syntax should be:
> 
> ```
> {
>    "templates": {
>         "./relative/path/to/template.yaml": {
>             "parameterOverrides": {
>                 "param1": "value1",
>                 "param2": "value2",
>                 ...
>             }
>         }
>     }
> }
> ```
> 
> See
> 
> https://github.com/aws/aws-toolkit-vscode/blob/b840baf6a9f510bb206201570fd45904e47a0100/src/lambda/config/parameterUtils.ts#L59

Thank you. Got it working with 1 minor modification. I first tried the relative path to template.yaml using "../template.yaml" but that didn't work. I then tried "template.yaml" instead and it worked.
