### ISSUE TITLE
Lambda: Download error on v1.26 

### ISSUE THREAD

**Issue by massiws** [aws/aws-toolkit-vscode#1857]
**Download Lambda don't work in version 1.26**

Trying to download a Lambda function from AWS the toolkit report an error: 

_Error downloading Lambda function arn:aws:lambda:<my-region>:<my-ID>:function:<my-function-name>: undefined_

**To Reproduce**

1. Upgrade AWS Toolkit to version 1.26.0
2. Select _AWS_ in the Activity bar
3. Right click on a deployed AWS Lambda
4. Select _Download_
5. Select destination folder 
6. Confirm data overriding warning
7. See the error notification

**Screenshots**
![err](https://user-images.githubusercontent.com/6533289/124091429-1fc55200-da56-11eb-99da-cbdf0370be23.png)

**Desktop:**

- OS:  Linux x64 5.4.0-77-generic 
- Visual Studio Code Extension Host Version:  1.57.1
- AWS Toolkit Version:  1.26.0

**Additional context**

Same installation in Windows 10 get same results.
Downgrading AWS Toolkit to version 1.25.0 make the problem disappear.

**Comment by bryceitoc9** [comment]
Hi @massiws , are there any specific errors mentioned in the `AWS Toolkit Logs` output channel?

**Comment by JadenSimon** [comment]
Hey @massiws ,

It would be helpful if you could try out this VSIX which should fix your issue:
1. Download and extract [buildArtifacts.zip](https://github.com/aws/aws-toolkit-vscode/files/6749949/buildArtifacts.zip)
2. From the VSCode command list (ctrl-shift-p or cmd-shift-p) run Extensions: Install from VSIX... to install the *.vsix file.
3. Reload VSCode and verify that the Toolkit has version 1.27 (not the release version 1.26).

**Comment by ejmvar** [comment]
Found same issue on 1.26
Installed 1.27 from VSIX.
Now, it's working.
Thanks a lot!!

**Comment by massiws** [comment]
> Hi @massiws , are there any specific errors mentioned in the `AWS Toolkit Logs` output channel?

No usefull info:
```
2021-07-02 14:19:49 [VERBOSE]: Loading Lambda Function .zip file
2021-07-02 14:19:55 [VERBOSE]: Finished loading Lambda Function .zip file
2021-07-02 14:20:06 [ERROR]: There is a file in the way: C:\Users\USER\AppData\Local\Temp\aws-toolkit-vscode\vsctkOvTpZT\function.zip
2021-07-02 14:20:06 [DEBUG]: telemetry: passive=0 lambda_import
```

Anyway, installing v1.27 from VSIX or official v1.27 fix the problem.

Thank you.
