### ISSUE TITLE
Connecting with AWS SSO Credentials

### ISSUE THREAD

**Issue by dsw-2** [aws/aws-toolkit-vscode#1868]
**Desktop (please complete the following information):**

- OS:  Windows_NT x64 10.0.18363
-   VS Code version: 1.58.0
-   AWS Toolkit extension version: 1.58.0AWS Toolkit Version:  1.27.0

**Question**

I'm trying to get the AWS extension setup using the AWS SSO Credentials option.  I have my credentials file created.  When try to connect, I get prompted to select the desired profile.  I select the profile and see the following error:  "Failed to load SSO credentials. Try logging in again."

My default browser is google chrome.  I thought the sso option would launch the default browser and start the sso login process.  Any suggestions on how to debug the problem?

**Comment by justinmk3** [comment]
Can you show the profile example from your ~/.aws (with private info removed).

Also may be helpful to see the logs: 

1. Set the Toolkit log level to "verbose": in VSCode settings search for "aws log level", then select "verbose".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View AWS Toolkit Logs` command to get the logs.

**Comment by justinmk3** [comment]
If you are still having this issue, try the `aws configure sso` command to get started, this will add a SSO profile to your ~/.aws . See https://github.com/aws/aws-toolkit-vscode/issues/531#issuecomment-896163603 for full steps.
