### ISSUE TITLE
CDK Visualizer does not read output path from cdk.json

### ISSUE THREAD

**Issue by Avinm** [aws/aws-toolkit-vscode#1875]
**Describe the bug**

CDK Visualizer searches for a cdk.out directory in the workspace and fails to load the construct tree if the directory is not found. It should read the output location from cdk.json instead of searching in just the "./cdk.out" directory

**To Reproduce**
1. Edit cdk.json to have `"output": "build/cdk.out"`
2. Open the CDK visualizer

**Expected behavior**:  Visualizer visualizes the construct tree

**Actual behavior**:  Visualizer fails with `Unable to load construct tree for this App. Run "cdk synth"`

**Comment by JadenSimon** [comment]
Hey @Avinm,

Looks like we don't parse the contents of `cdk.json` at all, and just assume that the output will always be in `cdk.out` in the same directory as the configuration file. Thank you for bringing attention to this issue, and let us know if there's anything else you find.
