### ISSUE TITLE
Partition based credentials validation

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#188]
It should be possible for users to tell if their credentials are not valid for a partition (standard, gov cloud, China), or of they are not valid at all.

Objectives:
* The Toolkit does not try to use credentials that fall into one of these categories, to prevent giving users confusing error messages ...
  * contain a typo in the access id / secret
  * use a stale access key
  * do not refer to a valid account

Accounts exist in only one partition, so no more than one partition will validate correctly. Credentials that do not validate in any partition are considered to be a problem with the user's credentials.

If credentials are valid in a partition, that partition's regions should display normally, and regions belonging to other partitions (if shown in the AWS Explorer) should inform the user that their profile is not valid in that partition.

If credentials are not valid in any partition, regions should indicate that their credentials are bad.

Example: a user has Oregon and Beijing in their AWS Explorer. They connect in the Toolkit with a profile related to an account in the China partition. They can see their Beijing resources, and the Oregon node indicates that this account is not valid in the Standard partition.

Additional Considerations:
* MFA needs to use the appropriate partition
* validation should happen on "first credential creation", and whenever changing profiles
* Any non-aws partition regions that have been disabled need to be re-enabled when support for other partitions is available

**Comment by awschristou** [comment]
Moving the toolkit to be single-region only (#549) will simplify portions of this story

**Comment by iceflow** [comment]
+1 for the China region support feature request.  Do we have roadmap for this now? 

Thanks.

**Comment by awschristou** [comment]
v1.7.0 of the toolkit is now available. This version includes support for China and GovCloud based regions.

You'll need to a `region` field to your shared credentials profile, and set it to one of the regions that you are working in (for example `cn-northwest-1` for a China partition region).

We don't have the user docs updated yet, some information can be found at https://github.com/aws/aws-toolkit-vscode/blob/master/docs/connecting-to-aws.md#working-with-regions-in-other-partitions
