### ISSUE TITLE
Add Serverless App tree sub-container

### ISSUE THREAD

**Issue by steveataws** [aws/aws-toolkit-vscode#19]
The current provider populates only a Lambda functions sub-container. If we are to support serverless apps too we'll want them to be contained in their own container.

The container will enumerate the currently bound workspace regions, but we need to determine how to identify a serverless app stack vs a 'regular' CloudFormation stack. For this issue it's sufficient to add the sub container and the bound regions; each region can show a 'no deployed applications' placeholder.

**Comment by acguglielmo** [comment]
Hello @steveataws,

I'm interested in working on this issue.

In _**AWS Toolkits for PyCharm**_ they have the following [tree schema](https://d2908q01vomqb2.cloudfront.net/da4b9237bacccdf19c0760cab7aec4a8359010b0/2018/11/27/pycharm-explorer-2.png). Do you think this schema will work well as the sub-containers inside the region containers? Or is it better to have the region containers inside the Lambda/CloudFormation containers?

**Comment by awschristou** [comment]
CloudFormation stacks will be added to the Explorer, showing only Lambda Function resources to start with.

This issue has been replaced with #165
