### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by sliedig** [aws/aws-toolkit-vscode#1930]
**Desktop (please complete the following information):**

N/A

**Question**
Would it be possible for you to include information about the changes in each release https://github.com/aws/aws-toolkit-vscode/releases? Would be nice to see what new features have been added and what issues have been resolved. 

Thanks.

**Comment by justinmk3** [comment]
Are you looking for something other than https://github.com/aws/aws-toolkit-vscode/blob/master/CHANGELOG.md ?

This is also listed in vscode:

![image](https://user-images.githubusercontent.com/55561878/128799974-597322ce-fe16-49a1-a053-2cf1ce4d24cd.png)

**Comment by sliedig** [comment]
LOL! Oops, my bad. 

Sorry, I just expected it in the release notes. This is fine.

**Comment by justinmk3** [comment]
Ah you mean directly on https://github.com/aws/aws-toolkit-vscode/releases . We will consider this.
