### ISSUE TITLE
AWS Toolkit created weird folder in user /home

### ISSUE THREAD

**Issue by jkemp814** [aws/aws-toolkit-vscode#1942]
**Describe the bug**

Extension is not placing folders under .config

**To Reproduce**

**Expected behavior**

Folders should be placed under .config

**Screenshots**

**Desktop (please complete the following information):**

-   OS: MX Linux (Debian 10 based)
-   Visual Studio Code Version: 1.59.0
-   AWS Toolkit Version: 1.28.0

**Additional context**

Hello, When connecting to the AWS services through the extension, I noticed a folder name 'file:' with many subdirectories in my home folder. 

Shouldn't this be under .config folder? It does find the .aws folder for my config and credentials. 

This is the structure that is being created. file:/home/ ' user name'/ .config/Code/User/globalStorage/ amazonwebservices.aws-toolkit-vscode/ (two JSON files)

I already have a Code folder under .config. So why is the extension not able to find it. Is the extension written for Windows? Seems to know the structure and where the Code folder is?

Please, I have uninstalled the extension until it's fixed

**Comment by jkemp814** [comment]
Turns out everywhere I have opened a .JSON file, there is this folder 'file:' Over nineteen of them even under my .mozilla and .THunderbird folders. VS Code opens these files. I hope they release your fix quick.

**Comment by jkemp814** [comment]
Installed the development version 1.29 and it seems to be normalized. Good job. How soon will the release version be available? Will it overwrite the development version once release?

**Comment by justinmk3** [comment]
> How soon will the release version be available? 

Planned for this week.

> Will it overwrite the development version once release?

vscode should auto-update it.

**Comment by justinmk3** [comment]
Fixed in AWS Toolkit 1.29
