### ISSUE TITLE
Unable to deploy Python SAM App with dependencies using AWS Toolkit when system python doesn't match runtime version

### ISSUE THREAD

**Issue by malbertus** [aws/aws-toolkit-vscode#1945]
**Describe the bug**

When using the AWS Toolkit to deploy a Python SAM app that requires external dependencies, the application appears to deploy successfully in CloudFormation (despite an unsuccessful build), however an internal server error occurs because the dependencies are not packaged and uploaded. 

In my case the system python version is 3.9.6 while the Lambda runtime version is 3.8

**To Reproduce**

1. Create Lambda SAM Application using the latest python runtime (3.8) and using the Hello World template
2. In `hello_world/app.py` import a random library (I picked scrapy, i.e. `import scrapy`)
3. Add library to requirements.txt
4. Deploy SAM Application using AWS Toolkit extension
5. Test application using API gateway endpoint URL output 
6. Internal server error

From VSCode output of 'Deploy SAM Application'
```
2021-08-13 11:00:32 [INFO]: Starting SAM Application deployment...
2021-08-13 11:00:32 [INFO]: Building SAM Application...
2021-08-13 11:00:32 [INFO]: Running command: (not started) [/usr/local/bin/sam build --build-dir /tmp/aws-toolkit-vscode/samDeployGCKm9F/build --template /Users/my-user/Documents/Code/hello-world/template.yaml]
2021-08-13 11:00:33 [INFO]: Building codeuri: /Users/my-user/Documents/Code/hello-world/hello_world runtime: python3.8 metadata: {} functions: ['HelloWorldFunction']

2021-08-13 11:00:34 [INFO]: 
Build Failed

2021-08-13 11:00:34 [INFO]: Error: PythonPipBuilder:Validation - Binary validation failed for python, searched for python in following locations  : ['/Users/my-user/.pyenv/shims/python3.8', '/Users/my-user/.pyenv/shims/python', '/usr/bin/python'] which did not satisfy constraints for runtime: python3.8. Do you have python for runtime: python3.8 on your PATH?

2021-08-13 11:00:34 [WARN]: "sam build" failed: /Users/my-user/Documents/Code/hello-world/template.yaml
2021-08-13 11:00:34 [INFO]: Packaging SAM Application to S3 Bucket: my-bucket-name
<snip>
Successfully created/updated stack - helloworld-v1 in $my-region
```

From CloudWatch logs:
`[ERROR] Runtime.ImportModuleError: Unable to import module 'app': No module named 'scrapy'`

**Expected behavior**

Application code and dependencies to be uploaded correctly so that no import errors are experienced.

**Screenshots**

![image](https://user-images.githubusercontent.com/28349399/129288768-faafa0df-deec-4f7b-820e-7a74e224fe33.png)

**Desktop (please complete the following information):**

OS:  Darwin x64 20.6.0 (macOS Big Sur 11.5.1)
Visual Studio Code Extension Host Version:  1.59.0
AWS Toolkit Version:  1.28.0

**Additional context**

The build process activated using 'Deploy SAM Application' doesn't seem to have any options to `--use-container` which was used successfully for direct invocation during local application debugging (using VSCode workspace launch configuration). As the AWS Toolkit also seems to use a random, temporary directory when deploying, it also ignores any build options defined in the application `.aws-sam` directory using `build.toml`. 

```
build.toml
[default]
[default.build]
[default.build.parameters]
use_container = "true"
```

During troubleshooting this issue, I also created a pyenv virtual environment using 3.8 to match the lambda runtime, however it looks like the shell used for 'Deploy SAM Application' doesn't pickup `.python-version` or look at the python interpreter configured in VSCode.

Workarounds:
Bypass VSCode/AWS Toolkit extension by using sam-cli from terminal window. Manually run `sam build --use-container` and `sam deploy`
OR
1. Install pyenv + pyenv-virtualenv
2. Use pyenv to install python version that matches runtime
3. Create and activate virtualenv using runtime version of python
4. From terminal with virtual environment activated, open VSCode with `code .` (assuming added to PATH)
5. Use Deploy SAM Application from VSCode/AWS Toolkit

**Comment by justinmk3** [comment]
Key issue:

> The build process activated using 'Deploy SAM Application' doesn't seem to have any options to `--use-container` which was used successfully for direct invocation during local application debugging

**Comment by malbertus** [comment]
No longer broken after recents changes to SAM/CDK
