### ISSUE TITLE
Unable to load json schema for AWS SAM template.yaml files

### ISSUE THREAD

**Issue by jordan-sf** [aws/aws-toolkit-vscode#1947]
**Describe the bug**

AWS SAM template.yaml files aren't being checked/intellisense'd.

Related error message:

> Problems loading reference 'Unable to load schema from '/Users/me/Library/Application Support/Code/User/globalStorage/amazonwebservices.aws-toolkit-vscode/sam.schema.json': .YAML(768)

Also, my global settings.json file's "yaml.schemas" property looks like this:
```
    "yaml.schemas": {
        "file:///Users/me/.vscode/extensions/atlassian.atlascode-2.9.1/resources/schemas/pipelines-schema.json": "bitbucket-pipelines.yml",
        "file:/Users/me/Library/Application Support/Code/User/globalStorage/amazonwebservices.aws-toolkit-vscode/sam.schema.json": [
            "template.yml"
        ]
    },
```

The referenced `sam.schema.json` is not on my system.

For comparison, note the aws toolkit's entry isn't using the proper file:// protocol but atlassian's is, and I confirmed that Atlassian's schema file is on my system.

**To Reproduce**

1. Install AWS toolkit v1.28.0
2. Create/open a SAM project
3. Open the template.yml file
4. The first un-commented line (AWSTemplateFormatVersion: 2010-09-09) has wavy underline under the first character and the popup for that error is the error message above.

**Expected behavior**

Step 4 above would not show that error, and intellisense would work on the file.

**Screenshots**

**Desktop (please complete the following information):**

-   OS:  Darwin x64 20.4.0
-   Visual Studio Code Version: 1.59.0
-   AWS Toolkit Version: 1.28.0

**Additional context**

After uninstalling and reinstalling and closing Code, I still get see the issue. Also, this is the content of the `/Users/me/Library/Application Support/Code/User/globalStorage/amazonwebservices.aws-toolkit-vscode/logs/aws_toolkit_20210813T142726.log` file:

```
2021-08-13 14:27:26 [ERROR]: log level: info
2021-08-13 14:27:26 [INFO]: Retrieving AWS endpoint data
2021-08-13 14:27:26 [INFO]: OS:  Darwin x64 20.4.0
2021-08-13 14:27:26 [INFO]: Visual Studio Code Extension Host Version:  1.59.0AWS Toolkit Version:  1.28.0
2021-08-13 14:27:26 [INFO]: telemetry cache not found: '/Users/me/Library/Application Support/Code/User/globalStorage/amazonwebservices.aws-toolkit-vscode/telemetryCache'
2021-08-13 14:27:26 [ERROR]: Could not get details from manifest:
```

**Comment by justinmk3** [comment]
Thanks for reporting. This should be fixed in the development (unreleased) version, can you try the steps given at https://github.com/aws/aws-toolkit-vscode/issues/1932#issuecomment-896973022 ?

**Comment by jordan-sf** [comment]
Thanks @justinmk3. Yes, that .vsix file in #1932 fixed my issue.

Thank very much!
