### ISSUE TITLE
Credentials File Not Detected

### ISSUE THREAD

**Issue by sbmsr** [aws/aws-toolkit-vscode#1951]
**Describe the bug**
When attempting to connect to AWS, I get the following message: 

![image](https://user-images.githubusercontent.com/2349518/129451217-764c75e2-45d8-406a-9e9f-38d327389e23.png)

After clicking "Yes", my aws config files open up (ACCESS_KEY_ID and SECRET_ACCESS_KEY redacted):

![image](https://user-images.githubusercontent.com/2349518/129451275-07a0d4dc-3515-4685-9f76-093b09ad6b0e.png)

From my understanding my credentials files are configured properly. To confirm this, I am able to run `aws s3 ls` from my cli and see my buckets in s3.

**To Reproduce**

1. Have credentials files present and working before extension init.
2. From the extension, try to `Connect to AWS`.
3. See `You do not appear to have any AWS Credentials defined. Would you like to set one up now?` popup.
4. Click yes.
5. See your credentials file configured as you expected.

**Expected behavior**

On `Connect to AWS` I expected my configuration to be detected, and a connection to be established.

**Desktop (please complete the following information):**

OS:  Darwin x64 20.5.0
Visual Studio Code Extension 
Host Version:  1.59.0AWS Toolkit 
Version:  1.28.0

**Comment by justinmk3** [comment]
> To confirm this, I am able to run `aws s3 ls` from my cli and see my buckets in s3.

`aws` CLI is more forgiving than the AWS SDKs.  Try the lowercase forms of `aws_access_key_id` and `aws_secret_access_key`

**Comment by sbmsr** [comment]
That did the trick @justinmk3 ! Had no idea the cli was more forgiving. Thanks so much!
