### ISSUE TITLE
How to turn off 'AWS: Add Debug Configuration ...'?

### ISSUE THREAD

**Issue by stuartmcmahon-h3d** [aws/aws-toolkit-vscode#1973]
**Desktop (please complete the following information):**

-   OS: Windows 10
-   VS Code version: 1.59.0
-   AWS Toolkit extension version: 1.29.0

How do I turn off the text/buttons that appear above all my export functions. Text below - also see screenshot:

```AWS: Add Debug Configuration | AWS: Edit Debug Configuration (Beta)```

![image](https://user-images.githubusercontent.com/80367066/130159150-ce37e501-bfba-4293-a078-c4e381dc4489.png)

**Comment by justinmk3** [comment]
1. Go to the vscode command palette (ctrl-shift-p)
3. Run the `AWS: Toggle SAM hints` command. There is also a setting in VSCode user settings page.

**Comment by stuartmcmahon-h3d** [comment]
That works, thankyou!
