### ISSUE TITLE
sam.schema.json:  Missing RequestModels, RequestParameters for serverless function API Event

### ISSUE THREAD

**Issue by Alenius** [aws/aws-toolkit-vscode#1986]
According to the [documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html) about the AWS::Serverless::Function.ApiEvent there should be 6 properties but in the toolkit there are 2 missing, RequestModels and RequestParameters. This causes me to get red squiggly underline with the title `Property RequestModel is not allowed`.

It would be nice to have these two properties (RequestModels and RequestParameters) added to the `sam.schema.json` so this doesn't happen anymore.

**Comment by jpinkney-aws** [comment]
We've updated the schema in the goformation package and you should no longer see any errors for RequestModels and RequestParameters.

_Note_: You might need to refresh VSCode to pick up the new schema!
