### ISSUE TITLE
how to link my standard amazon account to aws account?

### ISSUE THREAD

**Issue by Fundzofmental** [aws/aws-toolkit-vscode#1991]
**Desktop (please complete the following information):**

-   OS:
-   VS Code version:
-   AWS Toolkit extension version:

**Question**

**Comment by Fundzofmental** [comment]
Im curious to know if i can also link 2 accounts together to my aws cloud application?

**Comment by justinmk3** [comment]
Thanks for your question. This issue tracker is for the AWS Toolkit software. Questions about general AWS and IAM usage are better directed to [AWS support](https://aws.amazon.com/contact-us/). 

I'll do my best to answer your questions:

> how to link my standard amazon account to aws account?

https://aws.amazon.com/premiumsupport/knowledge-center/merge-aws-accounts

> It's not possible to merge multiple AWS accounts together.
>
> However, you can use AWS Organizations to manage multiple AWS accounts, and then combine the billing in one consolidated bill.

> Im curious to know if i can also link 2 accounts together to my aws cloud application?

There are some possibilities described the IAM docs: https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html
