### ISSUE TITLE
Advice - use Toolkit to manage all Lambda containers from the same project.

### ISSUE THREAD

**Issue by RaistlinD2x-Dev** [aws/aws-toolkit-vscode#2008]
**Desktop (please complete the following information):**

![versions](https://user-images.githubusercontent.com/83308842/132268878-fdb58511-2667-40a9-8971-04d16e7781f1.PNG)

-   AWS Toolkit extension version: $LATEST (I just got it a couple of days ago and don't know how to check)

**Question**

I'm trying to figure out an optimal method for handling my entire backend from the same repo. I've successfully utilized AWS Toolkit, API deployed and Lambda usable from my Angular app. I'm looking for advice on best practice and use of Toolkit.

I know how to expand a SAM Template file to create multiple resources but because of the UI prompts for S3, ECR, etc I don't see how to use the tool to handle the process automatically for multiple Lambda container builds. Is there a way to expand on the SAM template to include everything required for build and use a master template file to execute the build and deploy process for all functions or is best practice to simple create a separate repo for each Lambda? This seems suboptimal.

Sorry, I haven't found a lot of examples or anything to work off of or it's just my incompetence. Thanks in advance.

**Comment by justinmk3** [comment]
> API deployed and Lambda usable from my Angular app. I'm looking for advice on best practice and use of Toolkit.
> 
> I know how to expand a SAM Template file to create multiple resources but because of the UI prompts for S3, ECR, etc I don't see how to use the tool to handle the process automatically for multiple Lambda container builds.

Just to confirm, you're using `AWS: Deploy SAM Application` command to deploy? 

Can you expand on "multiple Lambda container builds"? A SAM template.yaml can define multiple Lambda functions, but I sense that you are looking for something else.

You may also find [AWS CDK](https://aws.amazon.com/cdk/) useful. I would consider it "best practice". But the AWS Toolkit currently has limited support for it.
