### ISSUE TITLE
As a user I'm able to pass custom env vars into a local lambda run/debug

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#201]
Acceptance criteria:
* user is able to pass in custom environment variables when Running/Debugging a Lambda handler locally 

Related to #149 , which allows user to pass in custom event data.

**Comment by mpiroc** [comment]
1. Add an `environmentVariables` property to [`HandlerConfig`](https://github.com/aws/aws-toolkit-vscode/blob/develop/src/lambda/local/configureLocalLambda.ts):

```typescript
export interface HandlerConfig {
    event: {},
    environmentVariables: {
        [ name: string ]: string
    }
}
```

Then update [`buildHandlerConfig`](https://github.com/aws/aws-toolkit-vscode/blob/develop/src/lambda/local/configureLocalLambda.ts#L109) to return:

```typescript
{
    event: {},
    environmentVariables: {}
}
```

While you're there, also fix [`getLocalLambdaConfiguration`](). Replace this:

```
const emptyHandlerConfig: HandlerConfig = {
    event: {}
}
```

With this: `const emptyHandlerConfig = buildHandlerConfig()`

2. Update [`SamCliLocalInvokeInvocation`](https://github.com/aws/aws-toolkit-vscode/blob/develop/src/shared/sam/cli/samCliLocalInvoke.ts#L15) to accept `environmentVariablesPath` as a new constructor parameter. It should be passed to `sam local invoke` with the `--env-vars` flag.

3. Update [`LocalLambdaRunner.invokeLambdaFunction`](https://github.com/aws/aws-toolkit-vscode/blob/develop/src/shared/codelens/typescriptCodeLensProvider.ts#L347) to read environment variables from `.aws/handlers.json` and save them to a new file. The path to this file should be passed to `SamCliLocalInvokeInvocation`.

If the `environmentVariables` property on a handler config is either missing or empty, either omit `environmentVariablesPath` parameter entirely, or use a file containing just `{}`.

**Comment by bryceitoc9** [comment]
SAM Local expects a file with `{FunctionName: {key:value}}` JSON pairs. Do we have the function name readily accessible to the LocalLambdaRunner aside from `this.localInvokeArgs.handlerName`? I can pull the name from there to build the function, but it seems kinda janky to strip the `app.` from before the function name.

**Comment by awschristou** [comment]
LocalLambdaRunner creates a dummy template file in `generateInputTemplate`, which already sets up the resource entry. The pure function name is in `relativeFunctionHandler`, but I am not sure you need that.

**Comment by bryceitoc9** [comment]
Right now, our dummy `template.yaml` file created for individual runs does not add environment variables:
```
Resources:
  awsToolkitSamLocalResource:
    Properties:
      CodeUri: awsToolkitSamLocalResource
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
```
This needs to be populated in order to overwrite the values with the JSON file. I propose we take values from both the main `template.yaml` and the `handlers.json` file so we have a notion of both defaults and overrides.

**Comment by mpiroc** [comment]
@bryceitoc9 That sounds reasonable to me. Note that `template.yaml` does not necessary exist, so make sure you consider that case.

**Comment by mpiroc** [comment]
@bryceitoc9 Re function name, you can use the key from `handlers.json`:

```typescript
{
    handlers: {
        myFunctionName: {
            event: {},
            environmentVariables: { ... }
        }
    }
}
```

**Comment by bryceitoc9** [comment]
PR: https://github.com/aws/aws-toolkit-vscode/pull/230

**Comment by bryceitoc9** [comment]
PR merged.
