### ISSUE TITLE
Users are able to debug locally using F5 and the Debug Panel

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#203]
Debug configuration does not reliably populate, and cannot be automatically updated with newer lambda handlers. It should be possible for users to indicate which handlers they'd like to see added into the debug configuration.

Acceptance criteria:
* Users are able to start debugging a lambda function locally using F5 and/or the Debug Panel
* Users are able to add function handler(s) into their debug configuration, even after launch.json is initially populated, without typing it in manually.

**Comment by mpiroc** [comment]
This issue is superceded by #263.

**Comment by justinmk3** [comment]
1.12 supports SAM local Lambda debugging by VSCode launch configs.
