### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by shivamchawla98** [aws/aws-toolkit-vscode#2047]
- Issue Type: `Performance`
- Extension Name: `aws-toolkit-vscode`
- Extension Version: `1.29.0`
- OS Version: `Windows_NT x64 10.0.22458`
- VS Code version: `1.60.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\shiva\AppData\Local\Temp\amazonwebservices.aws-toolkit-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by JadenSimon** [comment]
Hey @shivamchawla98 

Apologies for the extension causing issues! Looks like VS Code saved a performance log:
> ⚠️ Make sure to attach this file from your home-directory:
⚠️c:\Users\shiva\AppData\Local\Temp\amazonwebservices.aws-toolkit-vscode-unresponsive.cpuprofile.txt

Can you upload that file to this issue? We'll need it to figure out what was causing the extension to lock-up. If you could provide any additional context (e.g. what parts of the toolkit you were using, if any, prior to the crash) that would be much appreciated as well.
