### ISSUE TITLE
How to stop automatically adding many yaml paths into settings.json

### ISSUE THREAD

**Issue by goldeneggg** [aws/aws-toolkit-vscode#2112]
**Desktop (please complete the following information):**

-   OS: macOS Catalina 10.15.7
-   VS Code version: 1.60.2
-   AWS Toolkit extension version: v1.29.0

**Question**

When I enable your extension with the [YAML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) extension, I found the behavior as follows.

1. Automatically Add the `"file:///Users/USERNAME/Library/Application%20Support/Code/User/globalStorage/amazonwebservices.aws-toolkit-vscode/cloudformation.schema.json"` section and `""file:///Users/USERNAME/Library/Application%20Support/Code/User/globalStorage/amazonwebservices.aws-toolkit-vscode/sam.schema.json"` section nested in `"yaml.schemas"` section into my settings.json
2. And many yaml file pathes of my workspace are automatically added into the section above.

My workspace includes the aws/serverless-application-model repository. So many yaml file pathes of this repository are automatically added.
Example as follows. 

```json
  "yaml.schemas": {
    "file:///Users/USERNAME/Library/Application%20Support/Code/User/globalStorage/amazonwebservices.aws-toolkit-vscode/cloudformation.schema.json": [
      "aws/serverless-application-model/integration/resources/templates/combination/function_with_all_event_types_condition_false.yaml",
      "aws/serverless-application-model/integration/resources/templates/combination/api_with_request_parameters_openapi.yaml",
      "aws/serverless-application-model/integration/resources/templates/combination/function_with_custom_code_deploy.yaml",
      "aws/serverless-application-model/integration/resources/templates/combination/api_with_request_models_openapi.yaml",
      "aws/serverless-application-model/integration/resources/templates/combination/function_with_msk_using_managed_policy.yaml",

     // :
     // : (other many file pathes)
     // :
    ]
  }
```

**My Expectation**

I want to stop this behavior with some settings.
Some of the reasons as follows.

1. I want to stop that my settings.json is to be bigger
2. I want to stop that my settings.json including my local file pathes is uploaded to gist.github.com because I use the Settings Sync extension.

If possible, I want to set path patterns with wildcard.

```json
  "yaml.schemas": {
    "file:///Users/USERNAME/Library/Application%20Support/Code/User/globalStorage/amazonwebservices.aws-toolkit-vscode/cloudformation.schema.json": [
      "template.y*l",
      "packaged.y*l"
    ],
    "file:///Users/USERNAME/Library/Application%20Support/Code/User/globalStorage/amazonwebservices.aws-toolkit-vscode/sam.schema.json": [
      "template.y*l",
      "packaged.y*l"
    ],
```

Or/And I want to set schema filename only (__except local direcory__)

```json
  "yaml.schemas": {
    "cloudformation.schema.json": [
      "template.y*l",
      "packaged.y*l"
    ],
    "sam.schema.json": [
      "template.y*l",
      "packaged.y*l"
    ],
```

Thank you!

**Comment by justinmk3** [comment]
Thanks for your feedback! In Toolkit 1.30 (unreleased), we have changed the logic to avoid this.

**Comment by justinmk3** [comment]
AWS Toolkit 1.30 should no longer add paths to your settings.json when visiting template.yaml files.
