### ISSUE TITLE
Add support for temporary credentials

### ISSUE THREAD

**Issue by micholas** [aws/aws-toolkit-vscode#215]
**Is your feature request related to a problem? Please describe.**
Good security practices include using temporary credentials rather than long lived ones. Temporary credentials require a `AWS_SESSION_TOKEN` and are not supported by our plugin... thus our plugin enforces bad practices 

**Describe the solution you'd like**
Add support for `AWS_SESSION_TOKEN`

**Describe alternatives you've considered**
It may be better to not have a credentials editor than to have one that forces the least secure option.

**Comment by mpiroc** [comment]
Session tokens *are* supported by credential profiles. Outside of testing, I exclusively use the toolkit with temporary credentials.

We should still support environment variable-based authentication. Closing as a duplicate of #164.
