### ISSUE TITLE
Unable to create credentials file - 'aws.credential.profile.create' failed

### ISSUE THREAD

**Issue by roskill** [aws/aws-toolkit-vscode#2181]
![image](https://user-images.githubusercontent.com/12045053/137646449-8e2e3c10-1fad-4617-b23f-d3096dddcadf.png)

**Describe the bug**
Attempting to create an AWS credentials profile in VS Code after downloading and installing the extension results in the above dialog.

**To Reproduce**
1. Install extension
2. Open command palette (Shift+Command+P)
3. Search for AWS and choose AWS: Create Credentials Profile.

**Expected behaviour**
Able to access credentials configuration screen.

**System**
Mac OS Big Sur 11.6
Visual Studio Code 1.61.0
AWS Toolkit 1.31.0

**Comment by roskill** [comment]
@justinmk3 That's just where I keep credentials on this machine. 

I can configure credentials in AWS Toolkit for GoLand without running into these errors so there must be something that that VS Code does differently.

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/2335

**Comment by justinmk3** [comment]
#2335 implements a potential fix for this issue. @roskill if you want to try it we'd love your feedback: 

1. Download and extract [buildArtifacts.zip](https://github.com/aws/aws-toolkit-vscode/files/7620608/buildArtifacts.zip)
2. In VSCode, run `Extensions: Install from VSIX` to install the `*.vsix` file. (You can run commands with `ctrl-shift-p` or `cmd-shift-p`) 
3. Reload VSCode and verify that the Toolkit has the new version (not the older version).

**Comment by justinmk3** [comment]
AWS Toolkit 1.35 includes a potential fix for this, please let us know if there is still an issue after updating.
