### ISSUE TITLE
Unable to create credentials file - 'aws.credential.profile.create' failed 

### ISSUE THREAD

**Issue by VINAYREDDY26** [aws/aws-toolkit-vscode#2225]
We have written the needed data into your clipboard because it was too large to send. Please paste
<img width="1133" alt="Screen Shot 2021-10-21 at 10 37 07 PM" src="https://user-images.githubusercontent.com/69935037/138527530-344ab9c9-95c9-4190-b30f-8f394f41b390.png">
<img width="1488" alt="Screen Shot 2021-10-22 at 2 57 00 PM" src="https://user-images.githubusercontent.com/69935037/138527533-00804217-7111-429a-935a-5714b4d0a6bd.png">

.

**Comment by VINAYREDDY26** [comment]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/69935037/138786086-77b94b55-5add-49c2-9172-86c61a6a211f.png">
I have tried the Preferences: Open Settings (JSON) to open the JSON and observed  JSON extension error, also tried running after installing c++ .json and JSON extension.

**Comment by justinmk3** [comment]
AWS Toolkit 1.35 includes a potential fix for this, please let us know if there is still an issue after updating.
