### ISSUE TITLE
As a user, I am prompted for confirmation before `.aws/handlers.json` is overwritten

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#224]
If symbols are not available for `handlers.json` (for example, because the user has disabled the built-in JSON document symbol provider, or because the provider took too long to initialize, the 'configure' codelens will override `handlers.json`. As an additional safety measure, we should prompt the user for confirmation before overwriting the file.

**Comment by bryceitoc9** [comment]
From @awschristou : 

In configureLocalLambda.ts, change the loadSymbols method default for maxAttempts from 3 to 1

* Start up VS Code without having the handlers.json file open. If it is open, close it and restart VS Code.
* activate our extension
* go to your sam application's app.js file, click on the configure codelens
* edit handlers.json, then close the file
* Press Ctrl+R to simulate reloading VS Code
* Click on the configure codelens. File will be overwritten

**Comment by bryceitoc9** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/265
