### ISSUE TITLE
Unable to show all the S3 buckets

### ISSUE THREAD

**Issue by jingzhaoou** [aws/aws-toolkit-vscode#2246]
**Desktop (please complete the following information):**

OS:  Darwin x64 20.6.0
Visual Studio Code Extension Host Version:  1.61.2
AWS Toolkit Version:  1.32.0

**Question**

I have about 100+ AWS S3 buckets under my account. AWS Toolkit does not show all the buckets due to some unknown reasons. Is there a limit on the number of S3 buckets that AWS Toolkit can handle? Thanks.

**Comment by justinmk3** [comment]
You can check the Toolkit logs:

1. In VSCode settings, ensure that "aws log level" is "debug".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View Toolkit Logs` command to get the logs.
4. Remove any potential private info from the logs, before posting them here.

At "debug" log-level Toolkit will say the region for each bucket.  If you see a bucket for a given region and it's not listed in the expected region, please let us know.

**Comment by AMenzel** [comment]
Hi @justinmk3  , I do have a bucket in eu-west-1 and the LookupRegion() debug statement actually shows EU not eu-west-1 I guess this is the problem? Other regions and buckets work.

**Comment by justinmk3** [comment]
@AMenzel can you share the log(s) (after removing private info)?
