### ISSUE TITLE
Command 'aws.login' not found on Mac OS X 10.14.2

### ISSUE THREAD

**Issue by mikegil** [aws/aws-toolkit-vscode#234]
Followed build script...had issues getting to build correctly but deleting everything from the cloned directory and trying again resulted in build without errors.  VSIX install seemed to "work" and AWS commands are in the palette but none actually work.  Command 'aws.login' not found.

**To Reproduce**
cloned and built per script.  installed AWS CLI and configured.  Ran "code .".  Selected AWS Login from command palette.  Received error

**Expected behavior**
package run without errors

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.2
 - Visual Studio Code Version: 1.31.0
 - AWS Toolkit for Visual Studio Code Version: 0.0.1

**Additional context**

{ 'aws-toolkit-vscode': '0.0.1',
  npm: '6.7.0',
  ares: '1.15.0',
  cldr: '34.0',
  http_parser: '2.8.0',
  icu: '63.1',
  llhttp: '1.0.1',
  modules: '67',
  napi: '3',
  nghttp2: '1.34.0',
  node: '11.6.0',
  openssl: '1.1.0j',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.24.1',
  v8: '7.0.276.38-node.13',
  zlib: '1.2.11' }

**Comment by mikegil** [comment]
deleted cloned directory entirely and re-cloned.  Now builds but still doesn't work...visx installs and commands are available in vs.code but connect to AWS results in "command 'aws.login' not found"

**Comment by micholas** [comment]
I just started experiencing the same problem this morning. Which version of `vsce` are you running?

**Comment by mikegil** [comment]
I get the following message when I build the package:

The latest version of vsce is 1.55.0 and you have 1.51.1.
Update it now: npm install -g vsce


No matter how many times I run npm install -g vsce (which seems to succeed), re-running the build give the same message.  The actual version I get when I run vsce at the command line is 1.55.0

**Comment by micholas** [comment]
A new version of VS Code was just released that appears to have an issue with `aws-toolkit-vscode`. Please use the November version for now: https://code.visualstudio.com/updates/v1_30

**Comment by awschristou** [comment]
@mikegil please try updating to the latest in the `develop` branch, and let us know if you're able to start up the extension.

**Comment by mikegil** [comment]
Yes, it appears to.  Thanks!
