### ISSUE TITLE
Lambda Invoke hard to find if running on small screen

### ISSUE THREAD

**Issue by brianwthomas** [aws/aws-toolkit-vscode#235]
![vscode](https://user-images.githubusercontent.com/4368102/52380022-018fcf00-2a21-11e9-8fa0-bf40782ee34b.png)
**Describe the bug**

Not sure I'd call it a bug, but more of an improvement.  If you minimize VS code to a smaller window, when trying to invoke a lambda function, the 'invoke' button is hidden and hard to find.
**To Reproduce**

Invoke button to be more clearly visible (perhaps next to the template selection
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 
 - Visual Studio Code Version: 1.30.1
 - AWS Toolkit for Visual Studio Code Version: 0.0.1?

**Additional context**

**Comment by justinmk3** [comment]
Resolved by https://github.com/aws/aws-toolkit-vscode/pull/2691
