### ISSUE TITLE
"AWS: Connect to AWS" does not appear as an option for the AWS Toolkit

### ISSUE THREAD

**Issue by Eliasjamal** [aws/aws-toolkit-vscode#2351]
**Bug description**
"AWS: Connect to AWS" does not appear as an option for the AWS Toolkit

**To Reproduce**
AWS Toolkit to be installed
1. Open VS Code.
2. To open the Command Palette, on the menu bar, choose View, Command Palette. Or use the following shortcut keys:
3. Windows and Linux – Press Ctrl+Shift+P.
4. macOS – Press Shift+Command+P.
5. Search for AWS and choose AWS: Connect to AWS.

**Issue**
"AWS: Connect to AWS" does not appear as an option

**Expected behavior**
"AWS: Connect to AWS" to appear as an option

**Screenshots**

<img width="708" alt="image" src="https://user-images.githubusercontent.com/39851728/144381470-25398cbb-a92b-4fdb-83dd-08e9567e958a.png">

**Desktop:**

-   OS: Mac
-   Visual Studio Code Version: 1.62.3
-   AWS Toolkit Version: v1.34.0

**Additional context**

**Comment by JadenSimon** [comment]
The command was renamed to 'Choose AWS Profile...' in https://github.com/aws/aws-toolkit-vscode/pull/2012
We will need to update all references to the old name.

**Comment by Eliasjamal** [comment]
Thank you
