### ISSUE TITLE
telemetry: caller can query in-memory metrics

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#2364]
Problem:

telemetry/metrics are a useful source of "events" , but our code can't query them. This could be useful in tests, logs, asserts, etc.

Proposal:

1. Add a simple query interface to the telemetry provider. In production, this queries whatever hasn't been flushed/sent yet.
2. In tests (FakeTelemetryX), all metrics are kept in-memory (never flushed), and tests can query them.

**Comment by JadenSimon** [comment]
#2366 solves this with the exception that no metrics are stored in production.
