### ISSUE TITLE
wizard: support `keepScrollPosition` for quick picks

### ISSUE THREAD

**Issue by JadenSimon** [aws/aws-toolkit-vscode#2379]
VS Code 1.63 added support for [a flag](https://code.visualstudio.com/updates/v1_63#_quick-pick-api-improvements) (`keepScrollPosition`) to not auto-scroll to the top when adding/removing items. This is a _big_ UX improvement for quick picks that load items on-the-fly. Async `QuickPickPrompters` should have the `keepScrollPosition` flag enabled by default.

**Comment by justinmk3** [comment]
Implemented in AWS Toolkit 1.96
