### ISSUE TITLE
Bash with AWS CLI : Unable to locate credentials

### ISSUE THREAD

**Issue by PrasadPatharkar** [aws/aws-toolkit-vscode#2384]
**Describe the bug**
I am running an automated test cases through VS Code using Webdriverio. The credentials for logging into application are stored at s3 and shell file is supposed to fetch the data. I have done AWS Configuration for storing the s3 credentials. The details are also shown in 'credentials' and 'config' file but when the shell file is ran, it gives error 'download failed <s3 bucket path> - Unable to locate credentials'

**To Reproduce**
1. Configure AWS S3 with 'aws configure'
2. Provide details of Access Key, Password, Region etc.
3. Run the Shell file
4. Data from S3 should be fetched

**Expected behavior**

Data from S3 should be fetched

**Screenshots**
![image](https://user-images.githubusercontent.com/35989031/147050906-1f61ff32-9398-4ffd-8710-b26be93d98ae.png)

**Desktop (please complete the following information):**
OS:  Windows_NT x64 10.0.17763
Visual Studio Code Extension Host Version:  1.63.2
AWS Toolkit Version:  1.34.0

**Additional context**
Shell File ->

```
#!/bin/bash
#
# Run WebdriveIO test runner.
#
# Usage:
# run-tests.sh runner/wdio.conf.local.js - Run all browser tests locally
# run-tests.sh runner/wdio.conf.local.js smoketest - Run "smoketest" test locally
# run-tests.sh runner/wdio.conf.browserstack.js - Run all browser tests on browserstack service
# run-tests.sh runner/wdio.conf.browserstack.js smoketest - Run "smoketest" test on browserstack service

set -o errexit
set -o pipefail

echo 'Fetching secrets and setting environment variables...'
export TEST_DATA_S3_PREFIX="${TEST_DATA_S3_PREFIX:-s3://test-data-monetate-dev/}"
export BROWSERSTACK_AUTOMATE_USER=${BROWSERSTACK_AUTOMATE_USER:-'monetate1'}
export BROWSERSTACK_AUTOMATE_ACCESS_KEY=$(aws s3 cp ${TEST_DATA_S3_PREFIX}browserstack/${BROWSERSTACK_AUTOMATE_USER}/access-key.txt -) || ''

# UAT
 export IO_HOSTNAME=${IO_HOSTNAME:-'uat-api-public.monetate.org'}

# PRODUCTION
#export IO_HOSTNAME=${IO_HOSTNAME:-'api.monetate.net'}

export WEBUI_HOSTNAME=${WEBUI_HOSTNAME:-'uat.monetate.org'}
#fetches the username and password from amazon s3

 export WEBUI_USERNAME=$(aws s3 cp ${TEST_DATA_S3_PREFIX}uat/user.txt -) || ''
 export WEBUI_PASSWORD=$(aws s3 cp ${TEST_DATA_S3_PREFIX}uat/password.txt -) || ''
 export TESTRAIL_USERNAME=$(aws s3 cp ${TEST_DATA_S3_PREFIX}uat/testrailUserid.txt -) || ''
 export TESTRAIL_PASSWORD=$(aws s3 cp ${TEST_DATA_S3_PREFIX}uat/testrailPassword.txt -) || ''
 export TESTRAIL_PROJECTID='62'

# Below channel details are used for mybigcommerce
 export CHANNEL_ID='a-3e41bf76'
 export CHANNEL_DOMAIN='monetate.mybigcommerce.com'
 export CHANNEL_TYPE='p'
 export CHANNEL_DOMAIN_UK='monetate.mybigcommerce.uk'

# Below channel details are used for adidas
# export CHANNEL_ID='a-24f48522'
# export CHANNEL_DOMAIN='adidas.glass'
# export CHANNEL_TYPE='d'


echo 'Fetching data from s3...'

#fetches data folder from amazon s3
aws s3 sync ${TEST_DATA_S3_PREFIX}browser-test-data/data

echo 'Calling WebdriverIO test runner...'

CONFIG=$1
TEST_FILE_NAME=$2

if [[ -n $TEST_FILE_NAME ]]; then
    SPEC_FLAG=--spec
    SPEC_PATH=test/**/$TEST_FILE_NAME.js
fi

wdio $CONFIG $SPEC_FLAG $SPEC_PATH

**Comment by justinmk3** [comment]
> but when the shell file is ran, it gives error 'download failed - Unable to locate credentials'

That error [comes from AWS CLI](https://aws.amazon.com/premiumsupport/knowledge-center/s3-locate-credentials-error/) , but this issue tracker is for AWS Toolkit (an extension for VSCode).

But I'll try to help. It looks like your script is failing at the `aws s3 sync` step. To troubleshoot why it doesn't find your credentials, reduce the steps to the minimum needed to replicate the issue. 

- Try only this command: `bash -c 'aws s3 ls'`
- if that works, try putting only `aws s3 ls` in your script. 
- if that works, try adding more of your script until it fails.
- and so on...
