### ISSUE TITLE
credentials: Toolkit profiles are case-insensitive

### ISSUE THREAD

**Issue by Leigh-M** [aws/aws-toolkit-vscode#2394]
-   OS: Linux x64 5.13.1-051301-generic   (Ubuntu 21.10)
-   VS Code version: 1.62.3
-   AWS Toolkit extension version: 1.34.0

My AWS credentials and config files appear to be set up correctly, I can assume roles and list buckets in other accounts by passing named profiles to AWS CLI like: `aws s3api list-buckets --profile some-assumed-role`, yet AWS Toolkit errors with:
   Shared Credentials Profile leigh.m is not valid. It will not be used by the toolkit.
   login: failed to connect with "profile:some-assumed-role: Profile leigh.m is not a valid Credential Profile: Profile leigh.m is not supported by the Toolkit

There is a source profile in an AWS account that only allows assuming of roles in other accounts where I can perform more actions, so my credentials file looks like:

```
[leigh.m] # let's say account number 1000 for simplicity
AWS_ACCESS_KEY_ID = my_access_key_id
AWS_SECRET_ACCESS_KEY = my_secret_Access_key
```

My config file looks like:

```
[profile leigh.m]
mfa_serial = arn:aws:iam::1000:mfa/leigh.m
region = eu-west-1
output = json

[profile some-assumed-role]
role_arn = arn:aws:iam::2000:role/SomeAssumedRole
source_profile = leigh.m
role_session_name = some-session-name
mfa_serial = arn:aws:iam::1000:mfa/leigh.m
duration_seconds = 3600
region = eu-west-1
output = json
```

I have also tried to not use the config file (as it appears to suggest here: https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/mfa-credentials.html ) still the same issue

Why does AWS Toolkit say my leigh.m profile is not correct, as it works perfectly well for all AWS cli commands - just not VSCode AWS Toolkit extension?

**Comment by JadenSimon** [comment]
Hi @Leigh-M ,

Thanks for reporting this issue! This is definitely a toolkit bug; we are not normalizing the credentials files prior to validation. A simple solution until we can release a fix is to make all field names lowercase:
```
[leigh.m] # let's say account number 1000 for simplicity
aws_access_key_id = my_access_key_id
aws_secret_access_key = my_secret_Access_key
```

**Comment by Leigh-M** [comment]
Thanks @JadenSimon I can confirm the suggested workaround to change the access_key_id and secret_access_key to lowercase does resolve the issue (I am sure many people will have capitals for those as I do from various AWS docs so your fix once released will hopefully resolve many credentials issues!) thanks for investigating and resolving

**Comment by justinmk3** [comment]
Toolkit 1.35 includes a fix for this issue. Thank you for reporting it!
