### ISSUE TITLE
Investigate how we can identify serverless app stacks

### ISSUE THREAD

**Issue by steveataws** [aws/aws-toolkit-vscode#24]
One option may be to inspect the template and/or stack resources looking for the presence of the pseudo serverless resource type. Or perhaps serverless stacks have some form of tag attached that we can use. When we can identify apps, we can make suitable queries to populate the sub nodes in the container.

One other option if we cannot auto-identify would be to give the user command gestures to add stacks to their resource tree for a region (and remove them). This approach would also require multi-select in the resource picker.

**Comment by awschristou** [comment]
CloudFormation stacks will be added to the Explorer, showing only Lambda Function resources to start with.

This issue has been replaced with #165
