### ISSUE TITLE
Manage extesnion menu entry does nothing

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-vscode#243]
**Describe the bug**
The Manage Extension menu does nothing

**To Reproduce**
1. Right click on status bar area for AWS
2. Click Manage Extension
3. Nothing happens

**Comment by awschristou** [comment]
It is a VS Code facility. Any status bar entry added by an extension has this right click menu item. When you have an extension installed, it takes you to the extension details page. When you run the code directly from the repo, there is no extension installed, and it no-ops.

You can verify this by running `npm run install-plugin` from the command line, then opening VS Code, opening the AWS Explorer, then following your repro steps above. It should show you the repo's readme.md page.
