### ISSUE TITLE
When `source_profile` is set in shared credentials or config, toolkit shows No AWS credentials found

### ISSUE THREAD

**Issue by andrewclam1991** [aws/aws-toolkit-vscode#2437]
in `~/.aws/credentials`

```
[default]
aws_access_key_id=***
aws_secret_access_key=***
role_arn=arn:aws:iam::***
mfa_serial=arn:aws:iam::***
source_profile=default
```

and in `~/.aws/config`
```
[default]
region=us-west-2
output=json
```

I have a role with mfa enabled, it needs to set an additional field `source_profile` in the shared credentials or config file. Without this the AWS CLI commands fails with error `Partial credentials found in assume-role, missing: source_profile or credential_source`

But when I set the additional field `source_profile`, it then breaks the toolkit and it shows a pop-up message"No AWS credentials found" in vscode.

I'm using extension version: 1.35.0

**Comment by justinmk3** [comment]
Can you provide the logs (check that private info is removed)? 

1. In VSCode settings, ensure that "aws log level" is "verbose".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View Toolkit Logs` command to get the logs.
