### ISSUE TITLE
Commands are not descriptive

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-vscode#244]
**Describe the bug**
Several commands are too short and not descriptive enough.

ie. AWS: Invoke - Invoke what? Locally ? Remote ?
AWS: Get Policy - What policy?

**Comment by awschristou** [comment]
The command is registered to a context menu, and isn't intended to be exposed through the command palette. The commands are labelled appropriately for context menus, but not command palette.
 The fix is now in the `develop` branch, removing the command from the command palette.
