### ISSUE TITLE
No 'Connect to AWS' option in command palette

### ISSUE THREAD

**Issue by mkcomer237** [aws/aws-toolkit-vscode#2474]
**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04.3
-   VS Code version: 1.64.2
-   AWS Toolkit extension version: 1.35.0

**Question**

 I'm unable to connect to AWS in vscode because I don't see the connect option in the command palette.  See the screenshot below, there is no AWS: Connect to AWS available there.  

![image](https://user-images.githubusercontent.com/4369337/154340880-a57766da-0f91-4ab2-bde4-eff7c947c512.png)

**Comment by JadenSimon** [comment]
Hey @mkcomer237 

The command was renamed to `AWS: Choose AWS Profile...` in https://github.com/aws/aws-toolkit-vscode/pull/2012
I believe documentation is outdated; updates to documentation is being tracked here: https://github.com/aws/aws-toolkit-vscode/issues/1829

**Comment by justinmk3** [comment]
AWS Toolkit restored the `Connect to AWS` command (which is just an alias to the `Choose AWS Profile` command).
