### ISSUE TITLE
Validate SAM command gives no indication it is successful

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-vscode#248]
**To Reproduce**
1. Run `AWS: Validate SAM CLI version`
2. No indication it did anything

**Expected behavior**
Give a notification if valid

**Comment by awschristou** [comment]
@abrooksv if your SAM CLI version was valid, you should see a status bar notification. The notification disappears after about three seconds.

Does the notification appear for you?

![image](https://user-images.githubusercontent.com/39839589/52580182-aa04b100-2ddc-11e9-9b4a-d6f19607d97c.png)

**Comment by abrooksv** [comment]
Why would I look there instead of getting a notification?

**Comment by awschristou** [comment]
This command has been removed. Closing
