### ISSUE TITLE
SAM init 3rd step is confusing

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-vscode#249]
**Describe the bug**
Unsure what entering in the text box does

**To Reproduce**
1. Invoke create new SAM app
2. Select a runtime
3. No idea what step this does, there is no description or indication what to do
4. Typing and pressing enter does nothing

**Expected behavior**

**Screenshots**
<img width="688" alt="screen shot 2019-02-07 at 3 40 08 pm" src="https://user-images.githubusercontent.com/8992246/52450151-b04e1100-2aee-11e9-9841-037bdc29c8f6.png">
<img width="643" alt="screen shot 2019-02-07 at 3 39 58 pm" src="https://user-images.githubusercontent.com/8992246/52450152-b04e1100-2aee-11e9-8ca6-aae35edd2d4a.png">

**Comment by awschristou** [comment]
We will track this in #258 - closing.
