### ISSUE TITLE
Errors in SAM template.yaml for "S3WritePolicy"

### ISSUE THREAD

**Issue by dangeReis** [aws/aws-toolkit-vscode#2502]
**Describe the bug**
Seems like we are missing some supported properties.  

**To Reproduce**
Add a S3WritePolicy under the lambda Function.  

**Expected behavior**
No error shown

**Screenshots**
![image](https://user-images.githubusercontent.com/48328513/156781314-c6f0aaeb-b3ae-4d0f-85c2-5d250794b99b.png)

This is the error I'm getting
Property S3WritePolicy is not allowed.yaml-schema: aws:/home/russ/.vscode-server/data/User/globalStorage/amazonwebservices.aws-toolkit-vscode/sam.schema.json

**Desktop (please complete the following information):**

-   OS: Windows 11 WSL Ubuntu
-   Visual Studio Code Version: 1.65.0
-   AWS Toolkit Version: v1.36.0

**Additional context**

**Comment by JadenSimon** [comment]
Related https://github.com/aws/aws-toolkit-vscode/issues/2250
I believe this will need to be updated https://github.com/awslabs/goformation/blob/master/generate/sam-2016-10-31.json#L1351

**Comment by jpinkney-aws** [comment]
We've updated the schema in the goformation package and you should no longer see any errors with S3WritePolicy 🎉.

_Note:_ You might need to refresh VSCode to pick up the new schema
