### ISSUE TITLE
Stack Filter in Explorer

### ISSUE THREAD

**Issue by gkoreman** [aws/aws-toolkit-vscode#2510]
**Is your feature request related to a problem? Please describe.**

I have a lot of lambdas and other resources in my account and it can be difficult to find the items I want in the Explorer. 

**Describe the solution you'd like**

I would like to filter all of the resources in the Explorer based on a stack. I would like to select a stack from a dropdown (or just a text input field) and the Explorer would only show resources associated with that stack.

**Describe alternatives you've considered**

-none-

**Additional context**

-none-

**Comment by gkoreman** [comment]
Directly after opening this issue I found the CloudFormation->Stack list, which shows exactly what I want! Closing this ticket.

**Comment by justinmk3** [comment]
See also https://github.com/aws/aws-toolkit-vscode/issues/1877 for further plans to add various filtering capabilities.
