### ISSUE TITLE
SAM/typescript: can we leverage SAM CLI typescript support ?

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#2511]
In Feb 2022 SAM CLI released "native" support (based on esbuild) for TypeScript: 

- https://aws.amazon.com/blogs/compute/building-typescript-projects-with-aws-sam-cli/
- https://github.com/aws/aws-lambda-builders/pull/340

> Previously, to use TypeScript with AWS SAM CLI, you needed custom steps. These transform the TypeScript project into a JavaScript project before running the build.
>
> Today, you can use the sam build command to transpile code from TypeScript to JavaScript. This bundles local dependencies and symlinks, and minifies files to reduce asset size.
>
> AWS SAM uses the popular open source bundler [esbuild](https://esbuild.github.io/) to perform these tasks. **This does not perform type checking but you may use the [tsc CLI](https://www.typescriptlang.org/docs/handbook/compiler-options.html) to perform this task.**

Currently, AWS Toolkit already finds and uses `tsc` to compile typescript before calling SAM CLI to invoke/debug a typescript Lambda function.

## Todo

1. determine if SAM CLI's native typescript support lets us
    - remove/simplify logic related to typescript SAM applications
    - improve the experience (e.g. more reliable behavior by delegating to `sam`)

**Comment by JadenSimon** [comment]
Somewhat related: https://github.com/aws/aws-toolkit-jetbrains/issues/3069
We currently use a "custom" `tsconfig` that completely ignores the user's configuration for "code" run/debugs. This can easily lead to unexpected behavior.

**Comment by justinmk3** [comment]
Conclusion: this doesn't appear to gain a net reduction in code or complexity because:

1. to use the sam cli esbuild feature we would need to add a `Metadata` property to the generated template
2. we would need to find or install `esbuild` in the user's project or environment (which is equivalent to the current situation with `tsc`)
