### ISSUE TITLE
SSO: user can get credentials from connected accounts + roles

### ISSUE THREAD

**Issue by rancid-racer** [aws/aws-toolkit-vscode#2556]
**Is your feature request related to a problem? Please describe.**

The current SSO Integration feature leverages an existing configured profile load and does not actually implement credential fetching from the platform.  

**Describe the solution you'd like**

When operating as an administrator across multiple accounts, I would like to leverage usage of the SSO Auth Token to perform the list accounts action and list roles for account action as well as region selection for setting active credentials.  This would enable access to many accounts without having to create potentially hundreds of profiles to list through.

**Describe alternatives you've considered**

I have developed python libraries already that interact with these APIs to be able to code across many accounts quickly however changing authentication via aws configure sso is a long and burdensome process because the CLI menu is not as friendly as a UI  is.

**Additional context**

**Comment by justinmk3** [comment]
Thanks for the request, this would be a nice feature.

> I have developed python libraries already that interact with these APIs to be able to code across many accounts quickly however changing authentication via aws configure sso is a long and burdensome process because the CLI menu

For reference, which APIs did you use? Or can you point to an existing tool/script (or AWS CLI command, or AWS console feature) that does what you want? A more concrete "spec" (for the UI, at least) will be very helpful.

**Comment by JadenSimon** [comment]
@rancid-racer 

Would something like this work? This is the flow with a region already set, but it's possible to omit it. My credentials file just has the start URL and region. The flow prompts you for whatever fields are missing. So I could use start URL + account, then it would ask for region + role.

![Kapture 2022-03-31 at 11 24 52](https://user-images.githubusercontent.com/31319484/161124424-398ba4ba-1261-4f20-9548-c4f32f09cce4.gif)

**Comment by justinmk3** [comment]
Implemented in https://github.com/aws/aws-toolkit-vscode/pull/3023
