### ISSUE TITLE
Feature Request: Support Add Debug Configuration Codelens for non-SAM based Lambda 

### ISSUE THREAD

**Issue by Po-Shin** [aws/aws-toolkit-vscode#2564]
As mentioned [here](https://github.com/aws/aws-toolkit-vscode/blob/98119caf6bb89aec06f14f8878e50e9d356d0f63/README.quickstart.cloud9.md). Codelens of `Add Debug Configuration` helps users to add debug configuration. But it seems to be supported only for SAM app and not for legacy Lambda. Checked in the VSCode as well, we noticed that it's not a regression.

**Steps to reproduce 1**
- Create a new environment, and turn off toolkit toggle.
- Create Node hello-world Lambda functions from the example in AWS Resource window.
- Wait for the deployment to be done.
- Turn on Toolkit toggle and go to `index.js` in the lambda folder.
- Codelens is not provided.

**Steps to reproduce 2**
- Create Lambdas from AWS Lambda, and wait for the deployment to be done.
- open `index.js / app.js` in the lambda folder.
- Codelens is not provided.

Users can download Lambda functions/app, and the debugConfiguration will be injected to `launch.json` automatically if there's no error. But users still can't edit the configuration through codelens since it's not shown to them. Only for users who know the existence of `AWS: SAM Debug Configuration Editor` can change the configurations.

Guess this is a missing/broken feature.

**Comment by justinmk3** [comment]
Could be fixed by changing  the `Download` feature to generate a `template.yaml`.

**Comment by gsweetwood** [comment]
Reproduced using method 2 in VS Code (create lambda in console, download from toolkit, open `index.js`)

Adding a `template.yaml` file to the folder has no effect. I believe this hinges on the presence of project files for each language (`requirements.txt`, `package.json`, `build.gradle`, and so on. In the code they're labeled `<language>_BASE_PATTERN`). Adding and removing these files from the folder causes the code lenses to show and disappear.
