### ISSUE TITLE
"Local resources": Users can create, deploy SAM projects from a dedicated view/panel

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#257]
The command palette offers an action to create new Serverless Application projects, but we can improve the UX here through a more visible call to action.

Acceptance Criteria:

* AWS Viewlet has a new “Serverless Application” panel (in addition to the existing “Explorer” panel)
* Panel has an “Add” command on its title bar, which connects to the existing command that creates sam applications
    * Title bar button uses a “plus” symbol.
* Panel lists all SAM/CFN template files discovered in the workspace.
    * "Deploy" action is available on these files

**Comment by justinmk3** [comment]
AWS Toolkit 3.31.0 now features a "Application Builder" panel which detects local SAM Lambda resources and provides actions for them:

<img width="377" alt="image" src="https://github.com/user-attachments/assets/c17468a7-aaff-487c-80ea-dea42ded91b6">
