### ISSUE TITLE
SAM local invoke: missing node_modules

### ISSUE THREAD

**Issue by JoshuaWalsh** [aws/aws-toolkit-vscode#2570]
**Desktop (please complete the following information):**

-   OS: Windows 10
-   VS Code version: 1.58.1
-   AWS Toolkit extension version: 1.37.0

**Question**

I'm trying to use AWS Toolkit to develop a Lambda API in TypeScript. My TypeScript goes in a `src` directory, and tsconfig.json is configured to output the resulting JavaScript to a `dist` directory. I wasn't able to get the build process in SAM working, so instead I've just added a TypeScript build task as the preLaunchTask in my aws-sam launch configurations.

But I suspect I might've run into the same issue even without TS.

In template.yaml, `CodeUri` is set to "dist/" and `Handler` is set to "app.lambdaHandler". This works to run the transpiled JavaScript code, but when invoking the API it fails during the first `import` statement with `Error: Cannot find module`.

Connecting to the container using `docker exec -it containerName /bin/bash` I can see that the node_modules directory has not been copied. The build log also says

> package.json file not found. Continuing the build without dependencies.

Looking online, this is due to my `CodeUri` not including node_modules. So I tried changing `CodeUri` to "./" and `Handler` to "dist/app.lambdaHandler", but after this change the build fails:

> Error: NodejsNpmBuilder:NpmPack - NPM Failed: npm ERR! Invalid package, must have name and version

Looking at aws/aws-sam-cli#125 and aws/aws-sam-cli#908, the advice is to remove `--template-file`. But AWS Toolkit is adding this, and `invokeTarget.templatePath` in the launch configuration appears to be mandatory.

How can I include node_modules in my build?

**Comment by justinmk3** [comment]
Thanks for the detailed report. But I think we need a sample template.yaml and nodejs project structure, that reproduces the issue.

You mention `invokeTarget` so I infer you're trying to "debug locally", not "deploy".

> Looking at [aws/aws-sam-cli#125](https://github.com/aws/aws-sam-cli/issues/125) and [aws/aws-sam-cli#908](https://github.com/aws/aws-sam-cli/issues/908), the advice is to remove `--template-file`.

Is that referring to `sam deploy --template-file` (and `sam package`), see also discussion in https://github.com/aws/aws-sam-cli/issues/125#issuecomment-450210998 

For local debugging, only `sam build` and `sam local invoke` are used.

> I wasn't able to get the build process in SAM working, so instead I've just added a TypeScript build task as the preLaunchTask in my aws-sam launch configurations

AWS Toolkit generally depends on `sam` to build the project and ship the dependencies to the container. If `sam build` fails then I suspect the dependencies will not get shipped to the container.

**Comment by JoshuaWalsh** [comment]
I have published a [reproducible example project](https://github.com/JoshuaWalsh/aws-sam-typescript-reprex).

I don't think `sam build` is failing, the AWS Toolkit output includes "[INFO]: Build complete."

**Comment by JoshuaWalsh** [comment]
I was able to resolve this by replacing

    CodeUri: dist/
    Handler: app.lambdaHandler

with

    CodeUri: ./
    Handler: dist/app.lambdaHandler

Initially when I tried this I got an error

> Error: NodejsNpmBuilder:NpmPack - NPM Failed: npm ERR! Invalid package, must have name and version

and it turns out that I should've read this error message, since my package.json file was indeed missing a version.
