### ISSUE TITLE
Seamlessly connect to RDS via Secret Manager from VSCode

### ISSUE THREAD

**Issue by dhartford** [aws/aws-toolkit-vscode#2582]
**Is your feature request related to a problem? Please describe.**

Problem: Connecting to an AWS RDS instance that is backed by AWS SecretManager credentials is manual process, and problematic when password rotation is enabled.

Reason: Jealous of the IntelliJ integration :-).  https://aws.amazon.com/blogs/developer/seamlessly-connect-to-rds-and-redshift-instances-with-the-aws-toolkit-for-jetbrains/ 

**Describe the solution you'd like**

A similar experience as IntelliJ for 'connect via secretmanager' to RDS from at least one SQL Explorer/editor tool.

**Describe alternatives you've considered**

various different VSCode extensions, none seem to support 'connect via SecretManager', unsure if this is related to no integration option, or if integration option exists if no (known) extension supports it.

**Additional context**

N/A

**Comment by justinmk3** [comment]
Thanks for the request! I've merged it into #1914 so that we can collect upvotes 👍  there.
