### ISSUE TITLE
ECS exec: support interactive (terminal) commands

### ISSUE THREAD

**Issue by pedrovanzella** [aws/aws-toolkit-vscode#2607]
**Is your feature request related to a problem? Please describe.**

ECS Execute-Command already uses the `--interactive` flag. However, the command execution goes to an Output (read-only) pane. We often want to interact with a REPL inside the container (such as the Rails console), so starting a terminal process would be best.

**Describe the solution you'd like**

When running a command on an ECS task, start a terminal process instead.

**Comment by ckonefke** [comment]
This feature is definitely needed.  I found myself very jealous when I saw my co-worker with pycharm/JetBrains already has this ability.  Single, non-interactive commands are very limited, and if you accidentally run a continuous command there's no way to stop it other than stopping the task.  You could run another command to find the pid, and another to kill the pid, but can't we just have a CTRL-C?

**Comment by justinmk3** [comment]
> if you accidentally run a continuous command there's no way to stop it other than stopping the task.

@ckonefke that's a good point, I created https://github.com/aws/aws-toolkit-vscode/issues/2818 to track this.

**Comment by justinmk3** [comment]
This feature was included in AWS Toolkit 1.51. 

## `Open Terminal` on ECS tasks

Use the `Open Terminal...` command on ECS tasks to start an interactive terminal connected to the task container.

<img width="237" alt="image" src="https://user-images.githubusercontent.com/55561878/194167386-83931388-69da-4f63-b7a7-90d296fb56a2.png">

## Configure ECS settings

Look for "ecs" in VSCode settings to change the default command (shell) that is run by the `Open Terminal...` command.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/55561878/194167674-a8eb57bc-b7eb-436e-8f29-a4f59b57264c.png">
