### ISSUE TITLE
AWS SAM Direct Invoke - Invalid JSON in payload file

### ISSUE THREAD

**Issue by mr-davidc** [aws/aws-toolkit-vscode#2613]
I am trying to invoke a Lambda function locally using the AWS SAM tools in VS Code.

I have this debug configuration in my `launch.json` file:
```
{
    "configurations": [
        {
            "type": "aws-sam",
            "request": "direct-invoke",
            "name": "SendEmail",
            "invokeTarget": {
                "target": "template",
                "templatePath": "${workspaceFolder}/LambdaExampleProject/sam-template.yml",
                "logicalId": "SendEmail"
            },
            "lambda": {
                "runtime": "dotnet5.0",
                "environmentVariables": {},
                "payload": {
                    "path": "${workspaceFolder}/LambdaExampleProject/sample-payloads/SendEmailSQSPayload.json"
                }
            }
        }
    ]
}
```

And this is the contents of the payload file `SendEmailSQSPayload.json`:

```
{
    "Records": [
        {
            "messageId": "059f36b4-87a3-44ab-83d2-661975830a7d",
            "receiptHandle": "AQEBwJnKyrHigUMZj6rYigCgxlaS3SLy0a...",
            "body": "Test message.",
            "attributes": {
                "ApproximateReceiveCount": "1",
                "SentTimestamp": "1545082649183",
                "SenderId": "AIDAIENQZJOLO23YVJ4VO",
                "ApproximateFirstReceiveTimestamp": "1545082649185"
            },
            "messageAttributes": {},
            "md5OfBody": "e4e68fb7bd0e697a0ae8f1bb342846b3",
            "eventSource": "aws:sqs",
            "eventSourceARN": "arn:aws:sqs:us-east-2:123456789012:my-queue",
            "awsRegion": "ap-southeast-2"
        }
    ]
}
```

It is indeed valid JSON in the payload file but VS Code still throws this error:

`Invalid JSON in payload file`

Am I doing something wrong here? It seems like something that should be super simple according to the documentation.

Thanks in advance for any advice

-   OS: Windows 10 x64
-   VS Code version: 1.66.2
-   AWS Toolkit extension version: 1.37.0

**Comment by JadenSimon** [comment]
Hey @mr-davidc 

The error message is misleading and is shown in when the file could not be read as well. This may be due to issues with how the extension handles `${workspaceFolder}` on Windows. Can you try using an absolute _Windows_ file path and see if it works?

**Comment by mr-davidc** [comment]
Hi @JadenSimon,

I tried an absolute Windows file path like so:
```
"path": "C:\\Workspace\\Lambda-Projects\\LambdaExampleProject\\sample-payloads\\SendEmailSQSPayload.json"
```

And it still gave me the same error unfortunately...

Interestingly though, if I deliberately change the file path to one that **doesn't** exist, I get a different (correct?) error down in the bottom right of VS Code window:

![image](https://user-images.githubusercontent.com/67831386/166632638-457df5df-87f2-4031-a09e-b2c7781fa981.png)

So it seems maybe it does find the file if using a correct path because I get a different error? 🤷‍♂️

**Comment by JadenSimon** [comment]
> So it seems maybe it does find the file if using a correct path because I get a different error? 🤷‍♂️

Yup I think so too. I also tried a few different `payload` paths on my Windows PC and they all worked correctly. So it may be something with your specific setup. This would be a lot easier to figure out if we didn't swallow the error but until a fix goes out we have to resort to trial-and-error. Things to try:
* Make sure VS Code is opened as administrator
* Check the encoding of the JSON file. Is it `UTF-8`?
* Check the first 3 bytes of the file with `Get-Content -Path PATH_HERE -Encoding byte -TotalCount 3` (PowerShell 5). If it shows `239 187 191` then there is a BOM. Try saving without the BOM by changing the encoding in VS Code to just normal `UTF-8`:
<img width="168" alt="Screen Shot 2022-05-04 at 8 19 44 AM" src="https://user-images.githubusercontent.com/31319484/166714486-3679fd1c-2c98-4cf9-88da-22a873bee126.png">

**Comment by mr-davidc** [comment]
Thanks so much @JadenSimon . That was exactly the problem. The JSON file had UTF-8 with BOM encoding! 

After saving the file as plain UTF-8, it now reads the file in fine and all works great. Both absolute files path and relative file paths work including the reference of `${workspaceFolder}` (as in my original post).

Thanks again.

**Comment by JadenSimon** [comment]
Glad to hear! We're looking into adding better detection for this as BOM problems are not too uncommon. And they're very frustrating to debug.
