### ISSUE TITLE
Users can locally run/debug a lambda function from an outline view

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#262]
Run/Debug CodeLenses are contextually relevant to the functions they decorate, but users may not be aware of these until they read documentation or otherwise discover them. The sidebar could maintain a list of the current file's functions, with calls to action for run/debug/configure operations. This could be more visible than codelenses.

Inspiration: the Explorer viewlet's Outline panel.

Acceptance Criteria:

* AWS Viewlet has a “Serverless Application” panel (in addition to the existing “Explorer” panel)
* Serverless Application panel lists the current file's functions that are possible Lambda Functions (the same ones that get CodeLens decorations)
* Each of these functions has calls to action for run, debug, configure

**Comment by justinmk3** [comment]
Since launch-config support was added in 1.12, maybe this isn't needed.

**Comment by justinmk3** [comment]
A special-purpose "outline view" which lists a subset of vscode's own builtin "outline view", is unlikely to see much use.

We have since added the `AWS: Add SAM Debug Configuration` command which can be used in any code file. 

The general concept of a "Local tools" panel is covered by #257.
