### ISSUE TITLE
Users can deploy SAM apps via context menu on template.yaml in the file explorer

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#263]
The command palette is the standard way to trigger operations like this, but associating the action with the template file provides an intuitive way to access the action.

Acceptance Criteria:

* Sam template files (in the Explorer) have a context menu item to deploy Serverless Application to AWS

It is not required, but worth considering: Could Sam template files (when open in the editor) have a context menu item to deploy Serverless Application to AWS? Would this feel appropriate?

**Comment by justinmk3** [comment]
Toolkit 1.26 includes https://github.com/aws/aws-toolkit-vscode/pull/1770 . Known limitation: only works with files named literally `template.yaml`, `template.yml` or `template.json`.
