### ISSUE TITLE
Users can deploy Serverless Applications by interacting with the Serverless Application pane to increase feature discoverability

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#264]
The command palette is the standard way to trigger operations like this, but associating the action with the SAM relevant Panel provides an intuitive way to access the action.

Acceptance Criteria:

* AWS Viewlet has a "Serverless Application" panel (in addition to the existing “Explorer” panel)
* Serverless Application panel lists the sam template files in workspace folder(s). (Use the existing logic of finding template.y[a]ml files for which files to list)
* The template files listed contain a call to action to deploy the template to AWS

**Comment by justinmk3** [comment]
merged w/ https://github.com/aws/aws-toolkit-vscode/issues/257
