### ISSUE TITLE
When will debugging for nodejs16.x will be supported?

### ISSUE THREAD

**Issue by ryancabanas** [aws/aws-toolkit-vscode#2665]
## System details (run the `AWS: About Toolkit` command)

-   OS: Windows 10
-   Visual Studio Code version: 1.67.2
-   AWS Toolkit version: 1.38.0

## Question

We're using a CloudFormation template for the first time with a `AWS::Serverless::Function` resource that has its runtime set to `nodejs16.x` and I soon discovered that the current AWS Toolkit for VS Code doesn't seem to support debugging.  Any word on when debugging `nodejs16.x` will be supported?

Thanks!

**Comment by justinmk3** [comment]
Thanks for your question! We're waiting on SAM CLI to release (ETA next week) with a fix that will allow us to add nodejs16 support.

**Comment by ryancabanas** [comment]
Thanks!

**Comment by justinmk3** [comment]
AWS Toolkit 1.39 includes support for nodejs16.x, if you have also updated `sam` cli.

**Comment by ryancabanas** [comment]
Great!  Thank you!
