### ISSUE TITLE
SAM/CFN schemas should be associated to YAML files regardless of the initial save status

### ISSUE THREAD

**Issue by jpinkney-aws** [aws/aws-toolkit-vscode#2678]
## Problem
Currently new yaml files that **_haven't been saved_** after adding:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
```
do not get the cfn/sam schema associated with them automatically. However, it gets associated when the yaml file is saved.

## Steps to reproduce the issue
Right now if you create a new yaml file in VSCode, open it up in the editor and paste:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
```
**without saving** and then try to autocomplete underneath `Transform` the yaml file won't be associated with any schema and auto completion will just show the basic default tags.

## Expected behavior
I would have expected SAM/CFN schemas to be registered regardless of whether or not that initial save happens

## System details (run the `AWS: About Toolkit` command)

-   OS: macOS Big Sur
-   Visual Studio Code version: 1.67.2
-   AWS Toolkit version: v1.39.0-SNAPSHOT

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/2893
