### ISSUE TITLE
 I can't see my buckets

### ISSUE THREAD

**Issue by donPain** [aws/aws-toolkit-vscode#2683]
## System details (run the `AWS: About Toolkit` command)

-   OS: Ubuntu 22.04
-   Visual Studio Code version:
-   AWS Toolkit version:

## Question

in my log i see all buckets but i get the following final response 2022-06-08 14:11:10 [DEBUG]: ListBuckets returned response: { buckets: [] }

**Comment by justinmk3** [comment]
> in my log i see all buckets

Which log? Are there any permissions issue or credentials-related log messages in the AWS Toolkit logs?  

1. In VSCode settings, ensure that "aws log level" is "debug".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View Toolkit Logs` command to get the logs.
4. Remove any potential private info from the logs, before posting them here.

**Comment by JadenSimon** [comment]
Hey @donPain 

Buckets are displayed per-region so it probably means that you have no buckets in whatever region is being shown. You can change which regions are visible via the command `AWS: Show or Hide Regions`.

**Comment by donPain** [comment]
I showed all regions and none had a bucket :(

**Comment by donPain** [comment]
in the aws cli they are there

**Comment by justinmk3** [comment]
Can you share which region they are in?

**Comment by justinmk3** [comment]
> 2022-06-08 17:38:46 [DEBUG]: LookupRegion called for bucketName: private info (thats my buckets)
> 2022-06-08 17:38:48 [DEBUG]: ListBuckets returned response: {[]}

The LookupRegion logs normally should be followed by logs like:

```
2022-06-08 16:15:04 [DEBUG]: LookupRegion returned region: us-west-2
2022-06-08 16:15:04 [DEBUG]: LookupRegion returned region: us-west-1
```

I wonder if there's a permissions issue or other failure that we aren't handling correctly.

**Comment by JadenSimon** [comment]
Using an IAM role without access to `s3:GetBucketLocation` would probably cause this behavior.

**Comment by justinmk3** [comment]
In https://github.com/aws/aws-toolkit-vscode/pull/2686 I've added some logging to help with this. Can you try it and see if it gives a clue about the failure?

1. Download and extract [aws-toolkit-vscode-1.40.0-aa22a74be769.vsix.zip](https://github.com/aws/aws-toolkit-vscode/files/8865702/aws-toolkit-vscode-1.40.0-aa22a74be769.vsix.zip)
2. In VSCode, run `Extensions: Install from VSIX` to install the `*.vsix` file. (You can run commands with `ctrl-shift-p` or `cmd-shift-p`) 
3. Reload VSCode and verify that the Toolkit has the new version (not the older version).

**Comment by donPain** [comment]
Thanks a lot guys, now I can see my buckets :)

**Comment by justinmk3** [comment]
@donPain that's great! Was lack of `s3:GetBucketLocation` the issue? That could explain it, since AWS CLI probably doesn't use that call.

**Comment by donPain** [comment]
yes, after adding the permission i was able to see
