### ISSUE TITLE
GH Codespaces equivalent

### ISSUE THREAD

**Issue by sholtomaud** [aws/aws-toolkit-vscode#2684]
It's time for aws-toolkit-vscode to offer a viable competitor to 
[vscode-gh-codepsaces](https://docs.github.com/en/codespaces/developing-in-codespaces/using-codespaces-in-visual-studio-code)

Can we have killer feature options whereby we use ssm-agent-like secure tunnelling into both EC2 and CodeBuild images/containers for our development environments from VSCode on my laptop

So many times I just want to run a quick test of my code or my CDK or my AWSTOE tests of my components and I cannot create an equivalent test environment on my local machine. 

I don't want to be running Cloud9 instances just to code because that's an expense that I don't need, which has been solved for by my local laptop. 

I want to write on my laptop, and I want to test my code in a temporary instance/container in the cloud to make sure that the thing will run/compile/work. 

GitHub Codespaces seems to be aiming at this but it's not quite hitting the mark for AWS resources. 

AWS ... it is time for you to put some weight behind the vscode toolkit to compile all the cli's (SAM,CLI,CDK etc) into the toolkit, and bundle the ssm-agent also so that you can solve for AWS Codespaces (not Cloud9) and provide secure SSO traffic to the AWS development environments. 

So many times the VSCode OpenSSH server thrashes the EC2 servers and makes them unusable due to a leaky bug. It's time for AWS to take things into their own hands and show the way to ssm-agent inspired Developer nirvana

end of rant.

**Comment by justinmk3** [comment]
related:

* https://github.com/aws/aws-toolkit-vscode/issues/941
* https://github.com/aws/aws-toolkit-vscode/issues/1627

> put some weight behind the vscode toolkit to compile all the cli's (SAM,CLI,CDK etc) into the toolkit, and bundle the ssm-agent

- AWS Toolkit auto-installs `session-manager-plugin` for cases where we have added remote capability. 
    - Currently we do this for "ECS exec": https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/ecs-exec.html
- We are working on auto-installing `sam` cli, and also considering if it makes sense to auto-install `aws` cli.

**Comment by justinmk3** [comment]
> It's time for aws-toolkit-vscode to offer a viable competitor to
> [vscode-gh-codepsaces](https://docs.github.com/en/codespaces/developing-in-codespaces/using-codespaces-in-visual-studio-code)

AWS Toolkit 1.57 now supports [connecting VSCode](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/codecatalyst-overview.html#codecatalyst-overview-open) to Amazon CodeCatalyst Dev Environments: https://codecatalyst.aws/explore 



> Can we have killer feature options whereby we use ssm-agent-like secure tunnelling into both EC2 and CodeBuild images/containers for our development environments from VSCode on my laptop

Connecting VSCode to EC2 is tracked in https://github.com/aws/aws-toolkit-vscode/issues/941


> compile all the cli's (SAM,CLI,CDK etc) into the toolkit

- https://github.com/aws/aws-toolkit-vscode/issues/3027
- https://github.com/aws/aws-toolkit-vscode/issues/3028

Closing this issue since (I hope) https://codecatalyst.aws/explore addresses the main request here.

**Comment by sholtomaud** [comment]
Thanks for the response! :) 
There has been some great developments. Well done.
AWSTOE is a tool se need to use to test ImageBuilder components and we typically want to run it on an EC2 equivalent to the OS that we want the components to run within. 
To do this we want to get a session to a private subnet and we want to use an EC2 that has the AWSTOE installed.
How can we use the AMIs we build from ImageBuilder for CodeCatalyst + VSCode AWS toolkit for this use case?

**Comment by justinmk3** [comment]
> How can we use the AMIs we build from ImageBuilder for CodeCatalyst + VSCode AWS toolkit for this use case?

CodeCatalyst doesn't have an answer for that. CodeCatalyst Dev Environments are just containers defined in a ([customizable](https://docs.aws.amazon.com/codecatalyst/latest/userguide/devenvironment-devfile.html)) Dockerfile.

However, using AWS Toolkit to make it easier to connect vscode to EC2 is something we are thinking about: https://github.com/aws/aws-toolkit-vscode/issues/941
