### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by davchz13** [aws/aws-toolkit-vscode#2703]
- Issue Type: `Performance`
- Extension Name: `aws-toolkit-vscode`
- Extension Version: `1.39.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.68.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/super/AppData/Local/Temp/amazonwebservices.aws-toolkit-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by justinmk3** [comment]
> ⚠️ Make sure to **attach** this file from your _home_-directory:
> ⚠️`file:///c%3A/Users/super/AppData/Local/Temp/amazonwebservices.aws-toolkit-vscode-unresponsive.cpuprofile.txt`

@davchz13 can you upload the mentioned file? Thanks!

**Comment by sdee3** [comment]
I'd like to help get this unblocked, but my platform is completely different:

Extension Version: `1.46.0`
OS Version: `macOS Monterey version 12.5`
Platform: `Darwin arm64`
VS Code version: `1.69.2`

[CPU-20220728T101027.cpuprofile.txt](https://github.com/aws/aws-toolkit-vscode/files/9206993/CPU-20220728T101027.cpuprofile.txt)

I hope I got the recording right - I recorded using the extension to build and run my Lambda function with two Layers onto a Docker image in Debug mode. What I really hate is how the extension uses 99% of all Performance cores of the CPU and switches to throttling after ~20 minutes of use (which I found out with the help of [asitop](https://github.com/tlkh/asitop))

**Comment by justinmk3** [comment]
> the extension uses 99% of all Performance cores of the CPU and switches to throttling after ~20 minutes of use (which I found out with the help of [asitop](https://github.com/tlkh/asitop))

@sdee3 thanks for the profile. If I'm reading it right, it doesn't look like aws toolkit is showing up in the profile at all, and most of the time is idle:

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/55561878/182028680-b399e44d-c5b5-4086-850f-80bd6069f44e.png">

> my Lambda function with two Layers onto a Docker image in Debug mode.

Can you show the asitop (or any other "top"-like) list showing which processes are using the CPU? Perhaps the problem is docker?

**Comment by sdee3** [comment]
You're welcome, @justinmk3! Here's both:

![image](https://user-images.githubusercontent.com/11007038/182097239-99c0be93-9541-44ca-a581-742a61bc726e.png)

And after typing in `ps aux | grep 67756`, this is what I found:

![image](https://user-images.githubusercontent.com/11007038/182099439-0289ead0-1aee-4d6c-b4df-277e6b995b4a.png)

I don't know how to interpret the last one, I hope there's something within the line in the middle:

`/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/stefandjokic/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.46.0/dist/src/ssmDocument/ssm/ssmServer.js --node-ipc --clientProcessId=67756`

**Comment by justinmk3** [comment]
possibly related to file watchers,

- https://github.com/aws/aws-toolkit-vscode/issues/2382
- https://github.com/aws/aws-toolkit-vscode/issues/2327

**Comment by sdee3** [comment]
> @sdee3 can you reproduce the issue after uninstalling/disabling ALL extensions except AWS Toolkit and whatever debugger is needed for debugging your Lambda?

I tried this, and I also isolated the extension via `extensions.experimental.affinity`. I got a really good result:

![image](https://user-images.githubusercontent.com/11007038/182332524-8c306408-e92f-4fa0-9a99-3ef934610147.png)

Reverting all other extensions quickly got me back to the same usage patterns, after which I decided to open the `Running Extensions` window and Profile all of them while debugging my Lambda. This led me to a conclusion that `wix.vscode-import-cost` is the culprit, using over 99% of all resources to investigate a bundled JS file I use for debugging, and after disabling only that extension, my CPU is behaving normally. @justinmk3 thank you for suggesting where to look and your support!

**Comment by justinmk3** [comment]
AWS Toolkit 1.73 (next release) will include https://github.com/aws/aws-toolkit-vscode/pull/3445 which improves performance if the `aws.samcli.enableCodeLenses` setting is disabled (the default).

We will continue to improve performance, you can track open issues here: https://github.com/aws/aws-toolkit-vscode/labels/performance
