### ISSUE TITLE
SAM/CFN schemas paths take a lot of space in the UI

### ISSUE THREAD

**Issue by jpinkney-aws** [aws/aws-toolkit-vscode#2704]
## Problem
Currently when you open a SAM YAML file your status bar gets filled with the entire path of the JSON schema. This can be a little inconvient as it takes up ~40% of the entire status bar while you have the YAML file opened.

![Screen Shot 2022-06-20 at 9 14 24 AM](https://user-images.githubusercontent.com/103940141/174609739-58ebe7be-1bbc-4217-ba87-ebab96cb05d7.png)

## Expected behavior
Ideally, instead of showing the entire path of the JSON schema we should just see the title of the schema. This could be something like "Serverless Application Model (SAM) Schema" instead of the entire path to the JSON schema.

VSCode-YAML supports this by first looking to see if the JSON schema has a "title" property when displaying on the status bar. If it doesn't have a "title" property then it just displays the full path.

There are 2 ways we can solve this problem:
1. Find a way to modify the GoFormation schema auto generation to allow us to specify a title
2. When we pull down the schema, add in the "title" property

**Comment by justinmk3** [comment]
> something like "Serverless Application Model (SAM) Schema" instead of the entire path to the JSON schema

"Serverless Application Model (SAM) Schema" is still quite long, and removes hints which might be helpful to customers.

Can we have both concision + precision by truncating the frontmatter:
 
    aws:/aws-toolkit-vscode/sam.schema.json
