### ISSUE TITLE
PreSign URL not generated

### ISSUE THREAD

**Issue by Nithos** [aws/aws-toolkit-vscode#2705]
## Problem
Starting with version 1.39.0 the _Generate Presigned _URL__ option no longer functions properly. When clicked the popup to specify the expire time comes up but once entered and confirmed the URL is not updated. The clipboard just contains the prefix `https://s3.amazonaws.com/`. Not sure if its incorrectly generating it, failing silently or simply not populating the clipboard correctly.

Previous versions work correctly.

## Steps to reproduce the issue

1. Go to the AWS plugin window
2. Navigate to a file in your S3 bucket
3. Right click on a file and select 'Generate Presigned URL'
4. Enter expire value or keep default 15min
5. Paste the generate URL that is saved to the clipboard.

## Expected behavior
The presigned URL correctly generated with full path and expires token.

## Actual
URL only contains  the AWS prefix `https://s3.amazonaws.com/`

## System details (run the `AWS: About Toolkit` command)

-   OS: MacOS Monterey v12.4
-   Visual Studio Code version: 1.68.1
-   AWS Toolkit version:  v1.39.0

**Comment by JadenSimon** [comment]
Thanks for the report!

This should be fixed in the next release: https://github.com/aws/aws-toolkit-vscode/pull/2687

**Comment by Nithos** [comment]
Great thank you.

**Comment by justinmk3** [comment]
This should be fixed in 1.41 . Thank you!
