### ISSUE TITLE
Toolkit produces Run/Debug/Configure CodeLenses for .net Lambda Functions to allow local debugging

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#271]
This is about detecting which functions can be run/debugged locally. The code lenses are stubs, to be implemented in other tasks in the same epic.

Acceptance criteria

* Candidate Lambda functions are detected, producing `LambdaHandlerCandidate` objects for each one
  * Candidate Lambda function definition: [language specific]
* Each candidate lambda function has 3 code lenses: Run Locally, Debug Locally, Configure
* The Run and Debug code lenses call a stub command (to be implemented in another task) which will be responsible for performing the actual run/debug. The stub command can simply showInfo("Not implemented yet")
* The Configure code lens calls the `aws.configureLambda` command appropriately

**Comment by mpiroc** [comment]
It would be great (but not required) to ensure that the return type is valid. It must either be a standard data type (as listed in [this doc](https://docs.aws.amazon.com/lambda/latest/dg/dotnet-programming-model-handler-types.html#dotnet-programming-model-handler-signatures)), or have a serializer specified.
