### ISSUE TITLE
Is there a way to roll back to a previous version of AWS Toolkit?

### ISSUE THREAD

**Issue by ryancabanas** [aws/aws-toolkit-vscode#2720]
## System details (run the `AWS: About Toolkit` command)

-   OS: Darwin arm64 21.5.0
-   Visual Studio Code version: 1.68.1
-   AWS Toolkit version: 1.42.0

## Question

I'm currently running AWS Toolkit 1.42.0 and getting the following error when trying to debug: **"Runtime for Template Resource xxxxx is either undefined or unsupported."**  Nothing has changed in my `template.yaml` file, or in my `launch.json` file, since the last time the debugger successfully ran.  The only change is that I was using AWS Toolkit 1.40.0.  The debugger worked fine in that version.

Is there a way for me to roll back to that version and to stop AWS Toolkit from automatically updating?

Thanks.

**Comment by ryancabanas** [comment]
I take it back.  I installed the VS Code extension called "Blockman" today and that seemed to be the culprit, for some reason.  After uninstalling "Blockman", I can now debug successfully. 😳  Sorry for the false alarm.

**Comment by JadenSimon** [comment]
@ryancabanas 

That's odd that `Blockman` was causing problems. We'll need to dig into this further.

> Is there a way for me to roll back to that version and to stop AWS Toolkit from automatically updating?

Just for future reference:

![Screen Shot 2022-06-28 at 9 01 21 AM](https://user-images.githubusercontent.com/31319484/176227172-8210812d-f1b1-41f9-9522-5e43cdffdae6.png)

Then disabling auto-update:

![Screen Shot 2022-06-28 at 9 04 05 AM](https://user-images.githubusercontent.com/31319484/176227191-53b804cb-18d2-4a84-8c91-6e9917821d6c.png)


Unfortunately you can't disable just one extension :/ (I think?)

**Comment by ryancabanas** [comment]
> > "Runtime for Template Resource xxxxx is either undefined or unsupported."
> 
> If there was a regression between 1.40 and 1.42 that is useful to know, thanks. If you can provide more details, I have created a tracking issue: #2721
> 
> What `sam` cli version are you using?

I'm using `sam cli v1.52.0`.  But I no longer think that it's related to the AWS Toolkit version, or `sam cli`.  It seemed to be a problem with the [Blockman extension](https://marketplace.visualstudio.com/items?itemName=leodevbro.blockman) because as soon as I uninstalled `Blockman` and tried debugging again, the problem/error went away.

**Comment by ryancabanas** [comment]
@JadenSimon 

Good to know about choosing a specific AWS Toolkit version and how to prevent auto-updates to VS Code extensions.  Thank you!
