### ISSUE TITLE
Users are able to deploy .net sam applications to AWS

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#273]
This is a placeholder -- deploy features provided by #125 should work for .net. If any surprises come up, this issue represents the entrypoint for that work.

**Comment by bryceitoc9** [comment]
Validated that the command palette deploy command does work for .net deploys. Tested the app generated with `sam init --runtime dotnet` command as well as the app created with the `lambda.LexBookTripSample` blueprint (see https://github.com/aws/aws-lambda-dotnet#blueprints ; I manually created a SAM template for this blueprint).

Will try and generate a more complicated app, but this is looking good as-is for the time being.

**Comment by bryceitoc9** [comment]
Confirmed existing functionality works for .net 2.0 and 2.1. Found a bug that isn't specific to this runtime; filed that here: https://github.com/aws/aws-toolkit-vscode/issues/485

Closing as a no-op
