### ISSUE TITLE
How to Define custom invoke Lambda templates 

### ISSUE THREAD

**Issue by TomasHronek** [aws/aws-toolkit-vscode#2739]
## System details 

-   OS: Windows 10
-   Visual Studio Code version: 1.55.2
-   AWS Toolkit version: 1.44

## Question
Hi,
is possible somewhere create/edit sample request payloads? I would like to create new one and remove existing, but haven't found where are their defined, i looked at:  C:\Users\user\.vscode
Thanks Tomas

![image](https://user-images.githubusercontent.com/27373682/176895432-2015f3f6-1b21-490b-b99e-68511badbd85.png)

**Comment by justinmk3** [comment]
You can save any of the sample payloads to a file, then use the `Choose File` button in that UI. Does that answer your question?

**Comment by TomasHronek** [comment]
I saw this Choose File option, we d like to have more flexible solution like in DataGrip:
User can define template Run Config:
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/27373682/177110351-9671b1b3-7824-46cf-9b61-55437587d286.png)
This template can be then triggered from Context menu:
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/27373682/177110488-7ce61a95-b894-4190-8d74-d9dd7143ac41.png)
User can edit chosen params of the Run Configuration:
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/27373682/177110650-639288d9-1965-4bfd-bd87-bd76c023111f.png)
Is something similar possible in VSC? I just found this approach, but user still need to save somewhere launch.json files:
https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/serverless-apps-run-debug-no-template.html
Thanks Tomas

**Comment by justinmk3** [comment]
> I just found this approach, but user still need to save somewhere launch.json files:
> https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/serverless-apps-run-debug-no-template.html

launch.json is where vscode stores its "launch configs", which are likeJetBrains "Run configs". VSCode launch configs are available from its Run menu:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/55561878/177359810-6dc0495e-f281-42f7-af6c-9476fbfbced2.png">
