### ISSUE TITLE
SAM run/debug: do not stop on `node` entrypoint file 

### ISSUE THREAD

**Issue by ryancabanas** [aws/aws-toolkit-vscode#2758]
## System details (run the `AWS: About Toolkit` command)

OS: Darwin arm64 21.5.0
Visual Studio Code extension host:  1.69.0
AWS Toolkit:  1.46.0-3e2137d9f381
node: 16.13.2
electron: 18.3.5

## Question

When initiating a debugger session to debug an API locally, the debugger always automatically stops in the `internal/async_hooks` file at the first line of a function named `promiseInitHookWithDestroyTracking`.

Why does it do this and is there any way to prevent the debugger from doing this?  😁  Thanks!

**Comment by JadenSimon** [comment]
Good question! A lot of this comes down to legacy code paths that have hard-coded the node option `--inspect-brk` when running the Lambda. Looking at the [node documentation](https://nodejs.org/en/docs/guides/debugging-getting-started/), we find this entry:
```
    Enable inspector agent
    Listen on default address and port (127.0.0.1:9229)
    Break before user code starts
```

That last line is your answer:  **break before user code starts**.  The use of this option is likely just a remnant of the past, and the Toolkit should be able to use `--inspect` instead. I'm changing this issue to a feature request. There's not much users can do to change this without a pretty custom set-up.

**Comment by Skyrail** [comment]
I'd like to clarify here to make sure I'm not going mad. But am I right in thinking that everyone using the VSCode AWS Toolkit to debug their NodeJS Lambda functions has their debugger pause on the `internal/async_hooks` file and there's no fix or way around it? Is this just how 'things are done' - asking coming into Lambda NodeJS development from the outside.

I'm assuming there's no fix given that this 'feature request' is still open and I'm experiencing this frustration trying to debug my Lambda functions.

**Comment by justinmk3** [comment]
@Skyrail thanks for raising this. IIUC, `--inspect-brk` is being set by sam cli: https://github.com/aws/aws-sam-cli/blob/1adc080b82476288804c41c553c5e2ad86f28298/samcli/local/docker/lambda_debug_settings.py#L165

but I think AWS Toolkit can workaround this. Will take a look.

**Comment by Skyrail** [comment]
Thanks @justinmk3 - that clarifies things a little more. If it's the way it needs to be then so be it, it just felt weird coming in from the outside that this is 'normal' but that may be my misunderstanding as to why it's like that.

**Comment by justinmk3** [comment]
@Skyrail https://github.com/aws/aws-toolkit-vscode/pull/3846 includes a fix for this, can you confirm it works for you? 

1. Download and extract [buildArtifacts.zip](https://github.com/aws/aws-toolkit-vscode/files/12690119/buildArtifacts.zip)
2. In VSCode, run `Extensions: Install from VSIX` to install the `*.vsix` file. (You can run commands with `ctrl-shift-p` or `cmd-shift-p`) 
3. Reload VSCode and verify that the Toolkit has the new version (not the older version).

**Comment by Skyrail** [comment]
@justinmk3 installed and tested succesfully. 

Running a NodeJS 18.x application in debug mode without any breakpoints succesfully runs the application without stopping. Adding a break point the program pauses at the correct point as expected.

From my limited perspective I'd say that's a succesful fix, thank you!
