### ISSUE TITLE
Unrecognized properties in SAM schema

### ISSUE THREAD

**Issue by el-ko** [aws/aws-toolkit-vscode#2765]
## Problem
VS-code prompts problems on (SAM) template.yaml syntax. Problems originate Declaring `Policies`-property and `Events/Schedule`-property in a `AWS::Serverless::Function`-resource

`Policies`-property reports:
>Missing property "Version"
>Missing property "Queue"

`Events: Schedule`-property reports:
>Property Schedule is not allowed.
>Property Name is not allowed

## Steps to reproduce the issue

1. Define a `AWS::Serverless::Function` in a SAM-template
2. Define Policies statements & a Events: Schedule

![image](https://user-images.githubusercontent.com/28481538/179458309-2a3e8867-77e2-4712-bb2d-db3c77ca701e.png)

4. See error in problem report from vs-code
![image](https://user-images.githubusercontent.com/28481538/179458519-74eda042-43db-413b-bd52-2f363979e647.png)

## Expected behavior
No errors on defining Policies statements and Events: Schedule in a Serverless function resource. 

## System details (run the `AWS: About Toolkit` command)
OS: Windows_NT x64 10.0.19044
Visual Studio Code extension host:  1.69.1
AWS Toolkit:  1.45.0

**Comment by justinmk3** [comment]
Fixed in goformation: https://github.com/awslabs/goformation/pull/492
