### ISSUE TITLE
telemetry: emit metric for failed sam build

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#2774]
https://github.com/aws/aws-toolkit-vscode/blob/810dfe57b4871257756ef02c524e58f4ca25330f/src/shared/sam/localLambdaRunner.ts#L162

**Comment by JadenSimon** [comment]
Will show up in the `reason` field as `BuildFailure` for `lambda_invokeLocal` or `apigateway_invokeLocal`

https://github.com/aws/aws-toolkit-vscode/pull/2865/files#diff-b36cc56a594606340ec0320f08168751338535f63e948fdcaab177666baffb79R159
