### ISSUE TITLE
AWS Toolkit Connect not present in Command Palette

### ISSUE THREAD

**Issue by TexEvans** [aws/aws-toolkit-vscode#2784]
## Problem

AWS Toolkit Connect to AWS not present in Command Palette.  I've uninstalled and reinstalled.

## Expected behavior

Expect AWS Toolkit Connect to be in the menu

## System details (run the `AWS: About Toolkit` command)

-   OS: MacOS 12.4
-   Visual Studio Code version: 1.69.2
-   AWS Toolkit version: v1.46.0
<img width="710" alt="Screen Shot 2022-07-29 at 11 23 40 AM" src="https://user-images.githubusercontent.com/59584291/181803207-4605b887-68c7-47b8-87ff-2b351e77465e.png">

**Comment by justinmk3** [comment]
Command was renamed to `AWS: Choose AWS Profile`. We will update the documentation.

**Comment by justinmk3** [comment]
> We will restore `AWS: Connect to AWS` command (which is just an alias to `AWS: Choose AWS Profile`. #2788

AWS Toolkit 1.47 includes this change.
