### ISSUE TITLE
Video demo and one-page doc summary of the credential management support

### ISSUE THREAD

**Issue by steveataws** [aws/aws-toolkit-vscode#28]
As part of the definition of 'done' we need to record a video demo of how we manage credentials and create a one-page summary doc of the feature that can be used by doc teams in the preparation of user guide materials.

Requires completion of the credential management features.

**Comment by awschristou** [comment]
There is no video.
The user guide is available at https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/establish-credentials.html

Closing this issue.
