### ISSUE TITLE
It's literally changing my code

### ISSUE THREAD

**Issue by RamonPessoa** [aws/aws-toolkit-vscode#2826]
The code whisperer, should make code suggestion, and if I confirm the sugestion it should change the code, but some times i'm writing a code and I go back to some part of the line to include something, and code whisperer gives me a suggestion, I decline it, and it erases what i already wrote, i don't know how the reproduce the bug, but it's really annoying

**Comment by justinmk3** [comment]
With AWS Toolkit 1.56, CodeWhisperer now uses the VSCode inline completion API, which fixes this issue.
