### ISSUE TITLE
"Send Feedback" for CodeWhisperer features

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#2827]
## Problem

- Feedback specific to CodeWhisperer sometimes lacks context to make that obvious
- CodeWhisperer users may not easily discover the Toolkit's primary "Send Feedback" action 

## Proposal

1. Add "Send Feedback" actions in the CodeWhisperer section of "Dev Tools" panel...
    - as a hover icon?
    - as a dedicated node?
2. code change: include "codewhisperer" as the component name when sending feedback

![image](https://user-images.githubusercontent.com/55561878/184237282-8c3881f9-db58-4283-89fc-5e54d47f1fa4.png)

**Comment by zixlin7** [comment]
We have taken note of this and will consider this
