### ISSUE TITLE
CodeWhisperer: Lua language not supported

### ISSUE THREAD

**Issue by Zidras** [aws/aws-toolkit-vscode#2850]
## Problem
Lua currently not supported, and no indication in the documentation that this is the case.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/10605951/186748245-2133dabc-7f4b-4a35-9046-c2b322cee501.png">

## Steps to reproduce the issue

1. Create a .lua file
2. Alt+C to force check

## Expected behavior
Code suggestions should be provided by CodeWhisperer.

## System details (run the `AWS: About Toolkit` command)

OS: Windows_NT x64 10.0.22000
Visual Studio Code extension host:  1.70.2
AWS Toolkit:  1.48.0
node: 16.13.2
electron: 18.3.5

**Comment by andrewyuq** [comment]
Hello @Zidras ,
Thank you for your support, in this FAQs(and also the welcome page which will show when you first activated CodeWhisperer) it states that the languages we are supporting are Java, Python and Javascript for now. Lua is not supported at the moment.
https://aws.amazon.com/codewhisperer/faqs/

**Comment by Zidras** [comment]
> Hello @Zidras , Thank you for your support, in this FAQs(and also the welcome page which will show when you first activated CodeWhisperer) it states that the languages we are supporting are Java, Python and Javascript for now. Lua is not supported at the moment. https://aws.amazon.com/codewhisperer/faqs/

Hello @andrewyuq, thank you for your reply. I have to say the wording if **very** misleading:
"and supports programming languages `like` Python, Java, and JavaScript."

If this list is comprehensive, and currently **only** these 3 languages are supported, then the wording should reflect so:
"and supports the following programming languages: Python, Java, and JavaScript."

Just my 2c. If atm there are only these 3 languages, I believe this ticket can be closed (even if it's a feature request at this point) when the wording in the faq is explicit enough to not mislead users. Thank you

**Comment by andrewyuq** [comment]
@Zidras I agree with you. I have communicated to our team and the wording in the faqs should be fixed. Thanks!

**Comment by andrewyuq** [comment]
https://aws.amazon.com/codewhisperer/faqs/ the wording is fixed now. Closing the ticket as resolved.
