### ISSUE TITLE
Remember target directory when downloading files from S3

### ISSUE THREAD

**Issue by pawel-kuras** [aws/aws-toolkit-vscode#2855]
## Problem
When the aws toolkit extension is connected to S3, I can right-click a file, then choose "Download..." to download it to my local machine. Sadly, the "Save as" dialog doesn't remember the directory I select. So when I perform a second download, I have to select the same directory all over again.

Note: Essentially copied the description from the completed issue https://github.com/microsoft/vscode/issues/140358

## Expected behavior
It would be convenient if the previously-selected directory was remembered.

Alternatively, it would be convenient if you could set a default downloads directory, but this doesnt match the functionality vs-code went with, as they closed https://github.com/microsoft/vscode-remote-release/issues/5998 in favor of https://github.com/microsoft/vscode/issues/140358

**Comment by justinmk3** [comment]
> Alternatively, it would be convenient if you could set a default downloads directory, but this doesnt match the functionality vs-code went with, as they closed [microsoft/vscode-remote-release#5998](https://github.com/microsoft/vscode-remote-release/issues/5998) in favor of [microsoft/vscode#140358](https://github.com/microsoft/vscode/issues/140358)

That reference is helpful, thanks! It probably makes sense for AWS Toolkit to use the same globally-stored path as VSCode? 

From https://github.com/microsoft/vscode/commit/1b8e78461329d43d79a47a1c38e081e63d7f75ae#diff-d8122abf1f3d6b4464ce28fe7e0358f9a0f22b9cc8634804f509f04eda753788R799 that's `workbench.explorer.downloadPath` in globalStorage.

**Comment by justinmk3** [comment]
In AWS Toolkit 1.60, the S3 "Download" action now defaults to the last-used download location.
