### ISSUE TITLE
PayloadFormatVersion is not allowed

### ISSUE THREAD

**Issue by petro2050** [aws/aws-toolkit-vscode#2867]
`template.yaml` file warns about `PayloadFormatVersion` not being allowed.

<img width="203" alt="s1" src="https://user-images.githubusercontent.com/62858360/188257715-7fb44287-3f99-4b83-8c24-1db602bc907d.png">

**Comment by justinmk3** [comment]
Are you still seeing this issue?

AWS Toolkit 1.65+ includes an updated SAM/CFN json-schema from : 
https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json
