### ISSUE TITLE
Users can create a new .net SAM Application without directly using SAM CLI

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#288]
The existing "new sam app" functionality should work, but there may be some .net specific changes to make.

Acceptance criteria:

* User doesn't have to create files by hand
* User doesn't have to run commands at a command prompt
* User has a set of files produced for them that they can start working from
* appropriate .cs file is loaded into the editor after creation. If unable to determine a .cs file, open the template.yaml file instead

Appropriate .cs file = Try to load the .cs file referenced by the template.yaml file, if it exists, maybe falling back to something like Program.cs

**Comment by mpiroc** [comment]
Depends on #259 .

**Comment by mpiroc** [comment]
The only work for this task is to open the main code file after project creation. The rest is already implemented.
