### ISSUE TITLE
Requesting AWS Step Functions Code Snippets for YAML

### ISSUE THREAD

**Issue by gowthamshankar99** [aws/aws-toolkit-vscode#2891]
## Problem
AWS Toolkit provides AWS Step Functions Code Snippets for JSON and it works well. However the Code Snippets doesn't work for YAML.

**Comment by wong-a** [comment]
Thanks for the feature request @gowthamshankar99

When you say "Code Snippets", are you referring to the templates from the `AWS: Create a new Step Functions state machine` command, autocompletions, or something else?

**Comment by wong-a** [comment]
Testing in AWS toolkit version 1.78.0, both YAML snippet when entering ctrl + space and the templates seem to work fine

**Comment by gowthamshankar99** [comment]
it does work fine now. Im not sure if I had an older version of the plugin, thanks for the response
