### ISSUE TITLE
sam typescript: "Error: tsconfig.json or *.ts not found"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#2907]
> I have my `package.json`, `node_modules` and `tsconfig.json` files in my src/ directory.  When I run the debugger in vscode I get the error message:
> 
> ```bash
> 2022-09-13 17:50:57 [INFO]: Preparing to debug locally: Lambda "cleanupLeftoverTestAssets.handler"
> 2022-09-13 17:50:57 [INFO]: Building SAM application...
> 2022-09-13 17:50:57 [INFO]: Command: (not started) [/usr/local/bin/sam build --build-dir /tmp/aws-toolkit-vscode/vsctkTZ4wxw/output --template /tmp/aws-toolkit-vscode/vsctkTZ4wxw/app___vsctk___template.yaml --base-dir /Users/josh/git/lambda-jobs/src]
> 2022-09-13 17:51:01 [INFO]: Build complete.
> 2022-09-13 17:51:01 [ERROR]: SamLaunchRequestError: Failed to run launch configuration
> 	 -> Error: tsconfig.json or *.ts not found in: "/tmp/aws-toolkit-vscode/vsctkTZ4wxw/output/*"
> ```
> 
> When I look at the output directory it has this:
> ```bash
> ls /tmp/aws-toolkit-vscode/vsctkcBXB7s/output/*
> /tmp/aws-toolkit-vscode/vsctkcBXB7s/output/template.yaml
> 
> /tmp/aws-toolkit-vscode/vsctkcBXB7s/output/src:
> dist              node_modules      package-lock.json package.json
> ```
> 
> 
> Here is tsconfig.json (in the src/ directory)
> ```json
> {
>   "compilerOptions": {
>     "lib": ["es2020"],
>     "module": "commonjs",
>     "moduleResolution": "node",
>     "target": "es2020",
>     "sourceMap": true,
>     "strict": true,
>     "esModuleInterop": true,
>     "skipLibCheck": true,
>     "forceConsistentCasingInFileNames": true,
>     "resolveJsonModule": true,
> 
>     "outDir": "dist",
>     "rootDir": "."
>   },
>   "include": [
>     "./"
>   ]
> }
> ```
> 
> Here is my launch.json:
> ```json
> {
>   "version": "0.2.0",
>   "configurations": [
>     {
>       "type": "aws-sam",
>       "request": "direct-invoke",
>       "name": "Invoke Cleanup Test Assets Lambda",
>       "invokeTarget": {
>         "target": "code",
>         "projectRoot": "${workspaceFolder}/src",
>         "lambdaHandler": "cleanupLeftoverTestAssets.handler"
>       },
>       "lambda": {
>         "runtime": "nodejs14.x",
>         "payload": {},
>         "environmentVariables": {}
>       }
>     }
>   ]
> }
> ```
> 
> Any help or guidance would be appreciated.

_Originally posted by @josh803316 in https://github.com/aws/aws-toolkit-vscode/issues/1487#issuecomment-1246113309_

**Comment by JadenSimon** [comment]
Should be fixed by https://github.com/aws/aws-toolkit-vscode/pull/3099
