### ISSUE TITLE
Users are able to locally run/debug Python Lambda functions [Epic]

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#292]
Acceptance criteria

* Python based serverless applications can be run locally
* Python based serverless applications can be debugged locally
* event and env var data can be configured for local run/debug sessions

**Comment by tomisaacson** [comment]
Are there instructions for this anywhere?

**Comment by awschristou** [comment]
Thank you for reaching out @tomisaacson - we are in the process of updating the user documentation to include instructions for setting up your VS Code to work with local run/debug on Python Lambda functions.

Python support has not been released at this time, but is available on the `develop` branch of this repo. If you install the [Python Extension for VS Code](https://marketplace.visualstudio.com/itemdetails?itemName=ms-python.python) it should be possible to see CodeLenses for your Lambda handlers, similar to https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/create-sam.html#run-debug-sam-app

**Comment by tomisaacson** [comment]
But that article starts "After the AWS SAM application is created". How do I debug my pre-existing lambda? Do I have to create an AWS SAM application to wrap it in?

**Comment by awschristou** [comment]
You are correct. The naming of the issues/epics/tasks in the backlog are in the context of a lambda function within a SAM application. Sorry about the confusion - this was an oversight on our part.
