### ISSUE TITLE
Despite instructions to run toolkit in c9 without internet access, visualize step function graph requires internet connectivity that is easily patched.

### ISSUE THREAD

**Issue by simis2626** [aws/aws-toolkit-vscode#2922]
## Problem
Based on the instructions [here](https://docs.aws.amazon.com/cloud9/latest/user-guide/toolkit-welcome.html#access-toolkit), aws toolkit should be largely functional without an internet connection if the user provides appropriate S3 endpoint access.

The functionality to render a Amazon Step Function State Machine Graph requires connectivity to:
- 'https://do0of8uwbahzz.cloudfront.net/sfn-0.1.5.js'
- 'https://do0of8uwbahzz.cloudfront.net/graph-0.1.5.css'
As in file [util.ts](https://github.com/aws/aws-toolkit-vscode/blob/master/src/stepFunctions/utils.ts#L27)

Based on this [codepath](https://github.com/aws/aws-toolkit-vscode/blob/481f71c019903696e72bee64898caaa1ddffbba9/src/stepFunctions/commands/visualizeStateMachine/aslVisualizationManager.ts#L36) this download process can't be skipped or otherwise configured.

However, as a user if you populate graph.js and graph.css under .c9-project

## Steps to reproduce the issue

** Prereq: set AWS toolkit to debug level logging.

1) Launch an EC2 based Cloud9 instance in a private VPC without routing to the public internet, but with the S3 VPC Endpoints as described in this doco: https://docs.aws.amazon.com/cloud9/latest/user-guide/ec2-ssm.html#configure-s3-endpoint
1) Create and save a basic test step function: in a file called `sfn.asl.yaml`
```
Comment: test
StartAt: first
States:
    first:
      Type: Pass
      End: true
```
1) Click the `render graph` text at the top of the file. 
1) Observe in the logs that this [codepath](https://github.com/aws/aws-toolkit-vscode/blob/481f71c019903696e72bee64898caaa1ddffbba9/src/stepFunctions/commands/visualizeStateMachine/aslVisualizationManager.ts#L36) fires, and fails as there's no internet access.

## Expected behavior

Expose configuration options to allow skipping/bypassing [this specific line](https://github.com/aws/aws-toolkit-vscode/blob/master/src/stepFunctions/commands/visualizeStateMachine/aslVisualizationManager.ts#L36), or check for the presence of the file `graph.js` & `graph.css` under `/.c9/amazonwebservices.aws-toolkit-vscode/visualization/` and if present progress without attempting to download.

OR

Include `graph.js` and `graph.css` in the dependency set included in the S3 files for no internet access Cloud9s
https://docs.aws.amazon.com/cloud9/latest/user-guide/ec2-ssm.html#configure-s3-endpoint

## System details (run the `AWS: About Toolkit` command)

OS: Linux x64 4.14.291-218.527.amzn2.x86_64
AWS Cloud9 extension host:  1.67.2
AWS Toolkit:  1.50.0
node: 12.22.9

---

Happy to make a PR on this, but would like some direction from the maintainers about a direction that would be welcome. "skipping" this specific line](https://github.com/aws/aws-toolkit-vscode/blob/master/src/stepFunctions/commands/visualizeStateMachine/aslVisualizationManager.ts#L36) does work, but might not be a great, comprehensive solution.

**Comment by simis2626** [comment]
Note that if a user manually downloads the graph.css and graph.js files from the cloudfront URL in the source, and places them under `.c9/amazonwebservices.aws-toolkit-vscode/visualization/` and *deletes* [this specific line](https://github.com/aws/aws-toolkit-vscode/blob/master/src/stepFunctions/commands/visualizeStateMachine/aslVisualizationManager.ts#L36), from /opt/c9/dependencies/aws-toolkit-vscode/f0fea196013af4156ea9f5cafeefb6c061c612ec6f37f929c987bb25ee520e090dc11a6eb25a834bac14147aafa22b0b29371a454d129925f6fc7acc45d81dd3/dist/src/main.js:1658

Then the render state machine functionality works fine.

**Comment by JadenSimon** [comment]
Yeah this cache implementation is not robust; it should not fail if data is on disk. No need for extra configuration.

**Comment by simis2626** [comment]
PR raised #3098.
Would appreciate maintainer approving CI run when able. Thanks in advance.
