### ISSUE TITLE
SAM: FunctionResponseTypes marked as error

### ISSUE THREAD

**Issue by m-ronchi** [aws/aws-toolkit-vscode#2924]
## Problem
this function definition has an error according to sam.schema.json
![image](https://user-images.githubusercontent.com/35332423/194849597-71cf4801-7fd1-4219-8dd0-578855b564cc.png)
but is valid according to `sam validate`

## Steps to reproduce the issue

add it to a SAM template.yaml

## Expected behavior

should be valid

## System details (run the `AWS: About Toolkit` command)

OS: Darwin x64 21.6.0
Visual Studio Code extension host:  1.73.0
AWS Toolkit:  1.53.0
node: 16.14.2
electron: 19.0.17

**Comment by justinmk3** [comment]
Fixed in AWS Toolkit 1.63
