### ISSUE TITLE
ECS "Open Terminal" fails in Cloud9

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#2928]
Steps to repro:

1. in cloud9, go to AWS Explroer, expand ECS service
2. right click , select "Open Terminal"

logs (the first message might be irrelevant):

```
2022-10-11 21:19:44 [ERROR]: aws.ecs.openTaskInTerminal: Error: Failed to open terminal.
	 -> TypeError: Unexpected type cast: got string, expected primitive Boolean
...
2022-10-11 21:40:49 [ERROR]: aws.ecs.openTaskInTerminal: InvalidClientTokenId: The security token included in the request is invalid (statusCode: 403; requestId: 175bc3c5-a360-4d16-ae04-bba7ceb13b9a)
```

ref https://github.com/aws/aws-toolkit-vscode/pull/2905

**Comment by JadenSimon** [comment]
This is probably from the `terminal.integrated.tabs.enabled` hack I added. I didn't add a default value and C9 doesn't handle nested settings very well.

**Comment by JadenSimon** [comment]
I guess the terminal API just isn't implemented at all on C9. 

> InvalidClientTokenId: The security token included in the request is invalid

This is another bespoke credentials expiration error code :/
