### ISSUE TITLE
SFN: step function definition marked as wrong when it's not

### ISSUE THREAD

**Issue by m-ronchi** [aws/aws-toolkit-vscode#2938]
## Problem

json definition of step function (xxx.asl.json) is marked with errors if it contains intrinsic function calls, e.g. `States.UUID()`

## Steps to reproduce the issue

1. create a step function definition
2. add some dynamic input to a state like this
![image](https://user-images.githubusercontent.com/35332423/196748113-e4d58a28-96bd-4ab0-b196-bce43ef8141e.png)

## Expected behavior

no errors

## System details (run the `AWS: About Toolkit` command)

OS: Darwin x64 21.6.0
Visual Studio Code extension host:  1.72.2
AWS Toolkit:  1.51.0
node: 16.14.2
electron: 19.0.17

**Comment by jmtelljohann** [comment]
I'm having this problem too with States.ArrayContains

**Comment by ascrookes** [comment]
I'm having a similar error with a new intrinsic function expression.

I am using `States.JsonMerge($.json1, $.json2, false)`. I've confirmed that it does work in StepFunctions even though the AWS toolkit flags this as incorrect.

**Comment by justinmk3** [comment]
Fixed in AWS Toolkit 1.63
