### ISSUE TITLE
Github Copilot suggestions block left/right arrows

### ISSUE THREAD

**Issue by vfilter** [aws/aws-toolkit-vscode#2939]
## Problem
If AWS Toolkit and Github Copilot extensions to VC Code are both installed, every time Copilot makes a suggestion, the left/right arrow keys stop working, effectively 'trapping' the cursor. Up/down still work as expected.

## Steps to reproduce the issue

1. Install Github Copilot and AWS Toolkit
2. Create new file with .js (or any other) extension
3. Trigger a suggestion from Copilot
4. Try to move your cursor to the left or right with the arrow buttons on your keyboard while the suggestion is displayed

## Expected behavior
I should be able to freely move my cursor to the left and right

## System details (run the `AWS: About Toolkit` command)

-   OS: MacOS
-   Visual Studio Code version: Version: 1.72.2 (Universal)
-   AWS Toolkit version: v1.51.0

**Comment by JadenSimon** [comment]
This might be a conflict with the CodeWhisperer feature. Can you try the following:
1. Unzip and install this pre-release VSIX: [aws-toolkit-vscode-1.52.0-febbf4edaa63.vsix.zip](https://github.com/aws/aws-toolkit-vscode/files/9823845/aws-toolkit-vscode-1.52.0-febbf4edaa63.vsix.zip)
    * You can use the command palette command "Extensions: Install from VSIX..." to install it after unzipping
2. Reload VS Code

If that doesn't work try disabling the CodeWhisperer feature entirely by looking for "CodeWhisperer" in the settings. Uncheck the CodeWhisperer box under "Aws: Experiments" (requires a reload):

<img width="644" alt="Screen Shot 2022-10-19 at 12 52 28 PM" src="https://user-images.githubusercontent.com/31319484/196791712-0abcc064-2918-4b85-9ace-ae16622d927c.png">

**Comment by JadenSimon** [comment]
The latest release should have a fix. Feel free to re-open if the issue persists!
