### ISSUE TITLE
Investigate deprecating DisposableFiles in favor of existing mature npm module 

### ISSUE THREAD

**Issue by micholas** [aws/aws-toolkit-vscode#300]
**Is your feature request related to a problem? Please describe.**

We continue to use a few approaches to creating and cleaning up temp files including our efforts to develop and maintain `DisposableFiles`. NPM modules like [tmp](https://www.npmjs.com/package/tmp) and [tmp-promise](https://www.npmjs.com/package/tmp-promise) are likely higher quality might enable us to focus our time on core aws-toolkit-vscode functionality.

**Describe the solution you'd like**
Eliminate `DisposableFiles` and instead leverage a widely used NPM module to consistently create and clean up tempt files.

**Describe alternatives you've considered**
Continue attempt at re-invent the wheel.

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/475 was merged to an old `develop` branch but never into `master` ?
