### ISSUE TITLE
`invalid_grant: invalid grant provided` when using AWS Identity Center to authenticate aws-toolkit

### ISSUE THREAD

**Issue by jeichenhofer** [aws/aws-toolkit-vscode#3009]
## Problem

When configuring the aws-toolkit extension to authenticate using AWS Identity Center, the request cannot be authorized. Instead, an error message appears stating "`invalid_grant` Invalid grant provided" and blocks progress. I've seen [this issue on the `aws-cli` repo](https://github.com/aws/aws-cli/issues/5058), but I've confirmed that the region of the request to `https://oidc.us-west-2.amazonaws.com/device_authorization/associate_token` matches the region in which our management account has IAM Identity Center configured (`us-west-2`).

## Steps to reproduce the issue

(I've replaced my custom AWS IAM Identity Center domain with `mydomain` in these steps)

1. Go to command palette (`F1`)
2. Execute `AWS: Connect to AWS`
3. Select `Connect using AWS IAM Identity Center`
4. Input the "Start URL" for the AWS Access Portal (i.e., `https://mydomain.awsapps.com/start`)
5. In the browser window that opens, the API autofills a temporary code and loads a new page at `https://us-west-2.signin.aws/platform/login`.
6. Sign into the account with my personal IAM Identity Center credentials.
7. This redirects to `https://mydomain.awsapps.com/start/user-consent/authorize.html`, where I can click "Allow" and see the error message.

### Error Message

```
invalid_grant
Invalid grant provided
```

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/25592371/203716831-57d3ebcd-2150-45e3-9306-ab2bc5c32d33.png)

</details>

## Expected behavior

I expect the "Allow" button to verify the tokens and return something to the callback listener in vscode, which sets the temporary credentials for the AWS Toolkit extension and `aws-cli` environment in the container.

## System details

I am running this inside a vscode dev container, however I confirmed the same behavior when running with a locally installed vscode and AWS Toolkit extension.

```
OS: Linux x64 5.10.16.3-microsoft-standard-WSL2
Visual Studio Code extension host:  1.73.1
AWS Toolkit:  1.55.0
node: 16.14.2
```

### Dockerfile for dev environment
<details>
<summary>Dockerfile.dev</summary>

```Dockerfile
# install aws-cli in light container per https://github.com/aws/aws-cli/blob/v2/docker/Dockerfile
FROM alpine:latest as aws_installer
ARG AWS_ARCHIVE_NAME="awscli2.zip"
RUN apk add curl unzip
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o $AWS_ARCHIVE_NAME
RUN unzip $AWS_ARCHIVE_NAME
# The --bin-dir is specified so that we can copy the
# entire bin directory from the installer stage into
# into /usr/local/bin of the final stage without
# accidentally copying over any other executables that
# may be present in /usr/local/bin of the installer stage.
RUN ./aws/install --bin-dir /aws-cli-bin/

# build dev container
FROM ubuntu:jammy
RUN apt-get update \
    && apt-get upgrade -y

# vscode user creation
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

RUN apt-get install -y git vim wget gnupg2 software-properties-common

# terraform
RUN wget -O- https://apt.releases.hashicorp.com/gpg | \
    gpg --dearmor | \
    tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com `lsb_release -cs` main" | tee /etc/apt/sources.list.d/hashicorp.list
RUN apt-get update && apt-get install terraform

# aws cli installation
RUN apt-get install -y less groff
COPY --from=aws_installer /usr/local/aws-cli/ /usr/local/aws-cli/
COPY --from=aws_installer /aws-cli-bin/ /usr/local/bin/

# apt cleanup
RUN apt-get clean -y && apt-get autoremove -y

USER $USERNAME
```
</details>

### AWS Toolkit Logs
<details>
<summary>aws_toolkit.log</summary>

```Logs
2022-11-24 06:45:08 [ERROR]: log level: info
2022-11-24 06:45:09 [INFO]: Retrieving AWS endpoint data
2022-11-24 06:45:09 [INFO]: OS: Linux x64 5.10.16.3-microsoft-standard-WSL2
2022-11-24 06:45:09 [INFO]: Visual Studio Code extension host:  1.73.1
2022-11-24 06:45:09 [INFO]: AWS Toolkit:  1.55.0
2022-11-24 06:45:09 [INFO]: node: 16.14.2
2022-11-24 06:45:09 [INFO]: telemetry cache not found: '/home/vscode/.vscode-server/data/User/globalStorage/amazonwebservices.aws-toolkit-vscode/telemetryCache'
2022-11-24 06:45:27 [WARN]: auth: failed to restore previous session: Error: Connection does not exist: profile:sso-user-joe
2022-11-24 06:45:27 [WARN]: auth: failed to auto-connect using "ec2:instance": Error: Connection does not exist: ec2:instance
2022-11-24 06:45:27 [WARN]: auth: failed to auto-connect using "ecs:instance": Error: Connection does not exist: ecs:instance
2022-11-24 06:45:27 [WARN]: auth: failed to auto-connect using "profile:default": Error: Connection does not exist: profile:default
2022-11-24 06:50:10 [INFO]: telemetry: sent batch (size=7)
2022-11-24 06:55:45 [ERROR]: aws.auth.addConnection: InvalidGrantException: UnknownError
```
</details>

**Comment by JadenSimon** [comment]
Thanks for the bug report!

Looks like we’ll need to add an extra quick pick step to choose a region after inputting the start URL. I’m unaware of any API that allows us to determine the region the identity directory is in from the start URL alone.

**Comment by jeichenhofer** [comment]
What's odd is that the `SsoAccessTokenProvider` does [check the profile for the region to use when constructing](https://github.com/aws/aws-toolkit-vscode/blob/499ab7025f7587f0326a8d70508dc402f6115adb/src/credentials/sso/ssoAccessTokenProvider.ts#L61) the `OidcClient`. In fact, I did some work connecting the `aws-cli` to use the sso oidc workflow, and after poking around the `config` file to consolidate the `session` and `profile` into just a single profile block, I now see that there is an option to just select that profile from the dropdown when executing `AWS: Connect to AWS`. That seems to work correctly now.

I guess that means that the steps that `aws-toolkit-vscode` takes to generate the `.aws/config` file when defining the sso connection needs to take that region into account, just like you said.

For reference, here's the config I ended up using:

```
vscode@eae540dc3e8d:/workspaces/aws-infra$ cat ~/.aws/config
[profile sso-user-joe]
sso_account_id = myaccountid
sso_role_name = myrolename
region = us-west-2
output = json
sso_start_url = https://mydomain.awsapps.com/start
sso_region = us-west-2
sso_registration_scopes = sso:account:access
```

**Comment by JadenSimon** [comment]
> What's odd is that the SsoAccessTokenProvider does [check the profile for the region to use when constructing](https://github.com/aws/aws-toolkit-vscode/blob/499ab7025f7587f0326a8d70508dc402f6115adb/src/credentials/sso/ssoAccessTokenProvider.ts#L61) the OidcClient.

Yeah that class will use a region if provided, but we are always using `us-east-1` when creating a connection through the wizard.

> 2022-11-24 21:56:12 [WARN]: AwsContext: no default region in credentials profile, falling back to us-east-1: 

This is likely some other bug. I'll look into fixing it as the legacy auth logic is consolidated.

**Comment by davesc63** [comment]
Similar issue here.
Profile has correct setings for `sso_region = us-west-2` and `region = ap-southeast-2`
Codewhisperer / AWS toolkit creates a grant from` us-east-1`

**Comment by villelahdenvuo** [comment]
Any update on this? I can successfully connect via an SSO profile, but CodeWhisperer refuses to use that and wants me to login again giving the same invalid grant error:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/633524/216035160-f8ceab4a-840a-470f-8b67-d7837059ed6a.png">
<img width="514" alt="image" src="https://user-images.githubusercontent.com/633524/216035206-5f3cc078-bf02-47d4-81f1-8da9aadd9465.png">
<img width="324" alt="image" src="https://user-images.githubusercontent.com/633524/216035261-62403d09-9688-49bd-9b24-b1dbd592240f.png">

**Comment by henalbrod** [comment]
> Any update on this? I can successfully connect via an SSO profile, but CodeWhisperer refuses to use that and wants me to login again giving the same invalid grant error:
> 
> <img alt="image" width="386" src="https://user-images.githubusercontent.com/633524/216035160-f8ceab4a-840a-470f-8b67-d7837059ed6a.png">
> 
> <img alt="image" width="514" src="https://user-images.githubusercontent.com/633524/216035206-5f3cc078-bf02-47d4-81f1-8da9aadd9465.png">
> 
> <img alt="image" width="324" src="https://user-images.githubusercontent.com/633524/216035261-62403d09-9688-49bd-9b24-b1dbd592240f.png">

You need to edit your .aws/config file to use the classic format (before the adding of the session name and stuff) that way the connection appears to be selected in the toolkit.

```
[default]
sso_start_url = https://myapp.awsapps.com/start#/
sso_region = us-east-2
sso_account_id = 123456789
sso_role_name = myapp-rolename
region = us-east-1
output = json
```

**Comment by villelahdenvuo** [comment]
I actually found in the docs that the preview is not available in my region, so I assume that's the reason why it's not working.

**Comment by joshuawwright** [comment]
Looks like the interface needs a way to set the sso region here:

![image](https://user-images.githubusercontent.com/1731346/221258264-2711be8e-52bc-4ead-85f4-faab45b42fb7.png)

**Comment by GergelyMolnar** [comment]
I had the same issue. 
After I changed the AWS region to `us-east-1` and started the IDE registration again the code was accepted and my IDE is now registered. 
You find the AWS menu at the bottom of the JetbrainsIDE window. 

![Screenshot 2023-05-10 at 20 31 27](https://github.com/aws/aws-toolkit-vscode/assets/16977780/5e74a0b5-6dbb-46b8-aec8-ec6af32ec9bc)
