### ISSUE TITLE
Nagging popup for CodeWhisperer appears on every VSCode window launch - even if not in use, cannot be permanently dismissed

### ISSUE THREAD

**Issue by sammcj** [aws/aws-toolkit-vscode#3017]
## Problem

The AWS Toolkit extension has a nagging popup that occurs even when CodeWhisperer is disabled and cannot be permanently dismissed / disabled without removing the extension.

![SCR-20221128-lar](https://user-images.githubusercontent.com/862951/204382138-1e294b6d-0587-44df-8aa5-d75992bd8181.png)

## Steps to reproduce the issue

1. Install the AWS Toolkit extension
2. Ensure CodeWhisperer is disabled 
3. Open a VSCode window
4. Get popup
5. Try to disable pop - there's no option

## Expected behaviour

Any one, or all of:

- Dismiss the popup once and never see it again.
- If CodeWhipserer is not in use, the popup should never appear.
- There should be an option to never show the popup again.

## System details (run the `AWS: About Toolkit` command)

- 
- OS: Darwin arm64 22.1.0
- Visual Studio Code extension host:  1.73.1
- AWS Toolkit:  1.56.0
- node: 16.14.2
- electron: 19.0.17

---

![image](https://user-images.githubusercontent.com/862951/204382979-b1562304-0816-446d-acd7-b09394881893.png)

**Comment by udondan** [comment]
This is highly annoying 😿

**Comment by justinmk3** [comment]
In AWS Toolkit 1.60, this popup now includes a `Don't show again` button.
