### ISSUE TITLE
Not seeing Deploy SAM application 

### ISSUE THREAD

**Issue by jandresmartinez** [aws/aws-toolkit-vscode#3018]
## System details (run the `AWS: About Toolkit` command)

OS: Darwin arm64 21.6.0
Visual Studio Code extension host:  1.73.1
AWS Toolkit:  1.56.0
node: 16.14.2
electron: 19.0.17

## Question

I'm only seeing `Sync SAM Application` and not `Deploy SAM Application`in VSCode

![image](https://user-images.githubusercontent.com/10400786/204395722-d60f6f56-3706-477d-a57c-471dcf883f2d.png)

How can i troubleshoot it?

**Comment by justinmk3** [comment]
`Sync SAM Application` is now the default. You can switch back to the old `Deploy SAM Application` by settings the `aws.samcli.legacyDeploy` setting. But in general, we hope that `Sync SAM Application` is faster for development edit-test cycle, and if you find any issues with it please let us know.

Perhaps `Sync SAM Application` should be renamed to `Sync (Deploy) SAM Application` so one can type "deploy" in the vscode command list to find it?

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/3284 renames the command to `Sync Serverless Application (formerly Deploy)` so that typing "deploy" will find the command in the vscode commands list.
