### ISSUE TITLE
AWS Toolkit 1.58 breaks Lambda debugging

### ISSUE THREAD

**Issue by efremsternbach** [aws/aws-toolkit-vscode#3045]
## Problem
After upgrading to version 1.58 the debugging for python Lambda functions is broken. It can no longer "find" the template file specified in the launch.json file. For my project specifically the log shows

`2022-12-12 10:49:23 [ERROR]: SamLaunchRequestError: Invalid launch configuration: Invalid (or missing) template file (path must be workspace-relative, or absolute): D:\Development\source\repos\GitHub\portfolio-analytics-framework\portfolio_analytics_application\template.yaml [BadLaunchConfig]`

The path indicated is the correct path to the template file.

Downgrading the AWS Toolkit to v1.57 fixes this problem so this is clearly an issue introduced in v1.58

Please investigate.

Thanks

## System details (run the `AWS: About Toolkit` command)

-   OS: Windows 10 Pro 22H2
-   Visual Studio Code version: 1.74

**Comment by JadenSimon** [comment]
Hi @efremsternbach,

Thanks for the bug report! Were you seeing this error consistently on 1.58.0?

**Comment by efremsternbach** [comment]
May have jumped the gun on this. After downgrading to AWS Toolkit 1.57 and then upgrading again to 1.58 it seems to be working now. I did have to manually delete the build directory to get it to work. So I think after all this may have just been some kind of weird cache issue in my VSC application.

Thanks for your prompt reply anyway. You guys make an awesome extension for VSC

**Comment by JadenSimon** [comment]
> I did have to manually delete the build directory to get it to work. So I think after all this may have just been some kind of weird cache issue in my VSC application.

This is possibly related to our own "template registry" implementation. I've noticed inconsistencies with it in the past. I'm closing this issue and tracking improvements in https://github.com/aws/aws-toolkit-vscode/issues/3047
