### ISSUE TITLE
Editing files without extension on S3 changes the Metadata of the object

### ISSUE THREAD

**Issue by esaday** [aws/aws-toolkit-vscode#3055]
## Problem
When editing files without extension, Toolkit mutates the Metadata of the edited object. For instance, I have a file named `some_config` on S3 and its current Metdata for `Content-Type` is `text/plain`. 

When you change the contents of the file and save on VS Code (trigger upload to bucket), it changes the `Content-Type` of the object to `octet-stream`. This made me think the Toolkit is not preserving the current Metadata for the object and fallback to default values.

## Steps to reproduce the issue

1. Go to the `S3` tab in `EXPLORER` in Toolkit.
2. Double Click on any file containing text without the file extension.
3. Make changes and save
4. Check Metadata values for the object through cli or AWS console. 
5. See the `Content-Type` is changed to `octet-stream`

## Expected behavior
Toolkit should preserve the current/available metada of the object being edited.

## System details (run the `AWS: About Toolkit` command)
- OS: Darwin x64 21.6.0
- Visual Studio Code extension host:  1.73.1
- AWS Toolkit:  1.58.0
- node: 16.14.2
- electron: 19.0.17

**Comment by JadenSimon** [comment]
Thanks for the report! This likely affects more than just the file editor feature.

> This made me think the Toolkit is not preserving the current Metadata for the object and fallback to default values.

Yup I just looked at the code and this is exactly what's happening.

**Comment by JadenSimon** [comment]
Should be fixed in 1.61.0. Let us know if you have any more issues!
