### ISSUE TITLE
Debug locally: "ImportError: No module named debugpy"

### ISSUE THREAD

**Issue by marciogoulart** [aws/aws-toolkit-vscode#3075]
## System details (run the `AWS: About Toolkit` command)

-   OS: Microsoft Windows 10
-   Visual Studio Code version: 1.74.2
-   AWS Toolkit version: 1.59.0

## Question

Hi,

I would like support to debug a lambda built in CDK locally in VSCODE.

When I run the lambda via SAM LOCAL INVOKE it works perfectly, but when I add a breakpoint and run it in debug mode, some problems arise.

I performed some tests, the 
[aws_toolkit.log](https://github.com/aws/aws-toolkit-vscode/files/10324928/aws_toolkit.log)
main problem is not finding the debugpy module, but it is attached.

**Comment by marciogoulart** [comment]
lauch.json:

{
"configurations": [
{
"type": "aws-sam",
"request": "direct-invoke",
"name": "CodeverifyLocationLambda",
"invokeTarget": {
"target": "code",
"projectRoot": "VerifyLocationLambda",
"lambdaHandler": "verifyLocationLambda.lambda_handler"
},
"sam": {
"localArguments": [
"--template",
"${workspaceFolder}/NaasVerifyLocationRepository/infra/cdk.out/VerifyLocationFunctionStack.template.json",
"--debug"
]
},
"lambda": {
"runtime": "python3.8",
"memoryMb": 128,
"timeoutSec": 30,
"payload": {
"path": "${workspaceFolder}/NaasVerifyLocationRepository/infra/test.json"
},
"environmentVariables": {
"AWS_PROFILE": "outposts-stage"
},
},
}
]
}

**Comment by justinmk3** [comment]
related:

- https://github.com/aws/aws-toolkit-vscode/issues/2853
- https://github.com/aws/aws-toolkit-vscode/issues/2468

**Comment by arash-cid** [comment]
reopen this 💩 please

**Comment by justinmk3** [comment]
@arash-cid this is tracked in https://github.com/aws/aws-toolkit-vscode/issues/2468
