### ISSUE TITLE
All new regions not supported (9 in total)

### ISSUE THREAD

**Issue by cschnidr** [aws/aws-toolkit-vscode#3084]
## Problem
Currently toolkit supports 21 regions. [See here.](https://github.com/aws/aws-toolkit-vscode/blob/5c77e04d3ff085b950e4671800d6d6093a3a9253/resources/endpoints.json). The missing regions cannot be choosen in the AWS Explorer in the Toolkit.

Is it a valid workaround to edit the referenced endpoints.json above?

The following regions need to be added:
ab-south-2
ap-southeast-3
cn-north-1
cn-northwest-1
eu-central-2
eu-south-2
me-central-1
us-gov-east-1
us-gov-west-1

Check: aws ssm get-parameters-by-path --path /aws/service/global-infrastructure/regions --output json

## Expected behavior

All regions can be selected in the AWS Explorer in the Toolkit.

**Comment by JadenSimon** [comment]
Thanks for opening an issue!

This appears to be a bug as `endpoints.json` in the repo is a backup. The most up-to-date file is supposed to be downloaded automatically.

**Comment by cschnidr** [comment]
Thank you! Can you think of an easy workaround until this is fixed in the code?

**Comment by JadenSimon** [comment]
@cschnidr 

You can manually install a pre-release VSIX which contains the fix: [aws-toolkit-vscode-1.61.0-9ad44f4b88b5.vsix.zip](https://github.com/aws/aws-toolkit-vscode/files/10353954/aws-toolkit-vscode-1.61.0-9ad44f4b88b5.vsix.zip)

Download and unzip the artifact, then run the `Extensions: Install from VSIX...` command from the command palette. Select the VSIX to install and reload VS Code, you should see `1.61.0-9ad44f4b88b5` as the Toolkit version.

**Comment by JadenSimon** [comment]
Fixed in 1.61.0

**Comment by cschnidr** [comment]
@JadenSimon thanks a lot taking care for this! Resource explorer is now showing new regions like Europe (Zurich). However, there are many resources that gives a [Unavailable in region] message. E.g. click the cogwheel on Resources in Resoure Explorer and enable EC2::VPC and EC2::Subnet. For Subnet you get the list of subnets deployed for VPC you get [Unavailable in region] message and this is true for a number of other resources such as EC2::Host for example. Why is that and how can we help to get this resolved?
