### ISSUE TITLE
Fail to login

### ISSUE THREAD

**Issue by Fionawin** [aws/aws-toolkit-vscode#3092]
## System details (run the `AWS: About Toolkit` command)

-   OS: Window11
-   Visual Studio Code version: 1.74.2
-   AWS Toolkit version: v1.60.0

## Question

I have already set the AWS builder but still can not log in normally as the pictures show in the tutorial. Could you give me a hand, please? Thank you.
![image](https://user-images.githubusercontent.com/50728665/211212732-114508e0-1ae7-426a-962a-b43e67c18f51.png)

**Comment by justinmk3** [comment]
Do you have a `.aws/credentials` file in your user home directory? 
 
Can you provide the logs (check that private info is removed)? 

1. In VSCode settings, ensure that "aws log level" is "debug".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View Toolkit Logs` command to get the logs.

**Comment by Aracron** [comment]
I am also getting a failure.  I was coming here to create a new ticket and saw this.  It may be related.  I had previously used the toolkit in VS Code.  I received a new work laptop, and I copied over the .aws folder.  The toolkit in VS 2022 connects fine with my migrated profile.  VS Code fails with log below.  

The log complains about no default region, but I have both region and sso_region set

region=us-west-2
sso_account_id=xxxxxxxxxxxx
sso_region=us-west-2
sso_role_name=xxxxxx
sso_start_url=https://mycomp.awsapps.com/start#/


2023-01-10 07:39:32 [ERROR]: log level: info
2023-01-10 07:39:33 [INFO]: Retrieving AWS endpoint data
2023-01-10 07:39:33 [INFO]: OS: Windows_NT x64 10.0.19045
2023-01-10 07:39:33 [INFO]: Visual Studio Code extension host:  1.74.2
2023-01-10 07:39:33 [INFO]: AWS Toolkit:  1.60.0
2023-01-10 07:39:33 [INFO]: node: 16.14.2
2023-01-10 07:39:33 [INFO]: electron: 19.1.8
2023-01-10 07:39:33 [WARN]: AwsContext: no default region in credentials profile, falling back to us-east-1: 
2023-01-10 07:39:33 [WARN]: CloudFormationTemplateRegistry: addWatchPattern(**/*.{yaml,yml}): no workspace
2023-01-10 07:39:34 [WARN]: CodelensRootRegistry: addWatchPattern(**/requirements.txt): no workspace
2023-01-10 07:39:34 [WARN]: CodelensRootRegistry: addWatchPattern(**/package.json): no workspace
2023-01-10 07:39:34 [WARN]: CodelensRootRegistry: addWatchPattern(**/*.csproj): no workspace
2023-01-10 07:39:34 [WARN]: CodelensRootRegistry: addWatchPattern(**/go.mod): no workspace
2023-01-10 07:39:34 [WARN]: CodelensRootRegistry: addWatchPattern(**/build.gradle): no workspace
2023-01-10 07:39:34 [WARN]: CodelensRootRegistry: addWatchPattern(**/pom.xml): no workspace
2023-01-10 07:41:27 [WARN]: auth (codecatalyst): removing saved connection "codecatalyst.savedConnectionId" as it no longer exists
2023-01-10 07:41:27 [WARN]: auth (codewhisperer): removing saved connection "codewhisperer.savedConnectionId" as it no longer exists
2023-01-10 07:41:48 [ERROR]: _aws.auth.reauthenticate: Error: Unable to authenticate connection
	 -> TypeError: Cannot convert undefined or null to object

**Comment by Fionawin** [comment]
Sorry for the late reply. Here is my log.

2023-01-10 10:05:11 [ERROR]: API request failed: getUserDetails
params: { id: '74385408-5061-70e7-5fbb-f32b1fcd68d5' }
error: {
  message: 'You don’t have permission to perform this operation: GetUserDetails',
  code: 'AccessDeniedException',
  time: 2023-01-10T16:05:11.017Z,
  statusCode: 403,
  retryable: false,
  retryDelay: 61.06969408548226
}
headers: {
  'x-amz-apigw-id': undefined,
  'x-amz-cf-id': 'wp0cL5qDEA6mxkOmjFezV_7BzsNPJvVjG28BZNPWUY7_dlz_76l0xw==',
  'x-amz-cf-pop': 'ORD58-P6',
  'x-amzn-remapped-content-length': undefined,
  'x-amzn-remapped-x-amzn-requestid': undefined,
  'x-amzn-requestid': '2a362c90-8a10-4e76-bb4d-e45ec2da88b0',
  'x-amzn-served-from': 'us-east-2',
  'x-amzn-trace-id': undefined,
  'x-cache': 'Error from cloudfront',
  'x-request-id': undefined
}
2023-01-10 10:05:11 [WARN]: codecatalyst: failed to get Dev Environment: You don’t have permission to perform this operation: GetUserDetails
2023-01-10 10:05:20 [ERROR]: aws.login: TypeError: i.listConnections is not a function

> Do you have a `.aws/credentials` file in your user home directory?
> 
> Can you provide the logs (check that private info is removed)?
> 
> 1. In VSCode settings, ensure that "aws log level" is "debug".
> 2. Perform the steps to reproduce the issue.
> 3. Use the `AWS: View Toolkit Logs` command to get the logs.

**Comment by JadenSimon** [comment]
@Fionawin 

I'm assuming you're trying to use the AWS Explorer, but right now we don't support AWS Builder ID for the explorer. Do you have access to an AWS account (_not_ builder ID)? Valid IAM credentials are needed. Here's a decent starting point if you already have an AWS account: https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html

**Comment by yogendra** [comment]
Are you using SSO? In case you are, you can should copy the `sso_start_url` and `sso_region` from `sso` heading to `profile` heading. 

As an example, following config will not work:
```
# Not Working - configured by 'aws configure sso' command
[profile my-profile]
region = us-east-1
sso_session = sso-1
sso_account_id = ########
sso_role_name = $$$$$$$$$$$$$$

[sso sso-1]
sso_start_url = https://xyz.awsapps.com/start
sso_region = us-west-2
sso_registration_scopes = sso:account:access
```
But this one will work
```
# Working
[profile my-profile]
region = us-east-1
sso_session = sso-1
sso_account_id = ########
sso_role_name = $$$$$$$$$$$$$$
sso_start_url = https://xyz.awsapps.com/start
sso_region = us-west-2

[sso sso-1]
sso_start_url = https://xyz.awsapps.com/start
sso_region = us-west-2
sso_registration_scopes = sso:account:access
```

In the logs I saw an error as follows:
```
2023-01-26 16:32:10 [WARN]: Shared Credentials Profile my-profile is not valid. It will not be used by the toolkit.
```
So, I just copied the values over. I am guessing this is version mismatch betwen aws cli and library used in the aws toolkit.

**Comment by justinmk3** [comment]
> guessing this is version mismatch betwen aws cli and library used in the aws toolkit

AWS CLI in general is more forgiving than the AWS SDKs. This is unfortunately a known inconsistency.

**Comment by jordyjwilliams** [comment]
I was experiencing similar issues to this due to use of `aws-vault`. There could be a chance that a similar solution could be useful here. Using the [credential process](https://github.com/99designs/aws-vault/blob/master/USAGE.md#using-credential_process) in `~/.aws/config` enabled me to get this working as expected.  Solution pulled from [this discussion](https://github.com/aws/aws-toolkit-vscode/issues/164).

**Comment by hasokeric** [comment]
I have the same issue when using AWS CodeWhisperer Public Version released this week.

**Comment by justinmk3** [comment]
Latest Toolkit has many improvements for connecting to AWS Builder Id. The error reported here `AccessDeniedException` should happen less frequently, though it depends on the circumstances. 

There is a separate, unrelated `InvalidGrantException` issue https://github.com/aws/aws-toolkit-vscode/issues/3064 which can cause similar symptoms.

**Comment by sceptapular** [comment]
I'm running in circles for hours and days trying to understand this VSCode/AWSToolkit authentication setup.  I have an account in AWS IAM Identity Center set up.  It's active in VSCode.  (It says 'Connected with IAM Identity Center ([some account ID]' in the top left.)  It has 'full administrator access' to my entire AWS account.  Right below it, it says 'Select IAM credentials to view resources'.  Why is that?  Am I not supposed to authenticate with the SSO option to be more secure over using keys?  Why when I choose to 'create a connection profile' it asks for keys?  I used to have the traditional key-based profile set up and had the list of my AWS resources there, but AWS says to use SSO for best security so I'm trying that.

**Comment by justinmk3** [comment]
> I have an account in AWS IAM Identity Center set up. It's active in VSCode. (It says 'Connected with IAM Identity Center ([some account ID]' in the top left.) It has 'full administrator access' to my entire AWS account. Right below it, it says 'Select IAM credentials to view resources'.

@sceptapular you're on the right path, the wording is somewhat confusing. After you've `Connected with IAM Identity Center` , there is a second step, which is to choose IAM credentials that are auto-discovered by AWS Toolkit from your SSO org. Just click `Select IAM credentials to view resources` (or click the AWS statusbar) to see what credentials were found; the list will show _both_ credentials found locally as well as in the connected SSO org.

**Comment by sceptapular** [comment]
Thank you, thank you, thank you!  I thought it was either/or SSO or IAM,
didn't realize I still had to choose the IAM credentials.  My
conceptualization of the whole authentication chain admittedly isn't
crystal yet.

**Comment by BastienFaure** [comment]
Hello, I am facing a similar issue. Just tried to open CodeCatalyst through VS Code, and auth'ing with AWS Builder ID. It fails with a `AccessDeniedException`, see the error log extract below:
```  
2024-02-22 16:05:18 [ERROR]: API request failed (time: 384ms): getUserDetails
params: { id: '44683498-e011-7065-e2cf-507cee617214' }
error: {
  message: 'You don’t have permission to perform this operation: GetUserDetails',
  code: 'AccessDeniedException',
  '[__type]': 'See error.__type for details.',
  time: 2024-02-23T00:05:18.772Z,
  statusCode: 403,
  retryable: false,
  retryDelay: 32.11226322239842
}
headers: {
  'x-amzn-requestid': '0fd9f4a0-eaa7-413e-8b81-694b4bc628d8',
  'x-amzn-trace-id': undefined,
  'x-amzn-served-from': 'us-west-2,us-west-2',
  'x-cache': 'Error from cloudfront',
  'x-amz-cf-id': 'hNfScg1DLZa0-u72sQVKb56ttD3V-KBj8gTPl7Ebvjph6xkPnLnnig==',
  'x-amz-cf-pop': 'SFO5-P1'
}
2024-02-22 16:05:18 [ERROR]: aws.codecatalyst.openDevEnv: Error: CodeCatalyst: AccessDeniedException [AccessDeniedException]
	 -> AccessDeniedException: You don’t have permission to perform this operation: GetUserDetails (statusCode: 403; requestId: 0fd9f4a0-eaa7-413e-8b81-694b4bc628d8)
2024-02-22 16:05:29 [INFO]: telemetry: sent batch (size=3)

```

**Comment by justinmk3** [comment]
@BastienFaure have you completed the "sign up" process for CodeCatalyst?

**Comment by BastienFaure** [comment]
@justinmk3 I was about to write an update earlier this morning. I guess no, I had my Amazon Builder ID but I had not "enabled" CodeCatalyst for my account.

Definitely a manipulation error on my end but it could benefit a little bit more clarity rather than just the access error exception.
