### ISSUE TITLE
Step Functions Distributed Map definition is not recognized 

### ISSUE THREAD

**Issue by wagneraw** [aws/aws-toolkit-vscode#3094]
## Problem

When working with a State Machine definition that contains a distributed map, the plugin doesn't recognize the new state names and parameters for distributed map

![image](https://user-images.githubusercontent.com/20321937/211667732-4bd37871-971d-4b84-b169-f8153f4ed620.png)

## Expected behavior

Distributed Map shouldn't be reported as an error and the visualization should build similar to how it looks in the console

## System details (run the `AWS: About Toolkit` command)

- OS: Darwin arm64 21.6.0
- Visual Studio Code extension host:  1.74.3
- AWS Toolkit:  1.60.0
- node: 16.14.2
- electron: 19.1.8

**Comment by justinmk3** [comment]
Fixed in AWS Toolkit 1.63
