### ISSUE TITLE
Streamline deployment usability

### ISSUE THREAD

**Issue by micholas** [aws/aws-toolkit-vscode#310]
**Is your feature request related to a problem? Please describe.**
As a user when I re-deploy the same application, I have to type in the S3 bucket and CloudFormation template name over and over every time. This is tedious the point that it is difficult to imagine a user preferring this user experience to simply scrolling in command line history and ignoring this extension capability.

**Describe the solution you'd like**

As a user, I'd like to specify the CloudFormation stack name and S3 bucket once per SAM application and have it be a default from that point forward when re-deploying the same SAM app. Consider doing this during project initialization. Consider user experience of [serverless deploy](https://serverless.com/framework/docs/providers/aws/guide/quick-start/) and [amplify publish](https://aws-amplify.github.io/media/toolchain).

**Describe alternatives you've considered**

1. Specify S3 bucket and CloudFormation template name during project initialization.
2. Remember the S3 bucket and CloudFormation template name entered during 1st deployment and re-use it as the default for future deployments.

**Additional context**

**Comment by awschristou** [comment]
Closing this issue in favor of #1052
