### ISSUE TITLE
aws toolkit i am unable to config the aws toolkit extension in visual studio cde

### ISSUE THREAD

**Issue by Rk-1169123** [aws/aws-toolkit-vscode#3120]
## System details (run the `AWS: About Toolkit` command)

-   OS:
-   Visual Studio Code version:
-   AWS Toolkit version:

**Comment by Rk-1169123** [comment]
i try to use aws toolkit extension in visual studio code . i install the aws toolkit but unable to config and getting unable to authenticate connection

**Comment by justinmk3** [comment]
Does AWS CLI work? E.g.

    aws s3 ls

Can you provide the logs (check that private info is removed)? 

1. In VSCode settings, ensure that "aws log level" is "debug".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View Toolkit Logs` command to get the logs.
