### ISSUE TITLE
User is able to access general Explorer features without using the Command Palette to increase discoverability

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#313]
This came from internal feedback and UX Review discussions.

Some of the first interactions with the Toolkit revolve around the Explorer: connecting with credentials, and deciding which regions to show in the Explorer. It should be possible to access these directly from the Explorer.

Acceptance Criteria:
* The Explorer has button with either a gear icon or an ellipsis icon, which opens a menu when pressed. It is beside the current Refresh button
* the menu contains the following actions:
  * Show region in Explorer (command already exists)
  * Hide region in Explorer (command already exists)
  * Connect to AWS (command already exists)
  * Help (should open our docs page. If docs are not posted yet, open https://aws.amazon.com/visualstudiocode/ instead)

Here is a reference, using the [GitLens](https://github.com/eamodio/vscode-gitlens) extension as an example:
![image](https://user-images.githubusercontent.com/39839589/53506264-7a0b0e00-3a6a-11e9-8692-67a7121a327f.png)

**Comment by bryceitoc9** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/333
