### ISSUE TITLE
asl format doesn't allow Credentials key

### ISSUE THREAD

**Issue by Fryguy** [aws/aws-toolkit-vscode#3152]
## Problem

When viewing an .asl file for Amazon States Language, a `Credentials` key is considered an error.  According to the [ASL spec](https://states-language.net/#task-state):

> A Task State MAY include a "Credentials" field, whose value MUST be a JSON object whose value is defined by the interpreter. The States language does not constrain the value of the "Credentials" field. The interpreter will use the specified credentials to execute the work identified by the state's "Resource" field.

Additionally, the [Step Functions docs for Task](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-task-state.html#task-state-fields) show that Credentials is an Optional field.

So, I think the language should be allowing a Credentials key regardless of its content.

## Steps to reproduce the issue

Example ASL file:

```json
{
  "Comment": "Sample ASL",
  "StartAt": "FirstState",
  "States": {
    "FirstState": {
      "Type": "Task",
      "Resource": "arn:xxx",
      "End": true,
      "Credentials": {
        "user": "$.user",
        "password": "$.password"
      }
    }
  }
}
```

## Expected behavior

Expected this .asl to be valid and thus graphable.  Current output looks like this:

![Fullscreen_2_7_23__9_52_AM](https://user-images.githubusercontent.com/52120/217279008-e9764387-fe6b-4e3c-b9e7-9f9458b830c3.png)

## System details (run the `AWS: About Toolkit` command)

OS: Darwin x64 21.6.0
Visual Studio Code extension host:  1.73.1
AWS Toolkit:  1.62.0
node: 16.14.2
electron: 19.0.17

cc @agrare

**Comment by agrare** [comment]
Confirmed I am no longer seeing a syntax error for ASL files with `Credentials` fields on the latest toolkit version :+1:
