### ISSUE TITLE
Add credential_process support

### ISSUE THREAD

**Issue by tahoward** [aws/aws-toolkit-vscode#317]
**Is your feature request related to a problem? Please describe.**
For Enterprises using SAML based authentication against AWS through services like Okta there is no seamless fully integrated way to assume a role in AWS using AWS VS Toolkit.

**Describe the solution you'd like**
Support for interpreting a profile's `credential_process` parameter in `~/.aws/credentials`

Please see:
* [BOTOCORE](https://github.com/boto/botocore/pull/1316)
* [AWS CLI](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes)
* [AWS-SDK-JAVA](https://github.com/aws/aws-sdk-java/pull/1835)
* [AWS-SDK-GO](https://github.com/aws/aws-sdk-go/pull/2217)
* [AWS-IAM-AUTHENTICATOR](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/182)
* [AWS-SDK-JS](https://github.com/aws/aws-sdk-js/pull/1923)

**Describe alternatives you've considered**
Using a scheduled task to run external process for refreshing session token and injecting a static profile into `~/.aws/credentials`.

I did a cursory glance but did not identify if this is built on top of aws-sdk-net. If so I'll submit the appropriate feature request there as well.

**Comment by awschristou** [comment]
Thank you for the request @tahoward , the Toolkit for VS Code is developed in Typescript, currently using V2 of the AWS SDK for Javascript. The SDK does not appear to support `credential_process` at this time.

**Comment by awschristou** [comment]
@tahoward I had a chat with someone from the JS SDK team. It sounds like `credential_process` support is being looked into. If/when it is released into the SDK, we will be able to investigate further for the Toolkit.

**Comment by tahoward** [comment]
@awschristou Thanks for looking into!

**Comment by MetricMike** [comment]
Just wanted to ping that `credential_process` was released with [v2.429.0](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#24290) this week.

**Comment by mpiroc** [comment]
If I understand correctly, all that we need to do is bump our dependency on `aws-sdk` to `>2.429.0`, and we will get `credential_process` support for free.

**Comment by MetricMike** [comment]
That's my understanding as well, though the current  requirement in `package.json` is just on the major version, so a build/release should be all that's needed.

**Comment by bryceitoc9** [comment]
Took a quick look and we'll need to refactor our credential handling--right now, we're handling credentials rather than profiles. This change should be relatively quick once we move to profile handling.

**Comment by awschristou** [comment]
Today version 1.1.0 of the Toolkit has been released, which includes credential_process support.
