### ISSUE TITLE
AWS SAM: Property FunctionUrlConfig is not allowed

### ISSUE THREAD

**Issue by HenriqueSoares47** [aws/aws-toolkit-vscode#3194]
## Problem

hello
I'm using template to create lambda function AWS sam in VSCode.
I have an error validating the schema when I use the FunctionUrlConfig option
## Steps to reproduce the issue

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  recevied-status-lambda

  Sample SAM Template for recevied-status
Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Handler: github.com/dafiti-group/recevied-status-lambda
    Runtime: go1.x
    Architectures:
      - x86_64
    Tracing: Active
    Environment:
      Variables:
        AWS_REGION: us-east-1
        ENVIRONMENT: local
  Api:
    TracingEnabled: True
Resources:
  ReceviedStatusFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: recevied-status
      CodeUri: src/lambdas/
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowHeaders:
            - "*"
          AllowMethods:
            - "POST"
          AllowOrigins:
            - "https://www.example.com"
      Environment:
        Variables:
          ENV1: Value
      DeploymentPreference:
        Enabled: true
        Type: Linear10PercentEvery1Minute
```

**The problem message is: Property FunctionUrlConfig is not allowed.**

![image](https://user-images.githubusercontent.com/85643203/221653651-f50fc32b-5d8f-43dd-ab8f-96c3be655d69.png)

## Expected behavior
Updated SAM schema to accept FunctionUrlConfig

## System details (run the `AWS: About Toolkit` command)

-   OS: Ubuntu 18.04 LTS
-   Visual Studio Code version:  1.75.1
-   AWS Toolkit version: v1.63.0

**Comment by justinmk3** [comment]
Are you still seeing this issue?

AWS Toolkit 1.65+ includes an updated SAM/CFN json-schema from : 
https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json

**Comment by HenriqueSoares47** [comment]
After the update we are no longer having the problem.
