### ISSUE TITLE
vscode using a lot of CPU

### ISSUE THREAD

**Issue by caiorhian** [aws/aws-toolkit-vscode#3197]
Type: <b>Bug</b>

Based on a extension bisect report, it indicates that this extension is causing huge CPU spikes to happen, looking to the activity monitor looks like an rg process is spiking and using a lot of cpu.

Extension version: 1.63.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 19, 24|
|Memory (System)|16.00GB (0.42GB free)|
|Process Argv|--crash-reporter-id b8a1cee2-e0b0-4cf5-8869-c6660243d839|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30669238
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30662444

```

</details>

**Comment by JadenSimon** [comment]
Possibly related: https://github.com/aws/aws-toolkit-vscode/issues/2327

**Comment by justinmk3** [comment]
AWS Toolkit 1.73 (next release) will include https://github.com/aws/aws-toolkit-vscode/pull/3445 which improves performance if the `aws.samcli.enableCodeLenses` setting is disabled.

**Comment by justinmk3** [comment]
AWS Toolkit 1.96 also includes some recent performance improvements.

We are continuing to work other performance improvements, including startup time. https://github.com/aws/aws-toolkit-vscode/labels/performance
