### ISSUE TITLE
sam.schema.json: ResourcePolicy: CloudFormation construct not recognized

### ISSUE THREAD

**Issue by mattgillard** [aws/aws-toolkit-vscode#3199]
## Steps to reproduce the issue

when specifying ResourcePolicy: in a AWS::Serverless::Api resource I get a validation error:
`Property ResourcePolicy is not allowed.yaml-schema: aws://sam.schema.json`

```
ApiGateway:
    Type: AWS::Serverless::Api
    DependsOn: ApiCWLRoleArn
    Properties:
      EndpointConfiguration: 
        Type: PRIVATE
        VPCEndpointIds: 
          - !Ref APIGWVPCEndpoint
      Name: !Ref apiName
      StageName: "Prod"
      TracingEnabled: True
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './api.yml'
     Auth:
        DefaultAuthorizer: AADAuthoriser
        ResourcePolicy: #Property ResourcePolicy is not allowed.yaml-schema: aws://sam.schema.json
          IntrinsicVpceWhitelist:
            - !Ref APIGWVPCEndpoint
```

## Expected behavior

- validation error should not pop up

## System details (run the `AWS: About Toolkit` command)

Desktop (please complete the following information):
OS: MacOS 13.1 (Ventura)
Visual Studio Code Version: v1.75.1
AWS Toolkit Version: v1.63.0

**Comment by justinmk3** [comment]
Are you still seeing this issue?

AWS Toolkit 1.65+ includes an updated SAM/CFN json-schema from : 
https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json
