### ISSUE TITLE
Improve "Create New SAM Application" Wizard so users can understand the prompts better

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#320]
The wizard needs titles for proper descriptive explanations. 
The current "title" text is placed in the placeholder location, which disappears when you start filtering the selection box.

[createInputBox](https://code.visualstudio.com/api/references/vscode-api#window) will be required. Bonus marks if reusable for other wizards.

* Wizard uses [InputBox](https://code.visualstudio.com/api/references/vscode-api#InputBox) `title` instead of `prompt` and `placeholder`. The title text is rephrased as necessary to explain each step clearly
* Wizard has a [back](https://code.visualstudio.com/api/references/vscode-api#QuickInputButtons) button to navigate back a step (in addition to `Esc`).
* Navigating back a step defaults to the previously selected value

Example showing title in the placeholder section. It disappears as you type to filter runtime
![image](https://user-images.githubusercontent.com/39839589/53534662-b2373e80-3ab4-11e9-92cb-dc3346ebc3f0.png)

**Comment by bryceitoc9** [comment]
PR: https://github.com/aws/aws-toolkit-vscode/pull/364
