### ISSUE TITLE
S3 "Edit" feature treats paths as case-insensitive

### ISSUE THREAD

**Issue by baijudodhia** [aws/aws-toolkit-vscode#3276]
## Problem
I have 2 folders in my S3 bucket (Test and test). Both these folders have a file main.json each. By default the folders are sorted such that "Test" bucket is above "test" bucket. When I click the edit icon for test/main.json it opens Test/main.json which is a different file.

My folder and file structure inside s3 (notice difference in case for first letter in folder names) -

**bucket1/Test/main.json
bucket1/test/main.json**

## Steps to reproduce the issue

1. Create a bucket in S3.
2. Create 2 folders with same name with different case for first letter. (Test and test)
3. Add 2 files main.json in both the folder with different content inside both these files.
4. Try to edit **bucket1/test/main.json** but it opens **bucket1/Test/main.json** instead.
 
## Expected behavior

If I try to open or edit **bucket1/test/main.json** then it should open that file only and not the file from **bucket1/Test/main.json**

## System details (run the `AWS: About Toolkit` command)

OS: Windows_NT x64 10.0.22621
Visual Studio Code extension host:  1.76.2
AWS Toolkit:  1.66.0
node: 16.14.2
electron: 19.1.11

**Comment by justinmk3** [comment]
Fixed in AWS Toolkit 1.67

Thank you for reporting this!
