### ISSUE TITLE
F5 build lambda from a template in a container then locally debug

### ISSUE THREAD

**Issue by IRIElogic** [aws/aws-toolkit-vscode#3281]
## System details (run the `AWS: About Toolkit` command)

-   OS: Windows_NT  x64 10.0.19045
-   Visual Studio Code version: 1.76.2
-   AWS Toolkit version: 1.66.0
-  Node 16.14.2
- electron 19.1.11
-   Python version: 3.9.13
-   Docker version: 4.17.1  

## Question

I am attempting to get VSCode to build a lambda from a template in a container to properly simulate the true lambda environment and then interactively debug that environment.

Within VSCode I am hitting F5 to perform the build (in the docker container) and then invoke the debugger as is available when resolving dependencies locally and invoking

To reproduce the issue I have taken the helloworld toolkit sample and changed the lambda directives from:

      CodeUri: hello_world/
      Handler: app.lambda_handler
TO

      PackageType: Image
      ImageUri: "hello_world/app.lambda_handler"

In order to invoke the build in docker rather than windows

I have also added metadata to the lambda template

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hello_world
      DockerTag: v1

and finally added a DockerFile:

FROM public.ecr.aws/lambda/python:3.9
COPY app.py requirements.txt ./
RUN python3.9 -m pip install -r requirements.txt -t .
  Command can be overwritten by providing a different command in the template directly.
CMD ["app.lambda_handler"]

The build in the container works fine its just when it comes to starting the debugger I get

START RequestId: 2d49accc-b62c-480b-915a-8486dd7ff6ba Version: $LATEST
SyntaxError: Non-UTF-8 code starting with '\x96' in file /var/lang/bin/python3.9 on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details
28 Mar 2023 03:20:47,799 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 1 InvokeID=
SyntaxError: Non-UTF-8 code starting with '\x96' in file /var/lang/bin/python3.9 on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details
END RequestId: d1b6a8cf-6366-40c4-ab76-261ba78bfa74

mentioning an encoding conflict

I have attached a zip of the project, the complete build output and the logfile I am pointed to after I receive a popup dialog from VSCode saying

connect ECONNREFUSED 127.0.0.1:5858

which apears 10 times before giving you the option to view the aforementioned log (aws_toolkit_20230328T161904.log).

## To Reproduce

1. Unzip the attached zip
2. Open the folder in VSCode
3. Start Docker Desktop if not already running
4. Hit F5

 
[AWSToolkit_HelloWorld.zip](https://github.com/aws/aws-toolkit-vscode/files/11085146/AWSToolkit_HelloWorld.zip)
[aws_toolkit_20230328T161904.log](https://github.com/aws/aws-toolkit-vscode/files/11085147/aws_toolkit_20230328T161904.log)
[VSCode_Output.txt](https://github.com/aws/aws-toolkit-vscode/files/11085148/VSCode_Output.txt)

**Comment by justinmk3** [comment]
> SyntaxError: Non-UTF-8 code starting with '\x96' in file /var/lang/bin/python3.9 on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

This is strange. AWS Toolkit does not modify `/var/lang/bin/python3.9`. When starting run/debug--for packagetype=image only (not packagetype=zip)--we [specify](https://github.com/aws/aws-toolkit-vscode/blob/e0b432efee42e722bce1c5c3858d51c72aaad15a/src/shared/sam/debugger/pythonSamDebug.ts#L258) `sam --debug-args` as:

    sam --debug-args "/var/lang/bin/python3.9 /var/runtime/bootstrap.py"


ref: https://github.com/aws/aws-toolkit-vscode/blob/e0b432efee42e722bce1c5c3858d51c72aaad15a/src/shared/sam/debugger/pythonSamDebug.ts#L105-L108

Just taking python's error message at face value, I wonder if `public.ecr.aws/lambda/python:3.9` has provided an invalid  `/var/lang/bin/python3.9`. For troubleshooting, could you try the python3.10 image instead?

**Comment by justinmk3** [comment]
Using the attached zip I can reproduce the issue (thank you!). 

Creating a new python3.9 packagetype=image app with `sam --init` or AWS Toolkit's `AWS: Create Lambda SAM Application` command, I can't reproduce the issue.

So I strongly suspect this is related to one or more files encoded as Windows-1252 (cp1252) charset, which doesn't work with the Linux version of python (which runs in the container). 

The `starting with '\x96' in file /var/lang/bin/python3.9 on line 2` error message is misleading.
