### ISSUE TITLE
support [sso-session] section of config file

### ISSUE THREAD

**Issue by dansrogers** [aws/aws-toolkit-vscode#3322]
## Problem

Newer versions of awscli support [sso-session](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configure/sso-session.html) in the configuration file.  This is a way to store the same sso_start_url, sso_region, and sso_registration_scopes across several different profiles.

This indirection is not supported by aws-toolkit-vscode.

## Expected behavior

The following config would be a valid profile:
```
[profile profile1]
sso_session = mycompanysso
sso_account_id = XXXX
sso_role_name = XXXX

[sso-session mycompanysso]
sso_start_url = https://xxxx.awsapps.com/start/
sso_region = us-east-1
sso_registration_scopes = sso:account:access
```
But this does not work.  I get a log message that says that profile1 is not valid (in fact the UI won't even prompt me to select a profile, since it's rejected profile1 for missing sso_start_url)

**Comment by justinmk3** [comment]
This will be addressed in the next release. https://github.com/aws/aws-toolkit-vscode/pull/3317

Thanks for taking the time to report it!

**Comment by justinmk3** [comment]
Supported in AWS Toolkit 1.68
