### ISSUE TITLE
Ability to disable CodeWhisperer

### ISSUE THREAD

**Issue by timfallmk** [aws/aws-toolkit-vscode#3329]
## Problem
We used to be able to disable Codewhisperer (but not the whole extension) under "AWS > experiments" but this option has been removed (I assume because it's no longer an experiment).
<img width="956" alt="image" src="https://user-images.githubusercontent.com/5316117/231875293-6a3c263c-db40-42f1-8a15-63724eb10496.png">

My organization is not legally allowed to use Codewhisperer, but we can't disable just that feature without disabling the entire extension. Can we get some way of turning this off?

It would be great if it also removed highly annoying highlighted footer as well.
<img width="167" alt="image" src="https://user-images.githubusercontent.com/5316117/231875389-a2643f28-7398-4cb8-9f72-98b3f052f6cd.png">

## Expected behavior
Ability to disable entire Codewhisperer feature via settings.

**Comment by JadenSimon** [comment]
> My organization is not legally allowed to use Codewhisperer, but we can't disable just that feature without disabling the entire extension. Can we get some way of turning this off?

Seems reasonable, and I think being able to selectively turn off components would be nice in the resource explorer as well.

> It would be great if it also removed highly annoying highlighted footer as well.

Looks like a bug to me. It shouldn't be showing if you're not using the feature.

**Comment by George-B-Simpson** [comment]
Ugh, came here looking for how to get rid of that footer.

Guess I'll just knock AWS Toolkit out of there entirely for now.

**Comment by dark-penguin** [comment]
@timfallmk On which version were you able to disable it? I've downgraded all the way to 1.59.0, and there is still no option to disable it. The "CodeWhisperer release" commit was two days ago, so I thought rolling it back would help, but no, even downgrading does not help.

**Comment by timfallmk** [comment]
It was quite some time ago, I'm afraid I don't have a version number. The entire extension was "experimental" at that point.

**Comment by timfallmk** [comment]
@justinmk3 What specifically do you mean when you say "not signed in"? To AWS, To Codewhisperer? If it's AWS at all, then what's the point of keeping the extension on, as it's the same as disabling the entire thing.

**Comment by timfallmk** [comment]
@justinmk3 Thanks for pointing that out, I was not aware of it. I don't think it solves the problem though, as an explicit opt-in "enable" feature checkbox would clarify that CodeWhisperer is not currently active, nor _has ever been activated_. The latter is important for a legal compliance perspective, aside from being good practice.

It's not clear to me (and I think others are in the same position) that clicking that button is the difference between codewhisperer being "on" and "off". For example, I still am able to run commands from the command pallet for CW and be told things like "this language is not supported". That would suggest to me that at least some set of CW functionality is "on".

This would also possibly make it easier to solve the UI display bug.

**Comment by justinmk3** [comment]
> an explicit opt-in "enable" feature checkbox ... important for a legal compliance perspective

Didn't consider that, thanks for mentioning it.

> aside from being good practice

True. We're also trying to avoid unnecessary configuration where possible, but need to revisit this case.

**Comment by ZebraFlesh** [comment]
> So there should be no performance or UI cost, thus no need to disable it?

The annoyingly highlighted "CodeWhisperer" portion of the status bar enrages me and I want to burn it to the ground. I did not ask for advertising, nor do I want it. In the end, I've uninstalled the AWS Toolkit extension and will use the good old CLI. Being able to disable that annoying crap would return control of my IDE to me.

**Comment by justinmk3** [comment]
> The annoyingly highlighted "CodeWhisperer" portion of the status bar enrages me and I want to burn it to the ground.

We do plan to fix that.

Please avoid comments that don't add new information to this discussion.

**Comment by spencerthayer** [comment]
I don't believe sign is working correctly. No matter what I do I see `Select IAM Credentials to View Resources`. 

![image](https://user-images.githubusercontent.com/1019815/234938244-65a98fb9-6df5-4ffa-94a6-11d8d9fd880e.png)

**Comment by justinmk3** [comment]
`Select IAM Credentials to View Resources` is for AWS Explorer, not CodeWhisperer.

CodeWhisperer sign-in is available in the `Developer Tools` panel. If you don't see that panel, right-click on vscode to enable it: 
<img width="464" alt="image" src="https://user-images.githubusercontent.com/55561878/234943589-af61459f-c194-497c-ab6c-1c939182ec7b.png">

**Comment by acdha** [comment]
> > an explicit opt-in "enable" feature checkbox ... important for a legal compliance perspective
> 
> Didn't consider that, thanks for mentioning it.

I wanted to second this request: we have the same challenge of not wanting people to use it until our organization's policies allow it. The latest update to the toolkit changed it so that it now shows up in the status bar next to the profile selector and when VSC starts it opens the “CodeWhisperer Reference Log” panel without prompting. Based on the age of #3421 this makes me wonder whether something changed in the process of how it detects use of that feature since nothing changed in the AWS account I'm using and it's correctly detected that I don't have it enabled.

I'd also really strongly recommend make the “share with AWS setting” disabled by default with an explicit prompt (“Enable and Share”, “Enable”, “Disable”)  – that seems like an unnecessary tech press furor cycle in the making and I'd imagine it loses most of the legal weight.

**Comment by justinmk3** [comment]
> not wanting people to use it until our organization's policies allow it.

If your org can block traffic `codewhisperer.us-east-1.amazon.com`, that will block all CodeWhisperer functionality. That is the current recommended workaround.

**Comment by justinmk3** [comment]
Amazon Q and its "inline suggestion" features (formerly CodeWhisperer) is now a separate [Amazon Q extension](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.amazon-q-vscode).
