### ISSUE TITLE
Unable to connect AWS CodeWhisperer from VS Code

### ISSUE THREAD

**Issue by arnabnandy7** [aws/aws-toolkit-vscode#3335]
## Steps to reproduce the issue

1. In the AWS Toolkit for Visual Studio Code, under Developer tools, under CodeWhisperer, select Start. A dropdown menu will appear at the top of VS Code.
2. From the dropdown menu, select Use a personal email to sign up and sign in with AWS Builder ID
3. At the prompt Copy Code for AWS Builder ID. To proceed, open the login page and provide this code to confirm the access request: XXXX-XXXX
4. Upon clicking Copy to clipboard, it continously searching for the login page and the action but nothing appears in any browser and it gets timed out after certain time.
![image](https://user-images.githubusercontent.com/5053648/232221194-cc810355-171e-4543-b515-f62ab787afdf.png)

## Expected behavior
1. In the AWS Toolkit for Visual Studio Code, under Developer tools, under CodeWhisperer, select Start. A dropdown menu will appear at the top of VS Code.
2. From the dropdown menu, select Use a personal email to sign up and sign in with AWS Builder ID
3. At the prompt Copy Code for AWS Builder ID. To proceed, open the login page and provide this code to confirm the access request: XXXX-XXXX
4. Upon clicking Copy to clipboard, it should open login page where I should submit the code to confirm.

## System details (run the `AWS: About Toolkit` command)

-   OS: Windows 10
-   Visual Studio Code version: 1.77.3
-   AWS Toolkit version: 1.68.0

**Comment by awsanakkala** [comment]
@arnabnandy7 - It is unusual that nothing opened in a browser. Can you please try again after restarting the IDE or browser windows and let us know.? These steps shouldn't be needed but it will help us troubleshoot.

**Comment by arnabnandy7** [comment]
@awsanakkala you were right somehow it was not able to open the browser window since it was already opened. Now it's enabled and tested as well.
![image](https://user-images.githubusercontent.com/5053648/232228742-cbb22122-68e7-43c2-882f-34de627f94cb.png)
