### ISSUE TITLE
Toolkit is not usable when remote endpoints.json resource is not reachable

### ISSUE THREAD

**Issue by adnanalawiyat** [aws/aws-toolkit-vscode#3338]
## Problem
On startup, the extension makes a remote call to  https://idetoolkits.amazonwebservices.com/endpoints.json in [EndpointsProvider#load](https://github.com/aws/aws-toolkit-vscode/blob/v1.68.0/src/shared/regions/endpointsProvider.ts#L22). In an environment where https://idetoolkits.amazonwebservices.com/endpoints.json is blocked by firewall, the toolkit is unusable

## Steps to reproduce the issue

- block `idetoolkits.amazonwebservices.com` by a firewall rule
- start VSCode with AWS Toolkit installed
- the toolkit will get stuck waiting for https://idetoolkits.amazonwebservices.com/endpoints.json to return
- regions dropdown will be empty, with the following in the logs:

```
[WARN]: Unable to determine the Partition that Region us-east-1 belongs to
```

## Expected behavior

The extension should first load local endpoints.json and dynamically update with the result of remote call once it receives a response. Or there should be a reasonable timeout for https://idetoolkits.amazonwebservices.com/endpoints.json, which currently appears to never timeout after waiting for 30 minutes

## System details (run the `AWS: About Toolkit` command)

OS: Darwin x64 20.6.0
Visual Studio Code extension host:  1.77.3
AWS Toolkit:  1.67.0
node: 16.14.2
electron: 19.1.11

**Comment by justinmk3** [comment]
Fixed in AWS Toolkit 1.69
