### ISSUE TITLE
CodeWhisperer requires clicking "AWS" extension to connect

### ISSUE THREAD

**Issue by romanholidaypancakes** [aws/aws-toolkit-vscode#3348]
## Problem
currently, we must manually connect the aws id

**Comment by justinmk3** [comment]
> I need to click on the AWS Extension button.

Ok, yes, this is a known issue for CodeWhisperer features. We're working on it. 

Thanks for the report!

**Comment by JadenSimon** [comment]
Fixed in v1.70.0
