### ISSUE TITLE
Audit Toolkit Configuration, migrate some to Extension State

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#336]
There are likely some extension configuration settings that should reside in [global state](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext). Before releasing to Marketplace, the team should decide which (if any) should be migrated, and make the appropriate changes.

* any Toolkit configurations that aren't something that should be actionable to or manipulated by a user are moved out of configuration settings
* if things are moved to global state, a command exists that can be used to reset the global state (so that users wouldn't have to resort to uninstalling in order to "reset" things

**Comment by bryceitoc9** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/417

**Comment by bryceitoc9** [comment]
PR merged, but this has brought renewed focus to an existing issue (region order isn't persisting). Logged the bug and asking for feedback here: https://github.com/aws/aws-toolkit-vscode/issues/421
