### ISSUE TITLE
CodeWhisperer: Not able to generate code suggestion on line 2 from typing "# print Hello World" by typing Option-C on a new test.py file's line 1 

### ISSUE THREAD

**Issue by vincentquero** [aws/aws-toolkit-vscode#3365]
## System details (run the `AWS: About Toolkit` command)

-   OS: 13.2.1 (22D68)
-   Visual Studio Code version: Version: 1.77.3 (Universal)
-   AWS Toolkit version: v1.70.0

## Question

Hi guys, 

Im not able to get code suggestion on line 2 from typing "# print Hello World" by typing Option-C on a new test.py file's line 1 as I was explained it needed to be done. It says I'm logged in and I'm getting a message that says that the request is not recognised... 

<img width="1169" alt="Screenshot 2023-04-22 at 09 28 48" src="https://user-images.githubusercontent.com/58186276/233769916-21fabc34-cd10-4255-8735-1369ac447623.png">

Can you please help and email me your answer on querovincent@gmail.com ?

Regards, 
Vincent

**Comment by stondo** [comment]
same here

**Comment by andrewyuq** [comment]
Hi @vincentquero , you want to login to CodeWhisperer first since it shows not logged in yet. I would suggest to get the latest plugin since we have fixed a bunch of issues in the last month, and login to CodeWhisperer (click on the left `aws` icon to start)
