### ISSUE TITLE
SAM: failed to run: "python3.10 runtime is not supported"

### ISSUE THREAD

**Issue by Rybalochka-MS** [aws/aws-toolkit-vscode#3381]
## Problem
Hi there, I trying to locally run a Lambda function for Python 3.10. Previously I update all requirements: AWS SAM CLI, AWS CLI, CloudFormation template. But I got a `Error: 'python3.10' runtime is not supported` error.

Full output log:

> 2023-04-26 10:38:53 [ERROR]: log level: info
> 2023-04-26 10:38:53 [INFO]: endpoints: retrieving AWS endpoints data
> 2023-04-26 10:38:53 [INFO]: OS: Darwin arm64 22.2.0
> 2023-04-26 10:38:53 [INFO]: Visual Studio Code extension host:  1.77.3
> 2023-04-26 10:38:53 [INFO]: AWS Toolkit:  1.70.0
> 2023-04-26 10:38:53 [INFO]: node: 16.14.2
> 2023-04-26 10:38:53 [INFO]: electron: 19.1.11
> 2023-04-26 10:40:38 [INFO]: SAM CLI location: [object Object]
> 2023-04-26 10:40:38 [INFO]: SAM CLI location: [object Object]
> 2023-04-26 10:40:39 [INFO]: SAM CLI location: [object Object]
> 2023-04-26 10:40:39 [INFO]: Preparing to debug locally: Lambda "app.lambda_handler"
> 2023-04-26 10:40:39 [INFO]: Building SAM application...
> 2023-04-26 10:40:39 [INFO]: SAM CLI location: [object Object]
> 2023-04-26 10:40:39 [INFO]: Command: (not started) [/usr/local/bin/sam build --build-dir /tmp/aws-toolkit-vscode/vsctkrNAWTQ/output --template /tmp/aws-toolkit-vscode/vsctkrNAWTQ/app___vsctk___template.yaml --base-dir /root/functions/check_bpy_file --manifest /tmp/aws-toolkit-vscode/vsctkrNAWTQ/debug-requirements.txt]
> 2023-04-26 10:40:39 [INFO]: SAM CLI not configured, using SAM found at: '/usr/local/bin/sam'
> 2023-04-26 10:40:41 [ERROR]: Unexpected exitcode (1), expecting (0)
> 2023-04-26 10:40:41 [ERROR]: Error: undefined
> 2023-04-26 10:40:41 [ERROR]: stderr: Building codeuri: /root/functions/check_bpy_file runtime: python3.10 metadata: {} architecture: arm64 functions: checkbpyfile
> Error: 'python3.10' runtime is not supported
> 2023-04-26 10:40:41 [ERROR]: stdout: Build Failed
> 2023-04-26 10:40:41 [ERROR]: SamLaunchRequestError: Failed to build SAM application [BuildFailure]

## Steps to reproduce the issue
VSCode launch config:

>         {
>             "type": "aws-sam",
>             "request": "direct-invoke",
>             "name": "CheckFunction",
>             "invokeTarget": {
>                 "target": "code",
>                 "architecture": "arm64",
>                 "projectRoot": "functions/check_bpy_file",
>                 "lambdaHandler": "app.lambda_handler"
>             },
>             "lambda": {
>                 "runtime": "python3.10"
>             }
>         }

1. Setup launch config
2. Run a debug function with created config

## System details (run the `AWS: About Toolkit` command)

-   OS: macOS 13.1
-   Visual Studio Code version: 1.77.3
-   AWS Toolkit version: 1.70.0

**Comment by justinmk3** [comment]
That error comes from: https://github.com/aws/aws-sam-cli/blob/6c45ed979ab2943e2792fcddfb49b8395defae65/samcli/lib/build/workflow_config.py#L210-L211

Can you check `sam --version` ?

**Comment by Rybalochka-MS** [comment]
Sure, `SAM CLI, version 1.81.0`

**Comment by justinmk3** [comment]
"architecture": "arm64"

Does it work if you remove that, or change it to `"architecture": "x86_64"` ?

**Comment by Rybalochka-MS** [comment]
For `"architecture": "x86_64"` got `Error: 'python3.10' runtime is not supported`
If I remove this line, got `Error: 'python3.10' runtime is not supported`

Output log:

> 2023-04-26 20:36:55 [ERROR]: log level: info
> 2023-04-26 20:36:55 [INFO]: endpoints: retrieving AWS endpoints data
> 2023-04-26 20:36:55 [INFO]: OS: Darwin arm64 22.2.0
> 2023-04-26 20:36:55 [INFO]: Visual Studio Code extension host:  1.77.3
> 2023-04-26 20:36:55 [INFO]: AWS Toolkit:  1.70.0
> 2023-04-26 20:36:55 [INFO]: node: 16.14.2
> 2023-04-26 20:36:55 [INFO]: electron: 19.1.11
> 2023-04-29 08:33:54 [INFO]: SAM CLI location: [object Object]
> 2023-04-29 08:33:54 [INFO]: SAM CLI location: [object Object]
> 2023-04-29 08:33:54 [INFO]: SAM CLI location: [object Object]
> 2023-04-29 08:33:54 [INFO]: Preparing to debug locally: Lambda "app.lambda_handler"
> 2023-04-29 08:33:54 [INFO]: Building SAM application...
> 2023-04-29 08:33:54 [INFO]: SAM CLI location: [object Object]
> 2023-04-29 08:33:54 [INFO]: Command: (not started) [/usr/local/bin/sam build --build-dir /tmp/aws-toolkit-vscode/vsctkhiq8NH/output --template /tmp/aws-toolkit-vscode/vsctkhiq8NH/app___vsctk___template.yaml --base-dir functions/check_bpy_file --manifest /tmp/aws-toolkit-vscode/vsctkhiq8NH/debug-requirements.txt]
> 2023-04-29 08:33:54 [INFO]: SAM CLI not configured, using SAM found at: '/usr/local/bin/sam'
> 2023-04-29 08:33:57 [ERROR]: Unexpected exitcode (1), expecting (0)
> 2023-04-29 08:33:57 [ERROR]: Error: undefined
> 2023-04-29 08:33:57 [ERROR]: stderr: Building codeuri: functions/check_bpy_file runtime: python3.10 metadata: {} architecture: x86_64 functions: checkbpyfile
> Error: 'python3.10' runtime is not supported
> 2023-04-29 08:33:57 [ERROR]: stdout: Build Failed
> 2023-04-29 08:33:57 [ERROR]: SamLaunchRequestError: Failed to build SAM application [BuildFailure]
> 2023-04-29 08:34:43 [INFO]: SAM CLI location: [object Object]
> 2023-04-29 08:34:43 [INFO]: SAM CLI location: [object Object]
> 2023-04-29 08:34:43 [INFO]: Preparing to debug locally: Lambda "app.lambda_handler"
> 2023-04-29 08:34:43 [INFO]: Building SAM application...
> 2023-04-29 08:34:44 [INFO]: SAM CLI location: [object Object]
> 2023-04-29 08:34:44 [INFO]: Command: (not started) [/usr/local/bin/sam build --build-dir /tmp/aws-toolkit-vscode/vsctkDw4PZb/output --template /tmp/aws-toolkit-vscode/vsctkDw4PZb/app___vsctk___template.yaml --base-dir functions/check_bpy_file --manifest /tmp/aws-toolkit-vscode/vsctkDw4PZb/debug-requirements.txt]
> 2023-04-29 08:34:44 [INFO]: SAM CLI not configured, using SAM found at: '/usr/local/bin/sam'
> 2023-04-29 08:34:45 [ERROR]: Unexpected exitcode (1), expecting (0)
> 2023-04-29 08:34:45 [ERROR]: Error: undefined
> 2023-04-29 08:34:45 [ERROR]: stderr: Building codeuri: functions/check_bpy_file runtime: python3.10 metadata: {} architecture: x86_64 functions: checkbpyfile
> Error: 'python3.10' runtime is not supported
> 2023-04-29 08:34:45 [ERROR]: stdout: Build Failed
> 2023-04-29 08:34:45 [ERROR]: SamLaunchRequestError: Failed to build SAM application [BuildFailure]
> 2023-04-29 08:35:14 [INFO]: SAM CLI location: [object Object]
> 2023-04-29 08:35:14 [INFO]: SAM CLI location: [object Object]
> 2023-04-29 08:35:14 [INFO]: Preparing to debug locally: Lambda "app.lambda_handler"
> 2023-04-29 08:35:14 [INFO]: Building SAM application...
> 2023-04-29 08:35:14 [INFO]: SAM CLI location: [object Object]
> 2023-04-29 08:35:14 [INFO]: Command: (not started) [/usr/local/bin/sam build --build-dir /tmp/aws-toolkit-vscode/vsctkSTkhH2/output --template /tmp/aws-toolkit-vscode/vsctkSTkhH2/app___vsctk___template.yaml --base-dir functions/check_bpy_file --manifest /tmp/aws-toolkit-vscode/vsctkSTkhH2/debug-requirements.txt]
> 2023-04-29 08:35:14 [INFO]: SAM CLI not configured, using SAM found at: '/usr/local/bin/sam'
> 2023-04-29 08:35:16 [ERROR]: Unexpected exitcode (1), expecting (0)
> 2023-04-29 08:35:16 [ERROR]: Error: undefined
> 2023-04-29 08:35:16 [ERROR]: stderr: Building codeuri: functions/check_bpy_file runtime: python3.10 metadata: {} architecture: x86_64 functions: checkbpyfile
> Error: 'python3.10' runtime is not supported
> 2023-04-29 08:35:16 [ERROR]: stdout: Build Failed
> 2023-04-29 08:35:16 [ERROR]: SamLaunchRequestError: Failed to build SAM application [BuildFailure]

**Comment by Rybalochka-MS** [comment]
Hi there, did you have a chance to look into my issue?

**Comment by justinmk3** [comment]
Because the error comes from `sam`, I suggest reporting this to https://github.com/aws/aws-sam-cli . 

`python3.10` is listed in the supported runtimes: https://github.com/aws/aws-sam-cli/blob/6c45ed979ab2943e2792fcddfb49b8395defae65/samcli/lib/build/workflow_config.py#L156

so maybe the error is misleading and there is a different problem.

Other troubleshooting steps:


- confirm that `which sam` shows `/usr/local/bin/sam` and that `/usr/local/bin/sam --version` matches the expected sam version (1.81). 
- run `sam build` and `sam invoke` from your terminal manually , pointing to the same template used in your report above.

**Comment by Rybalochka-MS** [comment]
Hi, thanks for your support. Actually, I found a problem. I had an old link to sam in /usr/local/bin directory. When I change it, all is working fine. Thanks.
