### ISSUE TITLE
I cannot login with AWS Builder ID

### ISSUE THREAD

**Issue by cpx2017** [aws/aws-toolkit-vscode#3382]
## Steps to reproduce the issue

I clicked to select connection and add connection by use a personal email to sign in with AWS Builder ID.
and show error log as
`
2023-04-26 16:52:22 [ERROR]: API response (oidc.us-east-1.amazonaws.com /client/register): {}
2023-04-26 16:52:22 [ERROR]: aws.auth.addConnection: SyntaxError: Unexpected token < in JSON at position 0
`

## System details (run the `AWS: About Toolkit` command)

-   OS: Windows 10
-   Visual Studio Code version: 1.77.3
-   AWS Toolkit version: 1.70.0

**Comment by justinmk3** [comment]
This may indicate that `~/.aws/sso/cache` or one of its folders or files has wrong permissions. https://github.com/aws/aws-toolkit-vscode/issues/3351

**Comment by cpx2017** [comment]
Hi, [justinmk3](https://github.com/justinmk3). I was able to fix the problem as you suggested. And thank you for your response to fix this problem.
