### ISSUE TITLE
codewhisperer shows reference log output view even when disabled

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#3421]
## Problem

`CodeWhisperer Reference Log` output panel is displayed even if CW is not enabled. 

Related: #3329

![image](https://user-images.githubusercontent.com/55561878/236208587-9ba09876-a78a-4e6c-b21b-51dca99fa2c7.png)

## Expected behavior

In https://github.com/aws/aws-toolkit-vscode/pull/3402 we changed the behavior so that the CW statusbar item is not shown unless CW is enabled. CW should do the same for other UI elements:

- when CW is disabled, delete the `CodeWhisperer Reference Log` output panel
    - show the panel when CW is enabled
    - if CW is later disabled again (by clicking the "Remove Connection" button), again delete the panel
        - ![image](https://user-images.githubusercontent.com/55561878/236209950-4ae9f797-b5d5-445c-ab65-7723fff3fea5.png)

**Comment by zixlin7** [comment]
this should be resolved now that Amazon Q is in it's own extension
