### ISSUE TITLE
clean.js has a syntax error

### ISSUE THREAD

**Issue by jamsajones** [aws/aws-toolkit-vscode#345]
**Describe the bug**
Running ```npm run build``` when build-scripts/clean.js is invoked it throws an syntax exception. This is because ``` } catch {``` block does not have in the ```exists``` function at https://github.com/aws/aws-toolkit-vscode/blob/2f0fdcbc0ff89b922e8fcd419fbb5c42f0c7d6f7/build-scripts/clean.js#L21 .

**To Reproduce**
```bash
git clone https://github.com/aws/aws-toolkit-vscode.git
cd to aws-toolkit-vscode
npm install
npm run package
```

**Expected behavior**
Build completes without error.

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.13.6
 - Node Version: 8.10.0
 - AWS Toolkit for Visual Studio Code Version: HEAD of develop branch from github.

**Additional context**
Stack trace
```
/Users/jsstraub/projects/aws-toolkit-vscode/build-scripts/clean.js:21
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by awschristou** [comment]
It looks like your error is related to using node 8.1 instead of node 10+ , the current version mentioned in https://github.com/aws/aws-toolkit-vscode/blob/develop/CONTRIBUTING.md

Your PR addresses this, and is now in the develop branch. Thank you for the contribution!

**Comment by jamsajones** [comment]
Great. Thanks for pointing out the Node version being the problem. I have opened a issue (#351) on the lack of this requirement in the README and will open a PR soon to propose change to docs.
