### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by subhendupsingh** [aws/aws-toolkit-vscode#3467]
- Issue Type: `Performance`
- Extension Name: `aws-toolkit-vscode`
- Extension Version: `1.73.0`
- OS Version: `Windows_NT x64 10.0.22621`
- VS Code version: `1.77.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/sps14/AppData/Local/Temp/amazonwebservices.aws-toolkit-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by justinmk3** [comment]
Thanks for the report, can you share the contents of the file: `file:///c%3A/Users/sps14/AppData/Local/Temp/amazonwebservices.aws-toolkit-vscode-unresponsive.cpuprofile.txt`

**Comment by justinmk3** [comment]
Without the contents of the `cpuprofile.txt` this isn't actionable, however the latest release of AWS Toolkit includes numerous performance improvements. Would be great to hear your feedback, thanks!
