### ISSUE TITLE
CodeWhisperer - indenting new lines bug

### ISSUE THREAD

**Issue by Sandbird** [aws/aws-toolkit-vscode#3468]
## Steps to reproduce the issue

CodeWhisperer makes weird indent entries all of a sudden. Every time I type a new line, it keeps indenting it wrong. (PHP)
This happens while editing a line as well. Just by correcting a single letter, it will move the whole line back 1 tab.

![image](https://github.com/aws/aws-toolkit-vscode/assets/204934/2abc44c3-0797-4d84-b420-8c2f2ea8e186)

## Expected behavior

Stop moving the line.

## System details

-   OS: Win10 64bit
-   Visual Studio Code version: 1.78.2
-   AWS Toolkit version: 1.73.0

**Comment by Sandbird** [comment]
Disabling this makes the problem go away

![image](https://github.com/aws/aws-toolkit-vscode/assets/204934/b21a98b2-a7dc-4476-a308-a630914a7c33)

**Comment by Sandbird** [comment]
This is so annoying. I keep losing undo/redo actions because of this. I go back to see some code I wrote like 2 minutes ago to grab something, and while going forward again it will randomly indent some of that code, and then I lose my history. 
I've tried every setting possible. Nothing helps

**Comment by Will-ShaoHua** [comment]
Hi @Sandbird, wondering if you are able to provide me with complete file content so that I can repro this issue on my end?

**Comment by Sandbird** [comment]
Hi @Will-ShaoHua , thanks for the reply. I was about to create and an example, and then it hit me to try and disable everything I had first from other extensions and leave only AWS....and voila...the bug is gone. Some other extension probably got inline completion on an update it had and i didn't notice. We can close this, i'll find which one it is.
Thanks again

**Comment by Will-ShaoHua** [comment]
No problem @Sandbird, we are actively solving these bad user experience so feel free to open an issue if you see any when using CodeWhisperer! :)

**Comment by Will-ShaoHua** [comment]
btw if you know which extension is interfering with CodeWhisperer afterward, please let us know so that we can figure out the solution for that, thanks!

**Comment by Sandbird** [comment]
I just figured it out. It was: ChatGPT - EasyCode
https://marketplace.visualstudio.com/items?itemName=EasyCodeAI.chatgpt-gpt4-gpt3-vscode

And it does have Inline Completion (it didn't in the past). Disabling that the indent bug goes way, and AWS works as expected!
