### ISSUE TITLE
CodeWhisperer: setting disabled per user, but per workspace shows enabled

### ISSUE THREAD

**Issue by ezekiel747** [aws/aws-toolkit-vscode#3477]
## Problem
I uncheck the option "Code Whisperer: Share Code Whisperer Content With AWS"  from extension settings, at the user level, but when showing settings at workspace level it's checked, even though nothing specific is actually in the workspace settings file.

## Steps to reproduce the issue

1. Go to extensions, click on settings icon, select Extension settings
2. Select the User tab (not workspace)
3. Uncheck "Code Whisperer: Share Code Whisperer Content With AWS" 
4. Select the Workspace tab
5. Notice "Code Whisperer: Share Code Whisperer Content With AWS" is checked
6. Open the settings json file in workspace
7. Notice it doesn't have any value to override the User setting.

## Expected behavior
This should show up as unchecked as per User settings, if not otherwise overriden with a different value in the workspace settings.

## System details (run the `AWS: About Toolkit` command)

-   OS: Mac OS Monterey
-   Visual Studio Code version: 1.78.2
-   AWS Toolkit version: 1.73.0

**Comment by justinmk3** [comment]
This should be fixed in AWS Toolkit 1.82
