### ISSUE TITLE
Reduce the number of aws builder id logins

### ISSUE THREAD

**Issue by romanholidaypancakes** [aws/aws-toolkit-vscode#3488]
## Problem
When the current extension is updated or used for a long time, you need to login again, and the login verification process is cumbersome, which greatly affects the user experience.
## Expected behavior
Customizable token validity, or reduced login times.

**Comment by justinmk3** [comment]
#3498 (not released yet) should improve this behavior.

**Comment by justinmk3** [comment]
Thank you for the followup! Watch https://github.com/aws/aws-toolkit-vscode/issues/3248 for further improvements.
