### ISSUE TITLE
The requested operation is not recognized by the service.

### ISSUE THREAD

**Issue by sungamma** [aws/aws-toolkit-vscode#3505]
## Problem
I write a prompt in test.py. 
`# Write a quicksort` And then I type Alt+C， codewhisperer shows "Wating for Codewhisperer..." And then it shows"The requested operation is not recognized by the service."
![image](https://github.com/aws/aws-toolkit-vscode/assets/33790/a8e02c5a-0454-40a6-90db-285daacbab67)

## System details (run the `AWS: About Toolkit` command)

-   OS: win10 
-   Visual Studio Code version: 1.74.3(use setup)
-   AWS Toolkit version: v1.74.0

**Comment by TheMostVexingParse** [comment]
![image](https://github.com/aws/aws-toolkit-vscode/assets/131294606/4c07048d-952d-45da-a4e4-ba28244d158c)

I used to get the same error message.

I solved it by first authenticating through the "Connect to AWS" option and then authenticating **again** through the "Start" option under the CodeWhisperer section.

**Comment by sungamma** [comment]
thank you，it works for me

**Comment by sungamma** [comment]
Athough it worked by this method, but It would be nice to have an official fix

**Comment by justinmk3** [comment]
The next release will include https://github.com/aws/aws-toolkit-vscode/pull/3498 which should fix this issue.
