### ISSUE TITLE
Dev and testing is done with Node 10+. README build instructions missing this limitation.

### ISSUE THREAD

**Issue by jamsajones** [aws/aws-toolkit-vscode#351]
**Describe the bug**
I ran the build instructions in the README.md with node 8.10. The build script relied on features in Node 10+ and failed. The root cause is that the Node version that is being used for development and testing is 10+. This fact is not specified in the build instructions but should be.

**To Reproduce**
Read the build instructions in the README.md. Notice there is no Node version specified for the build.

**Expected behavior**
Node 10+ is required. I expect that they instructions should have me check my version before running the build instructions.

**Desktop (please complete the following information):**
 - OS: All
 - Visual Studio Code Version: N/A
 - AWS Toolkit for Visual Studio Code Version: N/A

**Comment by awschristou** [comment]
Thank you for the contribution. It is now in the develop branch.
