### ISSUE TITLE
Centralize NLS initialization.

### ISSUE THREAD

**Issue by micholas** [aws/aws-toolkit-vscode#353]
**Is your feature request related to a problem? Please describe.**

Currently we have a number of racing conditions in which modules use a class or object factory that will only work if some prerequisite initialization function has been called.

e.g. The `localize` object factory and `nls.config` initializer.

Traditionally we have dumped all of the initialization into `extension.ts`.

This is less than ideal for two primary reasons:

1. It creates an (often unnecessary) racing condition in which much of our consumer code would not work if `activate` in `extensions.ts` were not called 1st complicating tests which must account for this. 
2. It convolutes the focus of `extension.ts` by making it a dumping ground for initializers that could be done in appropriate utility modules such as `shared/logger` or `vsCodeUtils`.

Current Typical Consumer
```
import * as nls from 'vscode-nls'
const localize = nls.loadMessageBundle()
const message = localize(nlsKey, nlsTemplateString)
```

**Describe the solution you'd like**

A common practice for Node modules is for the module to initialize themselves so that any object factories and/or classes they provide just work without consumers needing to worry about such racing conditions.

Example solution in this specific case would be to have a utility package such as `sCodeUtils` initialize nls and provide a factory or exported const to the initialized object or function.

New NLS factory:
```
import * as nls from 'vscode-nls'

const env = process.env as EnvironmentVariables
if (!!env.VSCODE_NLS_CONFIG) {
    nls.config(JSON.parse(env.VSCODE_NLS_CONFIG) as nls.Options)()
} else {
    nls.config()()
}

export const localize = nls.loadMessageBundle()
```

New Consumer:
```
import { localize } from '../utilities/vsCodeUtils'
const message = localize(nlsKey, nlsTemplateString)
```

**Benefits**

1. `nls` is guaranteed to be initialized properly irregardless of any external order of operation dependencies.  
2. Loose coupling:  references to the  `vscode-nls` module (an implementation details) are not sprinkled throughout all consumer code.  Thus we _could_ change our multi-language support implementation without changing any code outside of the NLS factory.
3. Less lines of code. We save one line of code in each package that uses `localize`
4. `extension.ts` is less complex

**Describe alternatives you've considered**

1.  Status quo, keep dumping more initializer into `extensions.ts`. 
2. Introduce an entire Java style dependency injection framework.
3. Use basic ECMA module initialization to ensure classes/object factories that just work without racing conditions (current recommendation).

**Comment by mpiroc** [comment]
Closing this as `wontfix`. This is low-ROI work, and the official document uses the pattern:

```typescript
import * as nls from 'vscode-nls'
const localize = nls.loadMessageBundle()
```
