### ISSUE TITLE
I can't use codewhisperer

### ISSUE THREAD

**Issue by JuanMedina2021** [aws/aws-toolkit-vscode#3530]
## Problem
I can't use it
## Expected behavior
It should open codewhisperer
## System details (run the `AWS: About Toolkit` command)

-   OS:
-   Visual Studio Code version:
-   AWS Toolkit version:

**Comment by justinmk3** [comment]
what exact steps are you taking? 

Can you provide the logs (check that private info is removed)? 

1. In VSCode settings, ensure that "aws log level" is "debug".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View Toolkit Logs` command to get the logs.

**Comment by justinmk3** [comment]
Can't help without more information.
