### ISSUE TITLE
Error: Unable to authenticate connection - Microsoft Azure IAM provider

### ISSUE THREAD

**Issue by mwjanowi** [aws/aws-toolkit-vscode#3543]
## System details (run the `AWS: About Toolkit` command)

-   OS: Darwin x64 22.5.0
-   Visual Studio Code version: 1.78.2
-   AWS Toolkit version: 1.76.0

## Question
How can i remove this Connection Error with AWS Toolkit. 

I am unable to connect to my companies AWS accounts via their Azure SSO solution.
Can someone advise if I have to take some extra steps to allow VSCODE to connect?

My companies proxy, albeit not required in this situation, is hooked up to VSCODE.

It appears that when i select my profile within my .aws/config aws toolkit is unable to connect using this information.
/users/bin/pc is a homegrown corporate solution to execute the login process.

```
[profile MY-PROFILE-NAME]
credential_process             = /Users/bin/pc login aws --credential-process --exact-match --profile MY-PROFILE-ANME --role my-role
azure_tenant_id                = <id>
azure_app_id_uri               = <uri>
azure_default_username         = <email>
azure_default_role_arn         = 
azure_default_duration_hours   = 1
azure_session_duration_minutes = 60
```

**Comment by justinmk3** [comment]
`credential_process` is supported by AWS Toolkit but I would need to see your logs to guess about what is going wrong. 


Can you provide the Toolkit logs (remove private info):

1. In VSCode settings, ensure that "aws log level" is "debug".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View Toolkit Logs` command to get the logs.

> My companies proxy, albeit not required in this situation, is hooked up to VSCODE

Do you mean, you have configured vscode's proxy settings as described [here](https://code.visualstudio.com/docs/setup/network)?
