### ISSUE TITLE
AWS Toolkit regularly logging out

### ISSUE THREAD

**Issue by aderchox** [aws/aws-toolkit-vscode#3549]
## Problem
Very regularly I have to re-connect my AWS Builder ID
Is this by design / some intended security measure, or it should not happen?

## Steps to reproduce the issue
I don't know how to reproduce this because I don't see a clear pattern, but it occurs to me that it happens when I've been idle for some time and when I've not used it for a certain period of time (e.g. a week).

## Expected behavior
When I log in once, it must remain logged in unless I log out myself?

## System details (run the `AWS: About Toolkit` command)

-   OS: Win10 22H2 19045.2965
-   Visual Studio Code version: 1.78.2 (user setup)
-   AWS Toolkit version: 1.74.0

**Comment by justinmk3** [comment]
> * AWS Toolkit version: 1.74.0

The latest version of AWS Toolkit is 1.76, which has improvements in this area.

**Comment by aderchox** [comment]
No, I should've updated first, there's no reason, I just missed the update.
I've updated now and I will tell here if it happens again. Thanks.

**Comment by lkolchin** [comment]
Why is this issue closed?
Still happens on 1.79

**Comment by mtariqsajid** [comment]
> > * AWS Toolkit version: 1.74.0
> 
> The latest version of AWS Toolkit is 1.76, which has improvements in this area. Is there a reason you're using 1.74?
> 
> > I have to re-connect my AWS Builder ID ... a certain period of time (e.g. a week).
> 
> AWS Builder Id requires re-authentication after about 7 days. This is not controllable by AWS Toolkit.

is there a option to refresh it automatically. because i have go through the whole process every time. maybe plugin show notify user when expire ?

**Comment by justinmk3** [comment]
> Why is this issue closed?

Because the same topic is tracked in https://github.com/aws/aws-toolkit-vscode/issues/3614 

> > AWS Builder Id requires re-authentication after about 7 days. This is not controllable by AWS Toolkit.
> 
> is there a option to refresh it automatically. because i have go through the whole process every time. maybe plugin show notify user when expire ?

It's a hard limit on the service-side. AWS Toolkit can't do anything to extend or "refresh" the limit beyond 7 days.

We are working with the AWS Builder Id team to extend the limit and will update #3614 when we have more information.

**Comment by doublehelix** [comment]
Yeah... I'm still having this issue.
It occurs one or twice PER DAY.
If I close VSCode overnight I have to re-authenticate each morning.
If I let my laptop go to sleep during my lunch break, I have to re-authenticate after lunch.
Sometimes it's as little as 4 hours... sometimes it will last 6 before disconnecting.
I have a fixed IP, don't use VPN no network blockers or filters etc.
