### ISSUE TITLE
CI integ tests failing: Running as root without --no-sandbox is not supported

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#3550]
```
[10429:0609/133041.674749:ERROR:network_service_instance_impl.cc(521)] Network service crashed, restarting service.
--
19 | [0609/133041.694037:FATAL:electron_main_delegate.cc(304)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

- https://crbug.com/638180
- https://github.com/microsoft/vscode/issues/151187
- https://github.com/microsoft/vscode-test/issues/221#issuecomment-1584772835
- https://github.com/microsoft/vscode/issues/184687

## Solution

- Try adding these args: `sudo code --no-sandbox --disable-gpu-sandbox ...`
    - also update `vscode-test`: https://github.com/microsoft/vscode-test/pull/222
- or switch to unprivileged mode, but codebuild makes that difficult

**Comment by ITAxReal** [comment]
A lot of people won't switch to unprivileged mode because their working files will be unaccessible from vscode. Just give us working --no-sandbox flag instead!
