### ISSUE TITLE
Forbidden error after connected successfully

### ISSUE THREAD

**Issue by bandojulio** [aws/aws-toolkit-vscode#3582]
## Problem
I'm getting Forbidden error after getting connect to Code Catalyst. I'm using a VM with CentOS 9, it is working on Windows (host machine).

## System details (run the `AWS: About Toolkit` command)

-   OS: CentOS 9
-   Visual Studio Code version: 1.79.1
-   AWS Toolkit version: 1.77.0

Error below:

```
2023-06-14 19:06:24 [ERROR]: aws.codecatalyst.getStarted: UnknownError: Forbidden (statusCode: 403)
2023-06-14 19:06:25 [ERROR]: API request failed (time: 738ms): verifySession
params: {}
error: {
  message: 'Forbidden',
  code: 'UnknownError',
  statusCode: 403,
  time: 2023-06-14T22:06:25.105Z,
  retryable: false,
  retryDelay: 68.8914881382009
}
headers: {
  'x-amzn-requestid': undefined,
  'x-amzn-trace-id': undefined,
  'x-amzn-served-from': undefined,
  'x-cache': 'Error from cloudfront',
  'x-amz-cf-id': 'Obb3UplTcBnSF1C8lPdNewOtUNR9hxWsTuohD5_U4c15ZCoP0H6omw==',
  'x-amz-cf-pop': 'GRU3-P2'
}
2023-06-14 19:09:11 [INFO]: telemetry: sent batch (size=20)
2023-06-14 19:09:11 [INFO]: telemetry: sent batch (size=4)
```

**Comment by justinmk3** [comment]
> 2023-06-14 19:06:25 [ERROR]: API request failed (time: 738ms): verifySession

Did you sign up at https://codecatalyst.aws/ and complete the user creation process?

Also might be worth trying again, there was a service degredation 1-2 days ago.
