### ISSUE TITLE
Why does the Toolkit check for docker when trying to debug SAM CLI Lambda

### ISSUE THREAD

**Issue by mmoerman** [aws/aws-toolkit-vscode#3588]
## System details (run the `AWS: About Toolkit` command)

-   OS: Windows
-   Visual Studio Code version: 1.79.2
-   AWS Toolkit version: 1.77

## Question

SAM CLI supports launching a Lambda function via a remote docker, which Iuse from the command line successfuly using Windows WSL v2 and Ubuntu. This means I don't really have a local install of docker (except inside the Ubuntu VM). Given the AWS Toolkit checks for a local copy of docker I was unable to use "Start Debugging" in VSCode with the launch config I set up.

After some tinkering I was able to figure this out from your code, created a fake docker.cmd file in the path and tricked the AWS Toolkit in thinking docker was there. Then SAM CLI would properly launch the Lambda through the remote docker config, and everything was fine. (I have my DOCKER_HOST environment variable set to tcp://localhost:2375)

So I am not sure if I should turn this in a feature request or something, but would it be possible to do something so that I don't have to fake docker in this configuration? 
While we're at it would it be possible to have some config parameters to setup the DOCKER_HOST environment variable inside the toolkit config, now I had to define it at the global OS level.

**Comment by justinmk3** [comment]
Thanks for pointing this out. Yes, we should support this.

**Comment by justinmk3** [comment]
This check was removed in AWS Toolkit 1.86. Instead, AWS Toolkit now defers to `sam` for checking Docker, and will surface any `sam` errors. https://github.com/aws/aws-toolkit-vscode/pull/3761
