### ISSUE TITLE
"Open Terminal..." for a task definition's container returns list with many tasks (of other task definitions too)

### ISSUE THREAD

**Issue by chrispetsos** [aws/aws-toolkit-vscode#3589]
## Problem
I get several task IDs to choose from when opening a terminal inside an ECS container, where I would expect to get only one.

## Steps to reproduce the issue

0. It is assumed that you have several ECS task definitions which define a container named by the same name, e.g. 'api'.
1. Go to 'Your region -> ECS -> your cluster -> your task definition'
2. Right-click on 'your container name (e.g. api)', click on 'Open Terminal...'
3. You get a 'Choose a container instance (1/2)' list with several task IDs. Those task IDs belong to other task definitions also which define a container named 'api'.

## Expected behavior
The 'Choose a container instance (1/2)' list should contain task IDs only from the ECS task definition whose container I right-clicked.

## System details (run the `AWS: About Toolkit` command)

OS: Darwin x64 22.5.0
Visual Studio Code extension host:  1.77.3
AWS Toolkit:  1.77.0
node: 16.14.2
electron: 19.1.11

**Comment by JadenSimon** [comment]
Fixed in 1.78.0
