### ISSUE TITLE
User sees a welcome page to get familiarized with the Toolkit

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#361]
Work with the editing team to get a markdown file of the documentation landing page. Display this the first time each version of the toolkit is loaded for the first time. (In the future we can provide a more customized welcome page, and add functionality that allows users to suppress bringing this up each time)

Acceptance criteria
* the first time each version of the Toolkit is launched, an editor tab shows a welcome screen
* the contents are a copy of the documentation's front page
* a command palette entry exists to display this page at any time

Ideally the editor tab is a non-editable rich view.

**Comment by bryceitoc9** [comment]
The docs will likely have a link on installation instructions...probably best to reach out to the doc writers to make a note for users on said install pages to skip the plugin installation itself when coming from the plugin (other parts of installation, like the SAM CLI and AWS CLI installs as well as adding credentials will still be valid to have around). 

Will there be a way for the user to re-access this page?

**Comment by awschristou** [comment]
> Will there be a way for the user to re-access this page?

Good catch, added to the AC

**Comment by mpiroc** [comment]
This task has been split into #528 and #544 .
