### ISSUE TITLE
AWS Codewhisperer keeps asking me to sign in again every week

### ISSUE THREAD

**Issue by samdenty** [aws/aws-toolkit-vscode#3614]
## Problem

I'm trying to use AWS Codewhisperer but it keeps asking me to re-sign in every couple of days / week. Each time I sign in I select 'This is a trusted device', to no avail

## Expected behavior

Codewhisperer should stay signed in forever

**Comment by QixuanAI** [comment]
the same problem, and not only every week, but also every time I open another VS Code window or change another PC.

**Comment by samdenty** [comment]
Is there any resolution to this? this is probably going to make me uninstall aws codewhisperer even though i like it and use a competitor

**Comment by nawlbergs** [comment]
can I not use my IAM credentials?  its currently using both or something... IAM for all the toolkit explorer and this AWS Builder ID junk for code whisperer...

**Comment by justinmk3** [comment]
> can I not use my IAM credentials?

Kind of, if you set up IAM Identity Center (aka SSO) https://docs.aws.amazon.com/codewhisperer/latest/userguide/as-whisper-admin.html#codewhisperer-setup-enterprise-admin-authorize

**Comment by srinz9** [comment]
CodeWhisperer supports (1) BuilderID (Individual tier) and (2) Identity Center (IdC) (Professional tier)
BuilderID has a 7-day expiry and  IdC can be configured to upto 7-day session 

In the recent extension updates, we fixed cases where logouts happen sooner. 

We are also working on extending this - will share an update when ready.

**Comment by braincomb** [comment]
👍 

Using BuilderID and the logouts seem to happen sooner than 7-days.

The whole process is highly inconvenient and 7-days still seems too short. The whole process is like this:

1) Tell extension to reconnect with AWS.
2) Copy code.
3) Go to page and paste code. At this point this should have been the end of it, but no...
4) Go to AWS Builder ID page.
5) Click on "Already have AWS Builder ID. Sign In".
6) Click Next.
7) Finally be able to enter password and Sign In.
8) But wait, have to click Allow again.

What gives?

**Comment by soup-bowl** [comment]
If the BuilderID timeout is being caused by the source API, or at least another method unrelated to this vscode plugin, could there be a pointer to what issue is tracking it? A 7 day expiry seems to be a security-over-usability design and would like to feedback on that.

**Comment by justinmk3** [comment]
There is no public tracking issue. We will update here when we have a meaningful update to share.

**Comment by justinmk3** [comment]
Update: AWS Builder Id session maximum is now 30 days, instead of 7 days.

**Comment by justinmk3** [comment]
Update: 

- Identity Center (IdC, CodeWhisperer "Professional tier") now supports a session maximum of 90 days (configurable by the IdC administrator).
    - This is unrelated to AWS Builder Id, which has a session maximum of 30 days.

**Comment by muchisx** [comment]
hey @justinmk3 I do not see a setting to change the frequency for the session expiration.

I'm looking in this page and all submenus
https://profile.aws.amazon.com/#/profile/details

Am I looking in the wrong place?

**Comment by justinmk3** [comment]
@muchisx https://profile.aws.amazon.com/#/profile/details is for AWS Builder Id, which has a max of 30 days, it's not configurable. 

[IdC](https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html) (CodeWhisperer "Professional tier") is unrelated to Builder Id.

**Comment by doublehelix** [comment]
Yeah... I'm still having this issue.
It occurs one or twice PER DAY.
If I close VSCode overnight I have to re-authenticate each morning.
If I let my laptop go to sleep during my lunch break, I have to re-authenticate after lunch.
Sometimes it's as little as 4 hours... sometimes it will last 6 before disconnecting (even when working non-stop - no computer shutdown, no VSCode shutdown).
I have a fixed IP, don't use VPN no network blockers or filters etc.

**Comment by justinmk3** [comment]
Please open a new issue. There are multiple different scenarios that were discussed in this issue.

**Comment by andre-mr** [comment]
this is happening almost every day here. very annoying.

i open vs code and guess what:
![image](https://github.com/aws/aws-toolkit-vscode/assets/77874276/f7f417db-57b4-49b7-87ce-1ded402443c8)
let's fix that:
![image](https://github.com/aws/aws-toolkit-vscode/assets/77874276/6e56c897-4db2-44ac-b899-2882276d80de)
just to open browser and see this:
![image](https://github.com/aws/aws-toolkit-vscode/assets/77874276/4556511b-18aa-4875-bc0a-a57f6ed4c1eb)

and after those "30 days" make the auth workflow again, entering my "non-saveable" password in the browser. looks great as a password reminder by the way... 🙄

**Comment by justinmk3** [comment]
> this is happening almost every day  ... and after those "30 days" make the auth workflow again

@andre-mr can you open a new issue and share your logs

1. In the vscode [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette), run `Amazon Q: View Logs`. This reveals the Output panel with `Amazon Q Logs` selected.
2. Click the gear icon and choose `Debug`, then click it again and choose `Set As Default`.
3. Perform the steps to reproduce the issue.
4. Remove any private info from the logs.

**Comment by Firsh** [comment]
This is why AI won't take our jobs. We just uninstall it.

**Comment by justinmk3** [comment]
The latest release has a [bug fix](https://github.com/aws/aws-toolkit-vscode/commit/706a3a1064be86e5969ad5e26e474c2b3ddd04f4) intended to fix this issue.
