### ISSUE TITLE
Codewhisperer Reference log doesn't show references

### ISSUE THREAD

**Issue by lsutton00** [aws/aws-toolkit-vscode#3624]
## Steps to reproduce the issue

Enable Codewhisperer,
Open code reference log
Type some code and get a suggestion
See no references
![image](https://github.com/aws/aws-toolkit-vscode/assets/50231724/dd4d120d-9255-4bdb-a999-e718d87db560)

## Expected behavior

See references when getting suggestions

## System details (run the `AWS: About Toolkit` command)

-   OS: Windows 11
-   Visual Studio Code version: 1.79.2
-   AWS Toolkit version: 1.78.0

**Comment by andrewyuq** [comment]
Hi, this is working as expected. Only when a code has a reference(roughly 1% of all time), it will show references in this log.

**Comment by srinz9** [comment]
The CodeWhisperer reference tracker detects whether a code suggestion might be similar to particular CodeWhisperer open-source training data. The reference tracker can flag such suggestions with a repository URL and project license information or optionally filter them out. You can then more easily find and review the referenced code and see how it is used in the context of another project, before deciding to use it. All references are logged for you to review later to ensure that your code flow is not disturbed, and you can keep coding without interruption.

https://aws.amazon.com/codewhisperer/faqs/
