### ISSUE TITLE
SAM CLI (build): Error while passing custom '--manifest' parameter on buildArguments in launch.json

### ISSUE THREAD

**Issue by danieldias99** [aws/aws-toolkit-vscode#3632]
## Problem
My lambda imports the package ```requests```, and for that dependency i have to specify a requirements file (using --manifest argument of the sam CLI). Using 'buildArguments' I can't customize a path to my requirements file and the file generated by the toolkit is always updated on every run.

## Steps to reproduce 
In my lauch.json I have the following configuration:
```JSON
{
            "type": "aws-sam",
            "request": "direct-invoke",
            "name": "MyLambdaRunner",
            "invokeTarget": {
                "target": "template",
                "templatePath": "path/to/template.yml",
                "logicalId": "MyLambda"
            },
            "lambda": {
                "payload": {},
                "environmentVariables": {}
            },
            "sam":{
                "buildDir": "path/to/my/.aws-sam/",
                "buildArguments": ["-m path/to/my/requirements.txt"]
            }
 }
```

and when I run debug it creates a debug_requirements.txt file inside .aws-sam directory
![image](https://github.com/aws/aws-toolkit-vscode/assets/56049583/de1a7a06-74df-4aa7-acc0-967e1b56da20)

with the following content
![image](https://github.com/aws/aws-toolkit-vscode/assets/56049583/45beafd2-7ec5-4720-90d8-d7bb04ee8267)

if I change it to ```"buildArguments": ["--manifest path/to/my/requirements.txt"]``` it gives me an error saying "--manifest not supported".

## Expected behaviour

I want to specify a custom path to the requirements.txt file.

## System details (run the `AWS: About Toolkit` command)

-   OS: MAC OS
-   Visual Studio Code version: 1.79.2
-   AWS Toolkit version: v1.78.0

**Comment by justinmk3** [comment]
> if I change it to `"buildArguments": ["--manifest path/to/my/requirements.txt"]`

I think each argument needs to be a separate item in the list, try this:

    "buildArguments": ["--manifest", "path/to/my/requirements.txt"]

> it gives me an error saying "--manifest not supported".

Can you share the exact logs (after removing private info)?
