### ISSUE TITLE
SSO issue:  unable to get local issuer certificate 

### ISSUE THREAD

**Issue by mhungc** [aws/aws-toolkit-vscode#3637]
## System details (run the `AWS: About Toolkit` command)

-   OS: Windows 10
-   Visual Studio Code version: 1.79.2
-   AWS Toolkit version: v1.79.0

## Question

Hello folks.

I am having an error with the extension and visual studio code when trying to login via SSO. This is the issue at the end of configuring it:

**2023-07-03 00:16:08 [ERROR]: _aws.auth.reauthenticate: Error: Unable to authenticate connection
-> Error: unable to get local issuer certificate [UNABLE_TO_GET_ISSUER_CERT_LOCALLY]**

It didn't happen to me before.

I would greatly appreciate your help

**Comment by justinmk3** [comment]
Are you behind a proxy? See https://github.com/aws/aws-toolkit-vscode/issues/899#issuecomment-589500847 for advice. This generally requires you to configure vscode. 

Improved support of proxies is tracked in https://github.com/aws/aws-toolkit-vscode/issues/899
