### ISSUE TITLE
AWS toolkit developer tools and explorer section are not working

### ISSUE THREAD

**Issue by SantyTaco** [aws/aws-toolkit-vscode#3647]
## Problem
AWS toolkit developer tools and explorer section are not working in MAC Monterrey
## Steps to reproduce the issue
1.- Install Aws toolkit
2.- Restart VS code
3.- I cannot see any option in developer tool or explorer section
![Screen Shot 2023-07-06 at 12 12 30 PM](https://github.com/aws/aws-toolkit-vscode/assets/38363806/9b5ff3fc-cc61-4a98-aa40-e153e9f13e65)

## Expected behavior
I would like to try codewhisperer
## System details (run the `AWS: About Toolkit` command)

-   OS: MAC Monterrey
-   Visual Studio Code version: 1.79.2
-   AWS Toolkit version: v1.80.0

**Comment by justinmk3** [comment]
@SantyTaco Looks like Toolkit is failing to start. Can you share the logs (after removing any private info):

1. In VSCode settings, ensure that "aws log level" is "debug".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View Toolkit Logs` command to get the logs.
    - if the `AWS: View Toolkit Logs` command doesn't work, try the vscode "OUTPUT" view and select `AWS Toolkit Logs`: 
    - ![image](https://github.com/aws/aws-toolkit-vscode/assets/55561878/0949cc4f-f1d4-4646-a966-ddb318fa9534)
