### ISSUE TITLE
AWS Toolkit in Mac OS never returns from browser page (to enter credentials)

### ISSUE THREAD

**Issue by atabhatti** [aws/aws-toolkit-vscode#3672]
I am setting up AWS Toolkit on a MBP running Ventura (13.4.1).  I am trying to set up credentials for VS Code to allow full featured development but am having trouble connecting VS Code to AWS.  I already have a programmatic user set up with very limited access.  I also have AWS Toolkit set up for that user.  But I want another user to have wider access so I can use more of AWS Toolkit features, so I select AWS: Add New Connection and try to Add another IAM Identity Center Profile. I enter a new Start URL (https://d-xxxxxxxxxx.asapps.com/start) and select the right region.  I click on Sign in.  A window comes up telling me to Copy Code and Proceed (I do).  A popup comes up asking whether I want Code to open the external website.  I click Open.  A browser page opens ('Authorize Request") which asks for a code.  I enter it.  Then a page opens up asking for Sign in Credentials.  

What is it looking for?  I enter the credentials for my AWS Account and it says "We couldn't verify your sign-in credentials. Please try again."  That stays.  What am I doing wrong?

![Screenshot 2023-07-21 at 4 36 20 PM](https://github.com/aws/aws-toolkit-visual-studio/assets/27871105/2d8a6bbd-e80a-498c-b090-5177295b882b)
![Screenshot 2023-07-21 at 4 36 32 PM](https://github.com/aws/aws-toolkit-visual-studio/assets/27871105/a96ad963-18b2-4d63-8110-3b64bda9134c)

**Comment by justinmk3** [comment]
> A browser page opens ('Authorize Request") which asks for a code. I enter it. Then a page opens up asking for Sign in Credentials.
>
> What is it looking for? I enter the credentials for my AWS Account and it says "We couldn't verify your sign-in credentials. Please try again."

This is the user configured by the IAM Identity Center administrator. It's not your AWS account.

See also https://docs.aws.amazon.com/singlesignon/latest/userguide/get-started-choose-identity-source.html

**Comment by atabhatti** [comment]
This AWS account is a sandbox account with me as the only engineer. When
you say “This is the user configured by the IAM Identity Center
administrator.” I suppose I am the administrator. What user do I need to
set up?  Are there any special permissions I should give it?

**Comment by atabhatti** [comment]
Thanks Justin.

I went to IAM and set up a new user, entered those credentials into the AWS Toolkit and that process finishes.  But when I look at the AWS Explorer I don't see any resources?!

**Comment by justinmk3** [comment]
IAM is different than IAM Identity Center (formerly called AWS SSO). Sorry for the confusion :(

I recommend reviewing the IdC docs. In particular, https://docs.aws.amazon.com/singlesignon/latest/userguide/get-started-choose-identity-source.html explains how IdC can have different "sources" of users. The first, `Identity Center directory`, is the default and involves creating users manually. The others such as `Active Directory` pull the users from external sources.

**Comment by atabhatti** [comment]
Thanks Justin.

I went to IAM and set up a new user, entered those credentials into the AWS Toolkit and that process finishes.  Phew!  But when I look at the AWS Explorer I don't see any resources?!  What is going on?

![Screenshot 2023-07-21 at 5 53 39 PM](https://github.com/aws/aws-toolkit-vscode/assets/27871105/76e7c66f-bd50-4050-817f-bb71fe61e7fd)

**Comment by justinmk3** [comment]
In your screenshot, you are now connected to IdC but haven't selected "credentials". AWS Toolkit will auto-discover the available credentials. Just click on it in the Connection menu (shown in your screenshot), and then choose an item.

**Comment by atabhatti** [comment]
> IAM is different than IAM Identity Center (formerly called AWS SSO). Sorry for the confusion :(
> 
> I recommend reviewing the IdC docs. In particular, https://docs.aws.amazon.com/singlesignon/latest/userguide/get-started-choose-identity-source.html explains how IdC can have different "sources" of users. The first, `Identity Center directory`, is the default and involves creating users manually (but not in IAM!). The others such as `Active Directory` pull the users from external sources.

Yes I was totally confused by that (naming IS the hardest problem in CS!).  I now have a user in made in Identity Center Directory and am configured with that.

**Comment by atabhatti** [comment]
Got it!  I needed to give the user some additional access.  I made it a PowerUser and things look good now.  Thank you!
