### ISSUE TITLE
Inject credentials into launch.json tasks for debugging code

### ISSUE THREAD

**Issue by wparad** [aws/aws-toolkit-vscode#3673]
## Problem
When running a launched task via the launch.json for debugging code, the process that runs doesn't is authenticated. There are no credentials available to that process.

## Steps to reproduce the issue
1. Create an AWS connection and sign in.
2. Hit F5 to start a debugging session and launch your code.
3. Code will fail with missing credentials.

## Expected behavior
Credentials are available to the running process.

## System details (run the `AWS: About Toolkit` command)

OS: Linux x64 5.15.0-76-generic
Visual Studio Code extension host:  1.73.1
AWS Toolkit:  1.81.0
node: 16.14.2
electron: 19.0.17

**Comment by justinmk3** [comment]
> Expected behavior: Credentials are available to the running process.

Sounds like https://github.com/aws/aws-toolkit-vscode/issues/3061 (please confirm), but can you provide insight into your use-case:

- Are you expecting Toolkit to set `AWS_*` environment variables?
- If you are expecting Toolkit to set environment variables, can you provide sample code that would work after setting these environment variables?
    - What's the difference/benefit compared to getting credentials from a profile in `~/.aws/credentials` ? How much code is saved?

# Workarounds

This post https://stackoverflow.com/a/76716994/152142  describes current options:

- In your code, get credentials by referencing a profile name.
    - Example (python boto): `boto3.setup_default_session(profile_name='profile-name')`
- In launch.json, set `"env": { "AWS_PROFILE": "profile-name"}`

# Related

- https://github.com/aws/aws-toolkit-vscode/issues/3271
- https://github.com/aws/aws-toolkit-vscode/issues/1461

**Comment by justinmk3** [comment]
To be clear, will setting `AWS_*` environment variables address your request?

**Comment by wparad** [comment]
I don't want to be specify, but our code uses the AWS SDKs, so as long as the default credential provider chain finds the credentials it works. Right now we are using one of the hundred aws...sso....cli things that to spin up a metadata server, and I'm not a fan. It's just necessary for the credentials to exist everywhere in the vs code processes that are created, but our specific use case is debugging, but starting the debug process through the launch.json and via interacting with the AWS SDKs in typescript and rust. So as long as those SDKs look at environment variables, that's fine.
