### ISSUE TITLE
Do we want to cache and watch credential file activity?

### ISSUE THREAD

**Issue by steveataws** [aws/aws-toolkit-vscode#37]
We currently read and parse the credentials file when the user invokes the aws.login command, which is not a time sensitive operation. From the perspective of populating the dropdown list of profiles we don't therefore necessarily need to cache.

Where a file watch is helpful is in when the user deletes a profile we currently have bound in the explorer and views - although we have sdk clients instantiated in those views, view refresh logic may try and instantiate new clients with the now-deleted profile name and fail.

We need to determine the level of caching and file watch needed (current profiles only? all profiles?) and implement, with tests that we can instantiate fresh sdk clients (or error out nicely) if the user deletes an in-use profile.

**Comment by awschristou** [comment]
See #168
