### ISSUE TITLE
Please add support for Python3.11 Launch Debugger

### ISSUE THREAD

**Issue by Judas2016** [aws/aws-toolkit-vscode#3703]
## Problem
Invalid launch configuration: Run configurations for Image-based Lambdas require a valid Lambda runtime value, expected one of [python3.7, python3.8, python3.9, dotnet6, java11, dotnet5.0, dotnetcore3.1, java8.al2, go1.x, python3.10, nodejs12.x, java8, nodejs14.x, nodejs16.x, nodejs18.x]

when setting "runtime": "python3.11"

## Steps to reproduce the issue

Debug with similar launch.json configuration 
{
    "configurations": [
        {
            "type": "aws-sam",
            "request": "direct-invoke",
            "name": "configuration-update:xxxFunction",
            "invokeTarget": {
                "target": "template",
                "templatePath": "${workspaceFolder}/xxx/template.yaml",
                "logicalId": "xxxFunction"
            },
            "lambda": {
                "payload": {
                    "json": {
                        "field": "value"
                    }
                },
                "environmentVariables": {},
                "runtime": "python3.11"
            }
        }
    ]
}
## Expected behavior
Launcher works as expected and code is debugged. 

## System details (run the `AWS: About Toolkit` command)

-   OS: MacOS 13.4
-   Visual Studio Code version: 1.80.2 universal
-   AWS Toolkit version: 1.82.0

**Comment by justinmk3** [comment]
Included in AWS Toolkit 1.86.
