### ISSUE TITLE
use-container support for deploying sam applications

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#371]
This allows users to deploy sam applications that have native package references. (Otherwise they can deploy, but the lambda functions may not run)

Setting should go inside a template's `options` object

```javascript
{
    templates: {
        [ relativePath: string ]: {
            handlers: {
                [ name: string ]: {
                    useContainer?: boolean
                }
            }
            parameterOverrides: {
                [ key: string ]: string
            }
            options?: {
                useContainer?: boolean // default: undefined (do not use container)
            }
        }
    }
}
```

Acceptance Criteria:
* Each template configuration has an optional `useContainer` boolean 
* if the value is missing, it is treated as false
* when sam applications are deployed, the template config drives usage of the `--use-container` arg when running sam cli
* autocompletion support for the field provides a description, and mentions false as the recommended/default value (if #369 is not delivered yet, break this into a separate task)

**Comment by jpangburn** [comment]
When this is implemented, will it also allow a container build when using the "debug locally" CodeLens link?  Right now I'm using the command line and remote debugger to debug because I need a container build, so this feature supporting that too would be nice.  Thanks!

**Comment by awschristou** [comment]
Hi @jpangburn , issue #370 sounds like what you are asking for. If so, could you please react or comment on that one?

**Comment by justinmk3** [comment]
AWS Toolkit 1.12 (released today) includes the new [SAM local Lambda debugging experience](https://github.com/aws/aws-toolkit-vscode/pull/1215) which leverages VS Code "launch configurations". 

Full documentation: https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/run-debug-sam-app.html

The  `aws-sam` launch configuration supports a `sam.containerBuild` field which internally sets `--use-container`.
