### ISSUE TITLE
handler config falls back to to template config when use-container is not present

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#372]
Acceptance Criteria:
* When locally running/debugging a function, if the handler config does not have a `useContainer` value, the parent template's config value for `useContainer` is used instead
* if neither config has this value set, default to false
* autocomplete description for the handler config mentions the fallback approach

**Comment by justinmk3** [comment]
AWS Toolkit 1.12 (released today) includes a new [SAM local Lambda debugging experience](https://github.com/aws/aws-toolkit-vscode/pull/1215) which leverages VS Code _launch configurations_. 

Correct me if I'm wrong, but I don't think this feature is needed with the new UX.
