### ISSUE TITLE
handler config falls back to to template config when docker network option is not present

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#375]
Acceptance Criteria:
* When locally running/debugging a function, if the handler config does not have a `dockerNetwork` value, the parent template's config value for `dockerNetwork` is used instead
* if neither config has this value set, default to false
* autocomplete description for the handler config mentions the fallback approach

**Comment by justinmk3** [comment]
aws-sam launch configs don't have a dockerNetwork option, so I don't think this issue is relevant. We would instead look at supported samconfig.toml, if anything: https://github.com/aws/aws-toolkit-vscode/issues/2011
