### ISSUE TITLE
Add support for python3.11 in debugging profiles

### ISSUE THREAD

**Issue by goosewin** [aws/aws-toolkit-vscode#3753]
## Problem
As of now, the AWS Toolkit for VS Code does not support the `python3.11` runtime for SAM debugging profiles. Even though AWS Lambda has begun supporting `python3.11`, users trying to utilize this runtime in their SAM debugging profiles with targets set as `code` or `template` encounter an error.

## Expected behavior
When a user sets the runtime to `python3.11` in their SAM debugging profiles, they should be able to debug their Lambda functions without encountering any errors.

## Proposed solution
* Update the runtime validation logic to include `python3.11`
* Ensure the debugging docker images (if any) used by the toolkit are updated or have versions that support `python3.11`

**Comment by justinmk3** [comment]
Included in AWS Toolkit 1.86.
