### ISSUE TITLE
Users can skip pulling container images

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#376]
To be determined: if configured to skip images, toolkit should prompt user once every 24 hours if they'd like to check for a newer container. It would be better if we're able to query the container ourselves to see if a newer one is available. This might spin off into another task.

Acceptance Criteria:
* An extension configuration exists that allows users to toggle whether or not they want to skip pulling container images when running sam cli commands
* configuration defaults to false (do not skip)
* configuration setting has a useful description
* when the configuration value is true, `--skip-pull-image` is passed to sam build and sam local calls

**Comment by bryceitoc9** [comment]
(context backported from https://github.com/aws/aws-toolkit-vscode/pull/552 )

Internally while discussing this, we concluded that we should have a call to Docker to check to see if the images need to be updated (we just won't force it on them during the run). We may need to create a wrapper for Docker calls.

**Comment by justinmk3** [comment]
Not implemented in 1.12

**Comment by justinmk3** [comment]
This was implemented as `skipNewImageCheck` in `aws-sam` launch config.
