### ISSUE TITLE
Insufficient permissions to execute command. Configure a task role as described in the documentation.

### ISSUE THREAD

**Issue by copyNdpaste** [aws/aws-toolkit-vscode#3797]
Followup to #3767

## System details (run the `AWS: About Toolkit` command)

-   OS: mac 13
-   Visual Studio Code version: 1.81.1
-   AWS Toolkit version: v1.87.0

### error
![image](https://github.com/aws/aws-toolkit-vscode/assets/18900976/59605269-e2ab-4179-a87d-70116232e0a3)

Hello

I connected my aws profile on vscode.
Tried 'open terminal'.
And chose task id.
![image](https://github.com/aws/aws-toolkit-vscode/assets/18900976/fd8f3890-0bbd-43fd-a29a-d41b590f6dd8)
But `Insufficient permissions to execute command. Configure a task role as described in the documentation.` raised..

What policies should I add to my user on AWS IAM that using on vscode??
Or should I add policies to ecsTaskExecutionRole??

I added this on task-definition.json
```json
            "linuxParameters": {
                "initProcessEnabled": true
            }
```

```json
    "executionRoleArn": "arn:aws:iam::796195479418:role/ecsTaskExecutionRole",
```

documentation : https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html#ecs-exec-enabling-and-using

---------------

I used [`check-ecs-exec`](https://github.com/aws-containers/amazon-ecs-exec-checker) tool to check missing conf.

![image](https://github.com/aws/aws-toolkit-vscode/assets/18900976/fbee6286-e4c0-4c32-9871-831b3566f2cd)

```
  Can I ExecuteCommand?  | arn:aws:iam::x:user/xxx
     ecs:ExecuteCommand: allowed
     ssm:StartSession denied?: implicitDeny
  Task Status            | RUNNING
  Launch Type            | Fargate
  Platform Version       | 1.4.0
  Exec Enabled for Task  | OK
  Container-Level Checks |
    ----------
      Managed Agent Status
    ----------
         1. RUNNING for "nginx"
         2. STOPPED (Reason: null) for "sphinxsearch" - LastStartedAt: null
         3. RUNNING for "flask"
    ----------
      Init Process Enabled (fargate-task:x)
    ----------
         1. Enabled - "flask"
         2. Enabled - "nginx"
         3. Enabled - "sphinxsearch"
    ----------
      Read-Only Root Filesystem (fargate-task:x)
    ----------
         1. Disabled - "flask"
         2. Disabled - "nginx"
         3. Disabled - "sphinxsearch"
  Task Role Permissions  | arn:aws:iam::xxx:role/ecsTaskExecutionRole
     ssmmessages:CreateControlChannel: implicitDeny
     ssmmessages:CreateDataChannel: implicitDeny
     ssmmessages:OpenControlChannel: implicitDeny
     ssmmessages:OpenDataChannel: implicitDeny
  VPC Endpoints          | SKIPPED (vpc-x - No additional VPC endpoints required)
  Environment Variables  | (fargate-task:253)
       1. container "flask"
       - AWS_ACCESS_KEY: not defined
       - AWS_ACCESS_KEY_ID: not defined
       - AWS_SECRET_ACCESS_KEY: not defined
       2. container "nginx"
       - AWS_ACCESS_KEY: not defined
       - AWS_ACCESS_KEY_ID: not defined
       - AWS_SECRET_ACCESS_KEY: not defined
       3. container "sphinxsearch"
       - AWS_ACCESS_KEY: not defined
       - AWS_ACCESS_KEY_ID: not defined
       - AWS_SECRET_ACCESS_KEY: not defined
```

**Comment by justinmk3** [comment]
Toolkit checks for these permissions: https://github.com/aws/aws-toolkit-vscode/blob/343ac220ca065fbea4a56a53e6052047d9ec6db8/src/ecs/util.ts#L47-L50

**Comment by copyNdpaste** [comment]
@justinmk3 
Thank you!
Yesterday I found this [document](https://repost.aws/ko/knowledge-center/fargate-ecs-exec-errors).
I will try
