### ISSUE TITLE
AWS CodeCatalyst VSCode ssh connection timeout stuck dev environment

### ISSUE THREAD

**Issue by frosk1** [aws/aws-toolkit-vscode#3810]
## Problem

There is a problem when I want to connect in vs code to a aws codecatalyst dev environment via the aws toolkit extension, that the vscode ssh remote environment gets stuck in connecting to the host at

"Setting up SSH Host (details) Initializing VS Code Server"

After trying to connect via ssh I got the error message with more details:

"kex_exchange_identification: Connection closed by remote host

Connection closed by UNKNOWN port 65535"

## Expected behavior

vs code remote ssh extenstion should connect to the catalyst dev environemnt without any issue

## System details (run the `AWS: About Toolkit` command)

-   OS: windows10/11
-   Visual Studio Code version:1.82
-   AWS Toolkit version:1.87.0

**Comment by frosk1** [comment]
I already have a fixe for this bug:


After a long and tedious error search I finally could solve the issue.
`Host aws-devenv-*
ForwardAgent yes
AddKeysToAgent yes
StrictHostKeyChecking accept-new
ProxyCommand "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy RemoteSigned -File "c:\Users\{username}\AppData\Roaming\Code\User\globalStorage\amazonwebservices.aws-toolkit-vscode\codecatalyst_connect.ps1" %h`

This command invokes a somehow not really documented and updated powershell script generated from the toolkit.

By debugging this script I found, that it makes an http POST request by using the windows powershell "Invoke-WebRequest" command. This command has given an error, which has not been logged.

The error was due to missing capabilities to parse the http response, to fix this the Internet Explorer or Edge needed to be run at least once. If this has not happend, windows does not initialize some libraries to use in powershell...

So everyone having these issues on windows when want to connect to aws codecatalyst dev environemtns via VSCode make sure to do the following:

have openssh installed version > 7.6
have run InternetExplorer or Edge at least one time

Imagine I would have tested this on a windows os where IE or Edge would have been run/initilaized already, would have never found this bug....

**Comment by frosk1** [comment]
THE FIX:

change the webrequest in file "codecatalyst_connect.ps1" Line 71:

`$webRequest = Invoke-WebRequest -Method 'PUT' -Uri "$Endpoint$startSessionPath" -Headers @{"Content-Type" = "application/json"; "Authorization" = "Bearer $Token" } -Body "$startSessionQuery"`


to 

`$webRequest = Invoke-WebRequest -Method 'PUT' -Uri "$Endpoint$startSessionPath" -Headers @{"Content-Type" = "application/json"; "Authorization" = "Bearer $Token" } -Body "$startSessionQuery" --UseBasicParsing`

**Comment by justinmk3** [comment]
@frosk1 Thank you, that is extremely helpful. Nice debugging!

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/3817 includes your suggestion. Can you try the vsix and confirm that it fixes your issue: 


1. Download and extract [buildArtifacts.zip](https://github.com/aws/aws-toolkit-vscode/files/12563571/buildArtifacts.zip)
2. In VSCode, run `Extensions: Install from VSIX` to install the `*.vsix` file. (You can run commands with `ctrl-shift-p` or `cmd-shift-p`) 
3. Reload VSCode and verify that the Toolkit has the new version (not the older version).

**Comment by frosk1** [comment]
@justinmk3 works

**Comment by justinmk3** [comment]
Included in AWS Toolkit 1.90! We also are considering improving that script to make the logs and failures more visible. Thanks again for debugging this.

**Comment by frosk1** [comment]
Sounds great
