### ISSUE TITLE
not able to connect vscode to aws 

### ISSUE THREAD

**Issue by mtariqsajid** [aws/aws-toolkit-vscode#3847]
i am using windows 11 vscode 
but its not able to connect to aws code whisper

client_id: https://view.awsapps.com/start/user-consent/authorize.html?clientId=M3hPcmNwUktnSWI3S2lQT2dHV3ZFblZ6TFdWaGMzUXRNUQ&clientType=aGFzQ29uc2VudERldGFpbHNwdWJsaWM&

![image](https://github.com/aws/aws-toolkit-vscode/assets/68206359/1145ede1-6baf-4d50-8329-2155de6b0efc)

**Comment by justinmk3** [comment]
For troubleshooting, can you try deleting (or temporarily move/rename) your `~/.aws/sso/` folder (if it exists)?

**Comment by mtariqsajid** [comment]
> For troubleshooting, can you try deleting (or temporarily move/rename) your `~/.aws/sso/` folder (if it exists)?

deleting sso directory worked thank you
