### ISSUE TITLE
DynamoDB Missing

### ISSUE THREAD

**Issue by mattdicks** [aws/aws-toolkit-vscode#3850]
## Problem
DynamoDB is missing from the AWS resources.

## Steps to reproduce the issue

1. Go to 'AWS Toolkit' on the left nav.
2. Connect to AWS account
3. Click on 'Region' or make sure you're in the correct region.
4. DynamoDB is missing from the list of AWS resources.

## Expected behavior
DynamoDB shows up on the list of AWS resources.

## System details (run the `AWS: About Toolkit` command)

-   OS: MAC Ventura 13.4.1
-   Visual Studio Code version: Version: 1.82.2 (Universal)
-   AWS Toolkit version: 1.91.0

**Comment by justinmk3** [comment]
The `Resources` node has basic info about all resources exposed by [AWS Cloud Control](https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/what-is-cloudcontrolapi.html).

It would be helpful if you can upvote the existing tracking issue for more featureful DynamoDB support:
https://github.com/aws/aws-toolkit-vscode/issues/1421

Thanks
