### ISSUE TITLE
"Invalid code", cant sign in

### ISSUE THREAD

**Issue by YonatanAriel** [aws/aws-toolkit-vscode#3862]
## System details (run the `AWS: About Toolkit` command)

-   OS:
-   Visual Studio Code version:
-   AWS Toolkit version:

## Question
always get this error - Invalid code. Please try again. i cant sign in. it worked before

**Comment by justinmk3** [comment]
Is the error displayed in your web browser or in the AWS Toolkit? Can you show a screenshot or give more specific details?

For troubleshooting, also try deleting or temporarily moving the `~/.aws/sso/` directory.
