### ISSUE TITLE
VSCode login failure with remote WSL: Failed to setup

### ISSUE THREAD

**Issue by alexdeoliveira** [aws/aws-toolkit-vscode#3863]
## Problem
Using VSCode with WSL, after clicking on the “Sign up or Sign in” button it displays the error “Failed to setup” and I cannot enable the plugin.

## Steps to reproduce the issue

1. Install the plugin in VSCode using WSL
![image](https://github.com/aws/aws-toolkit-vscode/assets/34426/1f82a996-709c-42bc-aaa7-3832fe954b48)

2. Click on the AWS tab → Connect to AWS to Get Started → CodeWhisperer…
![image](https://github.com/aws/aws-toolkit-vscode/assets/34426/688c4b51-cdd7-42a4-b90c-5949e869f814)

3. Click on the “Sign up or Sign in” button
![image](https://github.com/aws/aws-toolkit-vscode/assets/34426/087e6ea9-cdd8-49ec-93a9-2eac0c174581)

Debug log:
```
2023-09-29 11:41:41 [DEBUG]: API response (oidc.us-east-1.amazonaws.com /client/register): {
  '$metadata': {
    httpStatusCode: 200,
    requestId: '[omitted]',
    extendedRequestId: undefined,
    cfId: undefined
  },
  clientId: '[omitted]',
  clientIdIssuedAt: 1695998502,
  clientSecret: '[omitted]',
  clientSecretExpiresAt: 1703774502
}
2023-09-29 11:41:41 [ERROR]: AuthWebview: Failed to setup: Failed to connect to AWS Builder ID
2023-09-29 11:41:41 [DEBUG]: Webview called command "isCodeWhispererBuilderIdConnected" with args: []
2023-09-29 11:41:41 [DEBUG]: Webview called command "failedAuthAttempt" with args: [
  {
    authType: 'awsId',
    featureType: 'codewhisperer',
    reason: 'defaultFailure'
  }
]
2023-09-29 11:41:41 [VERBOSE]: telemetry: emitted metric "auth_addConnection"
```

## Expected behavior
Display the window to continue authentication in the browser

## System details (run the `AWS: About Toolkit` command)

- OS: Microsoft Windows 11 Pro - Version 10.0.22621 Compilation 22621
- Visual Studio Code version: 1.82.2
- AWS Toolkit version: v1.91.0

**Comment by nkomonen-amazon** [comment]
@alexdeoliveira thanks for the detailed report.

Could you try again with the latest AWS Toolkit extension. The error log for this case should contain more detail than before and may help narrow down the issue.

**Comment by alexdeoliveira** [comment]
Hello @nkomonen-amazon , thank you very much for your response.

I updated the extension as per your suggestion, and after attempting to click the "Sign In" button, more detailed error logs appeared:

```
2023-10-13 15:47:49 [ERROR]: webviewId="authWebview": Error: Webview error
	 -> Error: Webview backend command failed: "startCodeWhispererBuilderIdSetup()"
	 -> Error: Failed to connect to AWS Builder ID [FailedToConnect]
	 -> Error: Failed to save "/home/alex/.aws/sso/cache/aws-toolkit-vscode-client-id-us-east-1-d4a6d746[omitted]1d31f16109623.json" [FSWriteFailed] (key: [object Object])
	 -> EntryExists (FileSystemError): Unable to create folder '/home/alex/.aws' that already exists but is not a directory [FileExists]
```

As we can see, there was an issue creating the folder in the .aws directory. I found that there was a shortcut file pointing to a non-existent folder in the Windows directory.

I recently migrated my disk, and it seems the path was incorrect.

I simply adjusted the shortcut path, and everything worked correctly.

Thank you, you may close this issue.
