### ISSUE TITLE
CodeWhisperer: handle quotes or brackets better

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-toolkit-vscode#3873]
## Problem
When using CodeWhisperer, I see suggestion like the below image many times. You can see duplicated closing quotes; one is from VSCode completion and the other is from CodeWhisperer's suggestion. Can we handle these quotes better in this situation? I don't want to manually remove the unnecessary closing quote after accepting CW suggestion.

<img width="325" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/7490655/7fca41db-fdeb-40ad-b1c2-a061e717ccf0">

The same can happen also with brackets.

<img width="305" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/7490655/1d3700a5-29f1-461d-8cc5-84f52b5fd6ef">

## Expected behavior
No duplicated quote or brackets.

**Comment by Will-ShaoHua** [comment]
Will fix within the PR #3865

**Comment by Will-ShaoHua** [comment]
hey @tmokmss , the fix is released today with plugin version 1.97.0, please give it a try and let us know if the issue still persist

**Comment by tmokmss** [comment]
@Will-ShaoHua Nice!! As far as I tested it now seems perfectly fixed. Thank you for the great work!
