### ISSUE TITLE
When our configuration file `.aws/templates.json` is opened in VS Code, it is treated as json rather than jsonc

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#390]
If you open one of vscode's config files (i.e. `.vscode/launch.json`), it defaults to jsonc ("JSON with Comments). We should determine how this is set, and change it to jsonc for our config files.

**Comment by bryceitoc9** [comment]
Looks like it's hardcoded in: https://github.com/Microsoft/vscode/blob/master/extensions/configuration-editing/package.json#L36

I'm not sure if we can apply something similar to the above to our configs. If we open our files via commands, we can specify the language (I don't believe opening through the file tree/through a file explorer would be able to pick up the filetype)

**Comment by mpiroc** [comment]
Could we use the [`files.associations` contribution point](https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language)? I.e.

```jsonc
"files.associations": {
    "templates.json": "jsonc",
}
```

**Comment by justinmk3** [comment]
AWS Toolkit 1.12 (released today) includes a new [SAM local Lambda debugging experience](https://github.com/aws/aws-toolkit-vscode/pull/1215) which leverages VS Code _launch configurations_. 

Toolkit no longer uses `.aws/templates.json`
