### ISSUE TITLE
IAM creds don't work with a c# service

### ISSUE THREAD

**Issue by dmrickey** [aws/aws-toolkit-vscode#3921]
## Problem
Running a c# service, it doesn't actually used the authenticated IAM credentials with the running service. I still have to auth through VS Code's terminal for the service to be able to interact with AWS.

## Steps to reproduce the issue
Run a c# MVC service and be authenticated via the AWS toolkit

## Expected behavior
Work as expected

## System details (run the `AWS: About Toolkit` command)
```
OS: Windows_NT x64 10.0.22621
Visual Studio Code extension host:  1.80.2
AWS Toolkit:  1.95.0
node: 16.17.1
electron: 22.3.14
```

**Comment by justinmk3** [comment]
Please provide exact steps. Are you running a SAM lambda? 

Or are you expecting AWS Toolkit credentials to be forwarded-to the vscode terminal? That is work in progress: https://github.com/aws/aws-toolkit-vscode/pull/3040
