### ISSUE TITLE
Extension always opens OUTPUT panel at VS Code start

### ISSUE THREAD

**Issue by rafrafek** [aws/aws-toolkit-vscode#3930]
## Problem

OUTPUT panel always opens at VS Code launch

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://github.com/aws/aws-toolkit-vscode/assets/23004737/4dc20bff-a1bb-43f7-99f9-10e0b61015e9">
  <source media="(prefers-color-scheme: light)" srcset="https://github.com/aws/aws-toolkit-vscode/assets/23004737/43e4e9c3-97cd-4aee-a37c-3e4a3c78838d">
  <img width="1390" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/23004737/4dc20bff-a1bb-43f7-99f9-10e0b61015e9">
</picture>

## Steps to reproduce the issue

1. Install the extension
2. Close all panels and close VS Code
3. Open VS Code and see the OUTPUT panel

Disabling this extension fixes the issue.

## Expected behavior

No OUTPUT panel at VS Code launch

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://github.com/aws/aws-toolkit-vscode/assets/23004737/f0424f39-2bdc-4716-b802-fd8072317dc8">
  <source media="(prefers-color-scheme: light)" srcset="https://github.com/aws/aws-toolkit-vscode/assets/23004737/54028813-6cc6-4c43-b8cb-b015e1dcf989">
  <img width="1346" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/23004737/f0424f39-2bdc-4716-b802-fd8072317dc8">
</picture>

## System details (run the `AWS: About Toolkit` command)

-   OS: MacOS Sonoma 14.0
-   Visual Studio Code version: 1.83.1 Darwin arm64
-   AWS Toolkit version: v1.95.0

`AWS: About Toolkit` command output:
OS: Darwin arm64 23.0.0
Visual Studio Code extension host:  1.83.1
AWS Toolkit:  1.95.0
node: 18.15.0
electron: 25.8.4

**Comment by rafrafek** [comment]
Fun fact: my screenshots are both light- and dark- theme compatible 😊

**Comment by object-Object** [comment]
This is the code at fault (added in 029f1d6d8644ae4697e4522a21492f815c383159):

https://github.com/aws/aws-toolkit-vscode/blob/6f50d9aef20ff5f3c1fd83a01265d513f6574431/src/redshift/activation.ts#L22-L24

No other feature opens the output channel on activation, so it's unclear why Redshift needs to.

The issue was introduced in `v1.95.0` of the extension. You can downgrade to `v1.94.0` as a workaround - it doesn't occur on that version.

**Comment by justinmk3** [comment]
This was an accident and will be fixed in this week's release. Thanks for the hint @object-Object !

**Comment by justinmk3** [comment]
Fixed in AWS Toolkit 1.96
