### ISSUE TITLE
ECS exec command: don't require SimulatePrincipalPolicy permissions

### ISSUE THREAD

**Issue by npvisual** [aws/aws-toolkit-vscode#3969]
## Problem

Using the "Open Terminal..." option on an ECS resource works great via the SSO session config (for IAM Identity Center) when using `AWSAdministratorAccess` permissions.

However when using the `AWSPowerUserAccess` permissions, I get the following error : 

```
2023-10-27 09:01:43 [ERROR]: aws.ecs.openTaskInTerminal: AccessDenied: User: arn:aws:sts::xxxx:assumed-role/AWSReservedSSO_AWSPowerUserAccess_xxxx/user is not authorized to perform: iam:SimulatePrincipalPolicy on resource: arn:aws:iam::xxxx:role/pod-1-silo-qa-xxxx because no identity-based policy allows the iam:SimulatePrincipalPolicy action (statusCode: 403; requestId: xxxxxx-f8d9-46b1-bab2-bc3e78724113)

```

What's interesting is that, when using the AWS CLI, I have no problem accessing the ECS instance with the `AWSPowerUserAccess` permissions : 

```
aws --profile staging-power ecs execute-command ...
```

with the following config

```
[profile staging-power]
sso_session = staging-power
sso_account_id = xxxxxx
sso_role_name = AWSPowerUserAccess
region = us-east-1
output = json
```

So I am wondering why the `AWSPowerUserAccess` cannot get access to the ECS instance.

## Steps to reproduce the issue

Go to : 
*  <Your Region>
* ECS
* Select your ECS cluster and task
* On your running container right click and select  "Open Terminal..."

You need to make sure your profile is connecting via the AWS CLI SSO using the `AWSPowerUserAccess` permission.

See error in the logs "Failed to run command: aws.ecs.openTaskInTerminal"

## Expected behavior

I would expect the same behavior that when I use `AWSAdministratorAccess` since I can use either permissions via the AWS CLI's `ecs execute-command` to connect to the ECS container.

## System details (run the `AWS: About Toolkit` command)

-   OS: macOS Sonoma 14.0
-   Visual Studio Code version: Version: 1.83.1 (Universal) -- see more below
-   AWS Toolkit version: v1.96.0

From the "About" menu : 
```
Version: 1.83.1 (Universal)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:46:55.789Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
```

**Comment by justinmk3** [comment]
Thanks for the clear report!

> when using the AWS CLI, I have no problem accessing the ECS instance with the `AWSPowerUserAccess` permissions

Toolkit is attempting `SimulatePrincipalPolicy` so that it can give better info if "exec command" fails. However, perhaps we can first try to proceed, and only attempt `SimulatePrincipalPolicy` if "exec command" fails.

**Comment by npvisual** [comment]
@justinmk3 : works for me.

On a different note I wonder why `iam:SimulatePrincipalPolicy` isn't available for `AWSPowerUserAccess`.
I guess "Power User Access" isn't what it used to be 😉.

**Comment by justinmk3** [comment]
Please try the latest AWS Toolkit!
