### ISSUE TITLE
Aws Toolkit running SAM (Node/Python/Other langs), timeout parameter weird behaviour

### ISSUE THREAD

**Issue by MFlyer** [aws/aws-toolkit-vscode#4004]
## Problem
I have multiple local environments with a template having

`Globals:
  Function:
    Timeout: 120`

Starting from aws toolkit 1.97.0 the default timeout had a value of 1234 millis and, at the same time, it seems not able to honor the yaml template defined Timeout (that's in seconds, not millis)

## System info

-   OS: Ubuntu 20.4
-   Visual Studio Code version: 1.84.0
-   AWS Toolkit version: 1.97.0

## Current workaround

Manually edit aws toolkit default timeout for lambda

**Comment by MFlyer** [comment]
Hi @justinmk3 ,
providing required info and some context about env used to provide you with logs:
- Python 3.8 Runtime,
- No samconfig.toml file in the app folder
- template.yaml has a Globals -> Function -> Timeout with 30 (seconds)
- Changing Timeout to 30000 (assuming millis) doesn't solve, it's the aws toolkit ignoring template.yaml timeout at all

Log file attached

Question of the day: why that "random" 1234 millis as a default, having something like 60000/90000 millis or the aws lambda default timeout should be more logic, don't you agree?! 
[aws_toolkit-logs.txt](https://github.com/aws/aws-toolkit-vscode/files/13278120/aws_toolkit-logs.txt)

**Comment by MFlyer** [comment]
I updated the aws toolkit yesterday morning and I started seeing the timeout, as soon as I understood that the issue was with the default 1234 millis I changed it to an acceptable value.
Currently I'm not able to delete that vscode setting, it seems mandatory, I only found it once after the aws toolkit update and I don't remember the previous value of the field

**Comment by justinmk3** [comment]
> not able to delete that vscode setting, it seems mandatory

The vscode settings UI doesn't really make it easy to "delete" a setting. Instead you would need to edit the settings.json:

1. run `Preferences: Open User Settings (JSON)` vscode command
2. search for `lambdaTimeout`
3. delete that line in the JSON file

**Comment by MFlyer** [comment]
Hi @justinmk3 ,
not able to reproduce it anymore:
- deleted lambdaTimeout property from JSON file
- the aws toolkit still has a timeout equal to 90000 millis (it states it's coming from my workspace settings, but I don't have it in the workspace settings?!)
- uninstalling the aws toolkit extension and installing it again still has the previous added "right" timeout
- no more able to reproduce that weird behaviour

**Comment by justinmk3** [comment]
@MFlyer thank you so much for troubleshooting this. We will try to think of an improvement to the logic here.

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/4054 was included in AWS Toolkit 2.0.0
