### ISSUE TITLE
CodeLenses will not appear on code in similar folders

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#407]
**Describe the bug**

If you have a workspace folder containing two folders, where one folder starts-with the other folder (eg: `myapp` and `myapp1`), codelenses will not appear on files in the second folder

As an aside: an exception is raised that should be logged within each `provideCodeLenses` (maybe `makeCodeLenses`) to help diagnose issues like this.

**To Reproduce**
1. Make a new empty workspace
1. make a new js 8.1 sam app into the workspace folder, called `myapp`
1. make a second js 8.1 sam app into the workspace folder, called `myapp1`
1. the `app.js` fie within `myapp1` will not have codelenses. the `app.js` fie within `myapp` will have codelenses. 

**Expected behavior**

Both files should gain codelenses

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Visual Studio Code Version:
 - AWS Toolkit for Visual Studio Code Version:

**Additional context**

**Comment by justinmk3** [comment]
Cannot reproduce this in Toolkit 1.17
