### ISSUE TITLE
Visualizing step function

### ISSUE THREAD

**Issue by LudwikBielczynski** [aws/aws-toolkit-vscode#4081]
## System details (run the `AWS: About Toolkit` command)

-   OS: Ubuntu 22.04
-   Visual Studio Code version:
-   AWS Toolkit version:

## Question
I am searching for a way to visualize the state function execution graph and execution progress in our companies web app. I searched for a javascript npm package under AWS care but I couldn't find anything. I scoped through the aws-toolkit-vscode codebase and found that during the rendering of the asl graph sfn.StateMachineGraph function is being used from the sfn-0.1.8.js added library (which in the description is called GrapheneStateGraph). I see that this is an Amazon library, but I cannot find any documentation about it.

Is there a way to get some more info about the package and its use?

**Comment by justinmk3** [comment]
> I see that this is an Amazon library, but I cannot find any documentation about it.

Currently it's not publicly documented nor supported.

**Comment by LudwikBielczynski** [comment]
Thanks @justinmk3 for a fast answer. Do you maybe know if there is any publicly available packages with documentation from AWS supporting that functionality?

**Comment by jormello** [comment]
As @justinmk3 mentioned, while the resources used for providing the visualization capability in the AWS Toolkit are publicly accessible, the service team does not provide any official documentation or support for the functionality. With that being said, we are aware that this is a pain point for customers and are looking to address this gap. 

The code related to generating the visualizations in the AWS Toolkit is mainly contained in:
- [aslVisualization.ts](https://github.com/aws/aws-toolkit-vscode/blob/master/src/stepFunctions/commands/visualizeStateMachine/aslVisualization.ts)
- [utils.ts](https://github.com/aws/aws-toolkit-vscode/blob/master/src/stepFunctions/utils.ts)
