### ISSUE TITLE
Is Amazon Q available for SSO in us-east-2 (IdC / SSO)?

### ISSUE THREAD

**Issue by Vinci08** [aws/aws-toolkit-vscode#4100]
## System details (run the `AWS: About Toolkit` command)

-   OS: Windows
-   Visual Studio Code version: 1.84.2
-   AWS Toolkit version: 2.0.0 2023-11-28

## Question
 I try to understand if AWS Q and Code Whisperer is available in VS Code for users with SSO in us-east-2. I followed the signin URL to use SSO and got this message:

> AWS Toolkit for VSCode can now access your data.
>
> You can close this window and start using AWS Toolkit for VSCode.

However, Amazon Q in VS Code just gave me back this error message "Permissions for this service may not be enabled by your SSO Admin, or the selected region may not be supported." I already added AmazonQFullAccess permission to my user just to test it out, but the error remained. Does this mean Amazon Q is only available to us-east-1 users during the preview?

**Comment by justinmk3** [comment]
Thanks for your question!

https://docs.aws.amazon.com/amazonq/latest/aws-builder-use-ug/regions.html indicates that us-east-2 is supported.

Have you set up Amazon Q in [AWS console](https://us-west-2.console.aws.amazon.com/amazonq/home#user-provisioning)?

**Comment by Vinci08** [comment]
Hi @justinmk3 , thank you for the links. The AWS console only allowed me to select between us-east-1 and us-west-2. I added my work email to test, but there's no additional communication from AWS whether I was added or how I should proceed. I tried again with VS Code and still had the same error message about selected region may not be supported. 

Since this is for work, I would rather authenticate via IAM Identity Center than AWS Builder. Please let me know if there're any other way to authenticate this. 

PS: AWS Explorer works just fine in VS Code if that info helps. Thanks

**Comment by andrewyuq** [comment]
Hi @Vinci08, check if you have the following:
1) In AWS Console, IAM Identity Center is setup in us-east-2.
2) A user for you has been created as part of the setup in 1).
3) In AWS Console, CodeWhisperer, CodeWhisperer Enterprise has been setup and you are added as a user to this enterprise.
4) In VSCode, enter the startUrl and region(us-east-2) when login to IAM Identity Center for CodeWhisperer.

**Comment by Vinci08** [comment]
hi @andrewyuq. To answer your inquiries:
1. yes it's in us-east-2. 
2. i am using my username
3. When I go to AWS CodeWhisperer, I got this. My region on top menu is still us-east-1.
![image](https://github.com/aws/aws-toolkit-vscode/assets/15873863/c1e04710-da34-4df6-8216-23d44442185e)

 I assume the error from step 3 made step 4 irrelevant.

**Comment by andrewyuq** [comment]
@Vinci08 I see what's going on here. 
The doc says: 
> Amazon Q in the AWS Management Console, AWS Marketing Website, AWS Documentation, AWS Console Mobile Application, and AWS Chatbot is available in the following AWS Regions.
It's referring to the AWS Q in the AWS Console. 
<img width="1791" alt="Screenshot 2023-12-06 at 1 18 29 PM" src="https://github.com/aws/aws-toolkit-vscode/assets/89420755/3540e034-9862-4743-9419-60463491c215">


If you are using Amazon Q in IDE, using IAM Idenity Center, then you will need to configure the IAM Identity Center is setup in us-east-2 and Amazon CodeWhisperer Enterprise(only available in us-east-1).

**Comment by justinmk3** [comment]
This documentation may be helpful: https://docs.aws.amazon.com/codewhisperer/latest/userguide/q-authentication.html
