### ISSUE TITLE
Errors on every command, can't do anything, tried reinstalling and older versions

### ISSUE THREAD

**Issue by brandon-constratum** [aws/aws-toolkit-vscode#4102]
## Problem
I receive "Error running command aws.*: command 'aws.*' not found. This is likely caused by the extension that contributes aws.*." errors for every command on the latest version from vscode marketplace and the vsix from github.

## Steps to reproduce the issue
1. Install from Github or VSCode
2. Try to perform any function like "Connect to AWS" or "Send Feedback"

## System details (run the `AWS: About Toolkit` command)
-   OS: Mac Ventura 13.6
-   Visual Studio Code version: 1.84.2 (Universal)
-   AWS Toolkit version: 2.0.0 (also tried with 1.100 and 1.99 and they did similar things, 1.13 let me connect to AWS but on update provided the same errors)

**Comment by justinmk3** [comment]
> 1.13 let me connect to AWS but on update provided the same errors

This indicates that vscode's state was somehow corrupted. 

AWS Toolkit only defines what commands it provides, it doesn't touch vscode's state. So this is likely a vscode bug.

A workaround is to delete vscode's state, found in your home directory (this is destructive, so it's better to rename the directory rather than delete it): `~/Library/Application Support/Code/User/`

**Comment by brandon-constratum** [comment]
> > 1.13 let me connect to AWS but on update provided the same errors
> 
> This indicates that vscode's state was somehow corrupted.
> 
> AWS Toolkit only defines what commands it provides, it doesn't touch vscode's state. So this is likely a vscode bug.
> 
> A workaround is to delete vscode's state, found in your home directory (this is destructive, so it's better to rename the directory rather than delete it): `~/Library/Application Support/Code/User/`

ahhh that makes sense, thanks for the quick reply, just tried a reinstall which didn't work but your workaround fixed it, thanks!!!
