### ISSUE TITLE
CodeWhisperer keeps asking me to sign in every time I restart VSCode (remote ssh to EC2)

### ISSUE THREAD

**Issue by TuscanShores** [aws/aws-toolkit-vscode#4121]
-   OS: MacOS Sonoma
-   Visual Studio Code version:
-   AWS Toolkit version:

**Comment by zixlin7** [comment]
Could you please share your toolkit version?

**Comment by TuscanShores** [comment]
It’s version v2.1.0 on Mac OS Sonoma.

Thanks.

From: Zoe Lin ***@***.***>
Date: Tuesday, December 5, 2023 at 12:07 PM
To: aws/aws-toolkit-vscode ***@***.***>
Cc: TuscanShores ***@***.***>, Author ***@***.***>
Subject: Re: [aws/aws-toolkit-vscode] AWS Code Whisperer keep asking me to sign in every time I shut down and start VSCode. (Issue #4121)


Could you please share your toolkit version?

**Comment by sino1641** [comment]
Same in VSC 1.87 and Toolkit 2.10.0 using Builder ID.
My laptop can stay login for 30d as described in #3614 
But I have connected to an EC2 and Toolkit is asking me credential invalid then authenticate again everytime I connect via remote ssh.

**Comment by Kenblair1226** [comment]
I'm using Cursor.sh v0.28.1 (which is VSC v1.86.2) and with AWS toolkit 2.11.0. Seems like whenever I restart my cursor requires to re-login to AWS builder ID.

**Comment by justinmk3** [comment]
The release of Amazon Q since this was reported, includes many improvements and fixes. If this is still an issue, please open a new issue that includes logs and detailed steps.
