### ISSUE TITLE
Unable to use chatbox. 

### ISSUE THREAD

**Issue by pattang56892** [aws/aws-toolkit-vscode#4128]
Why I was advised that "all is set you can now use Tabnine in your IDE / VS Code" , but there is no space / field to type in questions???

**Comment by pattang56892** [comment]
Why do you design a chat where there is no filed to allow you to enter any text?

**Comment by justinmk3** [comment]
Can you show a screenshot of what you're seeing? Amazon Q should look like this:

<img width="613" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/55561878/7b98a3ee-c0ec-4ff6-be24-733f04be080b">
