### ISSUE TITLE
[ERROR]: SamLaunchRequestError: Failed to run launch configuration 	 -> TypeError: Cannot read properties of undefined (reading 'items')

### ISSUE THREAD

**Issue by epietrowicz** [aws/aws-toolkit-vscode#4136]
## Problem
I have just started a new AWS SAM API project and I am having trouble debugging the endpoints in vscode with AWS Toolkit.

## Steps to reproduce the issue

1. `sam init`
2. AWS Quick Start Templates
3. Serverless API
4. nodejs18.x
5. Choose `n` for X-ray tracing and CloudWatch Insights
6. Project name: `debug-test`
```
    -----------------------
    Generating application:
    -----------------------
    Name: debug-test
    Runtime: nodejs18.x
    Architectures: x86_64
    Dependency Manager: npm
    Application Template: quick-start-web
    Output Directory: .
    Configuration file: debug-test/samconfig.toml
    
    Next steps can be found in the README file at debug-test/README.md
```
7. Open the `template.yaml` file and choose `AWS: Add API Debug Configuration` above the `Events` entry of the `getAllItems` lambda function.
8. In VScode's debugger menu, choose the newly generated debug configuration `API debug-test:getAllItemsFunction`

## Expected behavior
The default API debug template to work

## System details (run the `AWS: About Toolkit` command)

-   OS: Darwin x64 23.1.0
-   Visual Studio Code extension host:  1.84.2
-   AWS Toolkit version: 2.1.0
-   Node: 18.15.0
-   Electron: 25.9.2

Setting the AWS Toolkit log level to debug did not provide much additional detail:

```
2023-12-05 09:13:16 [VERBOSE]: SAM debug: config: "API debug-test:getAllItemsFunction"
2023-12-05 09:13:16 [VERBOSE]: telemetry: emitted metric "apigateway_invokeLocal"
2023-12-05 09:13:16 [ERROR]: SamLaunchRequestError: Failed to run launch configuration
	 -> TypeError: Cannot read properties of undefined (reading 'items')
```

**Comment by justinmk3** [comment]
Related? https://github.com/aws/aws-toolkit-vscode/issues/4057

**Comment by akksa** [comment]
I too get the same error. 
any updates?

**Comment by justinmk3** [comment]
A potential fix was merged in https://github.com/aws/aws-toolkit-vscode/pull/4151

Can you try the prerelease? https://github.com/aws/aws-toolkit-vscode/releases/tag/prerelease

**Comment by justinmk3** [comment]
AWS Toolkit 2.3.0 includes a (potential) fix for this. If the issue still occurs with 2.3.0, please let us know.
