### ISSUE TITLE
Get Policy: error

### ISSUE THREAD

**Issue by cbbarclay** [aws/aws-toolkit-vscode#418]
**Describe the bug**
Right click on a function and select get policy, and get an error for some functions that do exist in the Lambda console.

Lambda Function Policy: awscodestar-github-lambda-GetHelloWorld-3A9RETG830TE
Error getting Lambda Function Policy:

Code:
ResourceNotFoundException
Message:
The resource you requested does not exist.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:
 - Visual Studio Code Version:
 - AWS Toolkit for Visual Studio Code Version:

**Additional context**

**Comment by awschristou** [comment]
This feature will be removed with #460. Closing.
