### ISSUE TITLE
Unable to copy and paste responses from Amazon Q

### ISSUE THREAD

**Issue by williamchiu-nmic** [aws/aws-toolkit-vscode#4192]
## Problem

Unable to copy text (non-code) from Amazon Q prompts and responses.

## Steps to reproduce the issue

1. Click on the Amazon Q chat extension button
2. Copy the text "Hi, I'm Amazon Q."
3. Paste the text into a new text file.

## Expected behavior

"Hi, I'm Amazon Q." should appear in the text file. Actual behavior is a blank line is inserted into the new text file.

## System details (run the `AWS: About Toolkit` command)

OS: Windows_NT x64 10.0.22621
Visual Studio Code extension host:  1.85.1
AWS Toolkit:  2.4.0
node: 18.15.0
electron: 25.9.7

Other extensions installed:

```
code --list-extensions

amazonwebservices.aws-toolkit-vscode
donjayamanne.githistory
GitHub.remotehub
GitHub.vscode-pull-request-github
GrapeCity.gc-excelviewer
mechatroner.rainbow-csv
ms-dotnettools.vscode-dotnet-runtime
ms-mssql.mssql
ms-mssql.sql-bindings-vscode
ms-python.black-formatter
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-toolsai.datawrangler
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode-remote.vscode-remote-extensionpack
ms-vscode.remote-explorer
ms-vscode.remote-repositories
ms-vscode.remote-server
oderwat.indent-rainbow
quarto.quarto
tomoki1207.pdf
```

**Comment by justinmk3** [comment]
This is fixed in the latest version of Amazon Q
