### ISSUE TITLE
Selected regions in AWS Explorer pane do not persist order after restarting IDE

### ISSUE THREAD

**Issue by bryceitoc9** [aws/aws-toolkit-vscode#421]
**Describe the bug**
Adding regions to the AWS Explorer list the regions in the order that you added them in. Upon restarting the IDE, the regions revert to the order that they appear in in the Command Palette when selecting the regions. 

**To Reproduce**
1. Add a bunch of regions to the AWS Explorer with `>AWS: Show region in the Explorer`. Write down this order
  a. For added effect, ensure that the order is not the order the Command Palette lists the regions in
2. Restart IDE
3. Open AWS Explorer panel
4. Note that the order has changed

**Expected behavior**
***Not sure!*** We need to define this. Feedback from the community is very welcome.
Additional considerations: should we only display one region at a time?

**Screenshots**
Before: 
![before](https://user-images.githubusercontent.com/29374703/55115184-1abc1000-50a1-11e9-95f2-8863e5efd1d3.PNG)
After: 
![after](https://user-images.githubusercontent.com/29374703/55115261-52c35300-50a1-11e9-8a8e-c8185543c04f.PNG)

**Desktop (please complete the following information):**
 - OS: All
 - Visual Studio Code Version: All
 - AWS Toolkit for Visual Studio Code Version: All

**Additional context**
The region list comes from the defaultRegionProvider: https://github.com/aws/aws-toolkit-vscode/blob/develop/src/shared/regions/defaultRegionProvider.ts#L45 . This list is consistently ordered (normal regions alphabetized by region code, followed by alphabetized CN, followed by alphabetized GovCloud)

**Comment by justinmk3** [comment]
Regions are always alphabetical order.
