### ISSUE TITLE
tests: code coverage upload sometimes fails

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#4232]
# Problem

codecov upload sometimes fails:

```
[2024-01-05T14:54:04.561Z] ['error'] There was an error running the uploader: 
Error uploading to [https://codecov.io:](https://codecov.io/) 
Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='
Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```

# Expected behavior

- Configure our [ci job](https://github.com/aws/aws-toolkit-vscode/blob/82158f2ac8d4f3240a52127ec0a98db6f60109a6/.github/workflows/node.js.yml#L42-L56) so that it has the necessary codecov token.
- Enable code cover in integ + E2E tests: https://github.com/aws/aws-toolkit-vscode/blob/afbd56082e1f14b8fe38d11169ef36fa5a75eb43/buildspec/linuxIntegrationTests.yml#L12
    - Ensure those jobs have the codecov token.

This may involve adding a token to https://github.com/aws/aws-toolkit-vscode/settings/secrets/actions

**Comment by justinmk3** [comment]
From codecov GHA changelog: https://github.com/codecov/codecov-action/releases/tag/v4.0.0

> * Tokenless uploading is unsupported. However, PRs made from forks to the upstream public repos will support tokenless (e.g. contributors to OS projects do not need the upstream repo's Codecov token). This [doc](https://docs.codecov.com/docs/adding-the-codecov-token#github-actions) shows instructions on how to add the Codecov token.

**Comment by justinmk3** [comment]
GHA runners still show (different than above):

```
[2024-07-12T12:45:47.727Z] ['verbose'] Passed token was 0 characters long
...
[2024-07-12T12:45:47.928Z] ['verbose'] The error stack is: Error: Error uploading to https://codecov.io: Error: There was an error fetching the storage URL during POST: 429 - {'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 2497s.', code='throttled')}
```

**Comment by jpinkney-aws** [comment]
I don't see that error in GHA e.g. https://github.com/aws/aws-toolkit-vscode/pull/5276 shows everything was successful and the token is already set in the repo. Do you have a link to that run?

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/actions/runs/9908163035/job/27373347784?pr=5307

https://github.com/aws/aws-toolkit-vscode/actions/runs/9908163035/job/27373348092?pr=5307

https://github.com/aws/aws-toolkit-vscode/actions/runs/9908163035/job/27373347460?pr=5307

**Comment by justinmk3** [comment]
> GHA runners still show (different than above):

https://github.com/aws/aws-toolkit-vscode/pull/5310
