### ISSUE TITLE
CodeWhisperer with IdC (IAM Identity Center / SSO) never stays signed in for more than a few hours at a time

### ISSUE THREAD

**Issue by doublehelix** [aws/aws-toolkit-vscode#4361]
## Problem
Similar to issues described in #3614, however AM Identity Center, and every few hours.
- #3614 

AWS: IAM Identity centre authentication disconnects form the AWS Toolkit for VSCode after a few hours.
I'm using CodeWhisperer primarily, but every few hours (between 4 and 6 normally) I get disconnected and have to re-authenticate.

Plugin sidebar info:
![image](https://github.com/aws/aws-toolkit-vscode/assets/355130/246af902-c61d-4f5b-8682-584608466b80)

In the footer of VSCode:
![image](https://github.com/aws/aws-toolkit-vscode/assets/355130/acebc01d-d351-46ae-81be-5508a0ea81e6)

So, I re-authenticate.
It's important to note, checking the `This is a trusted device` checkbox seems to do nothing.
If I have to re-authenticate even after a few hours, it asks for my username and password again. My sign-in to `ap-southeast-2.signin.aws/platform/login` never persists.
![image](https://github.com/aws/aws-toolkit-vscode/assets/355130/2394df20-47b1-4c1e-a38b-459244922976)

Then, I allow:
- Enable Amazon CodeWhisperer analysis.
- Enable Amazon CodeWhisperer completions.
- Access to AWS IAM Identity Center accounts and permission sets.

![image](https://github.com/aws/aws-toolkit-vscode/assets/355130/8d6616d0-c485-4995-876e-a235bb6e9e24)

Then after a few hours, it disconnects again, and I have to re-authenticate.
Each time I lose connection in VSCode, my browser session has also expired, and I have to re-enter my credentials from scratch.
("This is a trusted device" I presumed kept me logged in for 7 days as per )

## Expected behavior
IAM stays logged in for up to 7 days

## System details (run the `AWS: About Toolkit` command)

-   OS: Windows_NT x64 10.0.22631
-   Visual Studio Code extension host:  1.85.2
-   AWS Toolkit:  2.7.0
-   node: 18.15.0
-   electron: 25.9.7

**Comment by justinmk3** [comment]
The session timeout for AWS IAM Identity Center (IdC, CodeWhisperer "Professional tier") is controlled by the IdC administrator in the AWS console. 

IdC now supports now supports a [session maximum of 90 days](https://aws.amazon.com/about-aws/whats-new/2023/09/aws-iam-identity-center-session-duration-limit-increases) (configurable by the IdC administrator). 

But the default timeout is still 8 hours:

> The default IAM Identity Center session duration continues to be eight (8) hours and any existing customer-configured session limits will remain unchanged.

This must be configured in AWS IdC, it's not controlled by AWS Toolkit nor the "This is a trusted device" checkbox.

**Comment by doublehelix** [comment]
### SOLVED
Our administrator has confirmed the AIM session timeout was set to 4 hours for "testing".
We've reset it to 30 days.
Will update if this doesn't solve the problem.
Resolved for now.
