### ISSUE TITLE
migrate to AWS SDK for JavaScript v3

### ISSUE THREAD

**Issue by lazyanubis** [aws/aws-toolkit-vscode#4371]
## Problem

My debug console always reports this warning. I'm not sure if it's because there's no upgrade. Why is the development dependency using version 3?  I am confused [Facepalm]

(node:72953) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `Code Helper (Plugin) --trace-warnings ...` to show where the warning was created)

![image](https://github.com/aws/aws-toolkit-vscode/assets/46840787/e4f9b95b-d081-4580-8ba2-15189ee3dba1)

![image](https://github.com/aws/aws-toolkit-vscode/assets/46840787/1ef4b26c-2e37-45fd-8c92-be03fe1912fb)

![image](https://github.com/aws/aws-toolkit-vscode/assets/46840787/49d0e9a3-fa6d-4e5e-a3ba-8ebcf4dbf3b3)

## System details (run the `AWS: About Toolkit` command)

-   OS:
-   Visual Studio Code version:
-   AWS Toolkit version:

**Comment by justinmk3** [comment]
> My debug console always reports this warning.

Are you working on the aws-toolkit-vscode repo itself? Or does it happen on other repos?

We plan to upgrade to v3 but it will take some time. We could try to silence this warning meanwhile, I agree that it's noisy.
