### ISSUE TITLE
webview error: "command aws.codewhisperer.focus not found"

### ISSUE THREAD

**Issue by rishabhChaurasia** [aws/aws-toolkit-vscode#4379]
[Screenshot (9)](https://github.com/aws/aws-toolkit-vscode/assets/83667470/3508a670-ab3b-4329-81c5-836d0fd4c555)
## Problem
i got webview error 

-->

**Comment by justinmk3** [comment]
It looks like you clicked Builder Id step to connect to Amazon Q, right?

Can you provide the Toolkit logs? 

1. In VSCode settings, ensure that "aws log level" is "debug".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View Toolkit Logs` command to get the logs.
4. Remove any private info from the logs.

**Comment by Jasonsssssss** [comment]
I got the same error, while I can use amazon Q properly
```
2024-04-06 00:40:50 [ERROR]: webviewId="authWebview": Error: Webview error
	 -> Error: Webview backend command failed: "showCodeWhispererView()"
	 -> Error: command 'aws.codewhisperer.focus' not found
```

**Comment by pritibiyani** [comment]
I'm facing similar issues with VS code. 

```
Version: 1.88.1 (Universal)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:42:52.765Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin x64 23.4.0
```


Error I'm getting: 
```
2024-04-18 13:52:12.440 [error] webviewId="authWebview": Error: Webview error
	 -> Error: Webview backend command failed: "showCodeWhispererView()"
	 -> Error: command 'aws.codewhisperer.focus' not found
```

**Comment by justinmk3** [comment]
Please update to the latest AWS Toolkit and/or Amazon Q extensions.
