### ISSUE TITLE
Debug nodejs20.x locally.

### ISSUE THREAD

**Issue by DiscreteTom** [aws/aws-toolkit-vscode#4380]
## Problem

NodeJS 20.x is [supported](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) as a lambda runtime.

However when debugging lambda functions with sam according to this [doc](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/serverless-apps-run-debug-no-template.html) using nodejs20.x, got:

```
[ERROR]: SamLaunchRequestError: Invalid launch configuration: Debug Configurations with an invoke target of "code" require a valid Lambda runtime value, expected one of [python3.7, python3.8, python3.9, dotnet6, java11, java8.al2, go1.x, python3.10, java8, python3.11, python3.12, nodejs14.x, nodejs16.x, nodejs18.x]
```

Env:

- SAM CLI: v1.108.0
- AWS Toolkit: 2.8.0

## Expected behavior

Debug locally.

**Comment by justinmk3** [comment]
This is implemented in the latest release. Thanks for reporting it!
