### ISSUE TITLE
Lambda: better UX for "no functions for this region"

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-vscode#44]
Currently the explorer shows "...no functions for this region..." like so:
![screen shot 2018-09-10 at 2 30 25 pm](https://user-images.githubusercontent.com/4661536/45325590-292c4b00-b506-11e8-8878-8f78a98d1d11.png)

It probably makes more sense to either have this show as a disabled node so that it's more obvious it's a placeholder node.

**Comment by justinmk3** [comment]
<img width="223" alt="image" src="https://github.com/user-attachments/assets/aa404e4c-75f8-485a-8394-f851d62d3f67">
