### ISSUE TITLE
Application Composer Issues

### ISSUE THREAD

**Issue by paul-uz** [aws/aws-toolkit-vscode#4410]
* Parameters not supported
* Mappings not supported
* Conditions not supported
* Removes parameters added manually in the YML
* Doesn't handle `!Ref`'s in properties box for resources like HostedZone, have to keep redoing them manually

<img width="319" alt="Screenshot 2024-02-08 at 15 41 46" src="https://github.com/aws/aws-toolkit-vscode/assets/73826774/a2c09524-13f5-4377-9eea-aafe211f8318">
<img width="371" alt="Screenshot 2024-02-08 at 15 41 39" src="https://github.com/aws/aws-toolkit-vscode/assets/73826774/a5a2db2c-96f0-451f-be67-6f5e78f793ce">

Example above, you can see how the !Sub function is used in the YML, is bastardised in the Composer settings window.

**Comment by ccaum** [comment]
Thanks, Paul. On the parameters being removed from the template, can you describe the steps you go through to reproduce this? We suspect this might be caused by not saving changes made directly to the template and then making changes in the canvas. To be clear, you _should_ be able to this, but we want to make sure we understand what's triggering it.

**Comment by paul-uz** [comment]
I'll have to try and recreate it step by step but I'm pretty sure it'd happen even after saving the template.

What's interesting is it would leave one parameter alone, despite one of the removed ones being used as a !Ref target.

**Comment by Zizaco** [comment]
The fact that Application Composer removes comments is very annoying

**Comment by JLargent42** [comment]
We rolled out a fix to how we're handling parameters that should address the problem you were facing. 
![image](https://github.com/aws/aws-toolkit-vscode/assets/65189184/6044e9ce-aca0-4e89-8019-bc3a92063465)

We've also updated our template parsing logic, so comments are better preserved now.

Thanks for the feedback, paul-uz and Zizaco!
