### ISSUE TITLE
About Uploading and Downloading

### ISSUE THREAD

**Issue by yuu996** [aws/aws-toolkit-vscode#4419]
## System details (run the `AWS: About Toolkit` command)

-   OS:windows11
-   Visual Studio Code version:1.86.1
-   AWS Toolkit version:2.9.0

## Question

Can I upload and download multiple folders?

**Comment by justinmk3** [comment]
Not yet, but it's in our backlog: https://github.com/aws/aws-toolkit-vscode/issues/3008
