### ISSUE TITLE
Allow for an arbitrary amount of debugger attachment retries via user prompts

### ISSUE THREAD

**Issue by bryceitoc9** [aws/aws-toolkit-vscode#446]
**Is your feature request related to a problem? Please describe.**
Stemming from https://github.com/aws/aws-toolkit-vscode/pull/440#discussion_r271497890, we currently have a user-configurable amount of retries in the event of debugger attachment failure. Implementing some sort of user action will signal to the user that something is wrong and allow them to proceed if they'd like. Limiting retries based on a number is more arbitrary and can break users if they don't realize the option to increase retries exists.

**Describe the solution you'd like**
A warning prompt telling users that the debugger is having issues connecting to the application, with a button to retry the debugger attach (queue up multiple retries so users won't have to continuously click the button) or cancel the execution.

**Describe alternatives you've considered**
User-configurable retry quantity (implemented soon, see https://github.com/aws/aws-toolkit-vscode/pull/440)

**Comment by mpiroc** [comment]
Closing as we no longer use retry-logic for timing the debugger attach.
