### ISSUE TITLE
codewhisperer: I can't login (blank webview)

### ISSUE THREAD

**Issue by JohnSmall** [aws/aws-toolkit-vscode#4511]
## Problem
I can't connect
## Steps to reproduce the issue
1) install the AWS extension
2) select any item, e.g. explorer or code whisperer
3) select "Connect to AWS to get started" I get a blank document so I can't connect

## Expected behavior
I should see options to connect 

-   OS: Ubuntu 22.04
-   Visual Studio Code version: 1.87.0
-   AWS Toolkit version: 2.12.0

**Comment by justinmk3** [comment]
> 3\. I get a blank document

Sounds like the webview isn't working. Do other webviews work in the same vscode instance?

Can you provide the Toolkit logs? 

1. In VSCode settings, ensure that "aws log level" is "debug".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View Toolkit Logs` command to get the logs.
4. Remove any private info from the logs.
