### ISSUE TITLE
Remove stack trace from Explorer Error view

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#456]
When the Explorer contains an error node, and the user shows error details, the view includes a stack trace. The stack trace applies to the Toolkit code, and is not something a user could act on. It should be logged for possible investigations.

Acceptance criteria:
* remove stack trace from error view page
* when errors occur that produce error nodes, log the error code, error message, and stack trace to the logs

**Comment by bryceitoc9** [comment]
This is replicable by adding a region you don't have access to to the AWS Explorer and clicking the dropdown for a resource type.
