### ISSUE TITLE
Edit Lambda Configurations

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#459]
As a user, I can see and modify configuration details of a Lambda function without having to use the web console.

The aspects that can be modified are currently TBD/open for requests.

**Comment by justinmk3** [comment]
AWS Toolkit 3.31.0 supports "Go to console" https://github.com/aws/aws-toolkit-vscode/issues/5452 and we don't plan to add a UI to edit most details of a Lambda function in the IDE.
