### ISSUE TITLE
Tracking: Ability to suppress dialogs that occur within vscode.debug.startDebugging

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#462]
Tracking issue for https://github.com/Microsoft/vscode/issues/71726

When the toolkit attaches the debugger, VS Code shows a modal dialog in some failure situations. This dialog makes for a jarring UX if we try to handle the failure result and take further actions, because the dialog articulates that debugging has stopped.

When we have guidance in this area, we may have opportunity to design improved experiences on the tail end of failed debugger attaches (such as automatic/prompted retries, or diagnostic functionality).

**Comment by mpiroc** [comment]
Closing as we no longer rely on retry logic for timing the debugger attach.
