### ISSUE TITLE
upload code to lambda create a new version in aws lambda

### ISSUE THREAD

**Issue by ashishagarwal7** [aws/aws-toolkit-vscode#4723]
## System details (run the `AWS: About Toolkit` command)

-   OS: Windows 10
-   Visual Studio Code version:1.76.0
-   AWS Toolkit version: 2.19.0

## Question

Hi, I am uploading my code from vscode to aws lambda, however every time a upload a code, aws lamdba creates a new version of the uploaded code. How can I upload the modified code to existing code without creating a new version?

**Comment by justinmk3** [comment]
Can you expand on why you want to do this? 

Though this is not currently supported, the feature request is tracked in: https://github.com/aws/aws-toolkit-vscode/issues/4178

**Comment by ashishagarwal7** [comment]
> Can you expand on why you want to do this?
> 
> Though this is not currently supported, the feature request is tracked in: #4178

@justinmk3 Wanted to upload the lambda and test its functionalities with API Gateway and AWS IoT Core.
Currently, I am trying SAM but It is using cloud formation and S3 which can increase our cost in future.
If any other way of doing so please suggest the same

**Comment by justinmk3** [comment]
> How can I upload the modified code to existing code without creating a new version?

I was a bit confused because I thought you were specifically asking for a way to avoid creating a new version.

If you only want to avoid SAM, that can be done by using the "Upload Lambda" feature of AWS Toolkit:

![image](https://github.com/aws/aws-toolkit-vscode/assets/55561878/bcc4c1f6-7ac7-46bd-8fa1-fd37b50e4d32)

**Comment by justinmk3** [comment]
> avoid creating new version of lambda every upload

Why?

**Comment by ashishagarwal7** [comment]
If I am testing lambda with api gateway, after testing some changes were there, I will re-upload the code which will create a new version of lambda. If the same process is done multiple times we will have multiple lambda for a single release which will create a confusion for me. That is why I want to avoid new versioning for lambda.
