### ISSUE TITLE
Add more metadata to telemetry calls

### ISSUE THREAD

**Issue by hunterwerlla** [aws/aws-toolkit-vscode#473]
Issue copied from: https://github.com/aws/aws-toolkit-jetbrains/issues/881

Active AWS account ID is needed in every telemetry message on a best effort basis

**Comment by bryceitoc9** [comment]
Additional info:
* We are sending the top-level AWS account ID, not the ARN, or the role/IAM user name.
* If the user isn't logged in, send `null`
