### ISSUE TITLE
AWS Explorer should support more resources and actions

### ISSUE THREAD

**Issue by rli** [aws/aws-toolkit-vscode#476]
The AWS Explorer currently only supports viewing CloudFormation stacks and Lambdas.

Customers want to be able to view more resources, such as S3 buckets and DynamoDB tables, as well as perform certain actions such as updating the configuration of bare Lambdas or directly edit a Dynamo table.

**Comment by meije702** [comment]
I would love to be able to control all my "serverless" AWS resources from the comfort of my VS-Code IDE, so that I don't have to use the AWS console online and can do my work from within the same interface.

**Comment by dcat52** [comment]
I also would like this functionality. I can't seem to find a way to edit the Lambda functions either. Would like to be able to develop the code locally with test cases and deploy to the lambda function online.

**Comment by bryceitoc9** [comment]
PRs for additional Lambda functionalities:
Updating existing function code: https://github.com/aws/aws-toolkit-vscode/pull/1269
Importing existing functions: https://github.com/aws/aws-toolkit-vscode/pull/1236

Out of curiosity, are there any other functionalities you're looking for in particular?

**Comment by justinmk3** [comment]
Toolkit 1.16 was released today and includes:

- S3
- Upload Lambda
- Import Lambda

DynamoDB is tracked in https://github.com/aws/aws-toolkit-vscode/issues/1421
