### ISSUE TITLE
Unable to run the toolkit 

### ISSUE THREAD

**Issue by sayalib02** [aws/aws-toolkit-vscode#4816]
Showing below errors in Visual Studio Code

- Error running command aws.refreshAwsExplorer: command 'aws.refreshAwsExplorer' not found. This is likely caused by the extension that contributes aws.refreshAwsExplorer.
- Error running command aws.cdk.refresh: command 'aws.cdk.refresh' not found. This is likely caused by the extension that contributes aws.cdk.refresh.
- Error running command aws.codecatalyst.manageConnections: command 'aws.codecatalyst.manageConnections' not found. This is likely caused by the extension that contributes aws.codecatalyst.manageConnections.

**Comment by justinmk3** [comment]
What exact version of vscode and AWS Toolkit are you using?

**Comment by justinmk3** [comment]
Please try the latest AWS Toolkit (version 3.0) and the new, standalone [Amazon Q extension](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.amazon-q-vscode).
