### ISSUE TITLE
"sam build" triggered from F5 in VSCode runs into timeout

### ISSUE THREAD

**Issue by hafeja** [aws/aws-toolkit-vscode#4817]
Cool stuff you guys built here 👍

## Question(s)
When I start to debug in VSCode (F5), I'm facing systematically following error after ~90 seconds: 

`"sam build" failed. Timed out waiting for build`.

![image](https://github.com/aws/aws-toolkit-vscode/assets/59864250/bb4958b1-3816-4de6-a937-292fb2a42ad4)

My `requirements.txt` file contains ~25 Python modules. 

1. May the timeout be caused by the time it takes to "pip install" the packages defined in the `requirements.txt` file?
2. How can I increase the timeout for the "sam build" command?
3. Is there another advice how to overcome this error?

If `requirements.txt` contains only ~3 python modules, "sam build" succeeds and the the debugger starts as expected.

## System details
Visual Studio Code version: Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621

AWS Toolkit version: v2.20.0

## Debug configuration
```json
{
          "name": "Lambda controller via SAM",
          "type": "aws-sam",
          "request": "direct-invoke",
          "invokeTarget": {
              "architecture": "x86_64",
              "lambdaHandler": "index.lambda_handler",
              "projectRoot": "./api",
              "target": "code"
          },
          "sam": {
              //"containerBuild": true
              "buildArguments": [
                  "--use-container",
                  "--debug"
              ]
          },
          "lambda": {
              "runtime": "python3.10", // * Define version which is installed locally
              "timeoutSec": 500,
              "environmentVariables": {
                  "FOO": "BAR"
              },
              "memoryMb": 512,
              "payload": {
                  "json": {
                      "body": "{\"operation\": \"query\", \"query\": {\"type\": \"JobMetadata\"}}"
                  }
              }
          }
}
```

Looking forward to get support!

**Comment by justinmk3** [comment]
> How can I increase the timeout for the "sam build" command?

That's controlled by the `aws.samcli.lambdaTimeout` setting. 

![image](https://github.com/aws/aws-toolkit-vscode/assets/55561878/43c9e818-6377-4b9e-8d69-f2446082b427)

Related code: https://github.com/aws/aws-toolkit-vscode/blob/e88e482a9e7a7819fab39c1aa5f41c3286fd2825/packages/core/src/shared/sam/localLambdaRunner.ts#L299

> Cool stuff you guys built here 👍

Thank you! If you have a MS account, consider leaving a [review](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode&ssr=false#review-details) :)
