### ISSUE TITLE
Undesirable behaviors when deploying with parameters with incomplete .aws/templates.json files

### ISSUE THREAD

**Issue by bryceitoc9** [aws/aws-toolkit-vscode#485]
**Describe the bug**
There are a few undesirable behaviors when deploying with parameters with an incomplete `.aws/templates.json` file:
1. Nonexistent file creates an empty `.aws/templates.json` file with no templating
2. A `.aws/templates.json` file that exists but is either empty, missing the `"templates"` field, or missing the filename field nested under the `"templates"` tag will throw an error and halt the wizard

**To Reproduce**
1. Nonexistent file creates an empty `.aws/templates.json` file with no templating
  a. Delete the `.aws/templates.json` file while you have a parameter in your SAM template file
  b. Run through the deployment flow and observe that a blank `.aws/templates.json` file is created with no templating.
2. A `.aws/templates.json` file that exists but is either empty, missing the `"templates"` field, or missing the filename field nested under the `"templates"` tag will throw an error and halt the wizard
  a. Delete your `.aws/templates.json` file's contents and save the blank file
  b. Run through the deployment flow and observe that an error pops up in the bottom right corner.

**Expected behavior**
`.aws/templates.json` file always loads with prepopulated fields for the `template.yaml` file.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Visual Studio Code Version: 1.33.0
 - AWS Toolkit for Visual Studio Code Version: 0.1.0

**Additional context**
`#2` is a much more breaking change than `#1` (due to the error). `#1` is an annoyance that will hinder the ability for users to use the parameter override functionality (since there's no way for a user to know the correct format).

Perhaps also consider outputting a comment to describe the purpose of the field.

**Comment by justinmk3** [comment]
AWS Toolkit 1.12 (released today) includes a new [SAM local Lambda debugging experience](https://github.com/aws/aws-toolkit-vscode/pull/1215) which leverages VS Code _launch configurations_. 

It does not use `.aws/templates.json` , so I assume this issue no longer applies.
