### ISSUE TITLE
Create and review design document for preventing deploy to CI/CD-managed stacks.

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#487]
Create a markdown design document for #486, place it in `design/prevent-pipeline-deploy.md`, and review it through the normal PR process.

As a starting point, see https://github.com/awslabs/aws-sam-cli/blob/develop/designs/_template.md.

**Comment by justinmk3** [comment]
see https://github.com/aws/aws-toolkit-vscode/issues/520#issuecomment-824348533
