### ISSUE TITLE
Clean up temp files generated by toolkit

### ISSUE THREAD

**Issue by bryceitoc9** [aws/aws-toolkit-vscode#489]
**Is your feature request related to a problem? Please describe.**
The toolkit generates a lot of temp files that aren't actively cleaned up. This includes logs and run/debugs. Run/debug is intended to be transient; logs shouldn't be cleaned up immediately but we should offer ways to clean these up.

**Describe the solution you'd like**
Clean up after the toolkit. We need to decide how often to clean up: after run/debug, after closing the toolkit, or on demand. Right now, we're favoring the following:
* Run/debug: clean up immediately after execution
* Logs: clean up on-demand (through IDE command)

**Comment by mpiroc** [comment]
Related: Should all of our temporary directories share a common (toolkit-managed) parent folder?

**Comment by justinmk3** [comment]
Toolkit has `src/shared/utilities/disposableFiles.ts` now
