### ISSUE TITLE
When pausing suggestions, the extension keep re-enabling automatic suggestions

### ISSUE THREAD

**Issue by revanshine** [aws/aws-toolkit-vscode#4897]
## System details (run the `AWS: About Toolkit` command)

-   OS:
-   Visual Studio Code version:
-   AWS Toolkit version:

**Comment by revanshine** [comment]
This is about the Amazon Q extension. I don't like the change from Code Whisperer in the AWS extension. I wish AWS had not made this change. With Code Whisperer, I was able to use it like IntelliSense, only when I wanted by invoking a keybind. Whoever designed Amazon Q seems to want to shove it down our throats. Very un-welcome change. Now I have both extensions un-installed. SMH

**Comment by justinmk3** [comment]
This could be a bug that has been reported during the first auto-install. Can you try re-installing Amazon Q and see if the problem still exists?

**Comment by zixlin7** [comment]
dup for [#5093](https://github.com/aws/aws-toolkit-vscode/issues/5093) and it's been fixed
