### ISSUE TITLE
Amazon Q extension reinstalls itself after uninstall

### ISSUE THREAD

**Issue by revanshine** [aws/aws-toolkit-vscode#4898]
## System details (run the `AWS: About Toolkit` command)

-   OS:
-   Visual Studio Code version:
-   AWS Toolkit version:

**Comment by justinmk3** [comment]
What is the exact version of AWS Toolkit you have installed? (run `AWS: About` command)

**Comment by justinmk3** [comment]
As a workaround, try explicitly performing `Sign Out` from the Amazon Q menu: 
<img width="384" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/55561878/17d4e2db-a028-4df6-89b1-f5d27388811d">

I was able to reproduce the issue, then confirmed that AWS Toolkit did *not* auto-install Amazon Q after the following steps:

1. go to Amazon Q, click the "..." menu, click `Sign Out` 
2. uninstall Amazon Q
3. restart VSCode

**Comment by CrowderSoup** [comment]
I'm also experiencing this bug. It's incredibly annoying to keep being prompted to install the Amazon Q extension when I don't want the Amazon Q extension.

**Comment by justinmk3** [comment]
Did you try the [workaround](https://github.com/aws/aws-toolkit-vscode/issues/4898#issuecomment-2096917813) ?

**Comment by asjadjawed** [comment]
> As a workaround, try explicitly performing `Sign Out` from the Amazon Q menu: <img alt="image" width="384" src="https://private-user-images.githubusercontent.com/55561878/328317109-17d4e2db-a028-4df6-89b1-f5d27388811d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTcyOTYsIm5iZiI6MTcxNTI1Njk5NiwicGF0aCI6Ii81NTU2MTg3OC8zMjgzMTcxMDktMTdkNGUyZGItYTAyOC00ZGY2LTg5YjEtZjVkMjczODg4MTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEyMTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyYTdhZGY0MDZlMzQ4NjExMzI0MzAwN2IwOTFjYTlmNDFiZGU3MjAxZTZjMjVjYmViNjllZGIzYTdiM2U5NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.unRr3AiZwA1pw649vMGEOcf7gCJKIGWmswMudClCCAE">
> 
> I was able to reproduce the issue, then confirmed that AWS Toolkit did _not_ auto-install Amazon Q after the following steps:
> 
> 1. go to Amazon Q, click the "..." menu, click `Sign Out`
> 2. uninstall Amazon Q
> 3. restart VSCode

Thanks this worked for me, it was driving me nuts.

**Comment by CrowderSoup** [comment]
I just tried the workaround and it does indeed work.

**Comment by justinmk3** [comment]
Fixed in AWS Toolkit 3.10.0. The auto-install may occur one last time, then will be skipped after that and won't reinstall.
