### ISSUE TITLE
/dev: selecting smaller folder still gives folder is too large for context error

### ISSUE THREAD

**Issue by jpinkney-aws** [aws/aws-toolkit-vscode#4903]
## Problem
When in /dev and you are trying to load a large repo you get `"The project you have selected for source code is too large to use as context. Please select a different folder to use for this conversation"`, as expected. However, when you select a MUCH smaller folder you still get the same error

## Steps to reproduce the issue
1. Open this repository in VSCode
2. in `/dev` use the prompt "Write a test for CodeCatalystRootNode"
3. Observe that we get "The project you have selected for source code is too large to use as context. Please select a different folder to use for this conversation"
4. Select `packages/core/src/codecatalyst`
5. use the prompt "Write a test for CodeCatalystRootNode"
6. Observe that we get "The project you have selected for source code is too large to use as context. Please select a different folder to use for this conversation" **Theres like 15 files total, this should probably work**
7. Select `packages/core/src/web`
8. use the prompt "Write a test for CodeCatalystRootNode"
9. Observe that we get "The project you have selected for source code is too large to use as context. Please select a different folder to use for this conversation" **Theres 2 files, this should definitely work**

## Expected behavior
When we select a smaller project we should be able to use /dev

## System details (run the `AWS: About Toolkit` command)
- Conversation ID: `5aab3fdc-513d-48ae-aa47-1b467c4b09d1`
- OS: Darwin x64 22.6.0
- Visual Studio Code extension host:  1.88.1
- Amazon Q:  1.1.0
- node: 18.18.2
- electron: 28.2.8

**Comment by sannicm** [comment]
[PR](https://github.com/aws/aws-toolkit-vscode/pull/4926/files) for fixing the issue
