### ISSUE TITLE
Generated code is littered with <span class="typewriter-part">

### ISSUE THREAD

**Issue by srhowell** [aws/aws-toolkit-vscode#4908]
## Steps to reproduce the issue

/dev generates code and tries to show it before adding it to the project.
I think it's trying to generate Markdown, but it's full of

    <span class="typewriter-part">

## Expected behavior
No `<span class="typewriter-part">` should appear anywhere.

## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: Windows 10
-   Visual Studio Code version: 1.88.1
-   AWS Toolkit version: 3.1.0
-   Amazon Q version: 1.1.0

**Comment by justinmk3** [comment]
Addressed by https://github.com/aws/aws-toolkit-vscode/pull/4909 which will be part of the next release.

You can also try a preview build here: https://github.com/aws/aws-toolkit-vscode/releases/tag/prerelease

**Comment by justinmk3** [comment]
Fixed in Amazon Q 1.2.0
