### ISSUE TITLE
Create and Review design document for resolving .NET Core lambda handlers from SAM templates.

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#491]
### Summarizing the discussion

* .NET handlers are referenced in template.yaml by their MetadataName
* Robustly resolving a MetadataName requires a full project system/parser, i.e. Roslyn.
* Proposed solutions include:
  * Create a Roslyn-based resolver in C#, and invoke it from TypeScript
  * Add an additional Property to the SAM resource specifying the containing file (this is not sufficient on its own, as we still need to resolve to a handler within the file)
  * Find a way to leverage the existing C# language server from the C# extension (not sure if this is feasible)

### Acceptance Criteria

This repository contains a document in `design/` describing the implementation plan and other options considered for resolving .NET Core handlers.

### Examples

Use https://github.com/awslabs/aws-sam-cli/tree/develop/designs as a starting place.

**Comment by justinmk3** [comment]
`sam` CLI resolves the handler so the remaining use-case here would be to auto-complete the handler name in template.yaml . That topic is covered by another backlog item.
