### ISSUE TITLE
Receiving html in command list

### ISSUE THREAD

**Issue by saldistefano** [aws/aws-toolkit-vscode#4913]
## Problem
Using Amazon Q in VS Code I get html in command listings instead of readable command text.
## Steps to reproduce the issue

 <span class="typewriter-part">wsl <span class="typewriter-part">--list <span class="typewriter-part">--verbose

## Expected behavior
Receive text that is readable
## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: Windows 11, running wsl2 on Ubuntu-22.04
-   Visual Studio Code version:1.88.1
-   AWS Toolkit version:v3.1.0
-   Amazon Q version:v1.1.0

![amazonq-html](https://github.com/aws/aws-toolkit-vscode/assets/90406131/5f83a82e-e2e2-4763-a7cf-31f5e2210685)

**Comment by justinmk3** [comment]
Addressed by https://github.com/aws/aws-toolkit-vscode/pull/4909 which will be part of the next release.

You can also try a preview build here: https://github.com/aws/aws-toolkit-vscode/releases/tag/prerelease

**Comment by saldistefano** [comment]
I verified in the preview build, works great now. Thanks for the Amazingly fast turn around. Keep up the great work, loving Q so far!
