### ISSUE TITLE
The automatic agent of Amazon Q interrupts with my code editing

### ISSUE THREAD

**Issue by Zvika88** [aws/aws-toolkit-vscode#4933]
## Problem
The automatic agent of Amazon Q interrupts with my code editing. It cannot be turned off.

## Expected behavior
Sometimes it is useful. But sometimes it is wrong and terribly annoying. What is worse is that i cannot be shut off, so it keeps popping its suggestions and prohibiting my edits. I need a way to tell it to shut the fuck up

**Comment by justinmk3** [comment]
1. click the Amazon Q statusbar item
2. click `Pause Auto-Suggestions`

<img width="727" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/55561878/0c4101cc-da94-4022-88f2-64c2e44dcc8b">

**Comment by Zvika88** [comment]
This is not what I see when using Amazon Q. Where is this status bar found?
I am using VS Code with the Amazon Q extension that was published on 2024-04-03. I see a split pane and a question bar on the bottom left. There is no status bar or other options shown in your screenshot. 

Where can these be found or how can they be turned on?

**Comment by justinmk3** [comment]
> Where is this status bar found?

The vscode [statusbar](https://code.visualstudio.com/docs/getstarted/userinterface) is at the bottom of vscode. Right-click it to check that Amazon Q status bar is enabled:

<img width="305" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/55561878/0ee13e29-3a41-4385-9c53-1a70944a1a61">


> I am using VS Code with the Amazon Q extension that was published on 2024-04-03

Latest Amazon Q version is 1.1.0 , released on April 30: https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.amazon-q-vscode

You can check the version with the `Amazon Q: About` command.

**Comment by Zvika88** [comment]
Thanks, found it.
