### ISSUE TITLE
Amazon Q Chat Hang

### ISSUE THREAD

**Issue by franckpochet** [aws/aws-toolkit-vscode#4935]
## AWS Toolkit V3.1.0 is intalled, I'm connected with my builder ID, Codewhisperer works correctly, but often the Amazon Q chat hang when I entered a prompt.

Here the logs of Amazon Q:
2024-05-06 12:26:10.777 [info] current client registration id=xxx 
expires at Tue Jul 30 2024 18:54:26 GMT+0200 (Central European Summer Time), 
key =xxx

OS: Windows_NT x64 10.0.22631
Visual Studio Code extension host:  1.89.0
Amazon Q:  1.1.0
node: 18.18.2
electron: 28.2.8

**Comment by Tagi3d** [comment]
+1

**Comment by justinmk3** [comment]
Does this happen while viewing typescript files? Could be related/same as https://github.com/aws/aws-toolkit-vscode/issues/4810

**Comment by franckpochet** [comment]
No, is with a JS file but I enter a question directly in the prompt and nothing happen at all except showing me the prompt in blue I just entered, but then the editbox is frozen, I couldn't do somthing else and it never anwsered.
As I past in my question, the Q logs just show that the connection exists and still valid.
No error, nothing...

**Comment by justinmk3** [comment]
Amazon Q 1.3.0 includes a (potential) fix for this. If the issue still occurs with the latest version of Amazon Q, we will need more details about the specific steps that reproduce the issue.

**Comment by franckpochet** [comment]
Just open VSCode with AWS Toolkit 3.2.0 and ASW Q 1.3.0, and I copnfirm it works.
