### ISSUE TITLE
Publish `AmazonWebServices.amazon-q-vscode` to Open VSX

### ISSUE THREAD

**Issue by corvuslee** [aws/aws-toolkit-vscode#4943]
Dear extension author,
The publishing workflow used to work (#1355) but now it's breaking as you're releasing both `AmazonWebServices.amazon-q-vscode` and `AmazonWebServices.aws-toolkit-vscode` in the same repo. Please consider pushing to the Open VSX marketplace instead of asking them to pull from your vsix files.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

**Comment by justinmk3** [comment]
Thanks for raising this.

> The publishing workflow used to work (#1355) but now it's breaking as you're releasing both `AmazonWebServices.amazon-q-vscode` and `AmazonWebServices.aws-toolkit-vscode` in the same repo.

That's unfortunate. We publish each vsix artifact to different tags, e.g.:

- https://github.com/aws/aws-toolkit-vscode/tree/toolkit/v3.2.0
- https://github.com/aws/aws-toolkit-vscode/tree/amazonq/v1.2.0

does that help?

**Comment by corvuslee** [comment]
Actually toolkit failed in the past few days/week until 3.2.0 was tagged as `latest` yesterday.

**Comment by justinmk3** [comment]
# Workaround

As a workaround, you can install the Amazon Q extension directly from [our published downloads](https://github.com/aws/aws-toolkit-vscode/releases). The vsix file(s) provided there are identical to what we would publish to OpenVSX. 

## How to install

1. Download Amazon Q (`amazon-q-vscode*.vsix`) or AWS Toolkit (`aws-toolkit-vscode*.vsix`) from https://github.com/aws/aws-toolkit-vscode/releases
2. Run `Extensions: Install from VSIX... from the VSCode` [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) and choose the vsix file(s).

**Comment by justinmk3** [comment]
Amazon Q and AWS Toolkit are now published to Open VSX: https://open-vsx.org/namespace/amazonwebservices
