### ISSUE TITLE
Add a maximum time limit to the debugger attach gating

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#497]
With #493 the Toolkit now waits for specific output to signal that we can proceed to attach the debugger. What if that message is never detected, but the SAM App is waiting for a debugger to attach? The promise will never resolve. There should be a time-based throttle on this check, to prevent states like this.

Acceptance criteria:
* there is a user configurable time limit to wait for a debugger attach gating message
* once the time limit has been exceeded, if the code is still waiting for a debugger attach message:
  * the child process is terminated
  * a message is written to the output channel
  * the toolkit code flow does not attempt to attach a debugger (the debug flow is exited)

**Comment by bryceitoc9** [comment]
PR: https://github.com/aws/aws-toolkit-vscode/pull/512
