### ISSUE TITLE
VS Code not showing suggestion widget 

### ISSUE THREAD

**Issue by srivaibhavsagar** [aws/aws-toolkit-vscode#5023]
## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: MAC
-   Visual Studio Code version:  Version: 1.89.1 
-   AWS Toolkit version: v3.5.0
-   Amazon Q version:v1.5.0

## Question

While trying to write code in python for aws cdk, VS code does not show any suggestion for available service like s3.
The suggestion widget shows as no suggestions while pressing control+space on my Mac.

<img width="727" alt="Screenshot 2024-05-18 at 11 46 48 AM" src="https://github.com/aws/aws-toolkit-vscode/assets/51719440/7a021516-bdf0-47d9-98e6-57a9cabc9f96">

**Comment by justinmk3** [comment]
> The suggestion widget shows as no suggestions while pressing control+space on my Mac.

ctrl+space is the normal vscode completion, it's not owned by Amazon Q. If you are trying to invoke Amazon Q inline suggestions (formerly "CodeWhisperer"), try option+c (alt+c on Windows/Linux).

Based on your screenshot, it looks like you are trying to complete a method using vscode's LSP features, which is unrelated to AWS Toolkit and Amazon Q.
