### ISSUE TITLE
Option to disable specific CWE checks

### ISSUE THREAD

**Issue by pascalpfeil** [aws/aws-toolkit-vscode#5031]
## Problem

Amazon Q started showing lots of useless CWE warnings in our code base, such as `CWE-483 - Incorrect Block Delimitation` when it's on a single line.

## Expected behavior
I would like to be able to turn off specific CWE checks instead of turning off the functionality as a whole. I'd like to be able to benefit from the useful checks while turning off the useless ones.

**Comment by justinmk3** [comment]
Is this different than https://github.com/aws/aws-toolkit-vscode/issues/4958 ?

**Comment by pascalpfeil** [comment]
Nope. Didn't find it because I was searching for CWE. 

Closing this, thanks!
