### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by tabarakmukhtar** [aws/aws-toolkit-vscode#5060]
- Issue Type: `Performance`
- Extension Name: `amazon-q-vscode`
- Extension Version: `1.6.0`
- OS Version: `Linux x64 5.15.0-67-generic`
- VS Code version: `1.89.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/amazonwebservices.amazon-q-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by justinmk3** [comment]
Possibly fixed by: 

- https://github.com/aws/aws-toolkit-vscode/pull/5129
- https://github.com/aws/aws-toolkit-vscode/pull/5183
