### ISSUE TITLE
Consolidate "local lambda runner" implementations.

### ISSUE THREAD

**Issue by bryceitoc9** [aws/aws-toolkit-vscode#507]
**Describe the solution you'd like**
Refactor the existing code behind the typescriptCodeLensProvider and pythonCodeLensProvider files

Key areas:
* Move typescriptCodeLensProvider to use localLambdaRunner's function-based handlers instead of the current class-based implementation
* Remove some of the experimental cruft from the pythonCodeLensProvider:
  * Lock down the values that we actually need
  * Make a more robust code directory finder and pull all code for the SAM project for the build/run steps
* Refactor localLambdaRunner functions to have leaner constructors. This may entail breaking the functions into smaller parts.
* Write tests to cover any new functions. We are currently deficient on tests for localLambdaRunner.

**Comment by bryceitoc9** [comment]
Specific areas of interest include: https://github.com/aws/aws-toolkit-vscode/pull/488#discussion_r278754525 , https://github.com/aws/aws-toolkit-vscode/pull/488#discussion_r279015088 , https://github.com/aws/aws-toolkit-vscode/pull/488#discussion_r277751532 , https://github.com/aws/aws-toolkit-vscode/pull/488#discussion_r277749574 , https://github.com/aws/aws-toolkit-vscode/pull/488#discussion_r277055790 , https://github.com/aws/aws-toolkit-vscode/pull/488#discussion_r276720666 , https://github.com/aws/aws-toolkit-vscode/pull/488#discussion_r275958444

**Comment by mpiroc** [comment]
Blocked by #518

**Comment by justinmk3** [comment]
Closed by https://github.com/aws/aws-toolkit-vscode/pull/1215
