### ISSUE TITLE
Display a "guided tour" upon install or upgrade of the AWS Toolkit

### ISSUE THREAD

**Issue by ghost** [aws/aws-toolkit-vscode#508]
**Is your feature request related to a problem? Please describe.**

After installing the AWS Toolkit, it's unclear to know what I should (or even can) do next. I guess I could go see the related documentation over on the AWS website, but I might not know how to get there or even how to navigate the docs once I get there. So, there's an opportunity to provide me with some kind of "Guided Tour" experience right in the middle of the Visual Studio Code IDE to make sure that I've got the AWS Toolkit connected to my AWS account and otherwise configured correctly, as well as teach me how to use the AWS Toolkit to its fullest potential. 

Also, whenever I upgrade the AWS Toolkit on my dev box and there are new features introduced, the Guided Tour should pop up and show me how to use them. 

**Describe the solution you'd like**

After installing the AWS Toolkit for the first time or after upgrading it, a single dialog box should display. This dialog box could include multiple pages that I can flip through, showing things like:

1. What's new in the current release. 
1. Post-install steps, such as connecting the AWS Toolkit to an AWS account and optionally opting in to giving AWS usage and crash information to help improve the product for everyone moving forward.
1. Embedded how-to videos that briefly walk through key usage scenarios--but not for AWS serverless development quite yet. 
1. Introducing me to AWS serverless, AWS Lambda, and AWS CloudFormation, and explaining the benefits of and interrelationships between them.
1. For AWS serverless app development and running/debugging AWS Lambda functions locally, how to install the AWS CLI and Docker, start Docker, and install the AWS SAM CLI.
1. Embedded how-to videos that briefly walk through key usage scenarios for AWS serverless development.
1. Suggested next steps for learning and doing, which link out to related documentation on the AWS website. 

I could quit this Guided Tour at any time. I could also check a box to hide the Guided Tour until the next time I upgrade, in which case it would be shown again, so I could at the very least see what's new in that release. I could also show this dialog again at any time on my own, if desired. 

**Describe alternatives you've considered**

The current experience of showing some information on the page with the plugin **Install** button is a good start, but it's not as visible and inviting as a Guided Tour could be.

**Comment by awschristou** [comment]
> For AWS serverless app development and running/debugging AWS Lambda functions locally, how to install the AWS CLI and Docker, start Docker, and install the AWS SAM CLI.

Each possible dependency that is listed could potentially indicate if it has been detected or not, and explain what feature(s) would be enabled if that dependency was installed, in addition to providing guidance on how to install it.

Additional considerations:
* This might be a good place to enable/disable anonymous usage data settings
* providing access to the changelog details

**Comment by justinmk3** [comment]
VSCode extensions can use the= "Getting Started" / `walkthroughs` contribution points:

- https://code.visualstudio.com/updates/v1_56#_welcome-page-walkthroughs

**Comment by justinmk3** [comment]
closed by #1897
