### ISSUE TITLE
amazonq inline suggestions: "Pause Suggestions" is not remembered after restarting IDE

### ISSUE THREAD

**Issue by dgokcin** [aws/aws-toolkit-vscode#5093]
## Problem

In VSCode, having multiple AI auto-suggestion tools turned on is often a bad experience. Although I like the chat functionality of Amazon Q, I prefer using other completion tools in my current setup. Currently, there is no way to turn off just the auto-completions permanently while keeping the chat functionality.

I know that there is the pause option on the menu bar; however, it does not persist after closing and reopening VSCode.

## Expected behavior

I would like to be able to toggle off the auto-suggestions persistently without losing the chat functionality.

**Comment by justinmk3** [comment]
> there is the pause option on the menu bar; however, it does not persist after closing and reopening VSCode

Ok, so making that persist would address this.

**Comment by dgokcin** [comment]
yes it would @justinmk3

**Comment by nagdeepanjan** [comment]
I agree with the suggestion. I have the same problem as the OP. I use VS Code and Google IDX. Amazon Q fails to remember to pause after IDE restart. I prefer using Copilot on the desktop; on IDX, I get their native Google Code Complete suggestions.

**Comment by justinmk3** [comment]
In Amazon Q 1.9.0, "Pause Auto-Suggestions" is now remembered after restarting VSCode.
