### ISSUE TITLE
Configure Lambda Timeout for local run

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#510]
~You can configure a Lambda Function's timeout in the SAM template, but you cannot configure it during local iteration. It should be possible to specify a different timeout configuration without changing the template file directly.~

Lambda Function's Timeout is configurable via SAM Template, but is not honored in local run/debug sessions.

This should apply to run only. Hitting breakpoints during debug increases the likelihood of exceeding the timeout, which wouldn't make sense.

Reference: [Template Spec](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction)

**Comment by bryceitoc9** [comment]
Looks like `debug` is already configured by SAM to ignore this. The following code will time out after 3 seconds on a normal run but will succeed on a debug (even without breakpoints):
```
let response;
exports.lambdaHandler = async (event, context) => {
    try {
        response = {
            'statusCode': 200,
            'body': JSON.stringify({
                message: 'hello world',
            })
        }
    } catch (err) {
        console.log(err);
        return err;
    }
    await new Promise((resolve, reject) => {
        setTimeout(() => {resolve()}, 10000);
    });
    return response
};
```

**Comment by bryceitoc9** [comment]
FYI, current iteration also doesn't pick up the value specified in the `templates.yaml` file. Do we want to implement this to pick up the `template.yaml` value, a specified override value in the `./.aws/templates.json` file, or both?

**Comment by awschristou** [comment]
I think it should take the template.yaml value when it can find one, and it should be possible to override this in the lambda configuration (in templates.json)

**Comment by maqen** [comment]
I second this, unusable when using with slow external APIs in function

**Comment by danvasem** [comment]
this is going to be in a next release?? It's pointless to limit local execution to just 3 seconds.

**Comment by awschristou** [comment]
Issue has been revised to accept the configuration from the SAM Template.
A change is currently in review.

**Comment by awschristou** [comment]
This change is now in the develop branch.
Closing the issue.
