### ISSUE TITLE
StepFunctions: Error checking not working as per the demo video

### ISSUE THREAD

**Issue by Elizabethbranion** [aws/aws-toolkit-vscode#5110]
## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: MacOS
-   Visual Studio Code version: Version: 1.89.1
-   AWS Toolkit version: v3.8.0
-   Amazon Q version: v1.7.0

## Question

Error checking not working as per the demo video:

Where Rob makes a deliberate mistake 13 min 59 seconds in - he demos the error checking functionality.

https://youtu.be/1RJtCKpdELQ?si=6zc6T_Pw8hgfWmwF&t=839

This no longer seems to work. Wondering why not.

Haven't raised an issue, as maybe that functionality has been removed i.e. this is intentional?

**Comment by justinmk3** [comment]
It should work. Can you provide the AWS Toolkit logs? There may also be logs in the "ASL" channel, if you see one.

1. In the vscode [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette), run `AWS: View Logs`. This reveals the Output panel with `AWS Toolkit Logs` selected.
2. Click the gear icon and choose `Debug`, then click it again and choose `Set As Default`.
3. Perform the steps to reproduce the issue.
4. Remove any private info from the logs.

Amazon Q: View Logs

**Comment by Elizabethbranion** [comment]
Sorry - I added the logging on here a while ago  and unfortunately must have neglected to click save.

I'll gather it again in a while.

In the mean time - I _have_ re-produced this on a different machine (i.e. a separated environment).

Here's a screen shot (attached). Note there is no "red underline" as there should be.

<img width="1722" alt="Screenshot 2024-06-07 at 17 43 55" src="https://github.com/aws/aws-toolkit-vscode/assets/69082436/40b951a0-b8be-4049-a1e0-74538ebf75b9">

**Comment by justinmk3** [comment]
Thanks! We have narrowed down the code related to this issue and are working on a fix.

**Comment by justinmk3** [comment]
Fixed in AWS Toolkit 3.12.0.
