### ISSUE TITLE
"template-first" lambda handler resolution

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#517]
Currently, we map SAM resources to source code by starting with the handler in source code, and searching for a matching handler in a SAM template. This has introduced unnecessary complexity into our handler resolution logic.

Instead, we should start by locating SAM templates in the workspace, and mapping each resource to a handler in source code. This map should be created as soon as the workspace is loaded, and should be updated whenever a template is changed, added, or removed. To resolve a handler, simply consult this map.

Acceptance criteria:

* A markdown design document is checked into the `design/` folder, following the same format as other design documents.
* The document should describe:
  * How should SAM templates in the workspace be located?
  * What is the shape of the handler map? How will it be queried?
  * When should the handler map be created/updated?
  * What should happen if multiple resources map to the same handler?
  * What should happen if a function in source code looks like a lambda handler, but isn't referenced by any SAM template?
  * Any user-facing behavior changes that will result from this change.

**Comment by justinmk3** [comment]
Toolkit has a "template registry" now.
