### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by ThePlenkov** [aws/aws-toolkit-vscode#5174]
Hi! I try to use the extension - it simply doesn't work.

Tried to reinstall many times - here is what I have:

I don't have any texts, %AWS is instead

![image](https://github.com/aws/aws-toolkit-vscode/assets/6381507/5c5d9546-3fe2-4f32-859b-43b9796aa062)
![image](https://github.com/aws/aws-toolkit-vscode/assets/6381507/12fb429b-93bb-4b47-8f71-a9648070c59f)
![image](https://github.com/aws/aws-toolkit-vscode/assets/6381507/70c985bf-9d5b-4fd9-b508-dbfd00680804)

but worse is - it doesn't work even if I choose those:
![image](https://github.com/aws/aws-toolkit-vscode/assets/6381507/765db2d1-63a5-4ade-a470-c8d6a745dadd)

Could you please help to solve it?
Thanks!

**Comment by justinmk3** [comment]
That's very unusual, and suggests that the vsix file didn't get installed correctly.

Are you using vscode or a derivative, like vscodium?

Can you share the details requested by the issue template :

-   OS:
-   Visual Studio Code version:
-   AWS Toolkit version:
-   Amazon Q version:

**Comment by ThePlenkov** [comment]
It's vscode. So what I observe is following. It works in Windows and WSL , but doesn't work in a remote container.

Let me try please to create an example
