### ISSUE TITLE
Common routine to detect if a given resource is associated with a pipeline

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#520]
Initially supports Lambda Functions and CloudFormation Stacks
Input: Resource ARN
Output: Tag value, or undefined if tag is not found

Acceptance Criteria: 
* Resources are checked for the presence of a `aws:codepipeline:pipelineArn` tag
* the tag value is returned when present, else undefined is returned
* If an error occurs in this process, it is logged as a warning, and undefined is returned
* success/failure metrics are recorded for each call

**Comment by mpiroc** [comment]
For the initial implementation, query for tags using the individual service clients, rather than the tagging-specific client.

**Comment by abrooksv** [comment]
We decided not to proceed with this
