### ISSUE TITLE
Users are shown a confirmation prompt when attempting to delete a CloudFormation Stack associated with a pipeline

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#523]
BLOCKED on #520 for pipeline-association detection

Acceptance Criteria
* if user deletes a CloudFormation Stack that is not associated with a pipeline, there is no change to the existing flow
* if user deletes a CloudFormation Stack that is associated with a pipeline, they are prompted (as defined [here](https://github.com/aws/aws-toolkit-vscode/blob/develop/designs/modify-resources-attached-to-code-pipeline.md)) to confirm
  * if user cancels, nothing further happens
  * if user confirms, the stack is deleted
* unit tests from the [Design Document](https://github.com/aws/aws-toolkit-vscode/blob/develop/designs/modify-resources-attached-to-code-pipeline.md) are implemented

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/issues/520#issuecomment-824348533
