### ISSUE TITLE
Users are shown a confirmation prompt when attempting to deploy a SAM Application to a CloudFormation Stack associated with a pipeline

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#524]
BLOCKED on #520 for pipeline-association detection
BLOCKED on #519 for deploy wizard confirmation

Acceptance Criteria
* Validation happens prior to the confirmation step.
* if user deploys a SAM App to a CloudFormation Stack that is not associated with a pipeline, there is no change to the existing flow
* if user deploys a SAM App to a CloudFormation Stack that is associated with a pipeline, they are prompted (as defined [here](https://github.com/aws/aws-toolkit-vscode/blob/develop/designs/modify-resources-attached-to-code-pipeline.md)) to confirm
  * if user cancels, they are returned to the stage in the wizard that prompts them to specify a stack to deploy to
  * if user confirms, the wizard progresses to the confirmation stage
* unit tests from the [Design Document](https://github.com/aws/aws-toolkit-vscode/blob/develop/designs/modify-resources-attached-to-code-pipeline.md) are implemented

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/issues/520#issuecomment-824348533
