### ISSUE TITLE
Login to EC2 using SSM

### ISSUE THREAD

**Issue by scott-doyland-burrows** [aws/aws-toolkit-vscode#5266]
I would like to be able to login to EC2 using SSM via the AWS toolkit.

This should work the same as it does for ECS Exec:

![image](https://github.com/aws/aws-toolkit-vscode/assets/61512176/bf49898c-24be-4ef8-b4c0-3ad8bc83de06)

This would be so helpful.

**Comment by justinmk3** [comment]
Related: https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-1609299367

**Comment by justinmk3** [comment]
# Status

AWS Toolkit 3.39.0 includes [these features](https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-2539726009):

* ✅ AWS Explorer (and VSCode command palette): Start/Stop/Reboot actions [#1559](https://github.com/aws/aws-toolkit-vscode/issues/1559)
* ✅ AWS Explorer: list EC2 instances, view their status.
* ✅ `AWS: Launch EC2 Instance` command opens the AWS web console launch page.
* ✅ `AWS: Open terminal to EC2 instance...` command opens a VSCode terminal connected to an EC2 instance.
    * Requires [remote-ssh](https://code.visualstudio.com/docs/remote/ssh) (which requires `ssh` on your local desktop).
    * Supports EC2 instances running Linux/macOS/**Windows**.
* ✅ `AWS: Connect to EC2 instance in New Window...` command connects VSCode to an EC2 instance.
    * Requires [remote-ssh](https://code.visualstudio.com/docs/remote/ssh) (which requires `ssh` on your local desktop).
    * Supports EC2 instances running Linux or macOS (**not Windows, currently**).
    * Your local desktop can be Linux/macOS/Windows.
    * <img width="591" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/55561878/8da31cbd-0542-4607-911b-d87ed39af443">
