### ISSUE TITLE
Black on Black text on "Dark High Contrast" theme

### ISSUE THREAD

**Issue by as-dmusser** [aws/aws-toolkit-vscode#5294]
## Problem
Text in form inputs on "Dark High Contrast" theme is black on black, rendering it invisible
## Steps to reproduce the issue
1. Change theme to "Dark High Contrast"
2. Open the AWS Toolkit Tab in VSCode
3. Create a new connection
4. Select Workforce Sign-in and hit continue
5. type anything into the "start url" field
observation: text is black on a black background and can only be seen when highlighted
6. Click on the Region dropdown
observation: text is black on a black background and can only be seen when hovered

## Expected behavior
expected:  Text should be white or the default color of high contrast font

## System details (run `AWS: About` and/or `Amazon Q: About`)
![Screenshot 2024-07-11 085846](https://github.com/aws/aws-toolkit-vscode/assets/171699438/51d748e7-1638-4376-8a5c-c578f4310cf7)

-   OS:  MS Windows 11
-   Visual Studio Code version:  1.90.0
-   AWS Toolkit version: 3.13.0
-   Amazon Q version:

**Comment by justinmk3** [comment]
This request was addressed in [AWS Toolkit 3.15.0](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode) and/or [Amazon Q 1.16.0](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.amazon-q-vscode)!

AWS Toolkit changelog: https://github.com/aws/aws-toolkit-vscode/blob/master/packages/toolkit/CHANGELOG.md
Amazon Q changelog: https://github.com/aws/aws-toolkit-vscode/blob/master/packages/amazonq/CHANGELOG.md
Release artifacts: https://github.com/aws/aws-toolkit-vscode/releases
