### ISSUE TITLE
Users can select CloudFormation Stack from a list during SAM deployment workflow

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#532]
Acceptance Criteria
* User is presented with a selection list of CloudFormation Stacks that are related to the region they are deploying to
* stacks are sorted alphanumerically
* supports pagination
* Selection box allows the user to create a new stack by entering its name.

Things to be aware of:
* be mindful of pagination! Either load through pagination, or have a "Load more Stacks" entry that retrieves the next page and adds them to the list

**Comment by JadenSimon** [comment]
Implemented in https://github.com/aws/aws-toolkit-vscode/pull/2982 for the new flow.
