### ISSUE TITLE
Amazon Q becomes unresponsive in VSCode after a few questions.

### ISSUE THREAD

**Issue by Doinysus** [aws/aws-toolkit-vscode#5327]
## Problem
Amazon Q becomes unresponsive

## Steps to reproduce the issue

1. Ask several questions in Amazon Q chat( I had some small python code open in the other pane only)
2. Post some code as part of suggestions.
3. After a few questions( I would say around 10-20, it's a bit random) it becomes unresponsive.

## Expected behaviour
Provide an answer and allow me to scroll through the answer and ask more questions.

## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: Windows 10
-   Visual Studio Code version: Version: 1.91.1 (user setup)
-   OS: Windows_NT x64 10.0.19045
-   AWS Toolkit version: v3.14.0
-   Amazon Q version: v1.15.0

**Comment by Will-ShaoHua** [comment]
hey @Doinysus , thanks for reporting. 
Could you share debug logs if possible
- In the vscode [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette), run set log levels... and choose debug
- open output panel and choose amazon Q logs
- remove any personal information

**Comment by Doinysus** [comment]
Unfortanately the log level was set as info when the problem occurred. I
tested now and it seems to be fine, but did increase the log level in case.
It used to trigger when the mouse over on the "sources" cuased the popout
to happen. Then the popout didn't disappear and the Amazon Q pane froze.
I will let you know if it replicates.

**Comment by zixlin7** [comment]
closing it for now, pls feel free to re-open if this issue occurs again
