### ISSUE TITLE
Amazon Q: unable to sign out, "start URL already exists"

### ISSUE THREAD

**Issue by kattaviz** [aws/aws-toolkit-vscode#5354]
Getting the below error while connecting to AQD.

A connection for this start URL already exists. Sign out before creating a new one.

Also not seeing Sign Out option.

**Comment by kattaviz** [comment]
i am using Visual Code to use AQD.

**Comment by justinmk3** [comment]
The Sign Out action can be found by clicking the "Amazon Q" item in the vscode statusbar, or from the "..." menu of the Q panel:

![image](https://github.com/user-attachments/assets/ac9886bb-e21b-461e-8e11-01572746b1d5)

Meanwhile, we are looking into a potential issue where the `A connection for this start URL already exists. Sign out before creating a new one.` message is displayed in some unwanted cases.

**Comment by allencanning-ft** [comment]
I am getting the same error message and am also unable to sign out as that is not an option on the pull down.

**Comment by justinmk3** [comment]
> am also unable to sign out as that is not an option on the pull down.

What about the statusbar?

**Comment by allencanning-ft** [comment]
unfortunately, no.  The status bar shows Sign Into get started, and Learn more about Q.

**Comment by kilativ** [comment]
I was able to resolve it by removing C:\Users\<username>\AppData\Roaming\Code\User\globalStorage\state.vscdb file

**Comment by nkomonen-amazon** [comment]
Potential fix in AWS Toolkit 3.16.0 and Amazon Q 1.17.0 (once released).

Please update us if your problem is fixed!

**Comment by jpinkney-aws** [comment]
The fix has been previously released. If you encounter any other issues feel free to let us know!
