### ISSUE TITLE
amazonq: Translate a piece of code into another code language

### ISSUE THREAD

**Issue by tverney** [aws/aws-toolkit-vscode#5366]
## Problem

We have the ability to highlight a piece of code and send it to the prompt, but we don't have any functionality that allow quick translate that piece of code into another language.

For example, I have a selected code in JS and I ask to create the same idea in a PY or Java code. I think this would give users a lot of flexibility and use.

<img width="1210" alt="Screenshot 2024-07-23 at 1 22 15 PM" src="https://github.com/user-attachments/assets/d90415ca-ac1f-45b4-908d-3cada6d7f53e">

PS: If I ask in the prompt, it already does that, but its verbose, and I think a quick action would make a lot of sense.

## Expected behavior

Have a quick action to send selected code into context that user can select which language wants translate to.

**Comment by justinmk3** [comment]
Choose `Send to prompt`, then type `translate to python` in the prompt and hit enter. 

Do you have ideas on how this can be improved?

**Comment by tverney** [comment]
> Choose `Send to prompt`, then type `translate to python` in the prompt and hit enter.
> 
> Do you have ideas on how this can be improved?

Maybe we add the selected code in the answer and a dropdown to select which language we want to translate to?

**Comment by tverney** [comment]
By the way, this would be really useful if Q give me the code answer in a language that I'll not be using or don't have in the project.

Majority of the code here is in js|ts|tsx (just few in py) and the answer its given in py. I would like to be able to transform to JS for example.

@justinmk3 

<img width="405" alt="Screenshot 2024-07-25 at 1 09 16 PM" src="https://github.com/user-attachments/assets/0fc1a011-dae0-4e14-bd35-c9910128214f">

**Comment by justinmk3** [comment]
We consider this out of scope. Using chat commands is the recommended way to achieve this.
