### ISSUE TITLE
@workspace attempts to index python virtual envs (.venv, venv)

### ISSUE THREAD

**Issue by wilmatos** [aws/aws-toolkit-vscode#5431]
## Problem
When triggering the indexing of a project, if the .venv or venv directories from a python virtual environment is not listed in the .gitignore file, the workspace feature tries to index all the files in those directories causing it to take a really long time OR fail due to size.

## Steps to reproduce the issue
In a workspace in vscode:
1. create a python virtual environment using virtualenv or venv with the dir name of .venv or venv.  
2. Confirm that the folder or directory is not listed in the .gitignore file.
3. Open Amazon Q Chat by clicking on Q icon or clicking on Amazon Q in status bar and selecting 'Open Chat'
4. Type `@workspace` in chat and hit enter (or send the prompt)
5. It will trigger indexing.
6. Open the Output panel
7. Select 'Amazon Q Language Server'
8. Observe it attempting to index the virtual env directory.

## Expected behavior
The indexing process should ignore the venv or .venv directory by default.

## System details (run `AWS: About` and/or `Amazon Q: About`)
-   OS: Sonoma 14.6
-   Visual Studio Code version: 1.87.2 (Universal)
-   AWS Toolkit version: v3.18.0
-   Amazon Q version: v1.19.0

**Comment by jpinkney-aws** [comment]
In the latest release we are ignoring venv files during local indexing!
