### ISSUE TITLE
Expose a synchronous API to Amazon Q allowing introspecting current session state.

### ISSUE THREAD

**Issue by heyrichardshi** [aws/aws-toolkit-vscode#5434]
## Problem

I would like to be able to call an API exposed by Amazon Q in order to determine the current session state (e.g. active, expired, logged out, etc). Currently, Amazon Q exposes no such API and I am forced to depend on implementation details of Amazon Q, such as reading the session cache files and making assumptions about them.

## Expected behavior

Amazon Q exposes a [synchronous API](https://code.visualstudio.com/api/references/vscode-api#extensions) that allows an operation to retrieve the current Amazon Q state, e.g. `extensions.getExtension('amazon.q').exports.getSessionState()` which would return some object containing data about the session state.

**Comment by justinmk3** [comment]
Has overlap with https://github.com/aws/aws-toolkit-vscode/issues/3780

**Comment by justinmk3** [comment]
@heyrichardshi why is it required for the api to be synchronous?

Resolving this, but can reopen if there is a use-case that isn't solved by the async api.
