### ISSUE TITLE
Support go to console for Lambda

### ISSUE THREAD

**Issue by paulmis** [aws/aws-toolkit-vscode#5452]
## Problem
Sometimes I'd like to debug a particular Lambda, and need to search for the right function from the interface. Since all of our business logic is on Lambda, we tend to do this quite a lot, and it decreases our productivity.

## Expected behavior
Instead, provide a shorthand to open the relevant Lambda function in the console, alongside other QoLs.
![Screenshot 2024-08-14 at 23 44 29](https://github.com/user-attachments/assets/4df8d26d-966e-49e1-b481-54b3e0fab58d)

**Comment by justinmk3** [comment]
Implemented in AWS Toolkit 3.31.0 

<img width="377" alt="image" src="https://github.com/user-attachments/assets/0dfbc0cd-7f11-4604-a193-5c2c32c017a1">
