### ISSUE TITLE
Document how to set up and work with credential modes supported in the Toolkit

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#546]

**Comment by awschristou** [comment]
Credentials Design docs are in #889 and user documents are in https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/establish-credentials.html

**Comment by awschristou** [comment]
Credentials Documentation now available - https://github.com/aws/aws-toolkit-vscode/blob/master/designs/credentials/credentials-management.md
