### ISSUE TITLE
Document how to configure lambda handlers

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#547]

**Comment by justinmk3** [comment]
AWS Toolkit 1.12 (released today) includes a new [SAM local Lambda debugging experience](https://github.com/aws/aws-toolkit-vscode/pull/1215) which leverages VS Code _launch configurations_. 

Documentation: https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/run-debug-sam-app.html
