### ISSUE TITLE
amazonq: AI Impersonation allowance

### ISSUE THREAD

**Issue by tverney** [aws/aws-toolkit-vscode#5537]
## Problem

![image](https://github.com/user-attachments/assets/e2a68175-aad5-4536-8095-6d2dd1892a19)

## Steps to reproduce the issue

1. Open chat
2. Ask AI to act as someone else famous / or that have specific knowledge 
3. It keeps stuck on the impersonation

## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: MacOS
-   Visual Studio Code version:
-   AWS Toolkit version:
-   Amazon Q version:

**Comment by justinmk3** [comment]
No longer reproducible.
