### ISSUE TITLE
Remove copyright date

### ISSUE THREAD

**Issue by bryceitoc9** [aws/aws-toolkit-vscode#556]
We open all of our files with:
```
/*!
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
```

We need to change this to:
```
/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
```
(or something similar)

We should ideally time this at a point where we don't have any open PRs.

**Comment by justinmk3** [comment]
Updated the description/title to _remove_ the year instead of _increment_ it.

See also https://github.com/awslabs/aws-c-common/pull/648
