### ISSUE TITLE
Amazon Q doesn't work with vscode tunnel: "127.0.0.1 refused to connect"

### ISSUE THREAD

**Issue by TPreece101** [aws/aws-toolkit-vscode#5563]
## Problem
When I try to sign in to the Amazon Q VSCode extension via VSCode Web I get an "invalid_grant" error
![Screenshot 2024-09-09 at 12 03 58](https://github.com/user-attachments/assets/08905b49-4a4a-46c5-86ae-304ff64090de)

And when I try to sign in when using tunnelling via the VSCode CLI the OAuth seems to try to direct me to a local URL
![Screenshot 2024-09-09 at 12 05 00](https://github.com/user-attachments/assets/6bc1c964-5a64-4d3a-b62f-dab094b7f221)

## Expected behavior
I would expect it to work as it does when I'm just developing locally (that works fine)

## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: (Local - Mac OS 14.5 (23F79)) (Remote - Debian 11 (bullseye))
-   Visual Studio Code version: Local - 1.93.0, Remote - 1.93.0
-   AWS Toolkit version:
-   Amazon Q version: 1.24.0

**Comment by azhar22k** [comment]
I have same issue too

**Comment by justinmk3** [comment]
@azhar22k what exact steps are you trying?

vscode tunneling should work, because the vscode extension runs in a "compute" backend (not directly in the web browser).

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/5847 may fix this.

Please try the vsix from https://github.com/aws/aws-toolkit-vscode/releases/tag/prerelease

**Comment by TPreece101** [comment]
That fixes it for me @justinmk3!
