### ISSUE TITLE
telemetry: Add --region to metrics for sam local invoke

### ISSUE THREAD

**Issue by bryceitoc9** [aws/aws-toolkit-vscode#559]
`sam local invoke` can use both the `--profile` and `--region` flags, which sets the AWS credentials and the simulated AWS region in the Docker container.

**Comment by bryceitoc9** [comment]
Contingencies:
* Implement following the `feature/dotnet` merge into develop so the change only needs to be made once across runtimes.
* Implement `--region` following a move to a single-region format so we don't have to implement a separate selector prior to local runs.

**Comment by mpiroc** [comment]
Related: https://github.com/aws/aws-toolkit-vscode/issues/416

**Comment by justinmk3** [comment]
profile is private info (PII) so we should not log that.

**Comment by justinmk3** [comment]
Region is a standard field on all metrics now: https://github.com/aws/aws-toolkit-vscode/blob/81539c0341002dd673a9b3cc725adb15b28b888d/src/shared/telemetry/telemetryService.ts#L245
