### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Gurubasava32** [aws/aws-toolkit-vscode#5592]
- Issue Type: `Performance`
- Extension Name: `aws-toolkit-vscode`
- Extension Version: `3.24.0`
- OS Version: `Windows_NT x64 10.0.22631`
- VS Code version: `1.91.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/bguru/AppData/Local/Temp/amazonwebservices.aws-toolkit-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by justinmk3** [comment]
can you provide the log file mentioned in the message?

    c:/Users/bguru/AppData/Local/Temp/amazonwebservices.aws-toolkit-vscode-unresponsive.cpuprofile.txt
