### ISSUE TITLE
amazon q chat: scrollbar styling does not match VS Code theme

### ISSUE THREAD

**Issue by matthewlloyd** [aws/aws-toolkit-vscode#5644]
## Steps to reproduce the issue

1. Install Amazon Q in VS Code.
2. Switch to any dark theme in VS Code.
3. Observe Amazon Q's scrollbar is jarringly bright white, wide, and different from the grey and narrow scrollbars in the rest of VS Code's interface.

## Expected behavior

The styling of the scrollbar, especially the color and the width, should match the other scrollbars in the VS Code interface.

## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: Windows 11
-   Visual Studio Code version: 1.93.1
-   Amazon Q version: 1.26.0

![image](https://github.com/user-attachments/assets/fda2007a-1dc8-4c73-8565-19e20d8a578f)

**Comment by Kannav02** [comment]
Hey @matthewlloyd !

I reproduced the issue on my Mac machine as well and I found the following result 

<img width="229" alt="Screenshot 2024-10-28 at 11 58 36 AM" src="https://github.com/user-attachments/assets/f10e9d2d-af85-41a1-9519-ea51b34d975a">


The idea here is to match the consistency of scrollbar of the extension to other scrollbar elements in vs code right?

if that's the issue, I would love to contribute to this

Thank you!

**Comment by Kannav02** [comment]
I believe what could be one of the possible solutions to this would be just re-applying the relevant settings to the extension's scroll-bar from VSCode's default configuration, it would make it consistent with all the settings for scroll-bars in VSCode

**Comment by Kannav02** [comment]
I'm currently holding off on starting the implementation while waiting for the maintainer's approval. Once they give the green light, I'll be happy to begin working on this task.

**Comment by justinmk3** [comment]
This request was addressed in [AWS Toolkit 3.32.0](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode) and/or [Amazon Q 1.34.0](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.amazon-q-vscode)!

- AWS Toolkit changelog: https://github.com/aws/aws-toolkit-vscode/blob/master/packages/toolkit/CHANGELOG.md
- Amazon Q changelog: https://github.com/aws/aws-toolkit-vscode/blob/master/packages/amazonq/CHANGELOG.md
- Release artifacts: https://github.com/aws/aws-toolkit-vscode/releases
