### ISSUE TITLE
Toolkit doesn't work when 'WSL - Installed'

### ISSUE THREAD

**Issue by BenPettit** [aws/aws-toolkit-vscode#566]
No functionality when extension is 'WSL - Installed'

AWS explorer shows "There is no data provider registered that can provide view data."

Command palette shows errors like "command 'aws.login' not found"

No 'AWS Toolkit Logs' apparent.

Appreciate this is insiders but toolkit running in WSL would make my life complete.

 - Running behind corporate proxy
 - OS: Windows 10 1903 + WSL Ubuntu 18.04.2 LTS
 - Visual Studio Code Version: 1.34.20-insider
 - AWS Toolkit for Visual Studio Code Version: 0.1.2

**Comment by awschristou** [comment]
Thank you for reporting this @BenPettit . 

This will require some investigation to support Remote Development.
Whoever is investigating: https://code.visualstudio.com/api/advanced-topics/remote-extensions may help

**Comment by awschristou** [comment]
Hey @BenPettit  could you please try the following, I'd like to know if this possible workaround gets you to a point where the AWS Explorer properly displays, or if there are additional issues to work through...

After opening VS Code but before clicking on the AWS panel, drop to the terminal. Manually create the folder `/root/.config/Code/logs/aws_toolkit`. Then try opening the AWS panel.

**Comment by virgilwashere** [comment]
## 🚧 WIP comment

- [ ] reloading `code-insiders` to clear environment.
- [ ] explictly activating `aws-vault` for `vscode-remote` process.

> After opening VS Code but before clicking on the AWS panel, drop to the terminal. Manually create the folder `/root/.config/Code/logs/aws_toolkit`. Then try opening the AWS panel.

I'm in the same situation as @BenPettit. `aws.*` commands not found.

Running `code-insiders` and `Remote Development: WSL`.

Your [docs](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/setup-credentials.html?shortFooter=true) say:
`The AWS Toolkit for Visual Studio Code locates and uses AWS access keys in the same way that the AWS CLI and the AWS SDKs locate and use them.`

`If you have already set your AWS credentials using the AWS CLI, the AWS Toolkit for Visual Studio Code will automatically detect and make those credentials available for use.`

implying that environment variables `AWS_PROFILE`, `AWS_DEFAULT_REGION`, `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_SESSION_TOKEN` should be honoured.  In my case [`aws-vault`](/99designs/aws-vault) sets them up.

My `git` configuration works wonderfully for `CodeCommmit`.

```ini
credential.helper=!aws-vault exec ${AWS_DEFAULT_PROFILE:-work-profile} -- aws codecommit credential-helper $@
credential.usehttppath=true
```



From the [troubleshooting](https://code.visualstudio.com/docs/remote/troubleshooting#_errors-storing-extension-data) docs:

### Errors storing extension data
Extensions may try to persist global data by looking for the `~/.config/Code` folder on Linux. This folder may not exist, which can cause the extension to throw errors like `ENOENT: no such file or directory, open '/root/.config/Code/User/filename-goes-here`.

**Resolution**: Extensions can use the `context.globalStoragePath` or `context.storagePath` property to resolve this problem. See the [extension guide] for details.

[extension guide]: <https://code.visualstudio.com/api/advanced-topics/remote-extensions#persisting-extension-data-or-state>

**Comment by BenPettit** [comment]
> Hey @BenPettit could you please try the following, I'd like to know if this possible workaround gets you to a point where the AWS Explorer properly displays, or if there are additional issues to work through...
> 
> After opening VS Code but before clicking on the AWS panel, drop to the terminal. Manually create the folder `/root/.config/Code/logs/aws_toolkit`. Then try opening the AWS panel.

~/.config/Code/logs/aws_toolkit got it working, I'll try out the rest of the functionality. Great work and thanks!

**Comment by awschristou** [comment]
@BenPettit  and @virgilwashere thank you for helping confirm the log path issue. 
PR #583 should help the extension activation issue, and we'll track looking into whether or not the log files should reside elsewhere with issue #582 .

**Comment by nemozny** [comment]
This issue hasn't been fixed as of today. While using Remote Development in VSCode the AWS Toolkit got installed on the remote machine, correctly I would think, as it reported no issues, but the plugin showed empty windows for both Explorer and Developer Tools. And I have restarted VSCode maybe two times.

Manually creating ~/.config/Code/logs/aws_toolkit on the remote machine fixed the problem and the plugin started to show menu items in its two windows.

**Comment by justinmk3** [comment]
> Manually creating ~/.config/Code/logs/aws_toolkit on the remote machine fixed the problem

That is strange. That path has not been used for at least 1 year (AWS Toolkit 1.29+): https://github.com/aws/aws-toolkit-vscode/pull/1694

Also `git grep -E 'aws_toolkit'` shows only 1 result: https://github.com/aws/aws-toolkit-vscode/blob/b603c0750559ba74d8f3abff7e08fcb949a0c48c/src/shared/logger/activation.ts#L149

@nemozny can you confirm the AWS Toolkit version installed in your WSL environment (and locally) is 1.45 ?

**Comment by nemozny** [comment]
Hi @justinmk3, my .vscode-server directory on the linux remote server has 1.46
```
~/.vscode-server/extensions> ls |grep toolkit
amazonwebservices.aws-toolkit-vscode-1.46.0
```
And my local W10 profile has also ```.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.46.0```
