### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by devanshu100** [aws/aws-toolkit-vscode#567]
- Issue Type: `Performance`
- Extension Name: `aws-toolkit-vscode`
- Extension Version: `0.1.2`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.34.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\dshrivastava\amazonwebservices.aws-toolkit-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by awschristou** [comment]
Hi @devanshu100  , can you please attach your cpuprofile.txt file to the issue?

We have an open issue #464 to perform webpack on the extension, which will reduce the extension's size, and based on the link you've provided, may increase performance.

**Comment by bryceitoc9** [comment]
@devanshu100 Just checking in, are you still running into this, and if so, can you attach the `cpuprofile.txt` file?

**Comment by datavisyn-ro-v** [comment]
Just received the same message.

Extension Version: `1.4.0 2019-12-02`
VS Code:

```
Version: 1.41.0 (user setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:37:42.077Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
```

[amazonwebservices.aws-toolkit-vscode-unresponsive.cpuprofile.txt](https://github.com/aws/aws-toolkit-vscode/files/3972852/amazonwebservices.aws-toolkit-vscode-unresponsive.cpuprofile.txt)

**Comment by serverhorror** [comment]
Just received the same message.

Extension Version: `1.4.0 2019-12-02`
VS Code:

```
Version: 1.41.0 (user setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:37:42.077Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
```

[amazonwebservices.aws-toolkit-vscode-unresponsive.cpuprofile.txt](https://github.com/aws/aws-toolkit-vscode/files/3972861/amazonwebservices.aws-toolkit-vscode-unresponsive.cpuprofile.txt)

**Comment by awschristou** [comment]
Thank you for the report @serverhorror , we have some changes now in the master branch around running webpack on the toolkit code. When this is released, it should help.

**Comment by awschristou** [comment]
Toolkit v1.5.0 is now out, and is the first version of the toolkit produces with webpacking. Startup performance and and vsix extension size has been improved.

Closing this issue out. Future issues with cpu load can be filed as new issues.
