### ISSUE TITLE
Please support Flutter sdk and dart language properly and update the context window for the chat

### ISSUE THREAD

**Issue by faheemstepsharp** [aws/aws-toolkit-vscode#5683]
Please add better flutter support and upgrade the flutter knowledge and code understadning please also learn from extensions like CODY by sourcegraph and improve the look and feel and UX of amazon Q

**Comment by justinmk3** [comment]
Flutter and dart are tracked here: https://github.com/aws/aws-toolkit-vscode/issues/3425

> please also learn from extensions like CODY by sourcegraph and improve the look and feel and UX of amazon Q

👍 we are definitely working on this. Thanks for the feedback!
