### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by josersleal** [aws/aws-toolkit-vscode#5694]
## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS:
-   Visual Studio Code version:
-   AWS Toolkit version:
-   Amazon Q version:

## Question
What is the pricing for the free tier?

**Comment by justinmk3** [comment]
Pricing info is here: https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/q-free-tier.html
