### ISSUE TITLE
SSO Sign in

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#57]
Requires SSO hooks to be available

* define and document an extension preference that is a collection of SSO endpoints
* each endpoint should have a corresponding display name string
* selecting to sign in with SSO presents the list stored in preferences
  * if no entries are found in preferences, inform the user that no SSO endpoints are defined, and how they can add some
* selecting an item from the list triggers SSO flow through a browser
* when signed in, the status bar should show information about the connected account

**Comment by chrisbelyea** [comment]
AWS CLI v2 makes getting temporary credentials via AWS SSO much easier. It would be great if the VS Code extension could make use of this.

It looks like CLI v2 stores temporary credentials in `~/.aws/cli/cache/` and `~/.aws/sso/cache/`.

**Comment by pcolmer** [comment]
As a workaround, you can use https://github.com/linaro-its/aws2-wrap in conjunction with a profile definition that uses the `credential_process` feature, e.g.:

```
[profile Wrapped]
credential_process = aws2-wrap --process --profile <awsprofilename>
```

If you then pick "Wrapped" as the profile you want to authenticate with, `aws2-wrap` will then generate the credentials for the extension to use.

**Comment by bryceitoc9** [comment]
FYI, this is now being worked on here: https://github.com/aws/aws-toolkit-vscode/pull/1304

**Comment by justinmk3** [comment]
Toolkit 1.21 includes support for AWS SSO. https://github.com/aws/aws-toolkit-vscode/pull/1304
