### ISSUE TITLE
Not loading on restart

### ISSUE THREAD

**Issue by ashitaphulwani** [aws/aws-toolkit-vscode#5742]
## Problem
Once I close Vs-code and restart the extension does not open its continuously lading

## Expected behavior
It should open
## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS:
-   Visual Studio Code version:
-   AWS Toolkit version:
-   Amazon Q version:

**Comment by justinmk3** [comment]
Need the details from the issue template, plus logs. If you have both Q and AWS Toolkit, need logs from both.

1. In the vscode [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette), run `Amazon Q: View Logs`. This reveals the Output panel with `Amazon Q Logs` selected.
2. Click the gear icon and choose `Debug`, then click it again and choose `Set As Default`.
3. Perform the steps to reproduce the issue.
4. Remove any private info from the logs.
