### ISSUE TITLE
Watch the user's AWS Credentials file for changes

### ISSUE THREAD

**Issue by bryceitoc9** [aws/aws-toolkit-vscode#576]
Right now, we validate credentials for a user's profile when the extension loads or when the profile changes. This means that we have faith that the user isn't changing their credentials file while the extension is loaded. This means that calls to the user's AWS resources may fail, and our telemetry can be off (due the the account ID changing without us noticing)

We need to implement a watcher to watch the credentials file for any changes. On file change, we should revalidate the credentials and load that into the AWS Context.

**Comment by mpiroc** [comment]
For the 'revalidate' portion of this, copied from #167:

@awschristou 
> When the Toolkit creates an initial AWS Credential profile, that profile is validated using STS getCallerIdentity. The same validation should happen whenever a user changes the Credential Profile used in the Toolkit. This helps to reduce the amount of errors encountered when trying to use invalid credentials.

**Comment by mpiroc** [comment]
This issue is covered as part of #168.
