### ISSUE TITLE
Support the NodeJS 10.x Lambda runtime

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#580]
AWS Lambda [now supports NodeJS 10.x](https://aws.amazon.com/about-aws/whats-new/2019/05/aws_lambda_adds_support_for_node_js_v10/). Therefore we need to enable debugging and new project creation for 10.x.

From the toolkit's point of view, there is no technical difference between 8.x and 10.x. So all that is needed is to add NodeJS 10.x to [`samLambdaRuntime.ts`](https://github.com/aws/aws-toolkit-vscode/blob/develop/src/lambda/models/samLambdaRuntime.ts), bump the minimum SAM CLI version, and perform testing for the new runtime.

### Acceptance Criteria

* When creating a new SAM application, the user can select the NodeJS 10.x runtime.
* When the user creates or opens a NodeJS 10.x SAM application, they can debug it from within VS Code using our code lenses.
* The user can successfully deploy a NodeJS 10.x SAM application.
* Bump the minimum SAM CLI version to the version which adds NodeJS 10.x support.
* All of the above workflows have been manually validated on all platforms (*nix, MacOS, and Windows).

**Comment by awschristou** [comment]
We will have to adjust the minimum SAM CLI version to whichever version onboards node 10 support also
