### ISSUE TITLE
Supporting step functions

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [aws/aws-toolkit-vscode#581]
Does the toolkit already support **Step Functions**? If not, are there are any **plans** to do so soon?

I searched and couldn't any mentions of step functions in the documentation nor in the list of open and closed issues, but apologies if it was raised before.

**Comment by bryceitoc9** [comment]
Apologies for the delay here. The toolkit does not currently support step functions.

**Comment by justinmk3** [comment]
closed by https://github.com/aws/aws-toolkit-vscode/pull/981
