### ISSUE TITLE
 Can my Github password also be an option for logging in to AWS?

### ISSUE THREAD

**Issue by Bab219** [aws/aws-toolkit-vscode#5818]
## Expected behavior
iclude option to log into aws online and on vs using github passwprd

**Comment by justinmk3** [comment]
This concept is sometimes called "federated login" or "social login". It's not supported yet.

**Comment by Bab219** [comment]
Thank you @justinmk3. I love in the UK, which although the option exists, does not require we use federated logins...I think this is way above me but does this mean in the future, not just with aws but other login processes, we would need to provide social login(s)?  I hope my question makes sense?

**Comment by justinmk3** [comment]
> we would need to provide social login(s)?

No :) I only wanted to provide some keywords for future reference. If federated or "social" login is supported in the future, it would just be another possible way to make it easier to use, for example, your github account to authenticate to your AWS account (which is how I interpreted your request).

If that feature is added, it would be part of the AWS cloud service, not AWS Toolkit.
