### ISSUE TITLE
amazonq: "maximum GenerateAssistantResponse reached for this month"

### ISSUE THREAD

**Issue by pitfunie** [aws/aws-toolkit-vscode#5848]
## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS:
-   Visual Studio Code version:
-   AWS Toolkit version:
-   Amazon Q version:

**Comment by pitfunie** [comment]
An error occurred while processing your request.
This error is reported to the team automatically. We will attempt to fix it as soon as possible.

Details: Maximum com.amazon.aws.codewhisperer.streaming.GenerateAssistantResponse reached for this month.

Request ID: b43d5d05-db99-438d-ae4e-1a1ee9913983

**Comment by justinmk3** [comment]
> Maximum com.amazon.aws.codewhisperer.streaming.GenerateAssistantResponse reached for this month.

That looks like a service message related to quota limit. Are you on the free tier? Can you provide more details?

**Comment by pitfunie** [comment]
Thank you, Justin:

I thought that was the issue as well the first time this happened.  That
AWS codewhisperer was the obvious issue.  And I was using Amazon Q for a
month.

The articles I found to be helpful turned out to just be lengthy.  Looked
for the words fix for the problem but none of that was found.

So is the problem free tier no. Is the problem developer no.   I have both
auth AWS for the Amazon Q extension for VSCODE Amazon Q (Q) so that is not
my reason for Q to stop work for my case.  Yea I know it could be Quota
limit.  I thought that was the case for a month But I needed  something now
and something stronger with self healing not fragile so I have be using
Copilot.

I eventually went back to Amazon Q because it is so convenient to use when
coding data preprocessing in VSCode.

It still was not working. I uninstalled Amazon Q extension and I think
shutdown MacBook Pro, something that I don’t do often.  Anyway, install
Amazon Q again and happily been coding for  I HAS NOT BEEN TWO WEEKS.

Then I asked Q an every lengthy coding question about AWS Application
Compose, and architecture constructs? Run book and Q crashed with the same
error.

It’s been three days now. I am using Copilot
and have Q on the back burner for now.  It seems to be that type of
service.

**Comment by pitfunie** [comment]
I'll look into Service Quota at some point

**Comment by justinmk3** [comment]
Thanks for those details. That definitely sounds like a service limit or service issue. It isn't something we can help you with here, because it would require your account info. Please contact AWS support: https://aws.amazon.com/contact-us/

**Comment by pitfunie** [comment]
Thank you, I will do that.

Justin,

So there are 5 categories.  The only one that can be adjusted is the ledger
Database.
Can you provide so guidance?

**Comment by pitfunie** [comment]
https://aws.amazon.com/contact-us/sales-contact-confirmation/

Submitted request.

No I don’t think this is a free tier.
Is the Pro license required?
If so Why just Q AI required.

**Comment by pitfunie** [comment]
Guess this is some sort of tier I am stuck with
