### ISSUE TITLE
Amazon Q chat not loading

### ISSUE THREAD

**Issue by ygeorge-dev** [aws/aws-toolkit-vscode#5863]
## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS:
-   Visual Studio Code version:
-   AWS Toolkit version:
-   Amazon Q version:

**Comment by ygeorge-dev** [comment]
I restarted vscode many times.
In my workshop event outputs, I click the url for vs code server:
https://d1stanncpdnm5y.cloudfront.net/?folder=/home/ubuntu/gen-ai-workshop

Then I click the Amazon Q icon. It never shows the options for free or
license. It never prompts me to confirm aws builderid.

**Comment by justinmk3** [comment]
> I click the url for vs code server:

That's an important detail. If you mean vscode "code server", that may be fixed by https://github.com/aws/aws-toolkit-vscode/pull/5847

Please try the vsix from https://github.com/aws/aws-toolkit-vscode/releases/tag/prerelease
