### ISSUE TITLE
Call to extractClasses seems to use path as file content incorrectly.

### ISSUE THREAD

**Issue by wmatosjr** [aws/aws-toolkit-vscode#5864]
https://github.com/aws/aws-toolkit-vscode/blob/5e8ad316718661bed35230e3596c13e5e2b53f30/packages/core/src/codewhisperer/util/supplementalContext/utgUtils.ts#L132

Shouldn't this be looking at the content of the editor.document.fileName and not the path?  Call to extractClasses attempts to extract classes from the path, resulting is this function always returning empty list.  Line should be: 

```typescript
testElementList.push(...extractClasses(testFileContent, languageConfig.classExtractionPattern))
```

**Comment by Will-ShaoHua** [comment]
hi @wmatosjr  thanks for reporting, yea it's a bug as you mentioned. Fix pr #5873
