### ISSUE TITLE
Does the toolkit for vscode work with Java 21?

### ISSUE THREAD

**Issue by jmihalich-ciandt** [aws/aws-toolkit-vscode#5872]
## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: Ubuntu 24.04
-   Visual Studio Code version: 1.94.2
-   AWS Toolkit version:3.29.0
-   Amazon Q version:

## Question
It does not appear that the java 21 runtime is supported by the latest aws toolkit for vscode for lambdas.  It only supports up to Java 17.  Is there a way to work around this?  Or, is there an ETA on when this will be supported?  Java 21 has been released since September 2023.

Thanks,
Joe

**Comment by justinmk3** [comment]
We are working on this. Please check the changelog / release notes of upcoming releases!

**Comment by justinmk3** [comment]
This was addressed in [AWS Toolkit 3.31.0](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode) !

AWS Toolkit changelog: https://github.com/aws/aws-toolkit-vscode/blob/master/packages/toolkit/CHANGELOG.md
Amazon Q changelog: https://github.com/aws/aws-toolkit-vscode/blob/master/packages/amazonq/CHANGELOG.md
Release artifacts: https://github.com/aws/aws-toolkit-vscode/releases

**Comment by jmihalich-ciandt** [comment]
confirmed this is working now. Thanks!
