### ISSUE TITLE
An error occurred while loading view: aws.AmazonQChatView

### ISSUE THREAD

**Issue by sangjiexun** [aws/aws-toolkit-vscode#5874]
## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS:
-   Visual Studio Code version:
-   AWS Toolkit version:
-   Amazon Q version:

**Comment by justinmk3** [comment]
Since there are no details given, I assume this is a duplicate of https://github.com/aws/aws-toolkit-vscode/issues/4503
