### ISSUE TITLE
"Error: Webview error" when Authentication for AmazonQ

### ISSUE THREAD

**Issue by davidtranjs** [aws/aws-toolkit-vscode#5909]
## Problem
I can't authenticate for AmazonQ extension on VSCode even login in browser success
## Steps to reproduce the issue
1. Go to Amazon Q 
2. Click "Re-Authenticate" button
3. Process login success on browser
![image](https://github.com/user-attachments/assets/620709f4-5674-4e75-aba6-1c56525dec62)
4. Back to VSCode and saw error 
![image](https://github.com/user-attachments/assets/3b87e7ac-e442-453d-9606-47b9eda6f273)
5. Click "View logs" and have this log

```
024-10-31 10:06:44.049 [info] auth: Handling validation error of connection: [some_id]
2024-10-31 10:06:44.049 [info] auth: Updating connection state of [some_id]
2024-10-31 10:06:44.095 [error] ssoSetup encountered an error: Error: Unable to authenticate connection
	 -> AccessDeniedException: Access denied
2024-10-31 10:06:44.095 [error] webviewId="aws.amazonq.AmazonCommonAuth": Error: Webview error
	 -> Error: Webview backend command failed: "reauthenticateAmazonQ()"
	 -> Error: Unable to authenticate connection
	 -> AccessDeniedException: Access denied
```

## Expected behavior
Authenticate success

## System details (run `AWS: About` and/or `Amazon Q: About`)

OS: Darwin arm64 23.6.0
Visual Studio Code extension host:  1.95.0
Amazon Q:  1.32.0
node: 20.18.0
electron: 32.2.1

**Comment by justinmk3** [comment]
Is this still an issue? Are you using the free tier or the pro tier?

Amazon Q Free tier does not support IdC for use from an IDE: https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/q-free-tier.html

Ensure that you have set up the Amazon Q Pro Tier in AWS console: https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/q-pro-tier-setting-up-access.html
