### ISSUE TITLE
Error: NodejsNpmBuilder:Resolver - Path resolution for runtime: nodejsXX.x of binary: npm was not successful

### ISSUE THREAD

**Issue by mtc-ecaro** [aws/aws-toolkit-vscode#5918]
## Problem

When testing NPM-based Lambda functions locally using JSON configuration in Visual Studio Code, an error occurs:

Error: NodejsNpmBuilder:Resolver - Path resolution for runtime: nodejsXX.x of binary: npm was not successful

Temporary Solution: Downgrading the AWS Toolkit to version 3.30

## Steps to reproduce the issue

Set up a Lambda function with Node.js runtime (nodejs20.x).
Attempt to run or test the function locally in VS Code with JSON configuration.

## Expected behavior

The Lambda function should run locally without path resolution issues for npm

## System details (run `AWS: About` and/or `Amazon Q: About`)

- OS: Windows 11 (latest version)
- Visual Studio Code: Latest version
- AWS Toolkit: Version 3.31
- Amazon Q: Not applicable

**Comment by roger-zhangg** [comment]
Hi @mtc-ecaro , thanks for reporting this. Could you please share the following detail
- Which shell is your default VSCode shell? (Powershell / WSL maybe?)
- Where did you get the resolution error. In terminal shell, or it's in toolkit logs
- Does downgrading resolve this issue immediately
- 
These will help us better resolve the issue. Thank you

**Comment by mtc-ecaro** [comment]
Hello, as requested here is the additional information:

- Powershell
- Toolkit logs
- Downgrading to .30 solve my issue

Just for context , I'm part of a small team and all of them had the same issue, we all have rolled back to .30 and are able to locally execute/debug the lambda functions successfully.

**Comment by justinmk3** [comment]
This request was addressed in [AWS Toolkit 3.32.0](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode) and/or [Amazon Q 1.34.0](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.amazon-q-vscode)!

- AWS Toolkit changelog: https://github.com/aws/aws-toolkit-vscode/blob/master/packages/toolkit/CHANGELOG.md
- Amazon Q changelog: https://github.com/aws/aws-toolkit-vscode/blob/master/packages/amazonq/CHANGELOG.md
- Release artifacts: https://github.com/aws/aws-toolkit-vscode/releases
