### ISSUE TITLE
Lambda Upload not showing current Runtime and Framework options

### ISSUE THREAD

**Issue by rob2sticks** [aws/aws-toolkit-vscode#603]
I'm attempting to upgrade my Lambda projects to .NET Core v2.2. I'm using Visual Studio 2015 and the ToolKit and it's Publish feature. I have installed .NET Core v2.2. I have installed the latest ToolKit (AWSToolsAndSDKForNet_sdk-3.3.523.0_ps-3.3.522.0_tk-1.14.5.0.msi). I have updated my aws-labmda-tools-defaults.json files to "netcoreapp2.2" and "dotnetcore2.0". The code is compiling successfully.

However, when I attempt to publish, the wizard only gives me options for a Runtime of ".NET Core v1.0" and a Framework of "netcoreapp1.0". Attempting to proceed with these settings causes a failure (no .NET project found in directory c:\xxx to build).

Whether it's relevant or not, NuGet does not show the ToolKit as being updated (it shows v3.2.3 as being installed).

Please advise...

**Comment by klaytaybai** [comment]
Hi @rob2sticks, you should consider upgrading to Visual Studio 2017 or 2019 as a good first step.  Visual Studio 2015 doesn't support .NET Core 2.0 or 2.2, so it wouldn't make sense for us to provide these options in our 2015 build.  Our Visual Studio 2017 and 2019 builds support using netcoreapp2.0.

The better location for this issue would be in the [aws-sdk-net](https://github.com/aws/aws-sdk-net/issues) repo.  If you would like to see more done on adding this support into the toolkit, please post there.

**Comment by rob2sticks** [comment]
I didn't want to upgrade unless I had to but will go that route. Thank you very much for the response and info. Cheers...

**Comment by mpiroc** [comment]
Closing as this issue is related to the toolkit for Visual Studio, not VS Code. Issues related to Visual Studio should be filed in the [aws-sdk-net](https://github.com/aws/aws-sdk-net/issues) repository.
