### ISSUE TITLE
Reduce confusion in "Create new SAM app" directory selector

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#608]
The text box in this selector is a search/filter, but this is not obvious to the user. They may type the name of a directory that they wish to create, hit Enter, and be surprised when this takes them back to the previous page.

If possible, we should disable 'Enter' when no directory is selected. We should also more clearly label the text box as a search/filter.

**Comment by awschristou** [comment]
This will be addressed with #673, #674, and #675 and was assisted with #654 . Closing.
