### ISSUE TITLE
Users can see a Welcome Page in-IDE from a Command

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#610]
We want users to have a welcoming on-boarding experience, that helps inform them on some of the Toolkit's capabilities.

The initial implementation will use the marketplace contents as the welcome page.
Other issues will wire this command into other locations within the Toolkit.

Acceptance Criteria:
* a Command Palette command exists that displays a welcome page
* The welcome page shown is the contents of the marketplace landing page, in `extension-readme.md`
* a formatted presentation of the welcome page is shown (no raw text)

**Comment by bryceitoc9** [comment]
We should be able to display HTML with TextDocumentContentProvider: https://code.visualstudio.com/api/references/vscode-api#TextDocumentContentProvider

We can compile the markdown into HTML via task: https://code.visualstudio.com/docs/languages/markdown#_compiling-markdown-into-html

**Comment by bryceitoc9** [comment]
PR: https://github.com/aws/aws-toolkit-vscode/pull/619
