### ISSUE TITLE
Users are presented with welcome information on First-Time start-up

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#611]
We want users to have a welcoming on-boarding experience, that helps inform them on some of the Toolkit's capabilities.

#610 contains the command to display the welcome page. This task helps bring the user to that page the first time they open the extension.

Acceptance Criteria:
* the first time the user activates the Toolkit after installing, a notification is shown
* the first time the user activates the Toolkit after updating the toolkit, a notification is shown
* the notification welcomes the user to the Toolkit, and contains a link which triggers the command (#610) to show the Welcome page
* the notification is non-modal, and non-blocking (is not awaited on)

**Comment by bryceitoc9** [comment]
PR: https://github.com/aws/aws-toolkit-vscode/pull/623
