### ISSUE TITLE
stepfunctions: asl format doesn't allow QueryLanguage key

### ISSUE THREAD

**Issue by GabrieleCedrinoCorley** [aws/aws-toolkit-vscode#6118]
## Steps to reproduce the issue
When viewing an .asl file for Amazon States Language, a QueryLanguage key is considered an error. According to the [ASL spec:](https://states-language.net/) 

![image](https://github.com/user-attachments/assets/ec60652c-8371-4904-9e16-1b498dafc51c)

So, I think the language should be allowing a QueryLanguage key. 

## Step to reproduce the issue

<img width="630" alt="image" src="https://github.com/user-attachments/assets/238594b7-28cc-44e5-8c8b-ea9163c87872">

## Expected behavior

Expected this .asl to be valid and thus graphable. 

## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: 
-   Visual Studio Code version: 1.95.3 (Universal)
-   AWS Toolkit version: 3.36.0
-   Amazon Q version:

**Comment by elvin-hwang** [comment]
Will close as duplicate, here's the fix for this issue
https://github.com/aws/amazon-states-language-service/pull/159

**Comment by nkomonen-amazon** [comment]
This request was addressed in [AWS Toolkit 3.38.0](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode) and/or [Amazon Q 1.40.0](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.amazon-q-vscode)!

    AWS Toolkit changelog: https://github.com/aws/aws-toolkit-vscode/blob/master/packages/toolkit/CHANGELOG.md
    Amazon Q changelog: https://github.com/aws/aws-toolkit-vscode/blob/master/packages/amazonq/CHANGELOG.md
    Release artifacts: https://github.com/aws/aws-toolkit-vscode/releases
