### ISSUE TITLE
Users can access the Welcome Page from the AWS Explorer menu

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#612]
We want users to have a welcoming on-boarding experience, that helps inform them on some of the Toolkit's capabilities.

#610 contains the command to display the welcome page. This task lets the user access the welcome page from the AWS Explorer menu.

![image](https://user-images.githubusercontent.com/39839589/59391670-e401a780-8d29-11e9-9c25-67336f846c48.png)

Acceptance Criteria:
* AWS Explorer menu has an item to show the Welcome page
* menu item does not get added to other VS Code extension menus

**Comment by bryceitoc9** [comment]
PR: https://github.com/aws/aws-toolkit-vscode/pull/619 (also covers https://github.com/aws/aws-toolkit-vscode/issues/610)
