### ISSUE TITLE
Amazon Q: (Windows) running powershell every 2 seconds

### ISSUE THREAD

**Issue by nistSean** [aws/aws-toolkit-vscode#6134]
## Problem

When the Amazon Q extension is enabled, there is a PowerShell command being executed continuously.

```
**********************
Windows PowerShell transcript start
Start time: 20241203145229
Username: xxxx\xxxxx
RunAs User: xxxx\xxxxx
Configuration Name: 
Machine: xxxxxxxxx (Microsoft Windows NT 10.0.22631.0)
Host Application: powershell.exe -NoProfile -NoLogo -InputFormat Text -NoExit -ExecutionPolicy Unrestricted -Command -
Process ID: 6868
PSVersion: 5.1.22621.4391
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.4391
BuildVersion: 10.0.22621.4391
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
**********************
Windows PowerShell transcript start
Start time: 20241203145229
Username: xxxx\xxxxx
RunAs User: xxxx\xxxxx
Configuration Name: 
Machine: xxxxxxxxxxx (Microsoft Windows NT 10.0.22631.0)
Host Application: powershell.exe -NoProfile -NoLogo -InputFormat Text -NoExit -ExecutionPolicy Unrestricted -Command -
Process ID: 6868
PSVersion: 5.1.22621.4391
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.4391
BuildVersion: 10.0.22621.4391
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
PS>CommandInvocation(Out-String): "Out-String"
>> ParameterBinding(Out-String): name="InputObject"; value="Exception calling "ReadLine" with "2" argument(s): "Specified method is not supported.""
Exception calling "ReadLine" with "2" argument(s): "Specified method is not supported."
At C:\Program Files\WindowsPowerShell\Modules\PSReadLine\2.0.0\PSReadLine.psm1:4 char:5
+     [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException
Exception calling "ReadLine" with "2" argument(s): "Specified method is not supported."
At C:\Program Files\WindowsPowerShell\Modules\PSReadLine\2.0.0\PSReadLine.psm1:4 char:5
+     [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException
PS>$OutputEncoding = [System.Console]::OutputEncoding = [System.Console]::InputEncoding = [System.Text.Encoding]::UTF8 ; Get-CimInstance Win32_PageFileUsage | Select AllocatedBaseSize, CurrentUsage

AllocatedBaseSize CurrentUsage
----------------- ------------
             9728            4


**********************
Windows PowerShell transcript start
Start time: 20241203145230
Username: xxxx\xxxxx
RunAs User: xxxx\xxxxx
Configuration Name: 
Machine: xxxxxxxxx (Microsoft Windows NT 10.0.22631.0)
Host Application: powershell.exe -NoProfile -NoLogo -InputFormat Text -NoExit -ExecutionPolicy Unrestricted -Command -
Process ID: 6868
PSVersion: 5.1.22621.4391
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.4391
BuildVersion: 10.0.22621.4391
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
PS>CommandInvocation(Out-String): "Out-String"
>> ParameterBinding(Out-String): name="InputObject"; value="Exception calling "ReadLine" with "2" argument(s): "Specified method is not supported.""
Exception calling "ReadLine" with "2" argument(s): "Specified method is not supported."
At C:\Program Files\WindowsPowerShell\Modules\PSReadLine\2.0.0\PSReadLine.psm1:4 char:5
+     [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException
Exception calling "ReadLine" with "2" argument(s): "Specified method is not supported."
At C:\Program Files\WindowsPowerShell\Modules\PSReadLine\2.0.0\PSReadLine.psm1:4 char:5
+     [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException
PS>exit
**********************
Windows PowerShell transcript end
End time: 20241203145230
**********************
```

## Steps to reproduce the issue

1. Go to Visual Studio
2. Enable the Amazon Q extension
3. Check powershell logs. 

## Expected behavior

Don't do this.

## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: Windows 11 
-   Visual Studio Code version: 1.95.3
-   AWS Toolkit version: 3.37.0 (edited 12/4/2024)
-   AWS CLI V2 2.18.7
-   Amazon Q version: 1.39.0

**Comment by nistSean** [comment]
This started for me 11/19/24 likely after updating VS Code and/or VS Code extensions.

**Comment by justinmk3** [comment]
> This started for me 11/19/24

For reference, [Amazon Q 1.36.0](https://github.com/aws/aws-toolkit-vscode/releases/tag/amazonq%2Fv1.36.0) was released on 11/14.

> AWS Toolkit version: 2.18.7

Is that version correct? Latest is AWS Toolkit 3.35.0. 

If you uninstall AWS Toolkit, does the problem still occur? This will help narrow down the issue.

**Comment by justinmk3** [comment]
> Steps to reproduce the issue
> 1. Go to Visual Studio
> 2. Enable the Amazon Q extension
> 3. Check powershell logs.

Can you give more specific details about where to find "powershell logs"? Is this a OS-global logs (Windows EventLog)? Exact steps about how to find these logs will help.

I've searched:

1. the code in this repo,
2. the code in `node_modules` used to build this project, and 
3. the final webpack'd `extension/dist/src/extensionNode.js` 

and did not find anything like (case-insensitive)  `out-string`, `ExecutionPolicy.*Unrestricted`, etc.

Our dev-dependencies (non-production) [use](https://github.com/aws/aws-toolkit-vscode/blob/337959a0c5a7813dab6d0cf30b58340f2321336a/package-lock.json#L20130) `readline-sync` but that is not shipped as part of the production build.

Powershell supports aliases, so it's possible there is some pwsh command invocation using a different "spelling" than what is reported in your logs. It's also possible that something is indirectly *triggering* a powershell script on your system?

**Comment by nistSean** [comment]
> > This started for me 11/19/24
> 
> For reference, [Amazon Q 1.36.0](https://github.com/aws/aws-toolkit-vscode/releases/tag/amazonq%2Fv1.36.0) was released on 11/14.
> 
> > AWS Toolkit version: 2.18.7
> 
> Is that version correct? Latest is AWS Toolkit 3.35.0.
> 
> If you uninstall AWS Toolkit, does the problem still occur? This will help narrow down the issue.

Are you looking for the version of AWS Toolkit installed on the Machine or in VS Code? That is the version number for the AWS Toolkit (or maybe CLI) installed on the machine. The AWS Toolkit VS Code plugin is 3.37.0

**Comment by nistSean** [comment]
In our environment, our systems are configured to log all PowerShell executions. I am attempting to get the details on how that is configured but I assume it's a group policy setting. Regardless of the logging, there is something executing over and over (>43K/day) when the Amazon Q plug-in is enabled. 

I removed all plugins from VS Code except Amazon Q (1.39.0). With the plug-in disabled I get one entry in the log when starting VS Code:

`
**********************
Windows PowerShell transcript start
Start time: 20241204072146
Username: ****\*****
RunAs User: ****\*****
Configuration Name: 
Machine: ********** (Microsoft Windows NT 10.0.22631.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command try { . "c:\Users\*****\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1" } catch {}
Process ID: 11944
PSVersion: 5.1.22621.4391
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.4391
BuildVersion: 10.0.22621.4391
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
PS>try { . "c:\Users\*****\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1" } catch {}
PS>TerminatingError(Get-PSReadLineKeyHandler): "A parameter cannot be found that matches parameter name 'Chord'."
PS>TerminatingError(Get-PSReadLineKeyHandler): "A parameter cannot be found that matches parameter name 'Chord'."
PS>TerminatingError(Get-PSReadLineKeyHandler): "A parameter cannot be found that matches parameter name 'Chord'."
PS>TerminatingError(Get-PSReadLineKeyHandler): "A parameter cannot be found that matches parameter name 'Chord'."
]633;A ]633;P;Cwd=C:\x5cUsers\x5c*****\x5cOneDrive - NIST\x5cDocuments\x5csource\x5cgit-documentation PS C:\Users\*****\OneDrive - NIST\Documents\source\git-documentation> ]633;B
`

As soon as I enable the Amazon Q extension, these logs start:
`
**********************
Windows PowerShell transcript start
Start time: 20241204074011
Username: ****\*****
RunAs User: ****\*****
Configuration Name: 
Machine: ********** (Microsoft Windows NT 10.0.22631.0)
Host Application: powershell.exe -NoProfile -NoLogo -InputFormat Text -NoExit -ExecutionPolicy Unrestricted -Command -
Process ID: 25140
PSVersion: 5.1.22621.4391
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.4391
BuildVersion: 10.0.22621.4391
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
**********************
Windows PowerShell transcript start
Start time: 20241204074011
Username: ****\*****
RunAs User: ****\*****
Configuration Name: 
Machine: ******** (Microsoft Windows NT 10.0.22631.0)
Host Application: powershell.exe -NoProfile -NoLogo -InputFormat Text -NoExit -ExecutionPolicy Unrestricted -Command -
Process ID: 25140
PSVersion: 5.1.22621.4391
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.4391
BuildVersion: 10.0.22621.4391
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
PS>CommandInvocation(Out-String): "Out-String"
>> ParameterBinding(Out-String): name="InputObject"; value="Exception calling "ReadLine" with "2" argument(s): "Specified method is not supported.""
Exception calling "ReadLine" with "2" argument(s): "Specified method is not supported."
At C:\Program Files\WindowsPowerShell\Modules\PSReadLine\2.0.0\PSReadLine.psm1:4 char:5
+     [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException
Exception calling "ReadLine" with "2" argument(s): "Specified method is not supported."
At C:\Program Files\WindowsPowerShell\Modules\PSReadLine\2.0.0\PSReadLine.psm1:4 char:5
+     [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException
PS>$OutputEncoding = [System.Console]::OutputEncoding = [System.Console]::InputEncoding = [System.Text.Encoding]::UTF8 ; Get-CimInstance Win32_Battery | select BatteryStatus, DesignCapacity, DesignVoltage, EstimatedChargeRemaining, DeviceID | fl
**********************
Windows PowerShell transcript start
Start time: 20241204074012
Username: ****\*****
RunAs User: ****\*****
Configuration Name: 
Machine: ********** (Microsoft Windows NT 10.0.22631.0)
Host Application: powershell.exe -NoProfile -NoLogo -InputFormat Text -NoExit -ExecutionPolicy Unrestricted -Command -
Process ID: 25140
PSVersion: 5.1.22621.4391
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.4391
BuildVersion: 10.0.22621.4391
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
PS>CommandInvocation(Out-String): "Out-String"
>> ParameterBinding(Out-String): name="InputObject"; value="Exception calling "ReadLine" with "2" argument(s): "Specified method is not supported.""
Exception calling "ReadLine" with "2" argument(s): "Specified method is not supported."
At C:\Program Files\WindowsPowerShell\Modules\PSReadLine\2.0.0\PSReadLine.psm1:4 char:5
+     [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException
Exception calling "ReadLine" with "2" argument(s): "Specified method is not supported."
At C:\Program Files\WindowsPowerShell\Modules\PSReadLine\2.0.0\PSReadLine.psm1:4 char:5
+     [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException
PS>exit
**********************
Windows PowerShell transcript end
End time: 20241204074012
********************** 
`

**Comment by nistSean** [comment]
This should be able to be recreated locally by enabling the following policy at either the Computer or User configuration via gpedit 

Administrative Templates --> Windows Components --> Windows PowerShell --> "Turn on PowerShell Transcript"

**Comment by justinmk3** [comment]
> Could it be related to #5780

I think that issue is referring to a "Activating extensions..." message which vscode will show when activating extensions. Unrelated to this issue.

> there is something executing over and over (>43K/day) when the Amazon Q plug-in is enabled.

This could be...

- the Amazon Q "Auto Reviews" feature. Click the Amazon Q statusbar item and try disabling Auto Reviews in the menu:
  <img width="502" alt="image" src="https://github.com/user-attachments/assets/035b9cf6-127a-44de-a663-c69dca0e2d78">
- the workspace indexing feature. In vscode settings, ensure that `amazonQ.workspaceIndex` is disabled:
  <img width="681" alt="image" src="https://github.com/user-attachments/assets/2fe196db-9514-4e5f-8c18-b172828e0046">

Let me know if you find improvement after the above steps. We'll still want to make this less noisy.

Meanwhile we will try to narrow this down.

**Comment by nistSean** [comment]
> > Could it be related to #5780
> 
> I think that issue is referring to a "Activating extensions..." message which vscode will show when activating extensions. Unrelated to this issue.
> 
> > there is something executing over and over (>43K/day) when the Amazon Q plug-in is enabled.
> 
> This could be...
> 
> * the Amazon Q "Auto Reviews" feature. Click the Amazon Q statusbar item and try disabling Auto Reviews in the menu:
>   <img alt="image" width="502" src="https://private-user-images.githubusercontent.com/55561878/392506000-035b9cf6-127a-44de-a663-c69dca0e2d78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzU1ODAsIm5iZiI6MTczMzMzNTI4MCwicGF0aCI6Ii81NTU2MTg3OC8zOTI1MDYwMDAtMDM1YjljZjYtMTI3YS00NGRlLWE2NjMtYzY5ZGNhMGUyZDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE4MDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYmRkMTcxNmM3YjU1YmViMjdkNjQ2MWQ1Mjc3YmJiYjU5OTU3OTZlNDA2YjU3MjMwM2EyYTAxYmFlOGM0ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2oDNlRbAgSEOE8OsaE5KjZpLiKNin6dHIMkL_QlrKc4">
> * the workspace indexing feature. In vscode settings, ensure that `amazonQ.workspaceIndex` is disabled:
>   <img alt="image" width="681" src="https://private-user-images.githubusercontent.com/55561878/392505667-2fe196db-9514-4e5f-8c18-b172828e0046.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzU1ODAsIm5iZiI6MTczMzMzNTI4MCwicGF0aCI6Ii81NTU2MTg3OC8zOTI1MDU2NjctMmZlMTk2ZGItOTUxNC00ZTVmLThjMTgtYjE3MjgyOGUwMDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE4MDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNDZhZTUxZTNhNDdmZmE0MjM3ODkzN2E3YWE2YTBiZDg4OGFlM2Q4Y2Y1MDJhNWI4N2NmZDAwNzkwNDhhMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pR9RA5tGiLdTtACqlD9ACtY-kmwee7VLQw0dCU9k92s">
> 
> Let me know if you find improvement after the above steps. We'll still want to make this less noisy.
> 
> Meanwhile we will try to narrow this down.

Thanks for the suggestions but it made no noticeable difference.
I unchecked the index workspace in the settings and tried pausing both reviews and suggestions but it didn't appear to make any difference. 

I also uninstalled and reinstalled everything from scratch today AWS CLI, VS Code, Extensions etc. (haven't added by AWS Toolkit, I mostly use the CLI) but that also didn't have any affect.

**Comment by nkomonen-amazon** [comment]
@nistSean would you say these are the correct/sufficient steps to reproduce the errors in the logs?

- Enable global Powershell Transcripts
  - Steps:
    - Open the Local Group Policy Editor (gpedit.msc).
    - Navigate to Computer Configuration > Administrative Templates > Windows Components > Windows PowerShell. 
    - Double-click Turn on PowerShell Transcription.
    - Set the policy to Enabled.
    - Specify the Transcript output directory to a secure location.
- Open Q and try to reproduce the user getting many logs
  - It looks like it may just be triggered by the extension starting up
  - If the above is not enough, ensure you have a workspace open and try some Q features

**Comment by nistSean** [comment]
I think that should be correct; unfortunately, in my environment, these settings are pushed down by domain policy, so I can't set or update them myself.

**Comment by justinmk3** [comment]
> I unchecked the index workspace in the settings and tried pausing both reviews and suggestions but it didn't appear to make any difference.

After unchecking the `amazonQ.workspaceIndex` setting, please try restarting vscode and then double-check that the setting is still unchecked. 

We have narrowed down the issue to [this code](https://github.com/sebhildebrandt/systeminformation/blob/3a92931c7d46605ffddc1aacb97a9727273b2888/lib/util.js#L402) which is used by the Q Workspace Index feature. We will consider how to mitigate this.

**Comment by nistSean** [comment]
> > I unchecked the index workspace in the settings and tried pausing both reviews and suggestions but it didn't appear to make any difference.
> 
> After unchecking the `amazonQ.workspaceIndex` setting, please try restarting vscode and then double-check that the setting is still unchecked.
> 
> We have narrowed down the issue to [this code](https://github.com/sebhildebrandt/systeminformation/blob/3a92931c7d46605ffddc1aacb97a9727273b2888/lib/util.js#L402) which is used by the Q Workspace Index feature. We will consider how to mitigate this.

I unchecked 
![image](https://github.com/user-attachments/assets/15ed30c6-1ca5-4fa9-aead-5ac685815a2d)
and restarted VS Code it's still unchecked but the log file generation continued.

**Comment by justinmk3** [comment]
In the next release of Amazon Q for VSCode, this powershell command will only run if the `amazonQ.workspaceIndex` setting is enabled (which is used by the `@workspace` Q chat feature).

Would you be able to try the prerelease extension from https://github.com/aws/aws-toolkit-vscode/releases/tag/prerelease to confirm that the improved behavior?

**Comment by nistSean** [comment]
> In the next release of Amazon Q for VSCode, the powershell command will only run if the `amazonQ.workspaceIndex` setting is enabled (which is used by the `@workspace` Q chat feature).
> 
> Would you be able to try the prerelease extension from https://github.com/aws/aws-toolkit-vscode/releases/tag/prerelease to confirm that the improved behavior?

@justinmk3 

I installed only the prerelease of the version of Amazon Q (v1.41.0-g0a40071). I haven't reinstalled the AWS toolkit since I started debugging this since it doesn't seem to be part of the problem (let me know if you need me to verify something).

From what I can tell, it is now working as intended. A couple of files were generated at launch, and several were generated when I used the /doc command to update usage in the readme. But there is no longer a continuous stream of log files. 

Can you tell me what the impact is from an end-user perspective? Is it now doing the indexing at the time of request instead of continually scanning for changes?

**Comment by justinmk3** [comment]
Thank you for confirming!

> Is it now doing the indexing at the time of request instead of continually scanning for changes?

The powershell task is a health-monitoring task to dynamically decide how much CPU to use while indexing.

The change that was made is that this health-monitoring task is skipped unless indexing is actually in-progress. That means the powershell "noise" will still occur if Q workspace-indexing is enabled and actively indexing.

**Comment by nistSean** [comment]
@justinmk3, Thank you.
