### ISSUE TITLE
Users can provide Quick Feedback about the Toolkit from the AWS Explorer Menu

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#614]
The AWS Explorer menu would contain a menu item that allows users to enter feedback that is sent directly to the Toolkit's development team.

Collaborate with the [JetBrains Toolkit](https://github.com/aws/aws-toolkit-jetbrains/issues/1018) on design.

TBD - data exchange

**Comment by justinmk3** [comment]
![image](https://user-images.githubusercontent.com/55561878/140241657-ddb3557e-a109-4eb8-9129-d29fd1cfd365.png)
