### ISSUE TITLE
error while loading view: aws.AmazonQChatView (DiskCacheError)

### ISSUE THREAD

**Issue by LewS** [aws/aws-toolkit-vscode#6140]
## Problem
AmazonQ worked for the first week or so, then when loaded shows the error 
`An error occurred while loading view: aws.AmazonQChatView`
AmazonQ is set to auto update.
Udating vs code, does not fix the problem.
## Steps to reproduce the issue
Install AmazonQ and wait for a week or so...
[Amazon Q Logs.log](https://github.com/user-attachments/files/18002524/Amazon.Q.Logs.log)

## Expected behavior
Ability to use amazonq chat functionality
## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: Linux - Ubuntu 24.04
-   Visual Studio Code version: 1.95.3
-   AWS Toolkit version: v.1.39.0
-   Amazon Q version: v3.37.0

**Comment by justinmk3** [comment]
```
2024-12-04 15:17:22.455 [warning] auth: failed to restore previous session: Error: Failed to update connection due to file system operation failures [DiskCacheError]
	 -> DiskCacheError: LOAD failed for '/home/lew/.aws/sso/cache/6e60c8cc5bae992900fecfad4781120f41eb6124.json' (key: dfd55e61-46f6-4faa-8b51-e13b49b26bc8)
	 -> SyntaxError: Unexpected end of JSON input
2024-12-04 15:17:22.465 [error] loadSavedConnection: Failed to refresh connection state: Error: Failed to update connection due to file system operation failures [DiskCacheError]
	 -> DiskCacheError: LOAD failed for '/home/lew/.aws/sso/cache/6e60c8cc5bae992900fecfad4781120f41eb6124.json' (key: dfd55e61-46f6-4faa-8b51-e13b49b26bc8)
	 -> SyntaxError: Unexpected end of JSON input
...
2024-12-04 15:17:22.493 [error] CodeWhisperer: Error when fetching feature configs Error: Failed to update connection due to file system operation failures
```

Looks like there are problems with the filesystem. We should handle this in a better way, but likely will still have problems if filesystem operations are failing.

**Comment by LewS** [comment]
Hey Nikolas, 6e60c8cc5bae992900fecfad4781120f41eb6124.json is 0 bytes, so nothing to add :/
That gives you a perfect picture of it at least, and hopefluly a clue as to where the deeper problem lays.
The toolkit json looks correct through.
