### ISSUE TITLE
Investigate how to reference AWS Code Catalog / Samples

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#615]
Customers need sample code to start with. Investigate how to reference the [AWS Code Catalog](https://docs.aws.amazon.com/code-samples/latest/catalog/welcome.html).

Collaborate with the [JetBrains Toolkit](https://github.com/aws/aws-toolkit-jetbrains/issues/1019) on design.

This would possibly go into the Welcome Page (#610) as an initial implementation

**Comment by justinmk3** [comment]
related: https://github.com/aws/aws-toolkit-vscode/issues/1174
