### ISSUE TITLE
Provide link of Learn AWS in the Welcome Page

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#616]
The Toolkit is a great place to help users develop an understanding about AWS. Determine how and where to guide those curious about learning more.

Collaborate with the [JetBrains Toolkit](https://github.com/aws/aws-toolkit-jetbrains/issues/1020) on design.

This would possibly go into the Welcome Page (#610) as an initial implementation

**Comment by justinmk3** [comment]
- https://github.com/aws/aws-toolkit-vscode/pull/1897
- https://github.com/aws/aws-toolkit-vscode/pull/2649
