### ISSUE TITLE
Write design document for `credential_process` support.

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#617]
Supporting `credential_process` will be more involved than simply upgrading our dependency on `aws-sdk`. We should create a design for the correct way to handle credentials before starting work on this.

Acceptance criteria:
* A design document is checked into the `design/` folder that describes
* Our model for handling credentials throughout the toolkit.
* How `credential_process` fits into this model.

**Comment by garthk** [comment]
More involved, how? Couple bullet points would help.

**Comment by garthk** [comment]
Not sure how to resolve this with #317:
> Today version 1.1.0 of the Toolkit has been released, which includes credential_process support.

**Comment by awschristou** [comment]
The toolkit's approach to credentials is now documented in #889

**Comment by awschristou** [comment]
Credentials Documentation now available - https://github.com/aws/aws-toolkit-vscode/blob/master/designs/credentials/credentials-management.md
