### ISSUE TITLE
Toolkit shows field not supported in JSONata Step Function definitions

### ISSUE THREAD

**Issue by mattbbc** [aws/aws-toolkit-vscode#6196]
## Problem

AWS recently introduced using JSONata as a query language option for Step Functions. When examining an example definition in a JSON file that uses JSONata as the Step Function query language, a number of the fields are flagged as not supported and the Step Function cannot be rendered into a preview graph.

## Steps to reproduce the issue

1. Go to [this AWS sample state machine definition](https://github.com/aws-samples/serverless-account-signup-service/blob/jsonata-variables/statemachine/application_service.asl.json), copy it into a folder on your machine and open the folder in VSCode.
2. Open the ASL state machine definition definition in the editor
3. Note that fields such as 'QueryLanguage' and 'Condition' and 'Arguments' are flagged as 'Field not supported' errors by the compiler
4. Click 'Render state machine graph' in the top right, or cmd + shift + v
5. See error - preview will not render

## Expected behavior

Fields should not raise compiler errors and state machine preview should render.

## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: macOS Sonoma 14.7.1
-   Visual Studio Code version: 1.95.3
-   AWS Toolkit version: 3.37.0
-   Amazon Q version: n/a

**Comment by justinmk3** [comment]
>  AWS Toolkit version: 3.37.0

Please try updating to AWS Toolkit 3.38.0. https://github.com/aws/aws-toolkit-vscode/blob/master/packages/toolkit/CHANGELOG.md#3380-2024-12-10
