### ISSUE TITLE
Unable to connect by Assuming Roles (with or without MFA)

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#620]
Assume role support has regressed in the Toolkit. This was noticed in v0.2.0.

Using roles with and without MFA are affected.

To repro:
* Create a role that has S3 Read Only access
* Create a user that only has permissions to `sts:AssumeRole` against the above role
* Configure the shared credentials:
```
[role-assumer]
aws_access_key_id = <USER_KEY>
aws_secret_access_key = <USER_SECRET>

[assumed-role]
role_arn = <ROLE_ARN>
source_profile = role-assumer
```
* Confirm this works with AWS CLI:
  * `aws s3 ls --profile assumed-role`
* Try using role in VS Code Toolkit

**Comment by bryceitoc9** [comment]
We weren't passing along the session token in our `sts.getCallerIdentity` call which meant we couldn't log the user in due to initial validation failing.

Fix here: https://github.com/aws/aws-toolkit-vscode/pull/621

**Comment by bryceitoc9** [comment]
Merged.
