### ISSUE TITLE
Windows: wrong CWD for SAM launch config when my code is on another drive

### ISSUE THREAD

**Issue by Seikilos** [aws/aws-toolkit-vscode#6207]
## Problem

When running a vs code launch configuration to debug my lambda, the build process fails with

```
2024-12-11 10:51:43.874 [info] Error: path is on mount 'D:', start on mount 'C:'
Traceback:
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
```

Have tried to find any parameter like `cwd` or passing absolute path to template file did not solve the issue. I would really like to avoid copying anything to C to make this work. Also running `sam build`, `deploy` etc from this directory works. It seems like cwd is not correctly set up in the launch config.

## Steps to reproduce the issue

 1. Have your code on another drive than C
 2. Use a similar configuration to start aws-sam direct invoke
 ```json
{
            "name": "Start local in debug",
            "type": "aws-sam",
            "request": "direct-invoke", 
            "invokeTarget": {
                "target": "api",
                "templatePath": "template.yaml",
                "logicalId": "RunJobLambda",

            },
            "api": {
                "path": "/job",
                "httpMethod": "post",
                "payload": {
                    "json": {}
                },
                "querystring": "abc=def&qrs=tuv",
                "headers": {
                    "cookie": "name=value; name2=value2; name3=value3"
                }
            },
            "sam": {},
            "aws": {}
        }
```

## Expected behavior

VS Code should allow me to debug the lambda function

## System details (run `AWS: About` and/or `Amazon Q: About`)

-   OS: Windows 11, 22H2 22621.4317
-   Visual Studio Code version: 1.95.3
-   AWS Toolkit version: v3.38.0
-   Amazon Q version: Not used

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/issues/2296 is a similar issue where some potential workarounds are discussed.

This may be a SAM CLI issue.

**Comment by Seikilos** [comment]
@justinmk3 Thanks!
This fixed my issue, I was looking at the available params on the top level of the aws-node launch configuration and did not thought about looking at those others too ...

```json
 "sam": { 
    "buildDir": "${workspaceFolder}/build",
    "buildArguments": ["--profile", "optional profile"]
 },
```

Fixed my problem!
