### ISSUE TITLE
Pressing up key while writing a message in the Chat window erases the message

### ISSUE THREAD

**Issue by xander-marjoram** [aws/aws-toolkit-vscode#6231]
## Problem

If you press the `ArrowUp` key while writing a message, it will be deleted with no obvious way to restore it.

The likely scenario to run into this is when writing a long message but you want to go back and edit what you have written. When your message is deleted without warning it can be extremely frustrating as you have to write it again from scratch.

## Steps to reproduce the issue
1. Go to the Amazon Q tab in the VS Code sidebar.
2. Start typing into the "Ask a question" textbox.
3. Press the `ArrowUp` key on the keyboard. The message will be erased.

Pressing `ArrowDown` or `Ctrl+Z` does not restore the message.

## Expected behavior
Pressing the up arrow should move the cursor up to the previous line of text, or do nothing if there is only one line.

Or, if there is a good reason for deleting the unsent message, it should be easy to restore it.

## System details (run `AWS: About` and/or `Amazon Q: About`)

- OS: Windows_NT x64 10.0.19045
- Visual Studio Code extension host:  1.96.0
- Amazon Q:  1.40.0
- node: 20.18.1
- electron: 32.2.6

**Comment by jpinkney-aws** [comment]
I believe this should be fixed by https://github.com/aws/aws-toolkit-vscode/pull/6227/files which will be included in our next release!

**Comment by xander-marjoram** [comment]
Thanks @jpinkney-aws for the quick response, glad to hear you're already on it!

**Comment by tomcat323** [comment]
This request was addressed in [AWS Toolkit 3.40.0](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode) and/or [Amazon Q 1.41.0](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.amazon-q-vscode)!

AWS Toolkit changelog: https://github.com/aws/aws-toolkit-vscode/blob/master/packages/toolkit/CHANGELOG.md
Amazon Q changelog: https://github.com/aws/aws-toolkit-vscode/blob/master/packages/amazonq/CHANGELOG.md
Release artifacts: https://github.com/aws/aws-toolkit-vscode/releases
