### ISSUE TITLE
unreliable test: opentabContext should include chunks if non empty:

### ISSUE THREAD

**Issue by Hweinstock** [aws/aws-toolkit-vscode#6266]
## Test Details

-   Name of test: opentabContext should include chunks if non empty:
-   OS of failure: MacOS
-   VSCode version of failure (minimum/insider/stable): insiders
-   Link to failing run: https://github.com/aws/aws-toolkit-vscode/actions/runs/12380173347/job/34555946785
-   Link to failing test: https://github.com/aws/aws-toolkit-vscode/blob/4a0187dbfb30132d3194bc0dfe7b0c50c417f668/packages/amazonq/test/unit/codewhisperer/util/supplemetalContextUtil.test.ts#L34-L57

## Log of Test Failure
```
1) supplementalContextUtil
       fetchSupplementalContext
         openTabsContext
           opentabContext should include chunks if non empty:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(actual?.supplementalContextItems.length === 4)

      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/unit/codewhisperer/util/supplemetalContextUtil.test.ts:56:24)
```

**Comment by justinmk3** [comment]
@Will-ShaoHua

**Comment by Will-ShaoHua** [comment]
checking

**Comment by Will-ShaoHua** [comment]
I think this one is the same root cause that it's using the real system clock and it's trying to call amazonq helper then timeout
