### ISSUE TITLE
More Telemetry Normalization

### ISSUE THREAD

**Issue by bryceitoc9** [aws/aws-toolkit-vscode#632]
We're currently emitting nonstandard telemetry data from the VS Code toolkit. From 6/13-6/20, we've emitted the following telemetry events:
```
session_start
aws_credentialslogin
session_end
lambda_aws.lambda.local.invoke.javascript
Command_aws.refreshAwsExplorer
lambda_deploy
DebugAttachSuccess_attempts
DebugAttachSuccess_duration
Command_aws.showRegion
project_aws.lambda.createNewSamApp
lambda_invokeremote
lambda_aws.lambda.local.invoke.python
aws_credentialscreate
lambda_invoke
lambda_configurelocal
Command_aws.samcli.detect
Command_aws.lambda.local.invoke.csharp
DebugAttachFailure_attempts
DebugAttachFailure_duration
Command_aws.hideRegion
```

We need to normalize these in the following ways:
* Ensure that the namespace (before the `_`) is listed here: https://github.com/aws/aws-toolkit-vscode/blob/a50b83a833dacf95d29216c7e446c67556cf7925/src/shared/telemetry/telemetryTypes.ts#L25 . `Command` is not a valid namespace, although it may not necessarily fall under an explicit namespace for now.
* ~Ensure that we're only sending events. We can tie some of the listed events to datum within other events (e.g. DebugAttachSuccess/Failure, + their attempts and duration)~ Split into https://github.com/aws/aws-toolkit-vscode/issues/635
* Ensure that correctly-namespaced metrics have the correct name attached. For instance, `lambda_aws.lambda.local.invoke.python` should be `lambda_invokelocal` with a Python runtime as metadata.

**Comment by mpiroc** [comment]
All metrics in the list not covered by #635 already use standard namespaces. Closing.
