### ISSUE TITLE
Convert nonstandard debugger metrics to metadata tags for local invocations

### ISSUE THREAD

**Issue by bryceitoc9** [aws/aws-toolkit-vscode#635]
We currently receive telemetry data for the following metrics:
```
DebugAttachSuccess_attempts
DebugAttachSuccess_duration
DebugAttachFailure_attempts
DebugAttachFailure_duration
```

These should not be individual metrics. We need to add these to the `lambda_localinvoke` events as separate metadata.

Acceptance Criteria:
* These metrics are no longer emitted.
* These metrics are included in the `lambda_localinvoke` (or equivalent) calls as so:
```
{
...
    metadata.isDebug: true
    metadata.attempts: # 
    metadata.duration: #####
...
}
```

**Comment by justinmk3** [comment]
@bryceitoc9 we don't have those individual metrics now, can we close this?
