### ISSUE TITLE
Remove nodejs6.10 from list of SAM runtimes in application setup

### ISSUE THREAD

**Issue by jbesw** [aws/aws-toolkit-vscode#637]
**Describe the bug**
When creating a new SAM application, nodejs6.10 is listed as runtime option. This has been deprecated and is no longer supported.

**To Reproduce**
1. From command palette, click "Create a new SAM Application"
2. In list of runtimes, observe nodejs6.10 option.

**Expected behavior**
This option should not be available.

**Screenshots**
![image](https://user-images.githubusercontent.com/24660852/59964402-0f288b80-94ce-11e9-8723-2e7e03439aa5.png)

**Comment by awschristou** [comment]
The change has been pushed into the develop branch.
