### ISSUE TITLE
Enhance feedback for directory selection on Create New SAM Application Wizard

### ISSUE THREAD

**Issue by bryceitoc9** [aws/aws-toolkit-vscode#650]
The Create New SAM Application wizard includes a step to select a workspace folder to create the SAM app in, or to select a folder outside of the workspace. Users who select a folder outside the workspace open the OS's file explorer and select a directory, and are immediately sent to the "Enter a name for your application" dialog.

This presents a few issues:
1. Users don't have any feedback that the directory was selected. The next Command Palette step at a glance looks very similar to the previous quick pick (especially if the user doesn't have any selected workspace folders)
2. [The documentation](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/create-sam.html) suggests that the workspace folder will be created and will pass you back to the same prompt to select the folder:
> You can use an existing location or use Choose a different folder... to create a new location. For this example, create a folder named MY-SAM-APP. 
3. Pressing "Enter" on the "Enter a name for your application" wizard page with no text constitutes going back a dialog, sending the user to the "Enter a name for your application" dialog that still does not contain the folder they were looking for.

There are a few different paths we can take with this. Some include:
* Add a confirmation prompt after the user selects a non-workspace folder to confirm they want to use this directory
* Add the workspace folder to the workspace the moment the user selects it. That way, going back a menu to the directory selection will automatically show the workspace in the prompt.
  * Instantly redirect a user creating a workspace to this refreshed quick pick instead of the application name input box
* Blank submissions on input boxes do not return undefined and thus do not go back a menu. A warning message also appears to explicitly tell users they cannot submit a blank name
* Implement some sort of visual persistence to confirm past steps. Convert the wizard to a webview? Have the title bar contain the results of the last steps? Etc.

Acceptance Criteria:
* A design document to remedy this issue as well to set a consistent standard for other similar instances in the future (non-Quick Pick/Input Box step in a Quick Pick/Input Box-driven wizard)

**Comment by awschristou** [comment]
Closing this issue. It has been replaced with #671, #672, #673, #674, #675
