### ISSUE TITLE
Support Globals section in SAM Template when resolving function details

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#651]
While the extension is running, there are times when the toolkit queries information (like runtime) from the SAM Template. These queries are not accounting for fields in the Globals section of the template.

Many of the routines are in `src\shared\cloudformation\cloudformation.ts` (but there may be others)

#627 was a similar change for providing Globals details to the SAM CLI.

**Comment by cvharris** [comment]
I just ran into this, getting an error `Resource does not specify a Runtime` because I have it defined in the Globals portion of my `template.yaml`. I saw that #627 was merged, was that supposed to account for Globals when using Run/Debug Locally from CodeLens?

**Comment by awschristou** [comment]
Hi @cvharris , I don't believe that scenario (placing a runtime in the Globals section) was considered/addressed by #627.

We're working on a new debug experience, which better leverages template file as a whole (including the Globals section). If you're interested in trying out an advance build of the new experience, please have a look at #1146 . We'd be interested in hearing any feedback you have! Unfortunately, I noticed your scenario does not work in that new system, so I've created an issue #1121 specifically with your use case. If you're able to provide any additional details, or even a sample template file on that issue, it would be helpful in working toward a solution.

**Comment by justinmk3** [comment]
This issue will be tracked in https://github.com/aws/aws-toolkit-vscode/issues/1211 after debugconfig work is released.

**Comment by justinmk3** [comment]
AWS Toolkit 1.12 (released today) includes the new [SAM local Lambda debugging experience](https://github.com/aws/aws-toolkit-vscode/pull/1215) which leverages VS Code "launch configurations".
