### ISSUE TITLE
Debugging node10.x fails with aws-sdk not found

### ISSUE THREAD

**Issue by tvogel8570** [aws/aws-toolkit-vscode#657]
Unable to debug a lambda function using the AWS Toolkit with runtime set to node10.x

Steps to reproduce
1) sam init to create HelloWorld
2) setup launcher config
3) debug normally
4) change runtime in template.yaml to node10.x and save template.yaml
5) debug now fails with `{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'aws-sdk'"
}`

**Comment by awschristou** [comment]
Hey @tvogel8570 thank you for reaching out. Can you please confirm a few things?
1. In step 4, did you set the runtime to `node10.x` or `nodejs10.x`? It would need to be `nodejs10.x`
1. Are you running from the command line or using CodeLenses to trigger the debug? It sounds like you are running from the command line. If this is the case, have you re-run `sam build` prior to running `sam local invoke` ?

**Comment by tvogel8570** [comment]
Thanks for the fast response!!!

1) yes it is nodejs10.x in the template.yaml
2) I was not doing a build previously.  I get the same results after doing sam build.  Here is the terminal output
  `PS C:\Users\TVoge\Documents\projects\api\sam-app> sam build HelloWorldFunction
2019-07-02 16:26:19 Building resource 'HelloWorldFunction'
2019-07-02 16:26:19 Running NodejsNpmBuilder:NpmPack
2019-07-02 16:26:21 Running NodejsNpmBuilder:CopyNpmrc
2019-07-02 16:26:21 Running NodejsNpmBuilder:CopySource
2019-07-02 16:26:21 Running NodejsNpmBuilder:NpmInstall
2019-07-02 16:26:24 Running NodejsNpmBuilder:CleanUpNpmrc

Build Succeeded

Built Artifacts  : .aws-sam\build
Built Template   : .aws-sam\build\template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Package: sam package --s3-bucket <yourbucket>

PS C:\Users\TVoge\Documents\projects\api\sam-app> sam local invoke  -e ./event.json --debug-port 5858 "HelloWorldFunction"
2019-07-02 16:26:43 Invoking app.lambdaHandler (nodejs10.x)
2019-07-02 16:26:44 Found credentials in shared credentials file: ~/.aws/credentials

Fetching lambci/lambda:nodejs10.x Docker container image......
2019-07-02 16:26:45 Mounting C:\Users\TVoge\Documents\projects\api\sam-app\.aws-sam\build\HelloWorldFunction as /var/task:ro,delegated inside runtime container
Debugger listening on ws://0.0.0.0:5858/8dd94dd4-0b98-412b-8802-a25b76e85051
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
2019-07-02T20:26:54.678Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'aws-sdk'","stack":["Runtime.ImportModuleError: Error: Cannot find module 'aws-sdk'","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:36:30)","    at Module._compile (internal/modules/cjs/loader.js:698:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)","    at Module.load (internal/modules/cjs/loader.js:600:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)","    at Function.Module._load (internal/modules/cjs/loader.js:531:3)","    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)","    at startup (internal/bootstrap/node.js:283:19)"]}
START RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Version: $LATEST
END RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72
REPORT RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72     Init Duration: 9033.89 ms       Duration: 0.00 ms       Billed Duration: 100 ms Memory Size: 128 MB     Max Memory Used: 54 MB  
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'aws-sdk'"
}
`

**Comment by awschristou** [comment]
Did you have success running and debugging the application when the runtime is set to node 8? 
Are you using the application produced by running `sam init`, or have you made additional changes to it (aside from the runtime)? If you've made modifications to the code, it sounds like running `npm install aws-sdk --save` from within the same folder that contains `package.json` would allow the next build and run to locate the missing module.

**Comment by tvogel8570** [comment]
Chris,
Fresh start this morning ...

### Summary
With an aws-sdk call added to hello-world/app.js (see code in Detailed steps below)
-- runtime set to nodejs8.10, running and debugging just works.
-- runtime set to nodejs10.x, running works but debugging requires npm installation of aws-sdk in function directory.



### Questions
A couple of clarifying questions.
1) Why does nodejs8.10 not need a local installation of aws-sdk but nodejs10.x does need one?
2) Will this affect how my SAM app is deployed to AWS?  
    Specifically the default Lambda container on AWS already has an aws-sdk.  Will the version that I installed be part of the deployment?  What kind of issues will this cause over time as versions of the aws-sdk progress?

### Detailed steps 
Created new directory
sam init
sam local invoke -e event.json "HelloWorldFunction" - **_success_**
sam local invoke -e event.json "HelloWorldFunction" --debug-port 5858 - **_success_**
change template.yaml to runtime nodejs10.x
sam build
sam local invoke -e event.json "HelloWorldFunction" - **_success_**
sam local invoke -e event.json "HelloWorldFunction" --debug-port 5858 - **_success_**

modify hello-world\app.js added 2 lines at top of file that use aws-sdk
  `const AWS = require('aws-sdk');
AWS.config.update({ region: "us-west-2" });`
change template.yaml back to runtime nodejs8.10
sam build
sam local invoke -e event.json "HelloWorldFunction" - **_success_**
sam local invoke -e event.json "HelloWorldFunction" --debug-port 5858 - _success_
change template.yaml to runtime nodejs10.x
sam build
sam local invoke -e event.json "HelloWorldFunction" - **_success_**
sam local invoke -e event.json "HelloWorldFunction" --debug-port 5858 - **_fail as before_**

npm install aws-sdk --save
sam local invoke -e event.json "HelloWorldFunction" --debug-port 5858 - **_success_**

**Comment by awschristou** [comment]
Thank you for the repro steps. This issue over on the SAM CLI repo sounds like a similar situation - https://github.com/awslabs/aws-sam-cli/issues/1246

These are great questions, I'd recommend asking over on the SAM CLI repo (https://github.com/awslabs/aws-sam-cli)

**Comment by justinmk3** [comment]
Should be fixed in sam 0.38+ https://github.com/awslabs/aws-sam-cli/issues/1246#issuecomment-563364505
