### ISSUE TITLE
Create SAM App wizard better describes the "Name your Application" step

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#671]
In the "new SAM Application" workflow, there is some confusion on the step where users are asked to give their application a name. User studies revealed that this step and the previous step (application location) are visually similar.

Acceptance Criteria:
* the prompt to enter an application name has a description (`InputBox.prompt` field) that says "Your application will be created in a subfolder with this name"

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/978 helps somewhat (by pre-filling a value), and also fixes a bug.
