### ISSUE TITLE
Prevent blank app name in Create SAM App wizard

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#672]
In the "new SAM Application" workflow, User Studies showed there is some confusion on the step where users are asked to give their application a name. 

If a user leaves the prompt blank and presses Enter (this happened a lot in studies), the workflow treats this like a Cancel gesture, returning the user to the previous step.

Acceptance Criteria:
* prevent application name prompt from allowing a blank string to be submitted
  * Suggestions:
    * When the prompt is closed and an empty string is returned, immediately re-open it. In this case, provide additional text in the description to indicate that empty text is not allowed
    * (preferable) open the prompt with `InputBox.validationMessage` set to the same validation text used when the text is validated as an empty string ("Application name cannot be empty"). This prevents the prompt from being submitted with a blank string.

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/978 helps somewhat (by pre-filling a value), and also fixes a bug.

**Comment by justinmk3** [comment]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/55561878/196818589-5144368a-6a6f-49f5-ad14-aadf00e00714.png">
