### ISSUE TITLE
Account for case when all regions are hidden in the Hide Region command

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#677]
If you run the "Hide Region" command when all of the regions are already hidden, you're shown an empty picker list. Not useful.

Acceptance Criteria:
* The hide region command shows an information message stating that none of the regions are visible in the explorer, if all regions are already hidden. The picker is not shown.

**Comment by justinmk3** [comment]
fixed by [2569](https://github.com/aws/aws-toolkit-vscode/pull/2569)
