### ISSUE TITLE
If a function is declared multiple times in a file, only show CodeLenses on the last one (JS/PY)

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#680]
If a Javascript or Python file has a function declared more than once in a file, all instances currently get CodeLenses. Only the last one in the file is actually run. Do not show CodeLenses on the other duplicates.

**Comment by justinmk3** [comment]
Do we care about this, now that the codelens is `Add Debug Configuration` ?

**Comment by awschristou** [comment]
I think this is reasonable to close out. The CodeLenses have a different context as of v1.12.0.
