### ISSUE TITLE
Can't find aws and sam in path despite being usable in the terminal inside vscode

### ISSUE THREAD

**Issue by danielloader** [aws/aws-toolkit-vscode#693]
**Describe the bug**
Extension can't find binaries in path that are in $HOME/.local/bin.

**To Reproduce**

**Expected behavior**
Find both in the path and work as documented.

**Screenshots**

![image](https://user-images.githubusercontent.com/55561878/215927911-f2db073b-f932-4334-94ab-02f1779bad16.png)

**Desktop (please complete the following information):**
 - OS: Manjaro KDE 18.0.4
 - Visual Studio Code Version: 1.35.1
 - AWS Toolkit for Visual Studio Code Version: 1.0.0

**Additional context**
Both are accessible from the terminal inside the app in the default environment.
Was able to manually set the aws-sam-cli path using the detect task but there's no apparent way to set the aws path seemingly.

**Comment by awschristou** [comment]
Thank you for reaching out @danielloader , it looks like the Toolkit is properly finding the SAM CLI, as your screen shot indicates the Build step worked and proceeded to the Package step. It seems like the SAM CLI is unable to locate the AWS CLI, which it uses during the packaging step.

Do you remember how you installed both the SAM CLI and the AWS CLI, and have you got more than one Python version installed on your system? I seem to recall that there are situations where the AWS CLI may get stored in a specific Python version depending on how it is installed, leaving the SAM CLI unable to find it. If possible (and if you didn't install it this way), try installing it with the [bundled installer](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html#install-tool-bundled) steps.

**Comment by danielloader** [comment]
Thanks for the response. 
As to how, it's just been installed with "pip install --user PACKAGE", though to rule out interpreter issues I've run that both on the system python (which installs my packages to $HOME/.local/bin) and inside the .venv virtualenv of the SAM root folder. 

```
loaderd@magnesium aws-lambda • $ which aws
/home/loaderd/.local/bin/aws
loaderd@magnesium aws-lambda • $ source .venv/bin/activate 
(.venv) loaderd@magnesium aws-lambda • $ which aws
/home/loaderd/Source/python/aws-lambda/.venv/bin/aws
```
The reason SAM is working is because the extension allows you to pick a path to it in the extension configuration.

Guess an alternative solution is to provide the ability to provide a path to both prerequisitie libraries?

**Comment by awschristou** [comment]
I'm wondering if the Toolkit is unable to find the AWS CLI on the path.
If you're willing to help try and narrow this down, I'd like you to try running the sam package ([reference](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-package.html) | [details](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-deploying.html)) step manually from a terminal. If this is successful, try to launch VS Code from the same terminal, and see if your deploy is successful. Please report on your outcome.

* If the manual package does not work, the AWS CLI cannot be found from the path, and a fresh install may help, preferably using the bundled installer
* If the manual package does work and the explicitly launched VS Code instance does work, somehow the way VS Code is normally launched on your system does not have the same $PATH environment value
* If the manual package does work and the explicitly launched VS Code instance does not work, I will need to investigate further

**Comment by danielloader** [comment]
Sorry about the delay, I can confirm your suspicion that if you check AWS CLI works in a terminal then open a directory in vscode via `code .` that AWS operates correctly. 
Additionally opening code from any path in the terminal works correctly. However opening it from the plasma application launcher seems to not work. 

The shortcut is aimed at `code-oss --unity-launch %F` with the `/usr/bin/code` executable just being a symlink to code-oss for ease. The integrated terminal sees it but I'm not surprised as it's spawning an interactive bash session.

In a slightly related case, did some digging on stackoverflow and this looks related: https://stackoverflow.com/questions/43983718/set-global-path-environment-variable-in-vs-code

So I went and entered a sudo session (`sudo -H bash`) and did `pip install awscli` and lo and behold vscode now picks it up. 

I guess this is strictly a vscode problem as one would expect it's not going to pick up local binary paths set explicitly in bash_profile or bashrc, that being said with that being an issue I can see a rationale for being able to set the AWS CLI path like you can set the SAM path - you may be wanting to install the tools in a virtualenv or you plain don't have access to installing binaries to `/usr/bin/`.

Thoughts?

**Comment by justinmk3** [comment]
> I guess this is strictly a vscode problem as one would expect it's not going to pick up local binary paths set explicitly in bash_profile or bashrc, that being said with that being an issue I can see a rationale for being able to set the AWS CLI path like you can set the SAM path

Yes. More flexibility there is tracked in https://github.com/aws/aws-toolkit-vscode/issues/1351

AWS CLI is not used by AWS Toolkit currently, but if that changes in the future, we will make its location configurable similar to SAM CLI.
