### ISSUE TITLE
Assume remote EC2 role

### ISSUE THREAD

**Issue by TryTryAgain** [aws/aws-toolkit-vscode#695]
It would be helpful to be able to assume roles using a remote EC2 instance/EC2-Role. 

I don't want to have to create/use API keys as described in https://github.com/aws/aws-toolkit-vscode/issues/620

Is this something that could be considered?

**Comment by awschristou** [comment]
Hey @TryTryAgain thank you for reaching out. To make sure I understand correctly, are you running VS Code within an EC2 instance, and you'd like it to be able to use the credentials available to the EC2 instance?

**Comment by TryTryAgain** [comment]
Thanks for the response @awschristou ... Not exactly what I'm hoping for. I'm hoping I can connect to a remote EC2 instance through SSH and then use its credentials and role switch from my local machine.

**Comment by bryceitoc9** [comment]
If I'm understanding this correctly, you're looking to:
* SSH into your EC2 instance
* Using the EC2 instance's credentials, run an `aws sts assume-role` call
* Pull the value returned by `assume-role` and add these credentials to your local machine?

If so, I'm thinking what you'll want to do in the future is to set all of this up as a [credential process](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html), which can handle the SSH and the credential injection.

HOWEVER, this toolkit does not currently support credential process. This is currently in our backlog: https://github.com/aws/aws-toolkit-vscode/issues/317 . If this is what you're looking to do, I would recommend setting the credentials by hand for now until we're able to get this done.

**Comment by justinmk3** [comment]
Is this different than https://github.com/aws/aws-toolkit-vscode/issues/918 ?

**Comment by justinmk3** [comment]
We merged https://github.com/aws/aws-toolkit-vscode/pull/1833 which adds support for [credential_source](https://docs.aws.amazon.com/sdkref/latest/guide/setting-global-credential_source.html). If you want to try the prerelease we'd love your feedback: 

1. Download and extract [awstoolkit-0ea03d.zip](https://github.com/aws/aws-toolkit-vscode/files/6737111/awstoolkit-0ea03d.zip)
2. From the VSCode command list (`ctrl-shift-p` or `cmd-shift-p`) run `Extensions: Install from VSIX...` to install the `*.vsix` file.
3. Reload VSCode and verify that the Toolkit has the new version (not the older version).

**Comment by TryTryAgain** [comment]
Unfortunately, that solution wouldn't help me and  is not what I'm looking for. My ec2 role creates custom sts creds for hundreds of accounts without any profiles configured... luckily I'm pretty sure credential source will likely be what I'm looking for. Thanks, either way.

**Comment by justinmk3** [comment]
> My ec2 role creates custom sts creds for hundreds of accounts without any profiles configured... luckily I'm pretty sure credential source will likely be what I'm looking for.

Note that Toolkit 1.26 https://github.com/aws/aws-toolkit-vscode/pull/1833 will also automatically try the EC2 metadata service ("instance credentials") if `~/.aws/` is missing.
