### ISSUE TITLE
CodeLenses only look two levels deep for tempalate.yaml files

### ISSUE THREAD

**Issue by hunterwerlla** [aws/aws-toolkit-vscode#704]
**Describe the bug**

The Codelens only looks two levels deep for template files. It is very reasonable to have this deeper, which prevents run and debug codelens's from showing up.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: all
 - Visual Studio Code Version: all
 - AWS Toolkit for Visual Studio Code Version: all

**Additional context**

**Comment by awschristou** [comment]
I suggest the following:
* change the default from 2 to 4
* make this a user-configurable setting

**Comment by charmingnyc** [comment]
Chris,

How/where does one change the default from 2 to 4?

I've discovered, that if I don't open VS Code from the top directory of the SAM App, I get various AWS Toolkit Log ERRORs, but mostly "2019-09-06 09:25:41 [ERROR]: Could not generate 'configure' code lens for handler 'app.lambdaHandler' Error: Unable to find a sam template associated with handler 'app.lambdaHandler' in "

**Comment by awschristou** [comment]
Hi @charmingnyc , thank you for reaching out. My note is a suggestion for changing the implementation (I've updated the comment to indicate this now).

**Comment by elmpp** [comment]
As I have a monorepo setup, my template.yaml files will be as such:

`/packages/infra/aws/hello-world/template.yaml`

The user-configuration option here would be welcome indeed 👍

**Comment by awschristou** [comment]
@charmingnyc @elmpp  a change (#857) has now made its way to the `master` branch. If you're interested in trying it out before it is released, you can build the toolkit from source.

**Comment by awschristou** [comment]
This was released in Toolkit v1.5.0

The toolkit will now show CodeLenses when the folders are deeper under workspace. The maximum depth is also configurable with `aws.sam.template.depth`
