### ISSUE TITLE
Intellisense for ECS Task Definition

### ISSUE THREAD

**Issue by seongmDevX** [aws/aws-toolkit-vscode#707]
**Is your feature request related to a problem? Please describe.**

When users write ECS task definition inside their IDE, IntelliSense is not provided.

See:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-task-definition.html

https://docs.microsoft.com/en-us/visualstudio/ide/using-intellisense?view=vs-2019

**Describe the solution you'd like**

The Amazon ECS DevX team has generated a JSON schema file that will provide such IntelliSense. We propose inside your extension we include a file matching system that will activate the ECS task definition IntelliSense based on the file name. 

**Describe alternatives you've considered**

A separate plugin or having a README file giving out instructions on how to modify their settings to have ECS IntelliSense

**Additional context**

**Comment by rli** [comment]
Thanks for the feature request.

For later reference, the extension point is [contributes.jsonValidation](https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation) and manual steps are available in the VS Code [documentation](https://code.visualstudio.com/Docs/languages/json#_json-schemas-and-settings)

**Comment by seongmDevX** [comment]
Hey Richard! So the DevX team was thinking about making our own separate extension but we thought about possibly combining it with yours. What are your thoughts on it? And if you think it is a good idea, what are the steps to merge my extension with yours?

**Comment by rli** [comment]
Summary of our discussion internally:

We think it's a good idea. We prefer that internal teams build into our toolkit, as customers in general would prefer to not have to install a new plugin for each AWS service.

For the actual contribution, simply submit a PR and someone from the team will work with you to get it merged.

**Comment by awschristou** [comment]
PR #722 has been merged into the master branch. Closing.
