### ISSUE TITLE
Add tests to default AWS client handlers

### ISSUE THREAD

**Issue by bryceitoc9** [aws/aws-toolkit-vscode#718]
The new ECS client (https://github.com/aws/aws-toolkit-vscode/pull/716) includes tests. We need to include similar tests for the other default clients in order to ensure our AWS client wrapping is functional.

Acceptance criteria:
* Unit tests for the other existing default AWS clients: CloudFormation, Lambda, and STS

**Comment by justinmk3** [comment]
Increasing test coverage is an ongoing goal so we can close this particular issue.
