### ISSUE TITLE
Functional Tests involving local lambda configurations

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#726]
Building off #689 and #690 , add some tests that verify different configuration parameters are used in local run and local debug features of SAM Applications.

Task can be split into smaller tasks as needed.
Will probably want a set of sample projects in the repo to load from that contain these scenarios.

Unknowns:
* we'll need a way to verify that the lambda function is operating with the expected parameters. One possible way is to steal the output and scan it, but I don't know if that is ideal.

Acceptance Criteria:
* applies to local run and local debug
* Validate that each runtime (node8/10, py2.7/3.6/3.7, dotnetcore2.1) loads a sample project and has codelenses available for the function handler
* Configuration scenarios to test
  * sam template contains two resources, the code file contains two functions
    * two sets of code lenses appear (one set for each function)
    * each function successfully runs/debugs
  * sam template contains environment variables, local run of function uses these values
  * function is configured to override a sam template environment variable, local run of function uses overridden value
  * sam template uses the Globals section, local run honors this

**Comment by justinmk3** [comment]
> Validate that each runtime (node8/10, py2.7/3.6/3.7, dotnetcore2.1) loads a sample project and has codelenses available for the function handler

covered by `integrationTest/sam.test.ts` and `integrationTest/codelens.js.test.ts`

The other variants are covered by https://github.com/aws/aws-toolkit-vscode/blob/2f6aa2b93d17e9bc3de5a3ab7536922a2d962e51/src/test/shared/sam/debugger/samDebugConfigProvider.test.ts
