### ISSUE TITLE
Functional Tests involving CodeLens availability

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#727]
Building off #691 , add some tests that verify codelens behavior for projects with different configurations.

Will probably want a set of sample projects in the repo to load from that contain these scenarios.

Acceptance Criteria:
* Validate that the scenarios work for each runtime (node8/10, py2.7/3.6/3.7, dotnetcore2.1) 
* Configuration scenarios to test
  * code files with more than one lambda handler only show code lenses for the function(s) that are referenced by a sam template

**Comment by justinmk3** [comment]
functional tests were added in https://github.com/aws/aws-toolkit-vscode/tree/8b12d6b783376f49c68e1ead17fc51da0b626945/src/test/shared/codelens
