### ISSUE TITLE
Support upper case keys in the shared credentials file

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#732]
Users have reported situations where their shared credentials file contains keys in upper case (#720). 

The current workaround is to make the keys lowercase in the shared credentials file.

This is supported in other tooling like the AWS CLI, we should try to support it in the Toolkit as well.

**Comment by bryceitoc9** [comment]
Confirmed that this case is currently unsupported by the JS SDK.

**Comment by awschristou** [comment]
Keys should be lowercase in the shared credentials file.
Uppercase keys will not be supported.

Closing issue.
