### ISSUE TITLE
Remove 'retry' from SAM integration tests when symbol retrieval has improved

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#737]
In #736 a retry attempt was added to integration tests where retrieving Symbols for Python code has not been reliable. This issue is a placeholder to follow up and remove the retry at a time when the symbols system reliability has improved.

**Comment by justinmk3** [comment]
integ tests were improved in https://github.com/aws/aws-toolkit-vscode/pull/1653 , https://github.com/aws/aws-toolkit-vscode/pull/1659 , https://github.com/aws/aws-toolkit-vscode/pull/1637 and others.
