### ISSUE TITLE
Can not access Amazon Web Services with the AWS Toolkit for Visual Studio Code in China region

### ISSUE THREAD

**Issue by Mason117** [aws/aws-toolkit-vscode#744]
AWS Toolkit for Visual Studio Code now can not be used for China region Customers, to be specific, cn-north-1 and cn-northwest-1. 

After create a Credentials Profile with secret access key and access key, and point out the region code such cn-north-1, user still can not access to AWS with the error : **Credentials profile default is invalid**

Please help.

**Comment by awschristou** [comment]
Thank you for reaching out @Mason117 - the AWS Toolkit for VS Code currently only supports the standard partition, meaning that the China Partition regions cannot be connected to.

This is being tracked in #188, so I will close this issue as a duplicate.
