### ISSUE TITLE
Add support for Ruby runtimes

### ISSUE THREAD

**Issue by nirvdrum** [aws/aws-toolkit-vscode#747]
**Describe the solution you'd like**

Currently, the set of supported SAM runtimes is limited to .NET Core, NodeJS, and Python. Since ruby2.5 is a valid SAM runtime, it would be great if that option were available from the AWS Toolkit VS Code Extension.

**Describe alternatives you've considered**

For the time being, I've managed to do what I need to by way of the `sam` CLI application.

**Comment by awschristou** [comment]
Hi @nirvdrum thank you for reaching out. I've labelled this as a feature request for future consideration.

Out of curiosity, were you able to manually set up debugging within VS Code? If so, I'd be interested in seeing what your Debug Configuration entry looks like in launch.json

**Comment by nirvdrum** [comment]
This was actually my first foray into serverless applications with Amazon. I was excited to see a plugin that I thought would aide with my development effort. But, I was going to write in Ruby. I ended up using the SAM CLI instead.

**Comment by wilkosz** [comment]
It would be great to get ruby2.7 runtime into this toolset!

**Comment by justinmk3** [comment]
@wilkosz  consider adding your upvote 👍  to the main description so it will be counted when we are deciding priorities.

**Comment by justinmk3** [comment]
This was addressed in [AWS Toolkit 3.31.0](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode) !

AWS Toolkit changelog: https://github.com/aws/aws-toolkit-vscode/blob/master/packages/toolkit/CHANGELOG.md
Amazon Q changelog: https://github.com/aws/aws-toolkit-vscode/blob/master/packages/amazonq/CHANGELOG.md
Release artifacts: https://github.com/aws/aws-toolkit-vscode/releases
