### ISSUE TITLE
Investigate whether CodeUri can be considered optional in SAM Templates

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#754]
The VS Code Toolkit validates that Resources in SAM Template files contain a `CodeUri` field. We should find out if this is required in the toolkit or not. The SAM CLI should be dealing with validation concerns if possible. Maybe we can interpret a missing field as "." instead.

**Comment by justinmk3** [comment]
Toolkit doesn't require CodeUri. Initiating a run/debug on a template.yaml that lacks a CodeUri, correctly invokes `sam` and attaches debugger. Though it fails (of course) because sam doesn't know where the application lives:

```
Debugger attached.
2022-03-21T21:00:45.757Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'
```
