### ISSUE TITLE
SAM Template Validations are swallowed without logs

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#755]
**Describe the bug**

In some cases, SAM Template validations are swallowed without logging them. Users are unable to determine if there is a problem that can be remedied.

There may be other locations, but `getAssociatedSamTemplate` is eating this error in the try/catch block.

**To Reproduce**
1. Make a NodeJS SAM App 
1. Open the SAM Template file
1. Remove the CodeUri fields from the resource entries and save the file
1. Open the sam app file
1. Note there are no SAM CodeLenses, and there are no helpful logs mentioning that the CodeUri field is missing

**Expected behavior**

1. SAM related CodeLenses will not appear. A log entry should indicate why they did not appear.

**Desktop (please complete the following information):**
 - OS:
 - Visual Studio Code Version:
 - AWS Toolkit for Visual Studio Code Version: 1.0.0

**Comment by justinmk3** [comment]
Logging and messaging were improved in 1.12
