### ISSUE TITLE
Issues handling Local Lambda invokes in SAM Applications

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#758]
We've discovered some deficiencies in the 1.0.0 version of the toolkit.
This issue is a placeholder to note some of the issues found for consideration in a new design of the Local Debugging experience. (It will be updated with more items prior to producing a new design)

---

CodeLenses do not appear in various circumstances:
* when a sam template does not reference the function (it should be possible to run a handler without a sam template -- see JetBrains toolkit for comparable functionality)
* #661 - when code is in a second subfolder (whether the second folder is in the handler or the codeuri, the toolkit fails to properly figure out how to handle this)
* #704 - CodeLenses do not appear for code whose sam template is more than two levels deep from the workspace folder
* (JS/PY) when package.json is in the same folder as the template.yaml file (toolkit planned for it to be in a subfolder)

Issues with CodeLens operation:
* the toolkit does not match handlers to templates consistently between the codelens provider logic and the codelens execution logic (this causes mismatches that result in a local run not getting set up with the proper environment)
* sam template validation is too strict, sometimes preventing local debugging functionality from working
* a lean sam template is produced during local invokes instead of reusing the existing sam template 
  * Lambda Layers don't work #746
  * References to other template entities don't work
* When there is more than one sam template resource with the same handler signature, a CodeLens only associates with one of these #912

**Comment by bryceitoc9** [comment]
Lambda Layers don't work (due to our template handling): https://github.com/aws/aws-toolkit-vscode/issues/746

**Comment by justinmk3** [comment]
AWS Toolkit 1.12 (released today) includes a new [SAM local Lambda debugging experience](https://github.com/aws/aws-toolkit-vscode/pull/1215) which leverages VS Code _launch configurations_. 

Need to review the items here to see if they were all addressed.

**Comment by justinmk3** [comment]
> a lean sam template is produced during local invokes instead of reusing the existing sam template
> ...
> References to other template entities don't work

Since https://github.com/aws/aws-toolkit-vscode/pull/1159 Toolkit now produces a "full" temporary template.

> Lambda Layers don't work #746

Tracked in #746 (might be fixed by #1159, needs confirmation).

All of the other referenced issues here were closed. 

Anything else should be tracked in new issues.
