### ISSUE TITLE
Allow to sync with S3 Bucket

### ISSUE THREAD

**Issue by Shababsoft** [aws/aws-toolkit-vscode#759]
**Is your feature request related to a problem? Please describe.**
As I have hosted the static site on the S3 Bucket and I am having trouble with sync changes between my local folder and S3 Bucket. 

**Describe the solution you'd like**
Can you provide a feature in the plugin that supports upload/download files from the S3 bucket? This will help me to sync changes between the local folder and the remote bucket. 

**Describe alternatives you've considered**
I have tried to use other plugin but they are working as expected and I guess this is official plugin from Amazon AWS.

**Additional context**

**Comment by awschristou** [comment]
Thank you for the request @Shababsoft - are you interested in plain upload to and download from an S3 bucket, or something more along the lines of comparing a local folder and an S3 location, and resolving differences between the two?

**Comment by dcat52** [comment]
@awschristou - I am also interested in this feature. The lines I am thinking of is like the Eclipse S3 feature. Except with the ability to select what folder it goes into!

Thanks,
Davis

**Comment by awschristou** [comment]
Thanks for the feedback @dcat52 ! 

In case you didn't know, the [aws cli](https://aws.amazon.com/cli/) has a [sync](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html) command that can synchronize between an S3 Bucket and a local folder.

**Comment by awschristou** [comment]
Hi @Shababsoft and @dcat52 , at this time we are starting to propose some S3 related functionality for the toolkit. If you're interested in joining that conversation, please take a look at the proposal in PR #942.

**Comment by justinmk3** [comment]
> Can you provide a feature in the plugin that supports upload/download files from the S3 bucket

Implemented in AWS Toolkit 1.12, released today.
