### ISSUE TITLE
Getting an invalid security token error when connecting to AWS

### ISSUE THREAD

**Issue by ceelya** [aws/aws-toolkit-vscode#761]
Using Visual Code and the AWS toolkit extension; when I attempt to use a named profile with valid access key and secret I get an error from the extension.

The error reads Credentials profile <profilename> is invalid.

The error in the AWS toolkit log is:

InvalidClientTokenId: The security token included in the request is invalid.

I have verified that I can use the named profile without issue from the AWS CLI and within Visual Studio 2019 without issue with the same credential values.

VS Code version is 1.38.1 and AWS Toolkit version is 1.0.0

Please note I have read the guidance about lower case key name values in the .aws\credentials file and about uninstalling the extension, restarting VS code and re-installing the extension, but that does not resolve the issue for me.

Repro:

Open VScode
Select AWS extension from menu nav
Click on Connect to AWS
Select named profile

I would expect to be able to connect without issue; perhaps this is a PubCloud vs GovCloud issue as named profiles for PubCloud work as expected.

**Screenshots**

![image](https://user-images.githubusercontent.com/8901010/64806498-4785b600-d561-11e9-95ad-681ce79e82a3.png)

**Comment by rugglcon** [comment]
I can verify with the repro steps that this is still an issue, here is my output from running the command you posted:

```
{
    "UserId": "<useridstring>:<email>",
    "Account": "<accountnumber>",
    "Arn": "arn:aws:sts::<accountnumber>:assumed-role/<role>/<email>"
}
```

I omitted details about the user account, but I did not get an error or some weird response.

**Comment by rugglcon** [comment]
I'm sorry, I did not restart VSCode and retry before I posted that comment. It works for me, go ahead and ignore my comment.

**Comment by ceelya** [comment]
I ran the command noted in the comment above in September and I get a valid response for a valid profile and US GovCloud West region.  However, when I attempt to set the same profile in VS Code I get an error Credential profile is invalid.  The toolkit works as expected for PubCloud but I consistently get an error when attempting to connect using a profile associated with GovCloud.  I will assume this does not support GovCloud connectivity at the current time.

**Comment by awschristou** [comment]
Thank you for the update @ceelya , the toolkit does not support GovCloud at this time. #810 is tracking support for regions outside the aws partition (such as GovCloud), so I will close this issue. Please take a moment to add a reaction (or comment) registering interest on that issue.
