### ISSUE TITLE
Add Support for Java8 Runtimes

### ISSUE THREAD

**Issue by mesa123123** [aws/aws-toolkit-vscode#763]
**Is your feature request related to a problem? Please describe.**

Currently the 'aws create sam application' feature does not have runtime support for java8 
**Describe the solution you'd like**

I'd like the java8 to become a feature for the create sam application option
**Describe alternatives you've considered**

I can create what I want from the cli tools at present, but its just annoying considering that this is perfectly valid and there is currently no way to simply do it through the ui

**Additional context**

![image](https://user-images.githubusercontent.com/22901019/65032813-fb3ed980-d997-11e9-8c95-138ac08f6a99.png)

Simply adding a java8 option to this menu would be great :)

**Comment by bryceitoc9** [comment]
We've intentionally [removed the option to create Java apps through the toolkit](https://github.com/aws/aws-toolkit-vscode/issues/322) as we currently don't have local run/debug support for Java; we felt that this would be the best way to represent the toolkit's current functionality.

If you would like to develop Java apps with a full-fledged local run/debug experience, we recommend using the [AWS Toolkit for Jetbrains](https://github.com/aws/aws-toolkit-jetbrains).

**Comment by mesa123123** [comment]
Hey Bryce

Thats a fair idea, is there a timeline on when this functionality will be
implemented again?

Peter

**Comment by dcat52** [comment]
Hello Bryce,

I am also interested in this functionality, is there an expected time-frame or way to help get it back in?

Thanks,
Davis

**Comment by bryceitoc9** [comment]
Unsure if anyone is still here, but I've got a PR up for Java support: https://github.com/aws/aws-toolkit-vscode/pull/1594/

You should be able to download a test copy of the extension by scrolling to the tests at the bottom and clicking "Details" next to one of the VS Code Package Tests in the build report.

Let me know if there are any issues!

**Comment by bryceitoc9** [comment]
Final merge PR for Java here: https://github.com/aws/aws-toolkit-vscode/pull/1654 ; you should be able to download a sample VSIX from the packaging tests in the checks.

**Comment by justinmk3** [comment]
Available in Toolkit 1.24
