### ISSUE TITLE
Won't work with SAM CLI

### ISSUE THREAD

**Issue by kennyk65** [aws/aws-toolkit-vscode#772]
I have a completely up-to-date (as of today) copy of VS Code on my Windows computer:  

    Version: 1.38.1 (system setup)
    Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
    Date: 2019-09-11T13:35:15.005Z
    Electron: 4.2.10
    Chrome: 69.0.3497.128
    Node.js: 10.11.0
    V8: 6.9.427.31-electron.0
    OS: Windows_NT x64 10.0.17134

I have just installed the AWS Toolkit.  Looks like 1.1.0.

I've just attempted to create a new SAM application.  The response: "Your SAM CLI version 0.7.0 does not meet requirements (0.16.0 ≤ version < 0.30.0). Please update your SAM CLI."

Fair enough, so I've just updated my SAM CLI.  Running "sam --version" returns:

    SAM CLI, version 0.22.0

Great, this falls within the specified range.  However, VS Code / AWS Toolkit still reports the same message, even after restarting.  I've uninstalled and reinstalled the extension, same result.  Anyone know how to get SAM capability working?

**Desktop (please complete the following information):**
 - OS: Windows 10, v 1803
 - Visual Studio Code Version:  see above
 - AWS Toolkit for Visual Studio Code Version:  see above

**Comment by awschristou** [comment]
Hi @kennyk65 thank you for reaching out. Can you please try closing and re-opening VS Code and seeing if you get the same message? There is a chance that the Toolkit was unable to find your new installation because it still thought the old version was around.
