### ISSUE TITLE
Add support for Go

### ISSUE THREAD

**Issue by inliquid** [aws/aws-toolkit-vscode#773]
Please add support of Go.

![изображение](https://user-images.githubusercontent.com/6797881/65691752-14234b00-e07a-11e9-890f-995cc4676d9d.png)

**Comment by bryceitoc9** [comment]
The SAM CLI currently doesn't have support for debug builds: https://github.com/awslabs/aws-sam-cli/issues/888 .

A few months ago, we consciously removed the ability to create new SAM applications for unsupported runtimes in order to best represent functionality: https://github.com/aws/aws-toolkit-vscode/issues/322 . We do not intend to add Go app creation at this time due to these limitations.

**Comment by inliquid** [comment]
> The SAM CLI currently doesn't have support for debug builds: awslabs/aws-sam-cli#888 .

I'm sorry? 
https://docs.aws.amazon.com/en_us/serverless-application-model/latest/developerguide/serverless-sam-cli-using-debugging-golang.html

And not really sure why you reference `dep` issue. Nowadays almost nobody want to use this tool in favor of `go modules`. `sam` itself does support Go projects. Not supporting it in VS Code extension because of that issue is insane.

**Comment by jfuss** [comment]
FYI: SAM CLI supports Go building (v0.41.0) so this issue should be unblocked for the toolkit.

Caveats:
* Modules is supported (not dep).
* We will produce a debug binary when `SAM_BUILD_MODE=debug` is set (this is the current pattern .Net builder follows).
* We do not allow building within the container.

**Comment by neoramos** [comment]
Would love to see support for GO!!! Please reconsider.  Thank you.

**Comment by justinmk3** [comment]
@neoramos  👍 reactions on feature requests help use decide priorities. Consider adding one to the top comment here.

**Comment by inigosola** [comment]
Golang support, please

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/1683 adds support for run/debug of Go SAM Lambda projects. We appreciate your feedback, if you want to try it:

1. Download and extract [Uploading toolkit.zip…]()
2. From the VSCode command list (`ctrl-shift-p` or `cmd-shift-p`) run `Extensions: Install from VSIX...` to install the `*.vsix` file.
3. Reload VSCode and verify the Toolkit version is `1.25.0-fff08e0ce806` (not 1.24 or older).
4. Note the **caveats**:
    - For Go1.15+, the latest VSCode Go extension must be used (because of a bug in older versions of the extension)
    - Go1.14 is the minimum supported version
    - CodeLenses require `gopls`
    - Debugging requires `dlv`

**Comment by JadenSimon** [comment]
Until the Go extension releases 0.24.3 (or 0.25.0), I recommend using Go1.14. Debugging won't work as expected otherwise.
