### ISSUE TITLE
Ability to Copy resource ARN from AWS Explorer

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#783]
The context menu on resource nodes in the AWS Explorer is sparse. It would be convenient if users had a way of copying a resource ARN to the clipboard.

Acceptance Criteria:
* AWS Explorer Nodes that represent resources (eg: Lambda Functions and CloudFormation Stacks) have a context menu entry `Copy ARN` that copies the resource ARN to the clipboard
* Menu item is not in context menu for non-resource nodes
* Menu item is in an appropriate location in the context menu, with separators where appropriate (where other menu items offer unsimilar functionality)

**Comment by kedar9444** [comment]
I would like to work on this, can you assign it to me?

**Comment by awschristou** [comment]
Thank you @kedar9444 , looking forward to your contribution!

**Comment by moneerrifai** [comment]
@awschristou Am I missed something but the Lambda (and CloudFormation) do not have the option to copy ARN in their context menus. See screenshot below.


<img width="358" alt="LambdaContextMenu" src="https://user-images.githubusercontent.com/5445607/78372482-f685ef80-758e-11ea-9320-dcc95c4650d8.png">

**Comment by awschristou** [comment]
@moneerrifai this issue represents the work required to add a "copy arn" entry to the context menu.

**Comment by awschristou** [comment]
This functionality has been released with v1.9.0 of the toolkit, which is now available.
