### ISSUE TITLE
Invalid Credentials Profile when profile name contains @ character

### ISSUE THREAD

**Issue by mikelax** [aws/aws-toolkit-vscode#787]
**Describe the bug**
If the profile name contains an `@` character, then the aws toolkit (within vs code) is not able to establish a connection and produces an error:  

>Credentials profile `profilenamewith@char` is invalid

**To Reproduce**
Create a profile name entry within the credentials file with an `@` character. 
Try to connect to AWS using this new profile. 
Create a second profile with the same values but no `@` in the name, observe this connection works. 

```
[profilen@medoesntwork]
aws_access_key_id = keyidvalue
aws_secret_access_key = secretkeyvalue
aws_session_token = footkenvalue==

[profilenameworks]
aws_access_key_id = keyidvalue
aws_secret_access_key = secretkeyvalue
aws_session_token = footkenvalue==
```

**Expected behavior**
I should be able to connect to aws using a profile that contains an `@` character. The same profile name works when using any `aws cli` commands with the `--profile` attribute.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Visual Studio Code Version: 1.39.2
 - AWS Toolkit for Visual Studio Code Version: 1.1.0 2019-09-20

**Additional context**

**Comment by bryceitoc9** [comment]
Hi @mikelax 

I can't replicate this on my side. Could you try restarting VS Code and the plugin? Our toolkit currently [overaggressively caches credentials](https://github.com/aws/aws-toolkit-vscode/issues/705) (including invalid ones), which means that if the credentials were selected while invalid during the extension's current activation, it will remain invalid throughout the rest of the session.

For reference, I was successful with a profile named `def@ult-old@`.

**Comment by mikelax** [comment]
@bryceitoc9 thanks for checking in. I did some further tests and now it does appear that profiles with an `@` are working. I could swear I tested several combinations yesterday, but maybe the caching was messing with me.
