### ISSUE TITLE
VsCode Lens Fails to Build

### ISSUE THREAD

**Issue by AndyHollings** [aws/aws-toolkit-vscode#793]
**Describe the bug**
After following the guide https://github.com/aws/aws-toolkit-vscode/blob/master/docs/debugging-python-lambda-functions.md

I can debug code manually as per the document when I debug using code lens it fails.

Build fails with error.

Preparing to run lambda_function.lambda_handler locally...
Building SAM Application...
An error occurred trying to run SAM Application locally: Error with child process: Building resource 'awsToolkitSamLocalResource'
,Running PythonPipBuilder:ResolveDependencies
,Error: PythonPipBuilder:ResolveDependencies - Traceback (most recent call last):

  File "<string>", line 1, in <module>

TypeError: 'module' object is not callable

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
**From VSCODE:-**
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

**AWS Toolkit 1.1.0**

**Comment by AndyHollings** [comment]
Linked Issue https://github.com/awslabs/aws-sam-cli/issues/1461

**Comment by LazerFX** [comment]
I've been working with @AndyHollings on this — the issue does appear to be easily reproducible if you have `pip 19.3.0` installed rather than `pip 19.2.3`.  I would recommend keeping this issue here for visibility so that anyone who does run into this issue can see there is a simple resolution.

**Comment by bryceitoc9** [comment]
Thanks for the research, @AndyHollings and @LazerFX ! 

Looks like https://github.com/awslabs/aws-sam-cli/issues/1461 just wrapped. Can you verify that the new SAM CLI version fixed this?

**Comment by LazerFX** [comment]
I haven't been able to reproduce the error recently, so I believe this is closed.  Apologies about the slow response - I've been working on other areas of the environment recently!
