### ISSUE TITLE
Code lens not working if lambda folder is not right under VS code workspace folder

### ISSUE THREAD

**Issue by XiamiYoung** [aws/aws-toolkit-vscode#796]
**Describe the bug**

Code lens not working if lambda folder is not right under VS code workspace folder

**To Reproduce**

Create a folder named A, cd to folder A then init a new lambda function with below command:
sam init --runtime nodejs -n helloworld -d npm -o .
A helloworld function will be generated, add folder A to VS code workspace, open app.js, code lens is there.

Delete helloworld folder and create a folder B under folder A,  cd to folder B then init a new lambda function with below command:
sam init --runtime nodejs -n helloworld -d npm -o .
A helloworld function will be generated under folder B, now go to VS code and check, code lens failed to work with below message(note that "root" folder in VS code is A now):

ERROR]: Could not generate 'configure' code lens for handler 'app.lambdaHandler' Error: Unable to find a sam template associated with handler 'app.lambdaHandler' in /Users/xxx/Documents/Code_Repo/A/B/helloworld/hello-world/app.js.

ok, now same code, same structure, if I add folder B to VS code workspace, code lens starts to work.

**Expected behavior**

No matter what folder level the lambda resides, code lens should be working always.

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Both Mac OS and Windows7
-   Visual Studio Code Version: 1.39.2
-   AWS Toolkit for Visual Studio Code Version: 
        aws-cli/1.16.264 Python/3.7.4 Darwin/18.7.0 botocore/1.13.0
        SAM CLI, version 0.22.0

**Additional context**

**Comment by bryceitoc9** [comment]
Hi @XiamiYoung,

Correct me if I'm wrong, but your directory structure now looks like this:
```
A
| event.json (from first init)
| README.md (from first init)
| template.yaml (from first init)
- B
  - hello-world
    | (generated SAM app)
  | event.json
  | README.md
  | template.yaml
```
The issue here is that the codelenses are picking up the top level `template.yaml` file. We don't interpret other nested templates while drawing codelenses; the specific issue here would be with the CodeUri field, which would be looking for handlers in `./A/hello-world`.

Is there a reason why you want to have nested SAM files like this?

**Comment by XiamiYoung** [comment]
Hi @bryceitoc9 , 

It looks like this

A
- B
  - helloworld
	  - hello-world
	    | (generated SAM app)
	  | event.json
	  | README.md
	  | template.yaml

It's not working if I add A to VS code, however if I remove A and add B to VS code, it's working. As you can see there's only one template.yaml.

the reason I do it like this is my project has multiple lambdas(eg. lambdaB and lambdaC), so I added project folder(A) into VS code workspace instead of each of them seperately, I would keep some scripts for each of lambda in their folder, take above for example, it looks like this:

A
- B
  - lambdaB
	  - hello-world
	    | (generated SAM app)
	  | event.json
	  | README.md
	  | template.yaml
  - scripts
- C
  - lambdaC
	  - hello-world
	    | (generated SAM app)
	  | event.json
	  | README.md
	  | template.yaml
  - scripts

As you suggested, I moved scripts into each of lambda folder and removed folder in the middle, now I can see the code lens however this behaviour looks weired.

A
  - lambdaB
	  - hello-world
	    | (generated SAM app)
	  | event.json
	  | README.md
	  | template.yaml
  	  | scripts
  - lambdaC
	  - hello-world
	    | (generated SAM app)
	  | event.json
	  | README.md
	  | template.yaml
	  | scripts

Thank you

**Comment by awschristou** [comment]
Thank you for clarifying @XiamiYoung -- This issue is captured in #704. I will close this issue as a duplicate.
