### ISSUE TITLE
Design how we will package and deploy functions in different languages to Lambda

### ISSUE THREAD

**Issue by steveataws** [aws/aws-toolkit-vscode#8]
From an extension point of view we want to hand off packaging and deployment to underlying language specific 'engines' (similar to how we handle web site vs web app projects in the Visual Studio toolkit). The user will invoke a single command (eg aws.packageLambda and aws.deployLambda), they will query the workspace to determine the language in use and hand off to the correct engine as appropriate.

For example, when packaging (and deploying) C# functions we'll want to delegate to our .NET CLI extension tooling. For functions in Node.js we'll want to do something else (for both packaging and deployment). And so on. At time of raising this issue we envisage the languages we need to support as being Node.js, Python and C#.

This issue is to design and document (in the repo) the interfaces to these engines so that they can be implemented.

**Comment by awschristou** [comment]
We will defer to the `sam build` portion of SAM CLI
