### ISSUE TITLE
aws-vault support

### ISSUE THREAD

**Issue by mthsmb** [aws/aws-toolkit-vscode#803]
I want to request [aws-vault](https://github.com/99designs/aws-vault) support.

**Comment by awschristou** [comment]
Hi @mthsmb , aws-vault is a third party tool that primarily makes use of short term credentials, and environment variables. Please see https://github.com/aws/aws-toolkit-vscode/issues/164#issuecomment-549940246 for reasons why this is not supported, and a workaround.
