### ISSUE TITLE
Support for Isolated Regions (China, GovCloud)

### ISSUE THREAD

**Issue by humzinator** [aws/aws-toolkit-vscode#810]
needs support for using vscode with govcloud keys

**Comment by awschristou** [comment]
Thanks for the request @humzinator , I have added this to our grouping of Credentials related requests (#733). Before adding govcloud support, the toolkit also requires some changes in order to support partitions other than the standard partition. This is represented by #188

**Comment by gholt-aws** [comment]
Tweaking the wording a bit to cover all isolated regions



Add support for isolated regions like https://aws.amazon.com/govcloud-us/, and https://www.amazonaws.cn/about-aws/china/.

**Describe the solution you'd like**
* Customers can see and select isolated regions in the region selector
* Customers can deploy to isolated regions
* Customers can execute lambdas in isolated regions
* Customers can retrieve lambdas from isolated regions
* Customers can debug lambdas from isolated regions locally
* Customers can use cloud debug in isolated regions

**Comment by awschristou** [comment]
v1.7.0 of the toolkit is now available. This version includes support for China and GovCloud based regions.

You'll need to a `region` field to your shared credentials profile, and set it to one of the regions that you are working in (for example `cn-northwest-1` for a China partition region).

We don't have the user docs updated yet, some information can be found at https://github.com/aws/aws-toolkit-vscode/blob/master/docs/connecting-to-aws.md#working-with-regions-in-other-partitions
