### ISSUE TITLE
Credentials invalid when adding AWS Toolkit if you already configure the CLI (credentials and config files)

### ISSUE THREAD

**Issue by xmoulin** [aws/aws-toolkit-vscode#811]
**Describe the bug**

I have 

> "credentials profile default is invalid"

 when I use "AWS : Connect to AWS". Even if I try AWS: Create Credentials Profile.

**To Reproduce**
1. Go to your home  directory: HOME/.aws
2. Create valid file credentials and config
3.  Try the CLI to ensure it's work fine : 'aws iam get-user' for exemple
4. Go to visualCode and install the AWS plugin
5. Try "AWS: Connect to AWS"
6. the error message "credentials profile default is invalid" appear.

Config file:
```
[default]
region=eu-west-1
output=json
```
credentials file:
```
[default]
AWS_ACCESS_KEY_ID = xxxxxxxxxxxxxxxxxxxxxxxxx
AWS_SECRET_ACCESS_KEY = yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
```
Important, if I drop my file and use Visual Studio to recreate those file (using AWS: Create Credentials Profile), using the same ACCESS_KEY and SECRET_KEY, It work fine.

**Expected behavior**
No bug during the step 6.

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Visual Studio Code Version: 1.40.1
-   AWS Toolkit for Visual Studio Code Version: 1.2.0

**Comment by bryceitoc9** [comment]
Looks like https://github.com/aws/aws-toolkit-vscode/issues/732 ; could you try changing `AWS_ACCESS_KEY_ID` and `AWS_SECRED_ACCESS_KEY` to lowercase? Make sure to restart VS Code after you've saved the credentials file; we currently have an overactive cache that we're looking into as well.

**Comment by xmoulin** [comment]
Ok, you're right!
That's it! Well done.
