### ISSUE TITLE
The SAM process did not make the debugger available within the time limit

### ISSUE THREAD

**Issue by felixgogo** [aws/aws-toolkit-vscode#822]
**Describe the bug**

An error occurred trying to run SAM Application locally: The SAM process did not make the debugger available within the timelimit.  Local invoke of SAM Application has ended.

**To Reproduce**

1. Generate a sample SAM application with AWS Toolkit for Visual Studio Code.
2. Setup a simple event data in templates.json after clicking "Configue".
3. Click "Debug Locally".

**Expected behavior**

Taking long time to fetch lambci/lambda:nodejs10.x Docker container.
Time limit error occurs.

**Desktop (please complete the following information):**

-   OS: MacOS 10.14.6
-   Visual Studio Code Version: 1.40.1
-   AWS Toolkit for Visual Studio Code Version: 1.2.0
-   Docker Desktop Version: 2.1.0.4 (39773)

**Comment by awschristou** [comment]
Thank you for reporting this @felixgogo - here are two workarounds you can try:
* you can configure the toolkit to wait longer before timing out by updating the setting `aws.samcli.debug.attach.timeout.millis` (this has a default value of 30 seconds). This would give your system more time to download the docker image. Information about adjusting VS Code configurations can be found [here](https://code.visualstudio.com/docs/getstarted/settings)
* you can pull down the docker image from a command line by running `docker pull lambci/lambda:nodejs10.x` . After this has completed, you should be able to debug locally without a timeout.

**Comment by felixgogo** [comment]
@awschristou 
It works again after restarting mac.  Thanks for the quick reply!
