### ISSUE TITLE
Make git credentials available to integrated git extension

### ISSUE THREAD

**Issue by drAlberT** [aws/aws-toolkit-vscode#828]
When using CodeCommit with IAM roles and MFA I couldn't find a way to use the git extension in Visual Studio Code as it always asks for username and password.

The auth with the Toolkit is perfectly working and I can see my lambdas and CFN stacks.

It would be perfect to have the AWS git credentials helper usable by codecommit repositories too. Ie the toolkit "exports" the credentials to git someway.

**Comment by awschristou** [comment]
Thanks for the suggestion @drAlberT 

To clarify, are you referring to the Source Control panel that is a part of VS Code, or a specific extension that you've installed into VS Code?

I'd like to better understand your scenario. Do you already have a CodeCommit repo cloned locally and would like the toolkit to make it easier to operate on (push/pull/etc)? Or are you looking for broader assistance in locating and cloning a CodeCommit repo?

**Comment by drAlberT** [comment]
Hi @awschristou 
  I already have the codecommit repo locally cloned and I can correctly use it in the integrated terminal, as I have configured the proper env variables and git credential helper for my linux user.

I was expecting to have "some" git feature (integrated, external, whatever ... the wider choice we have the better it is of course) in the IDE to work on the repo too ... but it cseems to completely ignore the credential helper in the account *and* the fact AWS toolkit is connected is not helping at all.

I think the ToolKit could someway "export" the credentials, inject them or whatever in order to have "vscode git gui(s)" to correctly work with CodeCommit.

AFAICS every extension about git I can try have the exact same behavior:
```
[2019-11-27 09:20:04:911] ChildProcess.exithandler
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch

'NoneType' object has no attribute 'secret_key'
fatal: could not read Username for 'https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/infrastructure': No such device or address
```
Hope this will clarify, feel free to ask me every for other info you need.

**Comment by kyllagdrgn** [comment]
@drAlberT have you found a solution since opening this issue. I see that there has been no movement in 2 years. I'm currently trying to solve the same problem. At this time I use the VS Code controls to manage the local git repository and go to the command line to run all remote repository commands. Thanks

**Comment by justinmk3** [comment]
Requires some setup, but I would expect the [CodeCommit git credentials helper](https://github.com/aws/git-remote-codecommit) to work transparently with VSCode's git support.

Long-term, we are thinking about how AWS Toolkit could help with this.

**Comment by drAlberT** [comment]
@kyllagdrgn no, didn't tried to go deeper anymore ... living with this limitation for now

@justinmk3 what kind of setup? any hint?

**Comment by justinmk3** [comment]
> @justinmk3 what kind of setup? any hint?

The setup steps are here: https://github.com/aws/git-remote-codecommit#set-up

**Comment by kyllagdrgn** [comment]
@justinmk3  Thank you, I will need to give this a try

**Comment by drAlberT** [comment]
Yep, using the credential helper with the profile as shown in the linked doc makes the job.

Closing, thanks.
