### ISSUE TITLE
Add support for nodejs12.x

### ISSUE THREAD

**Issue by krsnaa** [aws/aws-toolkit-vscode#831]
**Is your feature request related to a problem? Please describe.**

When I use `Runtime: nodejs12.x` in the template.yaml file , I get the following error:
Unsupported javascript runtime: nodejs12.x

Given that the SAM CLI already supports nodejs12.x, the AWS toolkit must as well.

**Comment by awschristou** [comment]
Thanks for reaching out @krsnaa , I'm looking into this.

**Comment by bryceitoc9** [comment]
FYI @krsnaa: https://github.com/aws/aws-toolkit-vscode/pull/835

**Comment by awschristou** [comment]
This was released in Toolkit v1.5.0
