### ISSUE TITLE
Error loading Schemas resources

### ISSUE THREAD

**Issue by sagar-rout** [aws/aws-toolkit-vscode#850]
Error loading schemas resources

**To Reproduce**

**Expected behavior**

Frankly, I am not sure. What should be the expected behavior because first time I clicked and I saw the error. Definitely, it is not a feature :crying_cat_face:  

**Screenshots**

![AWS_toolkit_schemas](https://user-images.githubusercontent.com/10592462/70398265-d055a600-1a19-11ea-8330-910e28677fee.png)
![vscode_version](https://user-images.githubusercontent.com/10592462/70398266-d055a600-1a19-11ea-89f5-2bada348257a.png)

-   OS: Ubuntu 18.04
-   Visual Studio Code Version: 1.40.2
-   AWS Toolkit for Visual Studio Code Version: 1.4.0

**Comment by kiiadi** [comment]
@sagar-rout the Event Bridge schema registry preview is currently only available in the following regions : 
* US East (Ohio)
* US West (Oregon)
* US East (Northern Virginia)
* Asia Pacific (Tokyo)
* Europe (Ireland)

We should really hide the Schema's node for regions where it is not supported.

**Comment by sagar-rout** [comment]
I think that would be better

**Comment by awschristou** [comment]
v1.6.0 of the toolkit is now released. Regions that do not support Schemas will no longer show the Schemas node.
