### ISSUE TITLE
Could not generate 'configure' code lens for handler

### ISSUE THREAD

**Issue by Hasan-git** [aws/aws-toolkit-vscode#877]
**Describe the bug**

**To Reproduce**
[ERROR]: Could not generate 'configure' code lens for handler 'med/hello-world/app.lambdaHandler' Error: Unable to find a sam template associated with handler 'med/hello-world/app.lambdaHandler' in c:\Users\Hasan\Desktop\AWS\sam\app\med\hello-world\app.js.
    at c:\Users\Hasan\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.4.0\out\src\shared\codelens\codeLensUtils.js:126:15

1. Go to 'app.js handler'
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8820596/71478932-d1991800-27fa-11ea-8d4c-71e38aa4a4d2.png)

**Desktop (please complete the following information):**

Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Additional context**

**Comment by awschristou** [comment]
Thank you for reporting this @Hasan-git . I believe this has been addressed in #857 , which will make its way to an upcoming release. In the meantime, could you please try opening the "sam\app" folder as your workspace folder in VS Code, and checking if the CodeLenses appear in your app.js file?

**Comment by awschristou** [comment]
Hi @Hasan-git , please try this with version 1.5.0 of the toolkit, which was just released.
