### ISSUE TITLE
Release readiness

### ISSUE THREAD

**Issue by steveataws** [aws/aws-toolkit-vscode#9]
automated release pipelines
    operational readiness review
    marketplace account -- use same as VS/VSTS extensions

**Comment by gliptak** [comment]
Consider enabling releases from Travis,. An example section is found at:

https://github.com/Microsoft/vscode-arduino/blob/master/.travis.yml#L62

Require adding an encypted API key to Travis.

**Comment by mpiroc** [comment]
This task is superceded by #166 and #283
