### ISSUE TITLE
Debug Locally, throws spawn sam ENOENT

### ISSUE THREAD

**Issue by apoorvHearth** [aws/aws-toolkit-vscode#902]
**Describe the bug**

AWS toolkit throws ENOENT when spawning the sam local invoke process

**To Reproduce**

1. Click Debug Locally for any lambda function

**Expected behavior**
To start the debugging process

**Screenshots**
![aws-toolkit-error](https://user-images.githubusercontent.com/59563600/72796905-31ea7080-3c66-11ea-814c-11d626a020f3.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 18.04LTS
-   Visual Studio Code Version: 1.41.1
-   AWS Toolkit for Visual Studio Code Version:1.5.0

**Comment by apoorvHearth** [comment]
Also, to clear the doubt of sam command not available in the PATH. I am able to locally invoke the lambda function from the terminal successfully.

**Comment by justinmk3** [comment]
> I am able to locally invoke the lambda function from the terminal successfully.

what command exactly? If you try the exact command given in the screenshot, does it work?

**Comment by apoorvHearth** [comment]
yep it does work

**Comment by apoorvHearth** [comment]
Closing the issue, I think I just needed to restart vscode now everything works well, for some reason, `sam local invoke` was not working before while `sam build` was working fine.
