### ISSUE TITLE
NetworkingError "unable to get local issuer certificate"

### ISSUE THREAD

**Issue by Bryan-Meier** [aws/aws-toolkit-vscode#917]
**Describe the bug**

After connecting to AWS, I try to expand Cloudformation, Lambda, or Schemas and get an error. It will not display anything accept error loading XXX resources.

**To Reproduce**

Open VS Code
Hit Ctrl + Shift + P
Type AWS: Connect to AWS
Select default credentials
In Sidebar of AWS toolkit extension
    Expand region
    Expand CloudFormation or any other node

**Expected behavior**

Show the appropriate resources based on the node being expanded and give no errors

**Screenshots**

![image](https://user-images.githubusercontent.com/58827791/73580960-76cb8f80-443c-11ea-902e-dd988edf85c3.png)

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Visual Studio Code Version: 1.41.1
-   AWS Toolkit for Visual Studio Code Version: 1.5.0

**Additional context**

I have rebooted, uninstalled and reinstalled the extension. The normal AWS CLI works fine from the command and powershell.

**Comment by bryceitoc9** [comment]
Hi @Bryan-Meier ,

Out of curiosity, are you behind a proxy? The toolkit doesn't currently support proxies, but we do have an issue open to track it: https://github.com/aws/aws-toolkit-vscode/issues/185

**Comment by lmayorga1980** [comment]
I have the same error.

**Comment by justinmk3** [comment]
@Bryan-Meier @lmayorga1980 Are you setting `HTTP_PROXY` or `HTTPS_PROXY` environment variables?

> The normal AWS CLI works fine from the command and powershell.

AWS CLI uses python. Node.js (Vscode) [has its own knobs and defaults](https://github.com/nodejs/node/issues/3742#issuecomment-155546646) related to  certificates.

> but I have to set a custom internal CA cert.

VScode exposes some [related settings](https://github.com/microsoft/vscode-remote-release/issues/587#issuecomment-501970569):

- `http.proxy`
- `http.proxyAuthorization`
- `http.proxyStrictSSL`: you can set this to false (security risk), and see if that fixes the issue. But a better solution is to fix your certificate chain.
- `http.proxySupport`
- `http.systemCertificates`

What are the values of those settings in your vscode?

**Comment by Bryan-Meier** [comment]
Thanks for the reply. I believe I figure out the issue and it pertains to my company's network and what they are allowing for traffic. Thanks again.

**Comment by justinmk3** [comment]
@Bryan-Meier thanks for the followup!

> but I have to set a custom internal CA cert

@lmayorga1980 see https://github.com/aws/aws-toolkit-vscode/issues/899
