### ISSUE TITLE
Error while compiling lambda function using npm and gulp commands

### ISSUE THREAD

**Issue by 1ds14te050manoj** [aws/aws-toolkit-vscode#919]
**Describe the bug**

Multiple error's while tying to build and compile lambda function using npm and gulp commands 

**Expected behavior**

 The Lambda function should be compiled and a folder should be created with compiled which when zipped can be uploaded to AWS lambda console

**Screenshots**
![image](https://user-images.githubusercontent.com/27077036/73644937-526dee00-469c-11ea-95dc-de1dcaab7deb.png)

**Desktop (please complete the following information):**

-   OS: windows 10
-   Visual Studio Code Version:
-   AWS Toolkit for Visual Studio Code Version: 1.5.0

**Additional context**
 I am trying to call batch file using command .\batch.bat which has the following commands to run:
echo off
cls

echo "build started"

call npm install

echo "started compiling"

call gulp deploy

echo "started packaging"

SET mypath=%~dp0

mkdir %mypath%\dist\zip

wzzip -p -r dist\zip\1033_STG_RMSG_MRDR.zip %mypath%\dist\*.*

echo "all done"

**Comment by awschristou** [comment]
This looks like you are trying to use the command line and not the Toolkit. Can you please confirm this?

The functionality provided by the toolkit operates directly on the SAM Template files, and does not call custom scripts.

**Comment by 1ds14te050manoj** [comment]
Yes, I have been running this in powershell command explorer. As i am new to VS code can you please guide me how to run this command's in toolkit? 
Thank you.

**Comment by awschristou** [comment]
The Toolkit has a [User Guide](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/welcome.html) which you may find useful. The Toolkit works with, and can deploy SAM Applications, which is covered in the [Serverless](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/serverless-apps.html) section.
