### ISSUE TITLE
VSCode Remote to EC2 instance (via SSH over SSM)

### ISSUE THREAD

**Issue by jovanshernandez** [aws/aws-toolkit-vscode#941]
**Desktop (please complete the following information):**

-   OS: Ubuntu18 and/or Amazon Linux2
-   VS Code version: 1.41.0
-   AWS Toolkit extension version: 1.70

**Anyway to connect to EC2 through VSCode without SSH Key?**

Trying to connect to EC2 through VSCode without SSH Keys. I'm able to connect to EC2s using AWS Credentials, AWS Profiles, and AWS SSM, but is there a way to pass that connection through VSCode/?

**Comment by awschristou** [comment]
Hi @jovanshernandez , when you mention "Connect to EC2", are you trying to use VS Code's [Remote Development](https://code.visualstudio.com/docs/remote/ssh) feature, that allows users to open a remote folder in the VS Code file explorer? Or did you have something else in mind?

**Comment by jovanshernandez** [comment]
@awschristou Correct, I am trying to open say the `/home/ubuntu/` folder on an EC2 in my VSCode desktop file explorer.

**Comment by justinmk3** [comment]
Duplicte of https://github.com/aws/aws-toolkit-vscode/issues/918 ? If not, please explain

**Comment by dmattia** [comment]
I do not believe this to be a duplicate issue.

This issue is talking about a connection like `aws ssm start-session --target "i-0012341ef010ffc4f"`, which uses the AWS CLI to open an SSH-like connection to a remote EC2. This is an AWS specific form of authentication, and is felt to be more secure by many because:

1. You can use SSM to access instances in private subnets, whereas SSHing requires some instance in a public subnet
2. SSM uses AWS creds, which has strong MFA support, whereas SSH is just SSH
3. SSM access control is controlled by AWS IAM Policies, whereas SSH requires maintaining public keys
4. All SSM access has built in monitoring and auditing by AWS Cloudtrail and the SSM service itself

So this issue is really just asking for almost a direct integration, or otherwise mirroring of functionality, of Microsoft's Remote Dev tooling but for SSM instead of SSH.

This is not related to ECS or EC2 metadata endpoints that issue #918 talks about

**Comment by ragebiswas** [comment]
+1 for this, I see this could be useful for many.

**Comment by asherawelan** [comment]
This would be the last piece in the puzzle for us...

**Comment by twitu** [comment]
This is a powerful feature and an important component in making AWS development experience secure but also seamless. + 💯 from my side.

**Comment by thomas-anderson-bsl** [comment]
As a workaround, you could update the ssh configuration file to run a proxy command, which routes ssh traffic via SSM. See https://pub.towardsai.net/how-to-do-remote-development-with-vs-code-using-aws-ssm-415881d249f3

**Comment by justinmk3** [comment]
Related: https://aws.amazon.com/blogs/architecture/field-notes-use-aws-cloud9-to-power-your-visual-studio-code-ide/ shows how to configure remote SSH over SSM so that VS Code can connect to an EC2 instance. Furthermore shows how to use Cloud9 as the remote instance from a local VS Code instance.

**Comment by szukalski** [comment]
This will work but you have to manually specify the AWS profile and region.

Outside of VS Code, your ssh config for SSM integration would look something like this:
```
host i-* mi-*
  User ec2-user
  ProxyCommand sh -c "aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
```
Then you would ssh to your instance directly. Ie. `ssh i-xzyyxzzxyyxzzxy`. Things work because you have an AWS profile and region loaded.

To get things working with VS Code, your ssh config would look like this:
```
host i-*.*.*
  User ec2-user
  ProxyCommand bash -c "aws ssm start-session --target $(echo %h|cut -d'.' -f1) --profile $(echo %h|/usr/bin/cut -d'.' -f2) --region $(echo %h|/usr/bin/cut -d'.' -f3) --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
```
You then connect to your instance with `i-xzyyxzzxyyxzzxy.profile_name.region`.

**Comment by jtele2** [comment]
@chm123 Can you elaborate? I cannot get this to work like so.

**Comment by chm123** [comment]
> @chm123 Can you elaborate? I cannot get this to work like so.

Basically you can follow
https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html

And try SSH from terminal (not from VS Code). If this works for you, you should be able to connect via VS Code.

**Comment by jtele2** [comment]
@chm123 Thank you for your response. I can get in via Windows Subsystem for Linux (WSL) but not from PowerShell with the proxy command. I have to use WSL because I cannot install SessionManagerPlugin (non-Admin rights). 

Is there a way to make ProxyCommand use WSL.exe to setup the Remote-SSH session?

**Comment by chm123** [comment]
@jtele2 

I'm using MacBook, so I'm not familiar with WSL. You can try this 
https://stackoverflow.com/questions/60150466/can-i-ssh-from-wsl-in-visual-studio-code

**Comment by jtele2** [comment]
Anyone else have ideas on how to get this to work with Windows (AWS CLI on PowerShell)?

**Comment by PeterBaker0** [comment]
+1 for this feature - would be very useful - going to try and setup workaround as above for now.

**Comment by mrgum** [comment]
one thing to note, vscode needs your credentials, so if you use temporary credentials, say via SSO to an IdP you need to close vscode and open it again from a terminal that has your session token, a PITA

if anyone knows a work-around, that doesn't involve session up a credentials file or iam user, that would be great

**Comment by szukalski** [comment]
@mrgum Source your credentials from an external process:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html

**Comment by sholtomaud** [comment]
Is there any update on the requirement to connect to EC2 through VSCode without SSH Key/.pem file?

**Comment by mrgum** [comment]
I managed to do this following https://aws.amazon.com/blogs/developer/introducing-aws-sso-support-in-the-aws-toolkit-for-vs-code/  I had to remove the other entries I had in credentials file as they were confusing it

in vscode aws: choose profile that opens up sso in browser and once you accept you can connect to host using its i-1234 id (you need the .ssh/config as above)

**Comment by sholtomaud** [comment]
What if we go the other way around and ask, why is it that an AWS Systems Manager session doesn't need the .pem file?

**Comment by mrgum** [comment]
I think we need a key because we are using Remote-SSH to connect, and and alternative Remote-SSM extension would need to be created?

**Comment by sholtomaud** [comment]
What if we go the other way around and ask, why is it that an AWS Systems Manager session doesn't need the .pem file?

**Comment by mrgum** [comment]
systems manager does not need the keys.  the remote-ssh (which is tunnelled over ssm as a transport) does.

**Comment by sholtomaud** [comment]
My point is that I can get a ssm "terminal" session into an EC2 file system from a browser, right?  

So why can't we implement the same feature set of the ssm "terminal" in VSCode? Maybe we don't in fact need to use the remote-ssh?

**Comment by sholtomaud** [comment]
For example what is this <awsui-app-layout>? Why can't that be implemented as a part of a VSCode extension?

![image](https://user-images.githubusercontent.com/398402/181128649-2860c9d1-5cf2-4f29-b607-a3f594cb1b11.png)

**Comment by thomas-anderson-bsl** [comment]
> For example what is this awsui-app-layout? Why can't that be implemented as a part of a VSCode extension?
> 
> ![image](https://user-images.githubusercontent.com/398402/181128649-2860c9d1-5cf2-4f29-b607-a3f594cb1b11.png)

As mentioned above, this particular issue is asking about [Remote Development using SSH](https://code.visualstudio.com/docs/remote/ssh), but using SSH over SSM.

What you're describing isn't resolving the issue, you're talking about embedding an SSM terminal into VSCode.

**Comment by antunesdq** [comment]
> > For example what is this awsui-app-layout? Why can't that be implemented as a part of a VSCode extension?
> > ![image](https://user-images.githubusercontent.com/398402/181128649-2860c9d1-5cf2-4f29-b607-a3f594cb1b11.png)
> 
> As mentioned above, this particular issue is asking about [Remote Development using SSH](https://code.visualstudio.com/docs/remote/ssh), but using SSH over SSM.
> 
> What you're describing isn't resolving the issue, you're talking about embedding an SSM terminal into VSCode.

"via SSM, without SSH"

![image](https://user-images.githubusercontent.com/29799062/181131182-60ae1c58-0940-426a-949c-5755094dc49c.png)

**Comment by justinmk3** [comment]
I've renamed the issue title to avoid confusion.

**Comment by sholtomaud** [comment]
It's unclear to me how my previous comment was off topic. Note that the first comment by @jovanshernandez  describes, **"Anyway to connect to EC2 through VSCode without SSH Key?"**

The initial title was "without SSH" and the topic change totally reverses the meaning of this issue and I think misses the point. 

"without SSH Key" is what I understood this issue to be about. 

"Embedding an SSM terminal into VSCode" (as my comment was described) would meet the requirement of connecting to EC2 through VSCode without SSH Key as described by @jovanshernandez

**Comment by justinmk3** [comment]
The thread is getting long so I minimized comments that are outdated.

**Comment by sholtomaud** [comment]
How do you connect via SSM-over-SSH (without local SSH keys)?

**Comment by mrgum** [comment]
@justinmk3 I think the title should be say SSH over SSM rather than the other way about

**Comment by mrgum** [comment]
Should we open a separate issue asking for remote-SSM, a different implementation based on remote-SSH but solely using SSM with no SSH or public keys involved?

**Comment by sholtomaud** [comment]
> Should we open a separate issue asking for remote-SSM, a different implementation based on remote-SSH but solely using SSM with no SSH or public keys involved?

why not work on this issue which started with the Q. 

`Anyway to connect to EC2 through VSCode without SSH Key?`

**Comment by justinmk3** [comment]
> Should we open a separate issue asking for remote-SSM, a different implementation based on remote-SSH but solely using SSM with no SSH or public keys involved?

vscode-remote [doesn't allow extensions](https://code.visualstudio.com/docs/remote/faq#_license-and-privacy) or forks, AFAIK. I would guess the most feasible approach is to use SSH over SSM via https://github.com/aws/session-manager-plugin, which is how I would propose to address this feature request.

**Comment by sholtomaud** [comment]
Thanks for the response @justinmk3  - you mentioned previously that "we can connect via SSM-over-SSH (without local SSH keys)" do you have an example of how I can do that? Or is this actually not the case?

**Comment by justinmk3** [comment]
see https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-873096740

**Comment by sholtomaud** [comment]
I'll give it a go

**Comment by sholtomaud** [comment]
you could get a list of all ec2's and then for each ec2 append something like the following for any given aws profile to .ssh/config, and then implement ssh key rotation for ec2-user on a schedule from VSCode extension:

```sh
Host LinuxHost
   ProxyCommand sh -c "aws ec2-instance-connect send-ssh-public-key \
      --instance-id  $(aws ec2 describe-instances --filter "Name=tag:Name,Values= HOSTNAME"  \
      --query "Reservations[].Instances[?State.Name =='running'].InstanceId[]"  \
      --output text --profile profilename) \
      --availability-zone ap-southeast-2a \
      --instance-os-user ec2-user \
      --ssh-public-key file:///Users/someuser/.ssh/somekey.pub --profile profilename > /dev/null; \
      aws ssm start-session --profile profilename \ 
      --target $(aws ec2 describe-instances --filter "Name=tag:Name,Values= HOSTNAME" \
      --query "Reservations[].Instances[?State.Name =='running'].InstanceId[]" 
      --output text --profile profilename) --profile profilename  \
      --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
   User ec2-user
   ForwardAgent yes
   UserKnownHostsFile /dev/null
   StrictHostKeyChecking no
```

**Comment by sawaca96** [comment]
### WSL 
`ssm-ec2-proxy-command.ps1`
```ps
$AWS_PROFILE="default"
$AWS_REGION=""
$PUBLIC_KEY_PATH="file://C:\Users\<username>\.ssh\<public key>"

$ssh_user = $args[0]
$ssh_port = $args[1]
$ec2_instance_id = $args[2]


aws ec2-instance-connect send-ssh-public-key `
    --instance-id "$ec2_instance_id" `
    --availability-zone "$AWS_REGION" `
    --instance-os-user "$ssh_user" `
    --ssh-public-key "$PUBLIC_KEY_PATH" `
    --profile "$AWS_PROFILE"

aws ssm start-session `
  --target "$ec2_instance_id" `
  --document-name 'AWS-StartSSHSession' `
  --parameters "portNumber=$ssh_port"
```
`vscode remote config`
```
Host ec2
  ProxyCommand C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File C:\Users\<username>\.ssh\ssm-ec2-proxy-command.ps1 %r %p <instance_id>
  User ec2-user
  ForwardAgent yes
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
```
### Mac
`ssm-ec2-proxy-command.sh`
```sh
#!/bin/bash

AWS_PROFILE=alphasquare
AWS_REGION=ap-northeast-2a
PUBLIC_KEY_PATH=file:///Users/<username>/.ssh/<public key>

# Arguments passed from SSH client
USER=$1
PORT=$2
INSTANCE_ID=$3

aws ec2-instance-connect send-ssh-public-key \
    --instance-id ${INSTANCE_ID} \
    --availability-zone ${AWS_REGION} \
    --instance-os-user ${USER} \
    --ssh-public-key ${PUBLIC_KEY_PATH} --profile ${AWS_PROFILE} > /dev/null; 

aws ssm start-session --profile ${AWS_PROFILE} \
    --target ${INSTANCE_ID} --profile ${AWS_PROFILE}  \
    --document-name AWS-StartSSHSession --parameters portNumber=${PORT}
```
`vsocde remote config`
```
Host ec2
    ProxyCommand sh -c "~/.ssh/ssm-ec2-proxy-command.sh %r %p <instance id>"
    User <user-name>
    ForwardAgent yes
    UserKnownHostsFile /dev/null
    StrictHostKeyChecking no
```

**Comment by jraj002** [comment]
@sawaca96 Followed your instructions for mac. However, get this error: Resolver error: Error: Permission denied (publickey,gssapi-keyex,gssapi-with-mic)

**Comment by sawaca96** [comment]
> @sawaca96 Followed your instructions for mac. However, get this error: Resolver error: Error: Permission denied (publickey,gssapi-keyex,gssapi-with-mic)

@jraj002 check your id_rsa.pub permission.  execute `chmod 400 id_rsa.pub`

**Comment by Roseidon** [comment]
> This will work but you have to manually specify the AWS profile and region.
> 
> Outside of VS Code, your ssh config for SSM integration would look something like this:
> 
> ```
> host i-* mi-*
>   User ec2-user
>   ProxyCommand sh -c "aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
> ```
> 
> Then you would ssh to your instance directly. Ie. `ssh i-xzyyxzzxyyxzzxy`. Things work because you have an AWS profile and region loaded.
> 
> To get things working with VS Code, your ssh config would look like this:
> 
> ```
> host i-*.*.*
>   User ec2-user
>   ProxyCommand bash -c "aws ssm start-session --target $(echo %h|cut -d'.' -f1) --profile $(echo %h|/usr/bin/cut -d'.' -f2) --region $(echo %h|/usr/bin/cut -d'.' -f3) --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
> ```
> 
> You then connect to your instance with `i-xzyyxzzxyyxzzxy.profile_name.region`.

This helped me a lot. With this we were finally able to configure this for us!
However we had some troubles with also enabling usages of MFA.
1. configure your vs-code
    - `"remote.SSH.showLoginTerminal": true,` (to enable the prompt to enter the MFA on log in at the remote)
    - `"remote.SSH.useLocalServer": false,` (to disable sharing the connection)
2. configure your profiles
    - the profile needs to have the word profile as prefix (some just used `[required-role]` which worked for `awsume` but not here)
    - the profile-name needs to be lower-case (somehow the proxy-command makes everything lower-case in the execution)
    - the `mfa_serial` needs o be defined on the profile (it does not work when it is defined in the default profile, that seems to be a known issue)
    ```
    [profile required-role]
    role_arn = arn:aws:iam::012301230123:role/Role_Name
    mfa_serial = arn:aws:iam::012301230123:mfa/your.identity@company.com
    source_profile = default
    ```
3. Then you can add configs to your `ssh-config`, e.g.
    ```
    Host ssm-*
      ProxyCommand bash -c "…" (see quoted comment)
    Host ssm-customer-foo
      HostName mi-12345678901234567.required-role.eu-central-1
    ```
4. And connect via vs-code to the remote
    - When the remote opens, you will see the prompt for MFA. Enter it quickly, there seems to be some timeout
    - When a timeout occurs, press retry
    - It is a bit hacky so far, but after some attempts on typing the MFA fast enough and retrying it worked. So if you know a stable way, let me know 😁

**Comment by bordenit** [comment]
The problem I am having is that it almost connects, but keeps putting in the fqdn for the user and assumes that fdqn is the user @instance-id. My ssh_config does not have an fqdn for the user on purpose. I don't want to use fqdn for an individual server since I am using identity center with SSMSessionRunAs passed in through aws sso. aws ssm-start-session works fine outside of vscode. Wish AWS would make a VSCode ssm module where the experience is similar and the SAML attribute for SSMSessionRunAs just passes in as it does outside of VSCode.

**Comment by mrgum** [comment]
I've found another option to connect to things without SSH or SSM and thought it might be useful to someone here too.
https://code.visualstudio.com/docs/remote/tunnels
you download and install a cli version of code on the remote machine and authorize it to github then all the traffic goes via them (so no good on isolated networks but fine elsewhere)

**Comment by justinmk3** [comment]
> Can we get "just SSM"?

To open a terminal? Or some other tasks (please specify)?

> SSH via SSM already works fine.

https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-692745060 reflects my general framing of this issue. I.e. Toolkit should automatically enable:

- connect with vscode remote-ssh (over SSM), without any configuration (just select an EC2 instance).
    - For reference, Toolkit already [implements this for CodeCatalyst](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/codecatalyst-overview.html#codecatalyst-overview-open), but not EC2 (the topic of this issue).
- connect a terminal
    - For reference, Toolkit already [implements this for ECS](https://github.com/aws/aws-toolkit-vscode/issues/2607#issuecomment-1268998721) but not EC2 (the topic of this issue).

**Comment by justinmk3** [comment]
> Currently this requires:
> 
> * VS Code
> * VS Code Remote extension
> * aws cli version 2
> ...
> * SSH (OpenSSH feature on Windows)
> * an SSH key on the EC2 instance

After this issue is addressed, these _won't_ be needed:

* aws cli version 2
* a specific SSH configuration like so: `Host devbox ...`

AWS Toolkit will auto-configure SSH for you. The reason for requiring SSH is because that is what vscode-remote requires.

**Comment by justinmk3** [comment]
> If we don't need aws cli it would be great to still use the AWS eco system (profiles, SSO, ...).

Absolutely. If you get a chance to try out "Dev Environments" with https://codecatalyst.aws/ , please let us know what you think. We have put a lot of work into how AWS Toolkit presents credentials, with more improvements planned.

**Comment by sholtomaud** [comment]
I've tried out the "Dev Environments" for codecatalyts and it works great.

Now we need to be able to get VSCode to get a session into a specific EC2 with a similar method.
________________________________

**Comment by borontion** [comment]
I implemented a simple prototype EC2 explorer, which can 1) start / stop instances and 2) open via SSH: https://marketplace.visualstudio.com/items?itemName=PengzhanZhao.ec2-farm. However, It does require to provision the EC2 with a uploaded key pair.

**Comment by sholtomaud** [comment]
@borontion nice. However we don't want to use key pairs or ssh.

**Comment by iancullinane** [comment]
@Roseidon your solution gets me through the mfa portion, but asks for a password afterwards. Is this supposed to happen? I don't have a password for this instance.

**Comment by Roseidon** [comment]
> @Roseidon your solution gets me through the mfa portion, but asks for a password afterwards. Is this supposed to happen? I don't have a password for this instance.

Unfortunately not, I haven't been prompted for a password afterwards.
Maybe that is an auth setting on the instance itself. So far I only worked with saving my public ssh key on the instance, but not with user/pass.

**Comment by trallnag** [comment]
For me it works on Windows 10, VS Code `1.79.2`, Remote SSH `0.102.0`. Entry in SSH config:

```
Host server
   User ubuntu
   ProxyCommand C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe "aws ssm start-session --target i-0824c21f7abd6347c --document-name AWS-StartSSHSession --parameters portNumber=%p"
```

**Comment by justinmk3** [comment]
# Status

We are actively working on [these features](https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-1466948917).

* Implemented:
    * ✅  `Open Terminal` on a EC2 instance
    * ✅  `AWS: Connect to EC2 Instance...` command
        * <img width="591" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/55561878/8da31cbd-0542-4607-911b-d87ed39af443">
* Not implemented yet:
    * ❌  Connect to EC2 instance via VSCode remote-ssh
    * ❌  Browse EC2 instances in AWS Explorer

**Comment by mwanser1** [comment]
> # Status
> 
> 
> 
> We are actively working on [these features](https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-1466948917).
> 
> 
> 
> * Implemented:
> 
>     * ✅ `Open Terminal` to an EC2 instance (including Windows instances)
> 
>     * ✅ `AWS: Connect to EC2 Instance...` command
> 
>         * <img width="591" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/55561878/8da31cbd-0542-4607-911b-d87ed39af443">
> 
>     * ✅ Browse EC2 instances in AWS Explorer
> 
>     * ✅ Start/Stop/Reboot actions [#1559](https://github.com/aws/aws-toolkit-vscode/issues/1559)
> 
>     * ✅ Connect to EC2 instance via VSCode remote-ssh
> 
> * Not implemented yet:
> 
>     * Connect to EC2 instance from Windows
> 
>     * Connect to EC2 Windows instance
> 
>     * Other actions: list EBS volumes, set shutdown schedule [#1559](https://github.com/aws/aws-toolkit-vscode/issues/1559)

Is AWS: Connect to EC2 Instance in version 1.91.0?  I'm not seeing it  in VS code nor could I find anything about this functionality in the docs.

**Comment by justinmk3** [comment]
> Is AWS: Connect to EC2 Instance in version 1.91.0?

The features in the above [comment](https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-1609299367) are implemented but not released. We're hoping to make it available as an "experimental" option. 

Will update this issue when there is any news.

**Comment by mwanser1** [comment]
I'm not entirely sure if this is a workaround but with ssm-tool and an key pair I am able to use remote-ssh vscode extension to connect to the instance.

**Comment by justinmk3** [comment]
See https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-873096740

**Comment by jfmcdowell** [comment]
Is there an update on this? I periodically (about every VSCode update) lose the ability to run SSM via the proxy script. Using my terminal is fine but inside of VSCode it seems to lose the awscli path.

See this issue for [additional details](https://github.com/microsoft/vscode-remote-release/issues/8844)

**Comment by justinmk3** [comment]
See https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-873096740

**Comment by justinmk3** [comment]
Current status is https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-1609299367

**Comment by la-cruche** [comment]
@justinmk3 those features are still not part of the extension? https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-1609299367 any ETA?

**Comment by deanhtid** [comment]
anything new on this? @justinmk3

**Comment by justinmk3** [comment]
Current status is https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-1609299367

**Comment by ekalosak** [comment]
Would like to see progress on this as well - it was a surprise to not see EC2 in the AWS VScode toolkit. I'm still cycling the public IP for my ec2 instance :(

**Comment by jordancparker** [comment]
Would it be possible to release this as experimental as mentioned in an above message @justinmk3. 

My understand would be that there would be an ability to SSM on Linux/Mac in its current phase.

**Comment by sholtomaud** [comment]
This `Connect to EC2 instance via VSCode remote-ssh,` is that considered `zero-trust` with MFA auth + Enterprise AzureAD? Can I access the EC2 without being in the private network using the DirectConnection to the AWS data centre from the on-prem network? OR is all traffic over the public internet?

**Comment by TheCaffeintedSloth** [comment]
> Would it be possible to release this as experimental as mentioned in an above message @justinmk3.
> 
> My understand would be that there would be an ability to SSM on Linux/Mac in its current phase.

Echoing this from June.  Any update on when the experimental will be released?  Have been hoping for this feature for quite awhile.

**Comment by justinmk3** [comment]
We've made progress on this and it's now in review. We definitely want to see this too :)

**Comment by tehnrd** [comment]
I have a single stateless ec2 bastion box, so the instance ID is constantly changing. Below is a simple config file that works for me and maybe others will find helpful. It will dynamically look up the ec2 instance ID based on the name of the ec2 instance.

I did have to set up a Key Pair for this to work.

```
Host auditr
    HostName ec2-0-00-00-000.us-east-2.compute.amazonaws.com
    User ec2-user
    IdentityFile /Path/To/Pem/file.pem
    ProxyCommand aws ssm start-session --target $(aws ec2 describe-instances --profile profileName --filters 'Name=tag:Name,Values=name-of-ec2-instance' 'Name=instance-state-name,Values=running' --query 'Reservations[].Instances[].InstanceId' --output text) --profile profileName --document-name AWS-StartSSHSession --parameters 'portNumber=%p'
```

**Comment by sholtomaud** [comment]
> I have a single stateless ec2 bastion box ...

There's your problem. Just delete the Bastion and this issue is solved.

**Comment by tehnrd** [comment]
> > I have a single stateless ec2 bastion box ...
> 
> There's your problem. Just delete the Bastion and this issue is solved.

I'm unsure how this helps, as the instance ID would get recreated/change, and you'd have to constantly update your scripts with the new instance ID.

Also, deleting is not a great option when using CDK or other IaC, as you'll get stack drift and all sorts of deployment challenges. I just shut down the instance when not needed, and the script above works great if the instance gets swapped out for any reason.

**Comment by justinmk3** [comment]
# Status

AWS Toolkit 3.39.0 includes [these features](https://github.com/aws/aws-toolkit-vscode/issues/941#issuecomment-1466948917).

* ✅ AWS Explorer (and VSCode command palette): Start/Stop/Reboot actions [#1559](https://github.com/aws/aws-toolkit-vscode/issues/1559)
* ✅ AWS Explorer: list EC2 instances, view their status.
* ✅ `AWS: Launch EC2 Instance` command opens the AWS web console launch page.
* ✅ `AWS: Open terminal to EC2 instance...` command opens a VSCode terminal connected to an EC2 instance.
    * Requires [remote-ssh](https://code.visualstudio.com/docs/remote/ssh) (which requires `ssh` on your local desktop).
    * Supports EC2 instances running Linux/macOS/**Windows**.
* ✅ `AWS: Connect to EC2 instance in New Window...` command connects VSCode to an EC2 instance.
    * Requires [remote-ssh](https://code.visualstudio.com/docs/remote/ssh) (which requires `ssh` on your local desktop).
    * Supports EC2 instances running Linux or macOS (**not Windows, currently**).
    * Your local desktop can be Linux/macOS/Windows.
    * <img width="591" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/55561878/8da31cbd-0542-4607-911b-d87ed39af443">


These features are *not* currently implemented:

* Connect to EC2 Windows instance
* Other actions: list EBS volumes, set shutdown schedule [#1559](https://github.com/aws/aws-toolkit-vscode/issues/1559)

---

Issue locked so that the above status is visible. Please open new issues with your feedback!
