### ISSUE TITLE
Vscode: Deploy SAM application change capabilities to CAPABILITY_NAMED_IAM

### ISSUE THREAD

**Issue by R00T88** [aws/aws-toolkit-vscode#943]
**Desktop (please complete the following information):**

-   OS: Windows 10
-   VS Code version: 1.42.1
-   AWS Toolkit extension version: 1.7.0

**Question**

Im trying to deply my cloudformation stack template that include a creation of IAM Role for lambda but when i select "AWS: Deploy SAM application" from commands palette im not able to change capabilities and for default it uses CAPABILITY_IAM and i want to change it to CAPABILITY_NAMED_IAM

2020-02-24 11:02:54 [ERROR]: stdout: Deploying with following values
	===============================
	Stack name                 : test-cf
	Region                     : eu-west-1
	Confirm changeset          : False
,	Deployment s3 bucket       : None
	Capabilities               : ["CAPABILITY_IAM"]
	Parameter overrides        : {}

Error: Error with child process: Error: Failed to create changeset for the stack: ssc-elb, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Requires capabilities : [CAPABILITY_NAMED_IAM]
Deploy failed

How can i change capabilities parameters?
It's possibile to select capabilities during SAM application deployment?

Thanks

**Comment by bryceitoc9** [comment]
Hi @R00T88,

We currently don't have support for that field at this time (we have the field [hardwired in](https://github.com/aws/aws-toolkit-vscode/blob/master/src/shared/sam/cli/samCliDeploy.ts#L28)).

I'll go ahead and turn this into a feature request; for now, you should be able to run the command yourself (`sam deploy`) with the correct parameters. If you want to run this from scratch, our "Deploy SAM application" workflow is a `sam build` followed by a `sam package` followed by a `sam deploy`; you should already have the packaged artifacts on your machine.

FWIW the Jetbrains toolkit adds [both `CAPABILITY_IAM` and `CAPABILITY_NAMED_IAM`](https://github.com/aws/aws-toolkit-jetbrains/blob/b8421f9d4890d0f5710435f887f7dcf94b9d0d0f/jetbrains-core/src/software/aws/toolkits/jetbrains/services/lambda/deploy/SamDeployDialog.kt#L132); we'll discuss internally if this is the correct behavior.

**Comment by R00T88** [comment]
Hi @bryceitoc9 
thanks for the feedback
Do you an eta for this?

Thanks

**Comment by bryceitoc9** [comment]
Fix: https://github.com/aws/aws-toolkit-vscode/pull/951

**Comment by awschristou** [comment]
This change has been released with v1.8.0 of the toolkit
