### ISSUE TITLE
Possibility to delete cloudformation stack from vscode

### ISSUE THREAD

**Issue by R00T88** [aws/aws-toolkit-vscode#946]
Desktop (please complete the following information):

OS: Windows 10
VS Code version: 1.42.1
AWS Toolkit extension version: 1.7.0

Question:

Do you think it's possible to implement a workflow to delete a cloud formation stack?

**Comment by awschristou** [comment]
CloudFormation stacks can be deleted by right clicking on them in the AWS Explorer and selecting "Delete CloudFormation Stack". A notification pops up in the lower corner to confirm that you want to delete the stack. Pressing Yes will delete the stack.
