### ISSUE TITLE
Users can locally debug Lambda Functions through the Debug Pane

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#949]
This is the work tracking item for the design in PR #933 , which uses Debug Configurations to drive the local debugging experience with SAM/Lambda Handlers.

**Comment by justinmk3** [comment]
related

- https://github.com/aws/aws-toolkit-vscode/issues/371
- https://github.com/aws/aws-toolkit-vscode/issues/370
- https://github.com/aws/aws-toolkit-vscode/issues/1031

**Comment by justinmk3** [comment]
AWS Toolkit 1.12 (released today) includes the new [SAM local Lambda debugging experience](https://github.com/aws/aws-toolkit-vscode/pull/1215) which leverages VS Code "launch configurations". 

Full documentation: https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/run-debug-sam-app.html
