### ISSUE TITLE
Refresh AWS Explorer after publishing to new state machine

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#993]
When publishing a Step Functions state machine to a new resource in my account, I have to refresh the AWS Explorer afterwards in order to see it. The AWS Explorer should show that state machine after it is published.

**Comment by justinmk3** [comment]
related https://github.com/aws/aws-toolkit-vscode/pull/1665

**Comment by justinmk3** [comment]
Fixed in AWS Toolkit 1.29
